### ISSUE TITLE
Error on GoogleMap component mount

### ISSUE THREAD

**Issue by VonD** [tomchentw/react-google-maps#100]
Hi, I'm having the following error : `Uncaught TypeError: Cannot read property 'firstChild' of undefined`.

The error is triggered by this line in the `componentDidMount` hook of `GoogleMap` : 

`const domEl = findDOMNode(this);` [source](https://github.com/tomchentw/react-google-maps/blob/master/src/GoogleMap.js#L79)

Could this be caused by the fact i'm using react 0.14.0-beta1 ? Or do you have any idea what can cause this ?

Many thanks

**Comment by tomchentw** [comment]
I just tried `react 0.14.0-beta1` and it seems to work correctly. Would you like to take a closer look?

<img width="1276" alt="screen shot 2015-08-18 at 10 04 55 am" src="https://cloud.githubusercontent.com/assets/922234/9320798/a49fdfe2-4590-11e5-8cc6-f2c5457d6023.png">

**Comment by VonD** [comment]
@tomchentw yes thanks for your answer.

The error came from the fact that `react-google-maps` as react 0.13 specified as peer dependency, so my bundle was using two different versions of react.

**Comment by tomchentw** [comment]
Gosh. Maybe I should remove peerDependencies since npm3 is there. What do you think?

**Comment by VonD** [comment]
peerDependencies should only be annoying for people using react beta, but why not. Or maybe add a little warning on the Readme. As you wish. I can submit a little PR if you want
