### ISSUE TITLE
Custom Marker not showing correct position when zooming in or out.

### ISSUE THREAD

**Issue by therajsagar** [tomchentw/react-google-maps#1005]
React Google Maps - 9.4.5

While zooming in or out custom marker are not located at their correct lat-lng position.
![scr](https://user-images.githubusercontent.com/45603741/63427139-11598880-c432-11e9-8271-d80f311b60f3.gif)

**Comment by JustFly1984** [comment]
@therajsagar this library is unmaintained, please refer to new library @react-google-maps/api
