### ISSUE TITLE
onMouseOver and onMouseOut events on markers appear to be named lowercase causing the event handler not to be attached.

### ISSUE THREAD

**Issue by TomCaserta** [tomchentw/react-google-maps#101]
Not sure if this applies to more than markers. Just thinking it might be wise to change it so it allows any case (or at least allows the React style capitalization of events). Alternatively making a note of it somewhere prominent would be great.

Currently you have to use `onMouseover` and `onMouseout` which is inconsistent to Reacts event system that uses `onMouseOver` and `onMouseOut`.

**Comment by tomchentw** [comment]
Yes, because the event isn't really handled by React Event System. They're provided by Google Maps JavaScript API v3
http://git.io/vsJon

**Comment by TomCaserta** [comment]
Yeah I understand that, but its just a little confusing that its not explicitly mentioned anywhere. I mean the code already transforms the first character to be uppercase. I mean its obvious when you realise whats going on but genuinely earlier I was wondering for about 20-30 minutes as to why my events wasnt firing as I just assumed you had converted the event names to be "react style" event names. 

But fair enough then, hopefully this'll lead someone to here if they try googling it.

**Comment by tomchentw** [comment]
Sorry about that. We really need a better documentation ...

**Comment by tomchentw** [comment]
Hmm I think I did convert it in some cases like `cursor_changed` will be `onCursorChanged`. `mouseover` event is a bit tricky though

**Comment by TomCaserta** [comment]
yeah I saw the event list and way you are converting. Unsure if you can do this efficiently, but would it just be possible to make it case insensitive? I mean its not a major issue, just something that would save people time in the future. 

Dont want to sound like I am annoyed by this at all simply because the library has saved me a lot of time (so thanks!).

**Comment by tomchentw** [comment]
If we had a way to:
1. get a list of React predefined event names
2. compare them in lowercase with google event names in lowercase
If there's a match but case isn't match, show the warning to the user. What do you think?

**Comment by stewartduffy** [comment]
Hi @TomCaserta what was the outcome of this?

**Comment by tomchentw** [comment]
Will look into this shortly.

We're also looking for maintainers. Involve in #266 to help strengthen our community!

**Comment by x5engine** [comment]
@TomCaserta is this still an issue?
