### ISSUE TITLE
UNSAFE Life cycles

### ISSUE THREAD

**Issue by yasithgamage** [tomchentw/react-google-maps#1014]
I'm not using any **UNSAFE** life cycles in my project and I'm getting warnings mentioning to update **withGoogleMap** component. 

![Screenshot from 2019-11-04 15-52-02](https://user-images.githubusercontent.com/53287572/68114053-2c10a900-ff1b-11e9-8e8d-70a2c90be070.png)

**Comment by JustFly1984** [comment]
@yasithgamage
The repo of this project is unmaintained more than a year, and we had build new version https://www.npmjs.com/package/@react-google-maps/api

We had rewrite it to TypeScript, and updating it frequently: https://github.com/JustFly1984/react-google-maps-api/tree/master/packages/react-google-maps-api
You can enjoy autocomplete.

You can see our docs: https://react-google-maps-api-docs.netlify.com/

Also a lot of examples: https://react-google-maps-api-gatsby-demo.netlify.com/ https://github.com/JustFly1984/react-google-maps-api/tree/master/packages/react-google-maps-api-gatsby-example/src/examples

The bundle size is much smaller: https://bundlephobia.com/result?p=@react-google-maps/api@1.7.7

Our Spectrum community: https://spectrum.chat/react-google-maps

Enjoy!

**Comment by yasithgamage** [comment]
> @yasithgamage
> The repo of this project is unmaintained more than a year, and we had build new version https://www.npmjs.com/package/@react-google-maps/api
> 
> We had rewrite it to TypeScript, and updating it frequently: https://github.com/JustFly1984/react-google-maps-api/tree/master/packages/react-google-maps-api
> You can enjoy autocomplete.
> 
> You can see our docs: https://react-google-maps-api-docs.netlify.com/
> 
> Also a lot of examples: https://react-google-maps-api-gatsby-demo.netlify.com/ https://github.com/JustFly1984/react-google-maps-api/tree/master/packages/react-google-maps-api-gatsby-example/src/examples
> 
> The bundle size is much smaller: https://bundlephobia.com/result?p=@react-google-maps/api@1.7.7
> 
> Our Spectrum community: https://spectrum.chat/react-google-maps
> 
> Enjoy!

Thanks.
