### ISSUE TITLE
Support react 0.14.0-beta3

### ISSUE THREAD

**Issue by boosh** [tomchentw/react-google-maps#102]
I'd do this myself but I'm a react noob... I'm getting errors about the import of `findDOMNode` after upgrading the dependency to react 0.14.0-beta3, and more errors after fixing that import...

**Comment by tomchentw** [comment]
I think it just a warning? #26

**Comment by tomchentw** [comment]
#100 I think you could still using it.

**Comment by boosh** [comment]
Perhaps removing the dependency from package.json might be enough. When I tried upgrading the dependency in a fork I had these errors though, and it didn't work. 

Have you tried with beta3 instead of just beta1?

**Comment by VonD** [comment]
@boosh I'm using this fork for the moment without any errors : https://github.com/VonD/react-google-maps/tree/no-peer-dependency

**Comment by tomchentw** [comment]
@VonD you're awesome!

**Comment by boosh** [comment]
Hmm I get an error when I copy and paste the simple map example into my project with that branch:
```
TypeError: Cannot read property 'firstChild' of undefined
```
When I installed it, it complained about needing react 0.13 but it not being installed...

In 0.14 they've split the DOM stuff out of core, so perhaps this is the problem?

**Comment by tomchentw** [comment]
@boosh Did you use the fork from @VonD ?

**Comment by boosh** [comment]
Yeah. I still had problems with it for some reason.

**Comment by VonD** [comment]
@boosh is by any chance react installed in the node_modules directory of the react-google-maps package ?

**Comment by tomchentw** [comment]
@VonD @boosh which version of `npm` are you using ?

**Comment by VonD** [comment]
2.5.1

**Comment by boosh** [comment]
I was using 3.0.0 but I've downgraded. I'll test it when I get chance.

**Comment by tomchentw** [comment]
If you use 3.0.0. npm will flatten your dependencies into the top most `node_modules`.

**Comment by tomchentw** [comment]
Closed by 443a5fd332774b6b8528e7f784dde0e3b4f4def2 and released [v4.0.0](https://github.com/tomchentw/react-google-maps/releases/tag/v4.0.0)
