### ISSUE TITLE
Fix Lodash import method to optimize build

### ISSUE THREAD

**Issue by t18n** [tomchentw/react-google-maps#1029]
## Getting Help

**Before doing this, did you**:

1. Read the [documentation](https://tomchentw.github.io/react-google-maps)
Yes

2. Read the [source code](https://github.com/tomchentw/react-google-maps)
Yes

Hi guys, I notice that we are importing lodash by `import _ from 'lodash';`, this method imports the whole library and make the build unnecessarily big.

![image](https://user-images.githubusercontent.com/14198542/74170426-2bc82e00-4c2d-11ea-801b-11a3c4915464.png)

To optimize the build, I believe we should do this way:
```
import map from 'lodash/map';
import tail from 'lodash/tail';
```
I can make a PR for it if we all agree :)

Read more: https://www.blazemeter.com/blog/the-correct-way-to-import-lodash-libraries-a-benchmark/

[gitter-url]: https://gitter.im/tomchentw/react-google-maps?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge

**Comment by JustFly1984** [comment]
@turbothinh 
The repo of this project is unmaintained more than a year, and we had build new version https://www.npmjs.com/package/@react-google-maps/api

We had rewrite it to TypeScript, and updating it frequently: https://github.com/JustFly1984/react-google-maps-api/tree/master/packages/react-google-maps-api
You can enjoy autocomplete.

You can see our docs: https://react-google-maps-api-docs.netlify.com/

Also a lot of examples: https://react-google-maps-api-gatsby-demo.netlify.com/ https://github.com/JustFly1984/react-google-maps-api/tree/master/packages/react-google-maps-api-gatsby-example/src/examples

The bundle size is much smaller: https://bundlephobia.com/result?p=@react-google-maps/api

Our Spectrum community: https://spectrum.chat/react-google-maps Our Slack channel: https://join.slack.com/t/react-google-maps-api/shared_invite/enQtODc5ODU1NTY5MzQ4LTBiNTYzZmY1YmVjYzJhZThkMGU0YzUwZjJkNGJmYjk4YjQyYjZhMDk2YThlZGEzNDc0M2RhNjBmMWE4ZTJiMjQ

Enjoy!
