### ISSUE TITLE
Custom marker icons cause lag

### ISSUE THREAD

**Issue by echenley** [tomchentw/react-google-maps#103]
Hey, first off this is a fantastic project! Thanks!

I'm building an application which supports potentially thousands of markers at a time, each sharing a custom icon instead of the default. This is quite possible using the vanilla maps API.

This library handles the default icon perfectly fine (at least with 200 markers). However, once I add a custom icon, there is a noticeable lag on renders. I am using svgs:

```javascript
marker.icon = {
    path: 'M0,89.6V23h17.5l0,0C18.1,12,22.1,0,35,0c12.9,0,16.9,12,17.5,23H70v66.6H0z M46.2,23 C45.8,15.9,43.8,6.3,35,6.3c-8.8,0-10.8,9.5-11.2,16.7H46.2L46.2,23z',
    fillColor: '#ff0000',
    fillOpacity: 1,
    strokeWeight: 0,
    scale: 0.3
}
```

Here is the code in context. Commenting out the icon prop causes the lag to disappear.

```javascript
var MapComponent = React.createClass({

    // other component stuff...

    toMarker(marker) {
        let { infoWindow } = this.state;
        
        let infoWindowEl = infoWindow === marker.key ? (
            <InfoWindow
                key={ marker.key }
                onCloseclick={ () => this.setState({ infoWindow: false }) }
            >
                <InfoWindowContent locationData={ allLocations[infoWindow] } />
            </InfoWindow>
        ) : null;

        return (
            <Marker
                ref={ 'marker' + marker.key }
                key={ marker.key }
                // if I comment out the following line, the lag disappears
                icon={ marker.icon }
                onClick={ () => this.openInfoWindow(marker.key) }
                position={ marker.position }
                animation={ marker.animation || null }
            >
                { infoWindowEl }
            </Marker>
        );
    },

    render() {
        /* other render stuff */
        return (
            <div className="sl-map-container">
                <GoogleMap
                    ref="map"
                    containerProps={ containerProps }
                    googleMapsApi={ typeof google !== 'undefined' ? google.maps : null }
                    onBoundsChanged={ this.setMinimumZoom }
                    onZoomChanged={ this.updateZoomLevel }
                    onIdle={ this.onMapIdle }
                    zoom={ zoomLevel }
                >
                    { markers.map(this.toMarker, this) }
                </GoogleMap>
            </div>
        );
    }
});
```

**Comment by tomchentw** [comment]
Which version are you currently using? v1 or v2?
If you are using v2, try `defaultIcon={ marker.icon }` instead?

**Comment by echenley** [comment]
Changing it to `defaultIcon` does help! What exactly is the difference between the two? I couldn't find a distinction in the google API. I am using v2.

**Comment by tomchentw** [comment]
The concept is very similar to [Controlled Component](https://facebook.github.io/react/docs/forms.html#controlled-components). Setting some props to `default`-prefixed will make them set just once.

**Comment by tomchentw** [comment]
But the down side is that you could not change the value anymore (by setting it to new value via props). Instead, it's fully controlled by the Google Maps JavaScript API v3.

**Comment by jerefrer** [comment]
@echenley Thanks for pasting your code in here, it helped me greatly to understand how to use `InfoWindow`.

I'm very new to React and I find it insanely difficult to make every step towards every goal using this library. I think the main cause is lack of documentation, mainly around `InfoWindow`.

I can see you have some working implementation of `InfoWindow` that one can open/close, would you be so kind as to add an example of this feature ? Or if you don't have time maybe just paste it in some gist so I can rework it and submit an example based on it ?

Thanks !

**Comment by jerefrer** [comment]
Okay I finally got those InfoWindow to work, I try to find some time and add an example with my solution.

**Comment by echenley** [comment]
@jerefrer Glad it was helpful! I agree that a thorough API documentation in addition to the examples is needed, especially for features where there isn't an obvious one-to-one relationship to the maps API. I've created [another issue](128) to address this.

**Comment by tomchentw** [comment]
Thanks @echenley !
