### ISSUE TITLE
Google Maps instance failing in Docs

### ISSUE THREAD

**Issue by oliviergf** [tomchentw/react-google-maps#1030]
The google maps examples in the Documentation are failing

![Screenshot from 2020-02-11 22-40-49](https://user-images.githubusercontent.com/39070243/74300973-922d7900-4d1f-11ea-99b4-ac1d8c425ae3.png)

due to those errors:

![Screenshot from 2020-02-11 22-41-24](https://user-images.githubusercontent.com/39070243/74301017-b1c4a180-4d1f-11ea-99aa-19fb392fc761.png)

Exact errors:
The Fusion Tables service will be turned down in December 2019 (see https://support.google.com/fusiontables/answer/9185417). Maps API version 3.37 is the last version that will support FusionTablesLayer.
**and**
Google Maps JavaScript API error: InvalidKeyMapError

Tried with Brave and Chrome browsers.

**Comment by joshnavdev** [comment]
Same error,
I try changin the API KEY but it shows the same error, can someone help with this?

**Comment by nos-nart** [comment]
I got the same error, has anyone had fixed it yet?

**Comment by batazor** [comment]
@tomchentw The sample documentation still doesn't work
