### ISSUE TITLE
Does it work with js-marker-clusterer

### ISSUE THREAD

**Issue by farrrr** [tomchentw/react-google-maps#104]
I try to use js-marker-clusterer in react-google-maps, but it seems not work.
Does it work with js-marker-clusterer?

**Comment by tomchentw** [comment]
Not sure. You could try to create a Component for that
https://github.com/googlemaps/js-marker-clusterer
Someone wants to help?

**Comment by farrrr** [comment]
okay, maybe I can try to create one later.
thx.

**Comment by frodosamoa** [comment]
I've implemented the clusterer in a previous version of `react-google-maps`, it was a while ago though, the version was v0.2.5.

**Comment by tomchentw** [comment]
Mind to put the code here so that someone could implement it in v2? Thanks @frodosamoa  :)

**Comment by frodosamoa** [comment]
I actually wouldn't mind tackling it myself! I'll get a PR open in the near future :relaxed:

**Comment by asaf** [comment]
@frodosamoa +1

**Comment by idolize** [comment]
Oh wow this looks very cool!

**Comment by farrrr** [comment]
I try to implement MarkerClusterPlus to react-google-maps,
And create a pull request https://github.com/tomchentw/react-google-maps/pull/124
I want to make a example, but I npm start gh-pages, it throw error...
-----
webpack: bundle is now VALID.
[TypeError: Cannot read property 'rawAsset' of undefined]
-----
so I can't build a example in gh-pages.

so if you want use this feature you need include MarkerClustererPlus script first.

then, use <MarkClusterer /> like others.

-----
          <GoogleMap
            containerProps={{
              style: {
                width: "98%",
                height: "92%"
              }
            }}
            ref="map"
            defaultZoom={ 6 }
            googleMapsApi={ google.maps }
            center={ labs.location }>
            <MarkerClusterer
              enableRetinaIcons={ true }
              averageCenter={ true }
              gridSize={ 40 }>
              <Marker ..../>
            </MarkerClusterer>
          </GoogleMap>
-----
it's a very simple example.

**Comment by tomchentw** [comment]
@farrrr it's a bug in `reacthtmlpack` just try to start it again.

I'll take a look at the PR soon. Thanks!

**Comment by tomchentw** [comment]
Closed for #124
