### ISSUE TITLE
How to edit existing polygon in reactjs

### ISSUE THREAD

**Issue by AarjuRabadiya** [tomchentw/react-google-maps#1040]
When I edit or drag the polygon that time getting the error that is a function not found.
In that getPath(), getPaths(), and getDraggable() function is not working.
How to use that function?
I want to draw a polygon and after that edit a polygon which I added using polygon class.

```
const onAdd = (data) => {
  const path = data.getPath();
  console.log("path", data);

  var pathArray = [];
  for (var i = 0; i < path.length; i++) {
    pathArray = [path.getAt(i).lat(), path.getAt(i).lng()];
    polygonArray.push(pathArray);
  }
};

const onEdit = (polygondata) => {
  console.log("polygon", polygondata.getPaths());

  var pathArraya = [polygondata.latLng.lat(), polygondata.latLng.lng()];

  console.log("....", pathArraya);

  // console.log("polygon", polygon.latLng.lng());
  // var pathArray = [polygon.latLng.lat(), polygon.latLng.lng()];
  // polygonArray.push(pathArray);
};
const MyMapComponent = compose(
  withProps({
    googleMapURL:
      "https://maps.googleapis.com/maps/api/js?key=" +
      global.config.googleApiKey +
      "&v=3.exp&libraries=geometry,drawing,places",
    loadingElement: <div style={{ height: `100%` }} />,
    containerElement: <div style={{ height: `500px` }} />,
    mapElement: <div style={{ height: `100%` }} />,
  }),
  withScriptjs,
  withGoogleMap
)((props) => {
  let polygonPath = [];

  if (props.alreadyExistCity) {
    
    polygonPath = props.alreadyExistCity.geometry.coordinates[0].map(
      (coordinateItem) => {
        console.log(coordinateItem);

        return { lat: coordinateItem[0], lng: coordinateItem[1] };
      }
    );
  }
return (
    <GoogleMap defaultZoom={12} center={props.mapCenter}>
 {props.alreadyExistCity ? (
        <Polygon
          draggable
          path={polygonPath}
          options={{
            strokeWeight: 2,
            fillColor: "#000",
            fillOpacity: 0.4,
            zIndex: 1,
            visible: true,
          }}
onDragEnd={onEdit}
/>
      ) : (
        <DrawingManager
         
          defaultOptions={{
            drawingControl: true,
            drawingControlOptions: {
              drawingModes: ["polygon"],
            },

            polygonOptions: {
              strokeWeight: 2,
              fillColor: "#000",
              fillOpacity: 0.4,
              clickable: true,
              editable: true,
              zIndex: 1,
            },
          }}
          onPolygonComplete={onAdd}
        />
      )}
    </GoogleMap>
  );
});

```

**Comment by aarazoo** [comment]
> When I edit or drag the polygon that time getting the error that is a function not found.
> In that getPath(), getPaths(), and getDraggable() function is not working.
> How to use that function?
> I want to draw a polygon and after that edit a polygon which I added using polygon class.
> 
> ```
> const onAdd = (data) => {
>   const path = data.getPath();
>   console.log("path", data);
> 
>   var pathArray = [];
>   for (var i = 0; i < path.length; i++) {
>     pathArray = [path.getAt(i).lat(), path.getAt(i).lng()];
>     polygonArray.push(pathArray);
>   }
> };
> 
> const onEdit = (polygondata) => {
>   console.log("polygon", polygondata.getPaths());
> 
>   var pathArraya = [polygondata.latLng.lat(), polygondata.latLng.lng()];
> 
>   console.log("....", pathArraya);
> 
>   // console.log("polygon", polygon.latLng.lng());
>   // var pathArray = [polygon.latLng.lat(), polygon.latLng.lng()];
>   // polygonArray.push(pathArray);
> };
> const MyMapComponent = compose(
>   withProps({
>     googleMapURL:
>       "https://maps.googleapis.com/maps/api/js?key=" +
>       global.config.googleApiKey +
>       "&v=3.exp&libraries=geometry,drawing,places",
>     loadingElement: <div style={{ height: `100%` }} />,
>     containerElement: <div style={{ height: `500px` }} />,
>     mapElement: <div style={{ height: `100%` }} />,
>   }),
>   withScriptjs,
>   withGoogleMap
> )((props) => {
>   let polygonPath = [];
> 
>   if (props.alreadyExistCity) {
>     
>     polygonPath = props.alreadyExistCity.geometry.coordinates[0].map(
>       (coordinateItem) => {
>         console.log(coordinateItem);
> 
>         return { lat: coordinateItem[0], lng: coordinateItem[1] };
>       }
>     );
>   }
> return (
>     <GoogleMap defaultZoom={12} center={props.mapCenter}>
>  {props.alreadyExistCity ? (
>         <Polygon
>           draggable
>           path={polygonPath}
>           options={{
>             strokeWeight: 2,
>             fillColor: "#000",
>             fillOpacity: 0.4,
>             zIndex: 1,
>             visible: true,
>           }}
> onDragEnd={onEdit}
> />
>       ) : (
>         <DrawingManager
>          
>           defaultOptions={{
>             drawingControl: true,
>             drawingControlOptions: {
>               drawingModes: ["polygon"],
>             },
> 
>             polygonOptions: {
>               strokeWeight: 2,
>               fillColor: "#000",
>               fillOpacity: 0.4,
>               clickable: true,
>               editable: true,
>               zIndex: 1,
>             },
>           }}
>           onPolygonComplete={onAdd}
>         />
>       )}
>     </GoogleMap>
>   );
> });
> ```

**Comment by aarazoo** [comment]
can't add label
