### ISSUE TITLE
infowindows fire twice, one blank ?

### ISSUE THREAD

**Issue by PokerJava** [tomchentw/react-google-maps#1065]
<img width="690" alt="Screen Shot 2563-11-29 at 19 18 35" src="https://user-images.githubusercontent.com/26649959/100541647-e20e0a00-3277-11eb-8552-85cfe54b2ac3.png">
<img width="737" alt="Screen Shot 2563-11-29 at 19 19 17" src="https://user-images.githubusercontent.com/26649959/100541649-e5a19100-3277-11eb-953b-24be19c1ec7d.png">

**Comment by JustFly1984** [comment]
@PokerJava Hello everybody. The repo of this project is unmaintained more than 3 years, and we had build new version https://www.npmjs.com/package/@react-google-maps/api

We had rewrite it to TypeScript, and updating it frequently: https://github.com/JustFly1984/react-google-maps-api/tree/master/packages/react-google-maps-api
You can enjoy autocomplete.

You can see our docs: https://react-google-maps-api-docs.netlify.app

Also a lot of examples: https://react-google-maps-api-gatsby-demo.netlify.app/ https://github.com/JustFly1984/react-google-maps-api/tree/master/packages/react-google-maps-api-gatsby-example/src/examples

The bundle size is much smaller: https://bundlephobia.com/result?p=@react-google-maps/api

Our Spectrum community: https://spectrum.chat/react-google-maps Our Slack channel: https://join.slack.com/t/react-google-maps-api/shared_invite/enQtODc5ODU1NTY5MzQ4LTBiNTYzZmY1YmVjYzJhZThkMGU0YzUwZjJkNGJmYjk4YjQyYjZhMDk2YThlZGEzNDc0M2RhNjBmMWE4ZTJiMjQ

Enjoy!

**Comment by PokerJava** [comment]
thank you
