### ISSUE TITLE
 Legacy context API has been detected within a strict-mode tree.

### ISSUE THREAD

**Issue by venkat-koganti-nll** [tomchentw/react-google-maps#1089]
Getting this error while using react-google-maps

Warning: Legacy context API has been detected within a strict-mode tree.

The old API will be supported in all 16.x releases, but applications using it should migrate to the new version.

Please update the following components: GoogleMap, Marker

using version 9.4.5

**Comment by JustFly1984** [comment]
@venkat-koganti-nll this package is unmaintained over 4 years. please use @react-google-maps/api instead.
