### ISSUE TITLE
Create a pool of google maps objects to get around memory leak

### ISSUE THREAD

**Issue by sdemjanenko** [tomchentw/react-google-maps#11]
Cool library.  I suggest an enhancement to get around a know google maps memory leak (http://stackoverflow.com/questions/21142483/google-maps-js-v3-detached-dom-tree-memory-leak). 

I think the best fix would be to see if there are any available google maps objects for reuse.  If not, create one.  On unmount return the google map object to the pool after the call to ```_set_map(null)```.

**Comment by tomchentw** [comment]
Feel free to submit a PR. Close for now

We're also looking for maintainers. Involve in #266 to help strengthen our community!
