### ISSUE TITLE
google.maps.LatLng call should not be necessary for geometric objects

### ISSUE THREAD

**Issue by Californian** [tomchentw/react-google-maps#111]
I think it would be preferable if points did not have to be manually composed with a google.maps.LatLng call for each point in a polygon's or polyline's path, or for any other geometric objects. This should be handled behind-the-scenes, as there is no other option for writing paths.

**Comment by Californian** [comment]
I'm going to be working on this over the weekend, and I'll submit a PR when complete.

**Comment by tomchentw** [comment]
I'm not sure whether this feature should be done in regardless of the level of abstraction of this library.

**Comment by Californian** [comment]
If you don't think it would be an improvement, feel free to close the issue.

**Comment by tomchentw** [comment]
Welcome to implement this under the namespace of `addons` folder :)
