### ISSUE TITLE
Development Environment -- docker-compose Fails

### ISSUE THREAD

**Issue by Californian** [tomchentw/react-google-maps#113]
When running `docker-compose` in the checked-out repository (with no modifications), it returns the following error.

```
> reacthtmlpack devServer ./Client.webpackConfig.js ../../public ./views/*.html.js --docker


  error: unknown option `--docker\'
```

**Comment by brainkim** [comment]
Also getting this problem. Any luck?

**Comment by Californian** [comment]
Well it looks like `examples/gh-pages/Client.webpackConfig.js` is what is supposed to be using this variable, and it just changes HOST from `localhost` to `0.0.0.0`. I removed the `--docker` from the command definition in `examples/gh-pages/package.json` and it seems to build correctly; maybe it's worth defaulting to `0.0.0.0` since I assume windows development is less common than docker. Regardless, I haven't spent any time on this really as I'm not actually modifying the gh-pages part (yet).

**Comment by brainkim** [comment]
Here's a commit showing the differences you wrote if anyone else is having this problem. This is probably the nicest open-source repository for anything that I've ever seen.

https://github.com/brainkim/react-google-maps/commit/ae54edb7c2a13ec40275e4f0b7ebae5d0798e029
