### ISSUE TITLE
Warning: owner-based and parent-based contexts differ

### ISSUE THREAD

**Issue by ilionic** [tomchentw/react-google-maps#116]
Getting this warning while trying to insert another React component into `<InfoWindow>`, in my case React-router Link

```
        <InfoWindow key={`${ref}_info_window`}
          onCloseclick={() => this.handleMarkerClick(marker, false)}>
          <div>
            <Link params={{id: marker.id}} to={'details'}>
              <img src={marker.thumb} />
            </Link>
            <p><strong>{marker.name}</strong><br/>
          </div>
        </InfoWindow>
```

**Comment by tomchentw** [comment]
Internally `InfoWindow` will render your content in another `React.render` call. Not sure how to deal with that...

**Comment by ilionic** [comment]
As alternative to `InfoWindow` I am trying to play around with `InfoBox` to see if it gives warning.
Though having issue with importing `InfoBox` component from /addons

I am using Webpack and loading components this way:
`import {GoogleMap, Marker, InfoWindow} from 'react-google-maps';`  - works fine.

```import {InfoBox} from 'react-google-maps/addons/';``` - module not found
Relative path to npm-modules isn't best way for me, like in examples. 
Any tips? Thanks

**Comment by tomchentw** [comment]
`import InfoBox from 'react-google-maps/lib/addons/InfoBox';`

**Comment by ilionic** [comment]
Thank you! Unfortunately warning is still present. 
Checked around and apparently this is context issue and should be resolved in React 0.14

**Comment by tomchentw** [comment]
Ref #109

**Comment by tomchentw** [comment]
Close this for #129
