### ISSUE TITLE
refs in OverlayView not defined in parent component's componentDidMount

### ISSUE THREAD

**Issue by brainkim** [tomchentw/react-google-maps#122]
If you have a component like so:
```
class MapControllerOrWhatever extends Component {
  componentDidMount() {
    console.log(this.refs.redSquare); // logs undefined
  }

  render() {
    const mapCenter = new google.maps.LatLng(40.71, -73.95);
    return (
      <div>
        <GoogleMap
          containerProps={{
            style: {
              height: '100%',
            },
          }}
          zoom={13}
          center={mapCenter}
          ref="map"
        >
          <OverlayView
            position={mapCenter}
            mapPaneName={OverlayView.OVERLAY_MOUSE_TARGET}
            >
            <div
              style={{
                width: 100,
                height: 100,
                backgroundColor: 'red'
              }}
              ref="redSquare"
            />
          </OverlayView>
        </GoogleMap>
      </div>
    );
  }
}
```
the ref to the redSquare div, which is a child of the `OverlayView` will be undefined in `componentDidMount`. Is there a way to mitigate this problem, or is it a consequence of the techniques you use to render the children of the OverlayView?

**Comment by tomchentw** [comment]
Unfortunately yes. Currently I don't see a possible solution out there.

**Comment by TonyFrancis** [comment]
Reason for this is that render happens on``` Parent``` first and then``` children```. So issue is that when Parent finishes render it calls ```componentDidMount``` fn() but at that Child ```Overlay``` is finished rendering so ```ref ```is not set with ```parent```. 

Work around for this is set timedelay so child renders  and ref is available at Parent 
```jsx
  componentDidMount() {
      setTimeout(console.log(this.refs.redSquare), 1000) #required delay 1sec or more
  }
``` 

React must need a ```componentDidDisplay``` lifecycle for this use of ```refs```

**Comment by tomchentw** [comment]
@TonyFrancis I think the reason here is we had a different React.render cycle for components like `OverlayView`, `InfoWindow` and `InfoBox`.

**Comment by TonyFrancis** [comment]
@tomchentw  yes that's the issue. React group try to propose a new lifecycle for this .
[ComponentDidDisplay](https://github.com/facebook/react/issues/5053)

**Comment by tomchentw** [comment]
@TonyFrancis wow it's so new. Thanks for the reference!

**Comment by tomchentw** [comment]
@brainkim @TonyFrancis Try callback style ref instead? At that time, you could always get up to date DOM. https://facebook.github.io/react/docs/more-about-refs.html#the-ref-callback-attribute

**Comment by tomchentw** [comment]
Close for now.

We're also looking for maintainers. Involve in #266 to help strengthen our community!
