### ISSUE TITLE
Comprehensive API Documentation

### ISSUE THREAD

**Issue by echenley** [tomchentw/react-google-maps#128]
While it is possible to figure out how to use this library by reading the examples and other available code samples, anything beyond basic usage becomes a struggle due to lack of documentation. For instance, the fact that `<InfoWindow />` can be nested inside `<Marker />` is undocumented except for [this unrelated example](http://tomchentw.github.io/react-google-maps/#events/event-closure).

A list of props available for each component (including possible children) would go a long way to making this library viable for the majority of developers.

**Comment by tomchentw** [comment]
Certainly agree with this. Do you have any idea on good documentation tools?

**Comment by echenley** [comment]
The overview is looking good! :+1: 

Not super experienced with documentation myself, but this looks like an interesting project: https://github.com/reactjs/react-docgen. I ran it over the `src/` directory but it doesn't understand that prop types are imported from another file. Am going to open an issue with them when I get the chance.

**Comment by echenley** [comment]
Will see what they say: https://github.com/reactjs/react-docgen/issues/33

**Comment by jerefrer** [comment]
:+1: Nice to see some docs, thanks !

**Comment by tomchentw** [comment]
[ESDoc](https://esdoc.org/) looks promising

**Comment by tomchentw** [comment]
We're also looking for maintainers. Involve in #266 to help strengthen our community!
