### ISSUE TITLE
React 0.14 issues thread

### ISSUE THREAD

**Issue by tomchentw** [tomchentw/react-google-maps#129]
* [x] `FIXME` stuff for `React.findDOMNode -> ReactDOM` #132 
* [x] `FIXME` stuff for `React.render -> ReactDOM`

**Comment by mauriyouth** [comment]
findDOMNode is depecrated,https://github.com/tomchentw/react-google-maps/blob/5d9cd84aa197342cded582ea1da3e10fb01e26fe/src/GoogleMap.js#L5,
now its in react-dom
