### ISSUE TITLE
DrawingManager markercomplete example

### ISSUE THREAD

**Issue by akatreyt** [tomchentw/react-google-maps#138]
I'm trying to get the gps of a marker when added to the map, I understand I'm supposed to use the Device Manager and markercomplete but I can't get it to work. Wondering if anyone had an example they could share? I was going to post this on stackoverflow but I didn't see a react-google-maps tag. 

Thanks

**Comment by tomchentw** [comment]
We're going to look into this shortly.

We're also looking for maintainers. Involve in #266 to help strengthen our community!
