### ISSUE TITLE
ScriptjsGoogleMap.componentWillReceiveProps throws warnings on all re-renders

### ISSUE THREAD

**Issue by andersaloof** [tomchentw/react-google-maps#143]
I've copied your async example, but my console is filled with warnings that props "query" and "loadingElement" have changed, even though they have not.

If I set loadingElement to false as a prop to <ScriptjsGoogleMap>, it's only reporting that query have changed, and even if I set query to an empty object, it thinks it has changed.

Seems to me that the issue is because theese props are objects, and compared with !== they will falsely report to be different, even though nothing has changed.

**Comment by tomchentw** [comment]
Thanks. Releases [v4.3.2](https://github.com/tomchentw/react-google-maps/releases/tag/v4.3.2)
