### ISSUE TITLE
OverlayView is completely rebuilt even if props don't change

### ISSUE THREAD

**Issue by sergiu-paraschiv** [tomchentw/react-google-maps#147]
I think I found the bug that causes this.
[This is line 149](https://github.com/sergiu-paraschiv/react-google-maps/blob/master/src/creators/OverlayViewCreator.js#L149) in `OverlayViewCreator.js`:
`this.getOverlayView()._redraw(this.props.mapPaneName !== prevProps);`

Pretty clear what the bug is. The condition is always going to be true.

**Comment by sergiu-paraschiv** [comment]
Made a PR for this: https://github.com/tomchentw/react-google-maps/pull/148

**Comment by tomchentw** [comment]
Kind of stupid, thanks for the fix and PR!

**Comment by sergiu-paraschiv** [comment]
Glad to be of service :)

**Comment by tomchentw** [comment]
Released [v4.3.3](https://github.com/tomchentw/react-google-maps/releases/tag/v4.3.3)
