### ISSUE TITLE
Icon resolution

### ISSUE THREAD

**Issue by captDaylight** [tomchentw/react-google-maps#149]
The Icon that I'm setting for my marker is coming in pixelated on my computer. I'm trying to figure out how to deal with 2x, 3x etc, how would I go about doing this?

**Comment by tomchentw** [comment]
Try looking at the official Google Maps JavaScript API v3 document? My initial thought is set the url for the icon dynamically to get different icons for different screens.

**Comment by tomchentw** [comment]
Close for now.

**Comment by tomchentw** [comment]
We're also looking for maintainers. Involve in #266 to help strengthen our community!
