### ISSUE TITLE
Binding new event after using DrawingManager

### ISSUE THREAD

**Issue by mychaelgo** [tomchentw/react-google-maps#151]
For example : i use DrawingManager to draw a polygon, and i can get coordinates from polygon i have drawn, but how i can bind the drag event for example to my polygon?

**Comment by tomchentw** [comment]
The `DrawingManager` is a component with state. So the polygon created by it is not controlled by `react-google-maps`. If you wish to control that, you'll have to:

1. setup a listener for `DrawingManager`
2. whenever a polygon is created, read out the data from the polygon from the event argument and save it to your `this.state`
3. render a `Polygon` component with that state
4. clear the state of `DrawingManager`

Not sure if it's doable though ...

**Comment by idolize** [comment]
@tomchentw It's doable - I've been using this exact approach for some time now :smile: It's not ideal in terms of a "controlled" API, because as you mention the `DrawingManager` has already added your "uncontrolled" shape to the map's internal state, but it's easy enough to work around.

```js
handleOverlayComplete = (evt) => {
  const type = evt.type;
  const overlay = evt.overlay;

  // Use react-google-maps instead of the created overlay object
  google.maps.event.clearInstanceListeners(overlay);
  overlay.setMap(null);

  // Ok, now we can handle the event in a "controlled" way
  this.props.doSomethingReactWithTheData(overlay);
  // ex:
  // let radius = shape.getRadius();
  // let center = shape.getCenter();
  // this.setState({ circles: [ ...this.state.circles, { radius, center }]});
}

<DrawingManager
  {...props}
  onOverlaycomplete={this.handleOverlayComplete}
/>
```

**Comment by idolize** [comment]
Perhaps this would be a good "advanced" example in the `gh-pages`

**Comment by tomchentw** [comment]
We're going to look into this shortly. Feel free to submit a PR. Close for now

We're also looking for maintainers. Involve in #266 to help strengthen our community!

**Comment by techsolutionlab** [comment]
Hello, onOverlaycomplete is not working.

**Comment by techsolutionlab** [comment]
Could you please let me know about it?
