### ISSUE TITLE
Unexpected token when running webpack

### ISSUE THREAD

**Issue by choiway** [tomchentw/react-google-maps#155]
I'm running the code in the geolocation example in my own app without loading all packages. When I run webpack I get this error and I can't figure out which package I'm missing. Any help would be appreciated. Thanks!

```javascript
Module build failed: SyntaxError: /app/components/Geolocation.js: Unexpected token (26:6)
  24 | export default class Geolocation extends Component {
  25 | 
> 26 |   var state = {
     |       ^
  27 |     center: null,
  28 |     content: null,
  29 |     radius: 6000,
```

**Comment by tomchentw** [comment]
`var state = {` is not a valid property initializer. Just use `state = {` and make sure you've configured babel correctly

**Comment by choiway** [comment]
Thanks, Tom. I think I'm missing something in the Babel configuration. I'll look at it again.
