### ISSUE TITLE
I want to make DirectionsRenderer draggable, but it doesn't work.

### ISSUE THREAD

**Issue by wi1d5ky** [tomchentw/react-google-maps#159]
Hi, Tom Chen, I want to do [this](https://developers.google.com/maps/documentation/javascript/examples/directions-draggable), but my direction just stuck. Here is what I did:

``` js 
render () {
	const {directions} = this.state;
	return (
		<GoogleMapLoader
			containerElement={
				<div
					{...this.props}
					style={{
						margin: "1rem 1.75rem",
						height: "300px",
						width: "500px"
					}}/>
			}
			googleMapElement={
			<GoogleMap
				ref="map"
				defaultZoom={17}
				defaultCenter={{ lat: 25.0432253, lng: 121.53263262 }}>
				{directions ?
					<DirectionsRenderer
						directions={directions}
						draggable={true}	// Draggable is here !!!
						map={this.refs.map}
						/> :
					null
				}
			</GoogleMap>
			}
		/>
	);
}
```
Do you know where is the problem?

thanks :)

**Comment by tomchentw** [comment]
First, you don't need to set `map={this.refs.map}` when using `react-google-maps`.

Second, the `draggable` is in `setOptions`, so you'll have to specify it:
https://developers.google.com/maps/documentation/javascript/reference#DirectionsRendererOptions

```js
<DirectionsRenderer
  directions={directions}
  options={{draggable:true}} // or defaultOptions
/> 
```

See `README.md` Rule 4: https://github.com/tomchentw/react-google-maps#rule-4

**Comment by wi1d5ky** [comment]
It works!! I couldn't understand Rule 4 before, but now I realize it!
Thank you for your detailed instant reply. :D

**Comment by tomchentw** [comment]
LOL sorry about the poor documentation :( #128

**Comment by wi1d5ky** [comment]
Nope, it's my bad.
I am new to react & My english isn't very good.
Don't beat yourself up. ;)

**Comment by tomchentw** [comment]
Thanks @wi1d5ky ! Let's keep moving.

**Comment by wi1d5ky** [comment]
Hi, Tom, it's me again :p 
I found that there is an event `directions_changed`, so I use `directionsChanged` as event-trigger but I get nothing... Here is my code:

``` js
updateMapInfo() {
		console.log("this.getDirections()");
}
...
<DirectionsRenderer
	directions={directions}
	options={{draggable:true}}
	directionsChanged={this.updateMapInfo.bind(this)} /> 
```

I have tried `directionsChanged={console.log("yo")}`, but there is nothing neither...

**Comment by Tjorriemorrie** [comment]
Isn't `directions` also in the options? Why is that a normal attribute?
