### ISSUE TITLE
Some issue when I setup this component

### ISSUE THREAD

**Issue by arthuryeti** [tomchentw/react-google-maps#16]
Hi there,

I have tried to use your component like you used on your examples.

It seems that context.getMap() throw an error.

Do you have some idea of the process to install your component ?

**Comment by jerefrer** [comment]
@tomchentw I've been struggling with this component for about everyting I wanted to do and I have found no other solution than to dive into more or less all the Issues and the source code to find little bits of explanations. I admit I'm pretty new to React as well so it hasn't helped.
So yes I absolutely agree : a Getting Started guide would have been deeply appreciated :relieved:
