### ISSUE TITLE
Center/Zoom Change Events Lack Arguments

### ISSUE THREAD

**Issue by bieber** [tomchentw/react-google-maps#160]
The `onCenterChanged` and `onZoomChanged` callbacks don't come with the new center/zoom level of the map, which makes it difficult to use the map in controlled mode (if you're controlling it, you'll have to get the component from a `ref` and manually call `getCenter()` or `getZoom`.  I know the args aren't there in the original Google API, but would you be open to adding them to the `GoogleMap` component?  I'd be glad to write up a pull request for you if you'd be okay with it, just figured I'd check first to see if it's worth doing

**Comment by tomchentw** [comment]
Good question. I'm worried about adding more complexity by adding event to arguments. That means we have to manually maintain the binding between Google Maps JavaScript API v3 and `react-google-maps`.
I think the `ref.getCenter` will do the trick, right? You just feel it's better and closer to React by adding event to arguments.

**Comment by bieber** [comment]
Yep, that's right, and that's a good point: I assume right now you're doing some kind of fairly automated pass-through of events, right?  If you don't feel comfortable moving it into react-google-maps proper, I'll just use a wrapper component that fits my use case a little better
