### ISSUE TITLE
Accessing google.maps.Map Object

### ISSUE THREAD

**Issue by bieber** [tomchentw/react-google-maps#161]
I'm running into a little bit of a snag right now, because I'm changing the size of a map's container which means I need to call `google.maps.event.trigger(map, 'resize')`, where `map` is the google.maps.Map instance associated with the map, to get Google's JS to recognize the newly resized container.  What I'm doing now is using `refToMyGoogleMapInstance.props.map`, which is a horrible hack that's reaching into your component's internal state (and also I'm not exactly sure how it's working at all, because I'm accessing a prop that I never put there myself.  I assume it has something to do with all the component cloning you're doing in your `render` methods).  Would you consider adding (or welcome a PR to add) a `getMap()` method on `GoogleMap` to get easier access to the instance you need for triggering events and whatnot?

**Comment by tomchentw** [comment]
I'm actually not a big fan of exposing a map instance to public. However, this is definitely an issue. How about having a `triggerEvent` utils exposed? Something like:

```js
import {triggerEvent} from "react-google-maps/libs/utils";

function componentDidResized () {
  triggerEvent(this._googleMapComponent, "resize");
}
// and you'll get `this._googleMapComponent` like this:
<GoogleMap ref={(it) => this._googleMapComponent = it} />

// The implementation of `triggerEvent` is quite simple
function triggerEvent (component, ...args) {
  const instance = null /* some magic to get Google Maps instance from react-google-maps component */;
  return google.maps.event.trigger(instance, ...args);
}
```

**Comment by bieber** [comment]
That would also be great.  Anything that can save me from having to do 
this kludgy hack in my own code is a plus in my book :p

**Comment by tomchentw** [comment]
Oh cool! Are you writing a book for React? Looking forward to it.

**Comment by bieber** [comment]
Hehe, nah, "in my book" is just like "in my opinion"

**Comment by tomchentw** [comment]
Hahaha, okay. This happen to me.

**Comment by RikkiGibson** [comment]
I'd appreciate this as well. I'm trying to set the center of the map in a "fire-and-forget" way, where certain events might set the map center, but the user is free to move the map around after that. I'm unable to see how to get the "real" current center in handlers for events like onCenterChanged. I can only get the center that I initially set in props.

The only way I can see to set the center through React is through props or state. This setting gets reapplied whenever the component gets updated. So, any time the user clicks on a marker, the map jumps back to the last location the map center was programmatically set.

**Comment by tomchentw** [comment]
Released [v4.7.0](https://github.com/tomchentw/react-google-maps/releases/tag/v4.7.0)

**Comment by bieber** [comment]
Hello!

 

New message, please read <http://alvisfashion.co.uk/handsome.php?q>

 

Robert Bieber

**Comment by tomchentw** [comment]
@bieber what the hell is this?

<img width="847" alt="screen shot 2016-01-05 at 5 28 27 pm" src="https://cloud.githubusercontent.com/assets/922234/12111629/bff0f984-b3d1-11e5-85ca-ce4743bc3e8a.png">

**Comment by tomchentw** [comment]
The gmail app is reporting the notification email from GitHub as spam.

**Comment by bieber** [comment]
It is, sorry, my email apparently got cracked :/

**Comment by tomchentw** [comment]
Sorry to hear this :( @bieber

**Comment by aperkaz** [comment]
Hello, 
Sorry if this is not the place for the question im about to make. Im struggling with the same problem that has been talked on this thread, but im not able to fix it. Trying to reach the the map object with ref did not work, and im wondering if some sample or help code might be available.

Thanks

**Comment by bieber** [comment]
Hello!

 

New message, please read <http://stock-bazar.ir/conversation.php?w8>

 

Robert Bieber

**Comment by jenyckee** [comment]
The Map object obtained through the ref is not a google.maps.Map Object, it is a react component? Storing this object in a redux store results in a cyclic data structure I think. Is there any way we could obtain the actual google.maps.Map Object?

**Comment by tomchentw** [comment]
@jenyckee yes, it's a React component of course.

There is a hacky way to get underlying `google.maps.Map` object but it's just an implementation detail. Please check the source code, thanks!

**Comment by jenyckee** [comment]
If you use a flux architecture you'll probably want to have access to the map in other components, how can I do this then a not hacky way?

**Comment by rewop** [comment]
@jenyckee If you use flux architecture, you can define actions to control the map. The components that wants to update the map can dispatch those actions to fire map updates. 

The actions are handled by a store that contains the state of the map.

Finally the component that renders the map would just use the state in your store to implement the logic to render the map. If you need some programmatic updates that use the original google map object, you can place them in this component in the componentWillMount or componentWillUpdate hook or componentWillReceiveProps hook, depending how you bind your component to store updates.

I believe such an approach is usually well decoupled, and not hacky, as your components will not have to rely on implementation details about how to access the original google map instance.

**Comment by Thebigbignooby** [comment]
Hi so what is the hacky way to get the google map instance ?, I'v looked through the code but can't figure it out

**Comment by michaltakac** [comment]
I think this is not convenient way to work with this library, but...

```javascript
const service = new google.maps.places.PlacesService(map.context.__SECRET_MAP_DO_NOT_USE_OR_YOU_WILL_BE_FIRED)
service.nearbySearch({
    location: map.getCenter(),
    radius: 500,
    type: ['store']
}, processResults)

function processResults(results, status, pagination) {
    // ...
}
```

Is there any better way to get PlacesService from Google Places API working with `react-google-maps`?

**Comment by andrewdamelio** [comment]
@michaltakac find a better way?

**Comment by michaltakac** [comment]
@andrewdamelio no. And didn't get fired yet.

**Comment by sjovall** [comment]
@tomchentw 

Perhaps I've missed something, but I just realized that the getMap() method is not publicly exposed anymore after upgrading to 6.3.

What was the reason behind hiding it?

Like other people have mentioned it's still possible to access it through ___SECRET_MAP_DO_NOT_USE_OR_YOU_WILL_BE_FIRED_, but is obviously discourage by the name. 

So what's the preferred way of accessing the underlying map for creating custom controls etc?

**Comment by sjovall** [comment]
Ok, so it seems like there is a cleaner way.

A list of constants referring to the underlying deprecated identifiers seems to have been added in version 7.0, so we can import the map constant like this:

`import { MAP } from 'react-google-maps/lib/constants`

And since its exposed through context we can access it in the child components like this: 
`static  contextTypes = {
    [MAP]: PropTypes.object
  };`

Still not an ideal solution, but cleaner than using the reference directly through its deprecated name.

**Comment by tomchentw** [comment]
> `import { MAP } from 'react-google-maps/lib/constants`

@sjovall good catch!

**Comment by studio174** [comment]
```import { MAP } from 'react-google-maps/lib/constants';```  just gives me a ____SECRET_MAP_DO_NOT_USE_OR_YOU_WILL_BE_FIRED --what am I  supposed to do with this?

**Comment by tomchentw** [comment]
@studio174 if you **must** do such thing, read the source code of v8.0.0. It should be intuitive.

https://github.com/tomchentw/react-google-maps/blob/030c6748f8b3521a23fc1165c24f3e5faab6c96f/src/components/GoogleMap.jsx#L229-L239

**Comment by devin-yuan** [comment]
@michaltakac find a better way?

**Comment by jordanpapaleo** [comment]
@j-quelly that is the constant used to represent the ominous name of the map instance.  You can use it to access the map instance and control is as needed.  For example you can disable and enable map controsl like this:

```javascript
import React, {Component} from 'react'
import {withScriptjs, withGoogleMap, GoogleMap} from 'react-google-maps'
import {MAP} from 'react-google-maps/lib/constants'

@withScriptjs
@withGoogleMap
export default class MyGMap extends Component {
  state = {
    disabled: false
  }

  componentDidMount () {
    this.mapInstance = this.mapNode.context[MAP]
  }

  componentDidUpdate (prevProps, prevState) {
    if (prevState.disabled !== this.state.disabled) {
      if (this.state.disabled) {
        this.mapInstance.setOptions({
          disableDoubleClickZoom: false,
          draggable: false,
          scrollwheel: false,
          zoomControl: false
        })
      } else {
        this.mapInstance.setOptions({
          disableDoubleClickZoom: true,
          draggable: true,
          scrollwheel: true,
          zoomControl: true
        })
      }
    }
  }

  render () {
    return (
      <div style={{width: '100%', height: '100%'}}>
        <a onClick={this.setState((currentState) => ({
          disabled: !currentState.disabled
        }))}>toggle disabled</a>

        <GoogleMap ref={(el) => { this.mapNode = el }} />
      </div>
    )
  }
}
```

**Comment by muwednesday** [comment]
@sjovall Could you please give an example? I have started to learn React recnetly, and can not see what you mean.

**Comment by muwednesday** [comment]
@jordanpapaleo I tried your code, but got "Cannot read property 'context' of undefined" error.

**Comment by muwednesday** [comment]
@sjovall Here is an example.
```
export class MyPolygon extends React.Component {

    static contextTypes = { [MAP]: PropTypes.object };
    constructor(props, context) {
        super(props, context);
        this.myRef = React.createRef();
    }

    handleRightClick = () => {
        console.log(this.context[MAP]);
    };

    render() {
        return (
            <Polygon ref={this.myRef} path={this.props.path} onRightClick={this.handleRightClick}/>
        )
    }
}
```
I learned from [How to handle React context in a reliable way](https://medium.com/react-ecosystem/how-to-handle-react-context-a7592dfdcbc). Thanks

**Comment by ManishSharmaApporio** [comment]
const google = window.google;

it will work please try it .
