### ISSUE TITLE
onZoomChanged Doesn't Always Fire

### ISSUE THREAD

**Issue by bieber** [tomchentw/react-google-maps#163]
Maybe I'm just doing something wrong, but I think there might be an issue with the implementation of the `onZoomChanged` callback on `GoogleMap`.  I have an implementation right now that looks like this:

			<GoogleMap
				ref="map"
				center={this.props.center}
				zoom={this.props.zoom}
				onCenterChanged={this.onCenterChanged.bind(this)}
				onZoomChanged={this.onZoomChanged.bind(this)}
			/>

with an `onZoomChanged` method that looks like this:

	onZoomChanged() {
		this.props.onZoomChange(this.refs.map.getZoom());
	}

For some reason, my `onZoomChanged` method gets called when I zoom the map with the +/- buttons, but not if I change it by double-clicking the map or using the mouse wheel.  Even more strangely, if I add this prop to the `GoogleMap` component to hide the street view control:

    options={{streetViewControl: false}}

it does successfully remove the street view control from the map, but then I don't get any zoom events triggered at all.  If it helps, here's the entire file where I'm subscribing to the events: https://github.com/bieber/mapcompare/blob/master/src/js/Map.js

**Comment by bieber** [comment]
I figured out the problem I was having with the double-click/scroll zoom.  The problem was that I was using the map in controlled mode for both zoom and center, and those actions were triggering first a center changed event, which was calling my callback and triggering a rerender, which caused me to never receive the zoom changed event that would have come after.  It's a little bit hacky, but I've solved that by just waiting for about 50ms after a center changed event and then checking both the zoom and center.

The second issue, however, still happens.  For some reason if I remove the street view control, the +/- buttons will only worked if double-clicked pretty rapidly

**Comment by tomchentw** [comment]
> which was calling my callback and triggering a rerender, which caused me to never receive the zoom changed event that would have come after.

Ahhh…got it. That's the tricky part of being a wrapper component. Sigh.

**Comment by tomchentw** [comment]
We're going to look into this shortly. In the meantime, feel free to submit a minimal repository that can fully reproduce this error so that anyone can try to help out. Thanks.

We're also looking for maintainers. Involve in #266 to help strengthen our community!
