### ISSUE TITLE
Get Marker position on dragend

### ISSUE THREAD

**Issue by zellen** [tomchentw/react-google-maps#164]
Hi. Just got a dragend-event to work but I cannot figure out how to get the new position of my marker.

I'm doing onDragend={this.onMarkerPositionChanged} and

onMarkerPositionChanged(e) {
      
   }

But how do I get the new position?

**Comment by zellen** [comment]
Nevermind. Just found the solution... e.latLng.lat()

**Comment by tomchentw** [comment]
:+1:

**Comment by graig12** [comment]
do you mind sharing the full solution for this please

**Comment by graig12** [comment]
never mind figured it out:)

**Comment by urikphytech** [comment]
@graig12 Maybe share your full solution for the next commenter to come?
