### ISSUE TITLE
Attach arbitrary data to marker

### ISSUE THREAD

**Issue by gumbyscout** [tomchentw/react-google-maps#165]
Is there any way to currently attach arbitrary properties to the object returned on a marker click, or the markers listed in a marker cluster click? I've figured out how to just inject stuff directly on a single marker click, but I can't figure out how to bubble up that injected data to a marker cluster. Thanks.

**Comment by tomchentw** [comment]
What do you mean? This doesn't sound like thinking in React ways. Couldn't you put those data in state and render them?

**Comment by gumbyscout** [comment]
What I'm trying to do, is use a bunch of models fetched from the server, which have coordinates and some other data attached to them, and make map markers and clusters out of them. When I click on a cluster or a marker, I need certain information to get the respective models again. The only information I currently can find with clusters, is the coordinates of the markers in that cluster, which isn't helpful because I can have markers with the same coordinates.

**Comment by tomchentw** [comment]
It sounds like we have to look for `MarkerCluster` api if it support this scenario?

**Comment by julienR2** [comment]
It looks like you need a custom marker, holding the info and rendering a marker, don't you ?
I had the same problem and ended up creating a parent class, to which I pass the data fetched from the server. This parent class will display the marker, but can also interact with your data on the marker click.

Little tips, you'll need to pass down the "mapHolderRef" to your child marker though the parent class.
Check this issue for more info: tomchentw/react-google-maps#94

Hope this helps !

**Comment by tomchentw** [comment]
Another thought, 
1. collecting `<Marker>` refs into an object, with `your-data-id` to `marker-inst` mapping.
2. when clicked, iterate this mapping to find the `your-data-id` of the specific `marker-inst`.

**Comment by sohibul** [comment]
@julienR2 how do you get `mapHolderRef`? I tried `this.props.mapHolderRef`, results `undefined`

**Comment by larrybotha** [comment]
@sohibul add `{...props}` to your custom marker when instantiated in your parent component, and then in your custom marker component add `mapHolderRef={ this.props.mapHolderRef}` to the react-google-maps `<Marker />`.

Custom markers need to have it explicitly passed down to them, either through a parent ref (if immediate parent isn't `<GoogleMap />` - all immediate children that are react-google-maps components get a `mapHolderRef` prop), or via `{...props}`, from which it will be passed its parent's props.

**Comment by joshburgess** [comment]
@larrybotha Thanks for the info. Do you know how we would go about passing mapHolderRef to our custom Marker component if it is defined as a stateless functional component? When I created it as a class, it was passed down and worked fine, but not if it was a function. Maybe this isn't possible and it requires the lifecycle methods of an ES6 class component?

**Comment by tomchentw** [comment]
Feel free to submit a PR. Close for now

We're also looking for maintainers. Involve in #266 to help strengthen our community!
