### ISSUE TITLE
Create Circle throws Warning and does not render

### ISSUE THREAD

**Issue by digitaldavenyc** [tomchentw/react-google-maps#169]
I'm trying to add a circle to my map, super simple but it's throwing a warning and not adding it to the map. I'm new to react-google-maps so this may be obvious. Code of my render is below

    Warning: React.createElement: type should not be null, undefined, boolean, or number. It should be a string (for DOM elements) or a ReactClass (for composite components). Check the render method of `Map`.

```
render: function() {
        let circle;
        if(this.state.bounds != null) {
           circle = (<Circle key="circle" center={new google.maps.LatLng(this.state.bounds[0], this.state.bounds[3])} radius={20} options={{
                    fillColor: "red",
                    fillOpacity: 0.20,
                    strokeColor: "red",
                    strokeOpacity: 1,
                    strokeWeight: 1
                    }} />)
        }
        return (
            <div className="map-wrap">
                <div id="map">
                    <GoogleMap defaultCenter={this.state.location} defaultZoom={this.props.zoom} options={_createOptions} onBoundsChange={this._onBoundsChange}>
                        {circle}
                    </GoogleMap>
                </div>
            </div>
        )
    }
```

**Comment by tomchentw** [comment]
What's the warning message?

**Comment by digitaldavenyc** [comment]
It's right above the code

**Comment by tomchentw** [comment]
uhh.. weird, I can't reproduce that on my local. Did you include the google maps javascript api `<script>` tag in your `<head>`?
Or could you fork this repo:
https://github.com/tomchentw/react-google-maps_examples_simple-map
and try to reproduce it there? thanks!

**Comment by tomchentw** [comment]
We're going to look into this shortly. In the meantime, feel free to submit a minimal repository that can fully reproduce this error so that anyone can try to help out. Thanks.

We're also looking for maintainers. Involve in #266 to help strengthen our community!
