### ISSUE TITLE
Changelog?

### ISSUE THREAD

**Issue by srcspider** [tomchentw/react-google-maps#170]
It would help a lot to have a changelog. Was doing some maintenance and `ncu` entry for this looked something like this,

```
react-google-maps            ^1.3.2  →   ^4.7.0
```

The changelog doesn't need to be indepth; just deprecations and breaking changes for the major releases is sufficient.

**Comment by tomchentw** [comment]
Yeah, we do have a [CHANGELOG.md](https://github.com/tomchentw/react-google-maps/blob/master/CHANGELOG.md) in both npm tarball and on GitHub repository. Sorry we don't put them into GitHub releases (if you're talking to this).

**Comment by srcspider** [comment]
Ah! Sorry about that. Went though a lot of packages and a lot of them had the changelog mentioned or in the README. It would probably help someone else who made the same mistake if you add a link to it there, but no big deal.

Thanks.
