### ISSUE TITLE
minZoom and maxZoom seems to not work

### ISSUE THREAD

**Issue by vvo** [tomchentw/react-google-maps#173]
Passing minZoom and maxZoom has no effect on zoom restrictions, any idea?

Simple google maps example without react-google-maps is ok

**Comment by vvo** [comment]
Any idea?

**Comment by tomchentw** [comment]
Put them in the `options` or `defaultOptions` property

**Comment by tomchentw** [comment]
Close for now.

We're also looking for maintainers. Involve in #266 to help strengthen our community!

**Comment by woniesong92** [comment]
@tomchentw when I put it in the `options`, it doesn't seem to work either

**Comment by sameerkambli** [comment]
@tomchentw

**Comment by tomchentw** [comment]
Is `minZoom` or `maxZoom` supported by the official Google Maps JavaScript API v3? If not, then use the solution proposed by @sameerkambli .

**Comment by kafka-tamura** [comment]
@tomchentw minZoom and maxZoom is supported by the official Google Maps Javascript API v3.
