### ISSUE TITLE
None of the UI control props are working

### ISSUE THREAD

**Issue by globexdesigns** [tomchentw/react-google-maps#175]
I'm trying to disable all the buttons on the map:

```
<GoogleMap mapTypeControl={false} panControl={false} streetViewControl={false} zoomControl={false}/>
```

None of those props seem to have any affect.

**Comment by globexdesigns** [comment]
Oops, nevermind. Looks like those needs to go into the `options` props.

**Comment by tomchentw** [comment]
Yes, `options` are the right place. Thanks!

**Comment by micahzev** [comment]
The **react-google-maps** documentation does not explain exactly how to do this.

Here is how you need to code the component:

```
  <GoogleMap
    defaultZoom={12}
    defaultCenter={{ lat: 48.855924, lng: 2.34532 }}
    defaultOptions={{
      styles: mapStyle,
     // these following 7 options turn certain controls off see link below
      streetViewControl: false,
      scaleControl: false,
      mapTypeControl: false,
      panControl: false,
      zoomControl: false,
      rotateControl: false,
      fullscreenControl: false
    }}
    disableDefaultUI />

```
A list of all available control options you can turn on/off are here: [https://developers.google.com/maps/documentation/javascript/controls#Adding_Controls_to_the_Map]
