### ISSUE TITLE
InfoBox doesn't work without google.maps.LatLng

### ISSUE THREAD

**Issue by ImaginateWayne** [tomchentw/react-google-maps#178]
When using `ScriptjsLoader`  the method `new google.maps.LatLng(x,y);`  fails with the error `ReferenceError: google is not defined`

This happens because I need to use the `new google.maps.LatLng(x,y);` method when using the `InfoBox` 

A work around (using the es6 notaion) is to create the object with functions that return the lat and lng for each of the values like so:
```
const myLatLng = {lat: _ => 25.03, lng: _ => 121.6}
...
<InfoBox defaultPosition={myLatLng}  >
...
```
My suggestion would be to be able to pass in a simple object into the InfoBox defaultPosition like so:
```
const myLatLng = {lat: 25.03, lng: 121.6}
...
<InfoBox defaultPosition={myLatLng}  >
...
```
This would remove the need to reference the `google.maps.LatLng ` object.

**Comment by tomchentw** [comment]
I think the official Google Maps JavaScript API v3 supports object literal. See `state.markers[0].position`:
https://tomchentw.github.io/react-google-maps/

However, in this case, it should be an issue of `InfoBox`.

**Comment by tomchentw** [comment]
It should add support for LatLngLiteral for `position` property:
https://github.com/lucasfs7/google-maps-infobox-module/blob/master/infobox-module.js#L89

**Comment by ImaginateWayne** [comment]
Updated title to more accurately describe the issue.

**Comment by tomchentw** [comment]
There's nothing I can do for now.

We're also looking for maintainers. Involve in #266 to help strengthen our community!
