### ISSUE TITLE
MarkerClusterer does not hide infoboxes

### ISSUE THREAD

**Issue by dcodus** [tomchentw/react-google-maps#184]
We are working on a react application using your package. We have encountered a problem with `<Infobox /> `
The problem is that `<Infobox />` is not hidden when using MarkerClusterer. We are trying to have an `<Infobox />` displayed above a marker at all times, but when the markers are clustered we expect the `<Infobox />` to be hidden. 

Here is a link to the code.
https://github.com/dispatch-react/Dispatch-working/blob/Map_dev/src/components/Geolocation.jsx

Can you please suggest a workaround.

**Comment by pirate** [comment]
Huh, I have the exact opposite problem, I cant get `InfoWindow`s to display when using `MarkerClusterer`...  My code is also fairly similar to your posted example.

**Comment by tomchentw** [comment]
Feel free to submit a PR. Close for now

We're also looking for maintainers. Involve in #266 to help strengthen our community!

**Comment by jeangarcia2414** [comment]
Hello , someone managed to solve this problem, I present the same problem and I can not find a solution

**Comment by CodingToBeWithHer** [comment]
Anybody found solution?

I have this behaviour:
open InfoWindow for markerA --> zoom out so markerA is part of cluster --> open infoWindow for markerB somewhere else on the map --> zoom in so markerA is not in cluster --> the empty infoWindow is above markerA for some reason...

**Comment by nehovaysyatopol** [comment]
> open InfoWindow for markerA --> zoom out so markerA is part of cluster --> open infoWindow for markerB somewhere else on the map --> zoom in so markerA is not in cluster --> the empty infoWindow is above markerA for some reason...

I have exactly the same bug. Please help!
