### ISSUE TITLE
Map does not display

### ISSUE THREAD

**Issue by tsaifi9** [tomchentw/react-google-maps#185]
*Versions*
*react@0.14.6*
*react-dom@0.14.6*
*react-google-maps@4.7.2*

Just trying to do a very basic example of getting the map to be displayed. Unfortunately, the map is not visible. There are no errors in the developer console as well 

```
var GoogleMap = require('react-google-maps/lib/GoogleMap');
var GoogleMapLoader = require('react-google-maps/lib/GoogleMapLoader');

var MapContainer = React.createClass({
  render: function() {
    return (
      <section style={{height: "100%"}}>
        map below here
        <GoogleMapLoader
          containerElement={ <div style={{height: "100%"}} /> }
          googleMapElement={ <GoogleMap defaultZoom={3} defaultCenter={{lat: -25.363882, lng: 131.044922}}> </GoogleMap> }
        />
      </section>
    );
  }
});

module.exports = MapContainer;

```

**Comment by tsaifi9** [comment]
fixed the issue. had to give the `section` absolute positioning

**Comment by tomchentw** [comment]
Yeah some tricky part of `height: 100%`

**Comment by deviantony** [comment]
Had the same issue, maybe you should update the example?

Cheers

**Comment by tomchentw** [comment]
We're looking into this shortly! We're also looking for maintainers. Involve in #266 to help strengthen our community!
