### ISSUE TITLE
set methods on marker?

### ISSUE THREAD

**Issue by kellyrmilligan** [tomchentw/react-google-maps#19]
I have a use case where on mouseover I want to change the icon of the marker. maybe i'm not 'thinking in react' but I don't see a way to do this with this library presently, as when I grab the ref to the marker, the setIcon method is not there. any ideas?

**Comment by kellyrmilligan** [comment]
sorry to bother you, any ideas on how to dynamically update existing markers?  the only solution i've found, but causes the markers to flicker is to set an active marker on the state, and when building the markers change that one that was clicked/hovered. this is not ideal for user experience of course. i'm investigating just rolling my own if this is not possible with this component.

**Comment by tomchentw** [comment]
Thinking in React:
* when hover, call setState() to change it
* in render function, use `this.state` to determine which icon to use for the marker, and pass to it: 
`<Marker icon={icon} />`

**Comment by tomchentw** [comment]
That's why I don't expose any `set` related methods out to the component.

**Comment by tomchentw** [comment]
#44

**Comment by tomchentw** [comment]
Close this. Feel free to reopen.

**Comment by Ghostavio** [comment]
I'm having the same problem

**Comment by tomchentw** [comment]
@Ghostavio could you use `props` to change the `<Marker>` component?
