### ISSUE TITLE
SearchBox not working after breaking change

### ISSUE THREAD

**Issue by lauffenp** [tomchentw/react-google-maps#190]
Where in the 'hierarchy' does Search Box go?

Is it nested inside  GoogleMap  tag? 

I get the following errors:
Uncaught TypeError: Cannot read property 'SearchBox' of undefined
Uncaught TypeError: Cannot read property '_currentElement' of null

I'd be happy to update the example if I could get a little direction.

**Comment by bitdivision** [comment]
I'm having this issue too.

**Comment by bitdivision** [comment]
I fixed the console error by adding `&libraries=places` to the maps script URL.

Unfortunately I've now got a grey map with no obvious console errors :(

**Comment by bitdivision** [comment]
Actually. my issue was caused by an undefined centre, nothing to do with SearchBox.

It should start working if you include the above library @lauffenp

**Comment by lauffenp** [comment]
Cool, that does it with the maps scripts URL. I can work on updating the example.

**Comment by lauffenp** [comment]
I am not able to alter the placeholder prop, however. If I find a solution I will update here.

**Comment by luisrudge** [comment]
I had this problem too. I had to add the `?libraries=places` to the maps script url as well.. Is this documented anywhere?
Maybe we can add a check [here](https://github.com/tomchentw/react-google-maps/blob/11262457d8a8d14ff6c0f3b1dfc2ac299f0cd066/src/creators/SearchBoxCreator.js#L46) and throw a warning/exception with some info on how to fix the issue?

@tomchentw do you want me to PR this?

**Comment by lauffenp** [comment]
@luisrudge can you change the placeholder prop?

**Comment by luisrudge** [comment]
@lauffenp yep.. not sure that has anything to do with what I said though..

**Comment by lauffenp** [comment]
@luisrudge How were you able to do that? Just adding 

````
<SearchBox
...
placeholder = {yourPlaceHolderString}
...
/>
````

doesn't work for me.

 I could update @tomchentw 's example if you could just give me a little more information.

**Comment by luisrudge** [comment]
this is my component:

```
<GoogleMapLoader                                                                  
  containerElement={<div style={{height}} /> }                                    
  googleMapElement={                                                              
    <GoogleMap                                                                    
      ref="map"                                                                   
      onZoomChanged={::this.zoomChanged}                                          
      zoom={zoom}                                                                 
      center={googleCenter}                                                       
    >                                                                             
    <SearchBox                                                                    
      controlPosition={google.maps.ControlPosition.TOP_CENTER}                    
      onPlacesChanged={::this.addressChanged}                                     
      ref="searchBox"                                                             
      placeholder="Pick an Address"                                               
      style={styles.searchBox}                                                    
    />                                                                            
    {!isSameLocationAsDefaultCenter(center) && <Marker position={googleCenter} />}
  </GoogleMap>                                                                    
  }                                                                               
/>                                                                                
```

**Comment by lauffenp** [comment]
Man, I cannot figure out why this escapes me. In the react console it shows that the placeholder prop is changed, but its not on the screen.

<img width="1261" alt="screen shot 2016-02-03 at 2 30 30 pm" src="https://cloud.githubusercontent.com/assets/8912028/12797764/d38cc5aa-ca82-11e5-9e0b-e0613a22d124.png">

` render () {

    return (
       <GoogleMapLoader
        containerElement={
          <div
            style={{
              height: "100%",
            }}
                  

          />
        }
        googleMapElement={
          <GoogleMap
            defaultZoom={3}
            defaultCenter={{lat: -25.363882, lng: 131.044922}}
            placeholder="Customized"
        >
           <SearchBox
          controlPosition={google.maps.ControlPosition.TOP_LEFT}
          ref="searchBox"
        placeholder="Customized your placeholder"
        onPlacesChanged={this.handlePlacesChanged}
        style={inputStyle}
        />
          </GoogleMap>
        }
      />
    );

  }`

**Comment by lauffenp** [comment]
Updating your react-google-maps dependency solves this problem.

**Comment by Eilt** [comment]
AppComponent.html:1 ERROR TypeError: Cannot read property 'ControlPosition' of undefined
    at MapmainComponent.push../src/app/mapmain/mapmain.component.ts.


![image](https://user-images.githubusercontent.com/39511541/43768766-5b5ea664-9a4d-11e8-8310-f2988be8fce9.png)


import { Component, OnInit, NgZone, ViewChild, ElementRef  } from '@angular/core';
import { MapsAPILoader } from '@agm/core/services/maps-api-loader/maps-api-loader';
import { AgmMap } from '@agm/core';



@Component({
  selector: 'app-mapmain',
  templateUrl: './mapmain.component.html',
  styleUrls: ['./mapmain.component.css']
})
export class MapmainComponent implements OnInit {
  
 
  
  lat: number = 36.6683764;
  lng: number = 48.5146292;
  zoom = 8;
  private agmMap: any;
  bounds: google.maps.LatLngBounds;
  searchBox: any;
  markers: Array<any>;
  icon: any;

  @ViewChild('search') public searchElement: ElementRef;
  places: any;
  
  @ViewChild('agmMap') set content(map: AgmMap) {
    if (map) {
      map.mapReady.subscribe(map => {
        this.agmMap = map;
      });
    }
    
  }
  
  constructor(private mapsAPILoader: MapsAPILoader,
    private NgZone: NgZone, ) {
   
      
      
    }
    ngOnInit(){
      
      // this.mapsAPILoader.load().then(() => {
        
      //     let autocomplete = new google.maps.places.Autocomplete(
      //         this.searchElement.nativeElement, { types: ["address"] });
      //  if(autocomplete!=undefined)
      // autocomplete.addListener('place_changed', () => {
      //   this.NgZone.run(() => {
      //     let place: google.maps.places.PlaceResult = autocomplete.getPlace();
      //     // console.log(place.geometry.location.lat().toString() + place.geometry.location.lng().toString())
      //     this.lat = place.geometry.location.lat();
      //     this.lng = place.geometry.location.lng();
      //     if (place.geometry === undefined || place.geometry === null) {
      //       return;
      //     }
      //   });
      // });

   // });
    this.places = this.searchElement;
    this.bounds = new google.maps.LatLngBounds();
    this.searchBox = new google.maps.places.SearchBox(this.searchElement.nativeElement);
    this.agmMap.ControlPosition[google.maps.ControlPosition.TOP_LEFT].push(this.searchElement.nativeElement);
    this.agmMap.addListener('bounds_changed', () => {
      this.searchBox.setBounds(this.agmMap.getBounds());
    });
    this.searchBox.addListener('places_changed', () => {
      var places = this.searchBox.getPlaces();

      if (places.length == 0) {
        return;
      }

      // Clear out the old markers.
      this.markers.forEach(marker => {
        marker.setMap(null);
      });
      this.markers = [];
      this.bounds = new google.maps.LatLngBounds();
      places.forEach(place => {
        if (!place.geometry) {
          console.log("Returned place contains no geometry");
          return;
        }
        this.icon = {
          url: place.icon,
          size: new google.maps.Size(71, 71),
          origin: new google.maps.Point(0, 0),
          anchor: new google.maps.Point(17, 34),
          scaledSize: new google.maps.Size(25, 25)
        }
        this.markers.push(new google.maps.Marker({
          map: this.agmMap,
          icon: this.icon,
          title: place.name,
          position: place.geometry.location
        }));
        if (place.geometry.viewport) {
          // Only geocodes have viewport.
          this.bounds.union(place.geometry.viewport);
        } else {
          this.bounds.extend(place.geometry.location);
        }
      });
      this.agmMap.fitBounds(this.bounds);
    });
  };

  

    }

**Comment by Eilt** [comment]
ERROR TypeError: Cannot read property 'ControlPosition' of undefined
    at MapmainComponent.push../src/app/mapmain/mapmain.component.ts.MapmainComponent.ngOnInit

![image](https://user-images.githubusercontent.com/39511541/43768901-ababb346-9a4d-11e8-9f61-36c610951fc0.png)


main map.ts


import { Component, OnInit, NgZone, ViewChild, ElementRef  } from '@angular/core';
import { MapsAPILoader } from '@agm/core/services/maps-api-loader/maps-api-loader';
import { AgmMap } from '@agm/core';



@Component({
  selector: 'app-mapmain',
  templateUrl: './mapmain.component.html',
  styleUrls: ['./mapmain.component.css']
})
export class MapmainComponent implements OnInit {
  
 
  
  lat: number = 36.6683764;
  lng: number = 48.5146292;
  zoom = 8;
  private agmMap: any;
  bounds: google.maps.LatLngBounds;
  searchBox: any;
  markers: Array<any>;
  icon: any;

  @ViewChild('search') public searchElement: ElementRef;
  places: any;
  
  @ViewChild('agmMap') set content(map: AgmMap) {
    if (map) {
      map.mapReady.subscribe(map => {
        this.agmMap = map;
      });
    }
    
  }
  
  constructor(private mapsAPILoader: MapsAPILoader,
    private NgZone: NgZone, ) {
   
      
      
    }
    ngOnInit(){
      
      // this.mapsAPILoader.load().then(() => {
        
      //     let autocomplete = new google.maps.places.Autocomplete(
      //         this.searchElement.nativeElement, { types: ["address"] });
      //  if(autocomplete!=undefined)
      // autocomplete.addListener('place_changed', () => {
      //   this.NgZone.run(() => {
      //     let place: google.maps.places.PlaceResult = autocomplete.getPlace();
      //     // console.log(place.geometry.location.lat().toString() + place.geometry.location.lng().toString())
      //     this.lat = place.geometry.location.lat();
      //     this.lng = place.geometry.location.lng();
      //     if (place.geometry === undefined || place.geometry === null) {
      //       return;
      //     }
      //   });
      // });

   // });
    this.places = this.searchElement;
    this.bounds = new google.maps.LatLngBounds();
    this.searchBox = new google.maps.places.SearchBox(this.searchElement.nativeElement);
    this.agmMap.ControlPosition[google.maps.ControlPosition.TOP_LEFT].push(this.searchElement.nativeElement);
    this.agmMap.addListener('bounds_changed', () => {
      this.searchBox.setBounds(this.agmMap.getBounds());
    });
    this.searchBox.addListener('places_changed', () => {
      var places = this.searchBox.getPlaces();

      if (places.length == 0) {
        return;
      }

      // Clear out the old markers.
      this.markers.forEach(marker => {
        marker.setMap(null);
      });
      this.markers = [];
      this.bounds = new google.maps.LatLngBounds();
      places.forEach(place => {
        if (!place.geometry) {
          console.log("Returned place contains no geometry");
          return;
        }
        this.icon = {
          url: place.icon,
          size: new google.maps.Size(71, 71),
          origin: new google.maps.Point(0, 0),
          anchor: new google.maps.Point(17, 34),
          scaledSize: new google.maps.Size(25, 25)
        }
        this.markers.push(new google.maps.Marker({
          map: this.agmMap,
          icon: this.icon,
          title: place.name,
          position: place.geometry.location
        }));
        if (place.geometry.viewport) {
          // Only geocodes have viewport.
          this.bounds.union(place.geometry.viewport);
        } else {
          this.bounds.extend(place.geometry.location);
        }
      });
      this.agmMap.fitBounds(this.bounds);
    });
  };

  

    }






mainmap.html



<nav class="navbar navbar-expand-md navbar-dark bg-dark fixed-top">
  <a class="navbar-brand" href="#">MAP</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExampleDefault" aria-controls="navbarsExampleDefault"
    aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarsExampleDefault">
    <ul class="navbar-nav mr-auto">

    </ul>


    <input class="form-control mr-sm-3" type="text" placeholder="Search for Location" autocorrect="off" autocapitalize="off"
      spellcheck="off" class="form-control" #search  id="pac-input" class="controls">

  </div >
</nav>

<div class="container">

  <div class="row">
    <div class="col-md-12">
      <div class="map">
        <agm-map #agmMap [latitude]="lat" [longitude]="lng" [zoom]="zoom" 
        [disableDefaultUI]=false [disableDefaultUI]=false
           >
       
          <agm-marker [latitude]="lat" [longitude]="lng">
          </agm-marker>
        </agm-map>
      </div>
    </div>
  </div>

</div>

**Comment by jainChetan81** [comment]
> I fixed the console error by adding `&libraries=places` to the maps script URL.
> 
> Unfortunately I've now got a grey map with no obvious console errors :(

that surprisingly worked...

**Comment by tsryu** [comment]
It worked when I added `{libraries: [ 'places']}`  on bootstrapURLKeys

```
bootstrapURLKeys={{ key: KEY_GOOGLE_MAP, language: 'en', libraries: ['places'] }}
```

**Comment by JustFly1984** [comment]
@tsryu The repo of this project is unmaintained more than 3 years, and we had build new version https://www.npmjs.com/package/@react-google-maps/api

We had rewrite it to TypeScript, and updating it frequently: https://github.com/JustFly1984/react-google-maps-api/tree/master/packages/react-google-maps-api
You can enjoy autocomplete.

You can see our docs: https://react-google-maps-api-docs.netlify.app

Also a lot of examples: https://react-google-maps-api-gatsby-demo.netlify.app/ https://github.com/JustFly1984/react-google-maps-api/tree/master/packages/react-google-maps-api-gatsby-example/src/examples

The bundle size is much smaller: https://bundlephobia.com/result?p=@react-google-maps/api

Our Spectrum community: https://spectrum.chat/react-google-maps Our Slack channel: https://join.slack.com/t/react-google-maps-api/shared_invite/enQtODc5ODU1NTY5MzQ4LTBiNTYzZmY1YmVjYzJhZThkMGU0YzUwZjJkNGJmYjk4YjQyYjZhMDk2YThlZGEzNDc0M2RhNjBmMWE4ZTJiMjQ

Enjoy!
