### ISSUE TITLE
bundled script compiles with React

### ISSUE THREAD

**Issue by larrybotha** [tomchentw/react-google-maps#191]
Not sure if I'm just being a noob here, but testing with both JSPM and browserify my bundled script compiles with the full React library when I'd prefer not to have React in my bundle.

I see both React and ReactDOM are peer dependencies; I'm confused as to why React is being bundled at all.

I've tested importing one module from react-google-maps vs no modules (not importing any React modules in either situation) and the difference is a few lines of code vs 20000.

Am I the only person seeing this?

**Comment by tomchentw** [comment]
Not sure. I never use JSPM before. I think you need to configure it correctly to let the module bundler knows where to load React from, since you don't want it in your bundle, then there must be some place to find React.

**Comment by larrybotha** [comment]
I get the same result with Browserify, though :/

Been battling for a while with Browserify and JSPM trying to see where I may have been going wrong. I may have to give WebPack another bash.

When importing react-google-maps into another application, if you don't import React into your app does WebPack compile without React for you?

**Comment by tomchentw** [comment]
We're going to look into this shortly. In the meantime, feel free to submit a minimal repository that can fully reproduce this error so that anyone can try to help out. Thanks.

We're also looking for maintainers. Involve in #266 to help strengthen our community!
