### ISSUE TITLE
Marker Clusterer not rendering

### ISSUE THREAD

**Issue by lauffenp** [tomchentw/react-google-maps#192]
I've got about 60 markers being displayed and am clustering:

<img width="925" alt="screen shot 2016-01-21 at 2 36 30 pm" src="https://cloud.githubusercontent.com/assets/8912028/12481873/67a24364-c04c-11e5-98d4-6d643711eabe.png">

I've got an event where I am setting a key within the props passed to markers when moused over and changing the icon to a yellow version:

<img width="922" alt="screen shot 2016-01-21 at 2 38 05 pm" src="https://cloud.githubusercontent.com/assets/8912028/12481895/a0ab7fc2-c04c-11e5-84c0-e0b01c2395e6.png">
But, often when mousing over, the marker cluster are not rendering:
<img width="907" alt="screen shot 2016-01-21 at 2 49 37 pm" src="https://cloud.githubusercontent.com/assets/8912028/12482142/4dfbaf2a-c04e-11e5-95e9-bcdb3204be79.png">

````
handleMouseOver(index,event){
let markers =[]
if (this.state.markerState===true){
        markers = this.state.markers;
} else {
     markers = this.props.Annotation;
}
markers[index] = update(markers[index],{
       flashkey: {
               $set:true
       }
})
    this.setState({ 
        markerState:true,
        markers:markers }); 
}
````
Then in the render method, either the this.state.markers or this.props.Annotation is passed to features, which is fed into a .reduce function inside of MarkerCluster:
````
<MarkerClusterer
           averageCenter={ true }
           enableRetinaIcons={ true }
           gridSize={ 20 }
           maxZoom = {15}
               ignoreHidden = {true}
                   styles= {mcStyles}>
   {features.reduce((array, feature, index) => {
        const {properties} = feature;
        const video = feature
        const {...geometry} = geometryToComponentWithLatLng(feature.location);        
            if (feature.flashkey != true) {
            array.push(
              <Marker 
                 visible = {true}
                 key={feature.id} 
                 icon = {{url:'public/img/icon.png'}}
                 {...properties}
                 {...geometry} 
                onClick = {this.props.onMarkerClick.bind(null, this, video)}
                 onMouseover={this.handleMouseOver.bind(this, index)} 
                >
              </Marker>
            );
               } else {
                array.push(
              <Marker  
                 visible = {true}
                 key={feature.id} 
                 icon = {{url:'public/img/yellow_icon.png'}}
                zIndex = {1000}
                 {...properties}
                 {...geometry} 
                onClick = {this.props.onMarkerClick.bind(null, this, video)}
                 onMouseout={this.handleMouseOut.bind(this, index)} 
                >
              </Marker>
                 );
               }
          return array;
        }, [], this)}
    </MarkerClusterer>
````

Is there something basic I'm missing here? I've been beating my head against the wall. The features array is fully populating, but items are being dropped from marker clustering. If I remove the marker cluster, it works fine.

**Comment by hmeerlo** [comment]
I have got the same problem. My map view is re-rendered every 10 seconds when new data comes in. But when it renders the second time, the MarkerClusterer disappears.

**Comment by lauffenp** [comment]
#172  Shows the same issue.

If I remove the zoom control on my <GoogleMap> tag it fixes the issue.

**Comment by lauffenp** [comment]
Closing to reduce issue buildup and redundancy

**Comment by hdrdavies** [comment]
@lauffenp did you resolve your problem?

**Comment by lauffenp** [comment]
Sorry @hdrdavies for the silence. I did resolve it by removing the zoom control on the googlemap tag. I'm starting a new project now so I will update this repo with additional issues.
