### ISSUE TITLE
Arbitrary ReactComponent on map

### ISSUE THREAD

**Issue by thunderkid** [tomchentw/react-google-maps#195]
Hi,
Is it possible to use arbitrary React components on a map? In your example I only see the use of the Marker class. Adding arbitrary react components can be done with the [google-map-react](https://github.com/istarkov/google-map-react) library, but that one doesn't cover as much of the google api as yours. I'm trying to choose between libraries.
Thanks!

**Comment by medmunds** [comment]
I'm having generally good luck using the OverlayView component to insert arbitrary React-based DOM into a map. (I'm using it for custom SVG markers.)

https://tomchentw.github.io/react-google-maps/#basics/overlay-view.

**Comment by dcworldwide** [comment]
@medmunds interesting idea. How many items are you rendering at once? Any drawbacks to this approach?

**Comment by thunderkid** [comment]
And do you know how this approach compares to the google-map-react library?

**Comment by medmunds** [comment]
@dcworldwide I haven't done extensive testing yet, but just playing around I've used >20 individual OverlayViews without noticing any obvious performance issues. I believe Google Maps uses some optimized compositing for its native markers, so you wouldn't be getting that.

The only other problem I've run into is there's no easy way to control zIndex on the OverlayViews. (I have a question open about that elsewhere in this project.)

@thunderkid I haven't used google-map-react personally, but glancing through their code, it looks like they also use a Google Maps [OverlayView](https://developers.google.com/maps/documentation/javascript/reference#OverlayView) to hold the React components. One difference is they seem to use a single GMaps OverlayView to hold all the React components. They make that overlay as large as possible, and individually [position the child components within it by lat/lng props][1].

I don't know if the single-overlay approach is more performant. (If so, it wouldn't be too hard to render all your components in a single react-google-maps OverlayView, by essentially duplicating the positioning code from google-map-react and listening for the map's onProjectionChange to update the positions.)

One slight advantage to multiple overlays with react-google-maps is that the getPixelPositionOffset callback gives you your React component's rendered width and height, making it really easy to position your component anywhere relative to the lat/lng (center, bottom-right, whatever).

[1]: https://github.com/istarkov/google-map-react/blob/64ca283d23b14b89ae627b4e972656aff40e051c/src/google_map_markers.js#L216-L220

**Comment by jcheroske** [comment]
I've found that using user-defined components works, but that you must manually pass down props used internally by this library. The internal google maps objects, such as the underlying map, are passed down with props and not context. I use a pattern like this:

```
const MyMapComponent({myProp1, myProp2, ...props}) {
  return <Marker position={something} {...props} />
}
```

**Comment by tomchentw** [comment]
Since we now have major adoption for `react@^0.14`, we should be able to fix this.

We're also looking for maintainers. Involve in #266 to help strengthen our community!
