### ISSUE TITLE
Overlapped markers (OverlappingMarkerSpiderfier, MarkerCluster……etc)

### ISSUE THREAD

**Issue by asaf** [tomchentw/react-google-maps#198]
Hey,

I have a situation where marked items overlaps each other,
Is there any supported visualisation that handles this case?

I came across this: http://jawj.github.io/OverlappingMarkerSpiderfier/demo.html

Thanks,

Asaf.

**Comment by pirate** [comment]
https://tomchentw.github.io/react-google-maps/#basics/marker-clusterer

**Comment by simonbs** [comment]
Did anyone get OverlappingMarkerSpiderfier working with React Google Maps and possibilyt the marker clusterer?

**Comment by tomchentw** [comment]
Feel free to create a wrapper component around `OverlappingMarkerSpiderfier`. PR is welcomed

**Comment by Bazze** [comment]
I did get the OverlappingMarkerSpiderfier to work, however I had to get some hooks into this library before it was possible. More specifically I needed to be able to access the map and marker objects after they had been initialized. See my 3 commits to accomplish this here: https://github.com/Bazze/react-google-maps/tree/v4.7.2-oms-edits

Then I do the following in my app to get it working:
```
onMapInitialized(map) {
	this.oms = new OverlappingMarkerSpiderfier(map);

	this.oms.addListener('click', (marker, event) => {
		let m = _.find(this.state.markers, {_markerObject: marker});

		m.showInfo = true;
		this.setState(this.state);
	});

	this.initMarkers();
}

onMarkerInitialized(marker, gmMarker) {
	marker._markerObject = gmMarker;

	this.setState({ markers: this.state.markers });

	this.oms.addMarker(gmMarker);
}
```

Not very pretty, but it works. I'd definitely love a more "official" solution for this :)

**Comment by tomchentw** [comment]
Feel free to submit a PR. Close for now

We're also looking for maintainers. Involve in #266 to help strengthen our community!
