### ISSUE TITLE
Question: setting zIndex on OverlayView

### ISSUE THREAD

**Issue by medmunds** [tomchentw/react-google-maps#199]
I need to control the stacking order of multiple OverlayViews. Is there a good way to set a zIndex on an OverlayView, and have it actually affect the stacking?

```jsx
const pos = {lat: -34.397, lng: 150.644};

<GoogleMap defaultZoom={8} defaultCenter={pos}>
  <OverlayView position={pos} mapPaneName={OverlayView.OVERLAY_MOUSE_TARGET}>
    <div style={{zIndex: 2}} ref="childDiv">This should be in front</div>
  </OverlayView>
  <OverlayView position={pos} mapPaneName={OverlayView.OVERLAY_MOUSE_TARGET}>
    <div style={{zIndex: 1}}>This should be in back</div>
  </OverlayView>
</GoogleMap>
```

Setting zIndex on the `<div>` child of the OverlayView doesn't change the stacking, because each OverlayView actually gets [wrapped in a _containerElement div][1]. It seems like the zIndex would need to go on that container.

And the OverlayView component doesn't seem to accept a style prop for the container, or have its own zIndex prop (like a Marker does).

I'm currently hacking it by setting the containerElement's style inside the OverlayView's getPixelPositionOffset callback. (Roughly `this.refs.childDiv.parentNode.style.zIndex = 2`. Using getPixelPosition because the container element must exist by then.). But this seems incredibly hacky. Is there a better way?

Here's [a fiddle][2] with full example code. (Though it won't actually run in jsfiddle. Aside: is there a library version of react-google-maps hosted somewhere that could be used from a fiddle?)

[1]: https://github.com/tomchentw/react-google-maps/blob/v4.7.2/src/creators/OverlayViewCreator.js#L51-L52
[2]: https://jsfiddle.net/medmunds/9b7qr7v8/

**Comment by tomchentw** [comment]
Related to #93

**Comment by Tux1** [comment]
Finally how did you manage your issue ?

**Comment by medmunds** [comment]
@Tux1 for now, I'm just using the hack described above, which seems to work even though it's ugly. For the exact code, look for "uncomment this for a hack workaround" in the fiddle linked in the original report.

Long term, the solution described in #93 (getting rid of the extra wrapper div) sounds like the best approach. (Unfortunately, I'm on some other projects right now, and won't be able to look into that myself for at least a month.)

**Comment by tomchentw** [comment]
Feel free to submit a PR. Close for now

We're also looking for maintainers. Involve in #266 to help strengthen our community!
