### ISSUE TITLE
compare to pieterv/react-googlemaps

### ISSUE THREAD

**Issue by razum2um** [tomchentw/react-google-maps#20]
Is there any substantial disadvantages in https://github.com/pieterv/react-googlemaps which was started in September'14.

What are the advantages of your version?

**Comment by tomchentw** [comment]
I found that repo after I've finished this project, lol. And after carefully looking into their codes,
Pros of `react-google-maps`:
* Abstraction: using context to pass internal google map instance
* DSL Components: writing your Google Map component in declarative way

Pros of `react-googlemaps`:
* Clean interface and definition for props and events: the definite it explicitly

**Comment by razum2um** [comment]
thanks for response, see also https://github.com/pieterv/react-googlemaps/issues/14
