### ISSUE TITLE
can't set searchbox value progamatically

### ISSUE THREAD

**Issue by luisrudge** [tomchentw/react-google-maps#200]
This lib is insane! Thanks for that!

I'm using this lib with redux and I can't set the value of the SearchBox progamatically. This is a problem whenever the component is umounted and mounted again, since the map element is re-created. Other props like `center` and `zoom` are persisted with redux and passed as props. What I want, is to pass the SearchText value as props as well. Do you think that's possible?
Here's a gif showing the issue:

![gmaps](https://cloud.githubusercontent.com/assets/941075/12772343/8e4a8e52-ca17-11e5-9e3a-d51d9fd061b4.gif)

Thanks again!

**Comment by rairity** [comment]
The link below provides an answer for how to set the SearchBox value programmatically (the solution even goes so far as describing how you might also automatically fire the search event); it's not a React-ified solution, so your mileage may vary.

http://stackoverflow.com/a/24462418

a fiddle:

http://jsfiddle.net/doktormolle/R8XdL/

**Comment by luisrudge** [comment]
Maybe that can work, but I'm not messing with google's stuff in my code, only react-google-maps.. I'm opening the issue so we can discuss how to add this behavior to the current lib.

**Comment by tomchentw** [comment]
@luisrudge could you take a look at the source code of `SearchBox` and issue a PR to make it work? I believe it's doable.

**Comment by tomchentw** [comment]
We're going to look into this shortly. Thanks for providing the gif.

We're also looking for maintainers. Involve in #266 to help strengthen our community!

**Comment by dash1291** [comment]
Did anyone work on this feature?

**Comment by ivandevp** [comment]
Is there any solution to this use case?

**Comment by akhilmr95** [comment]
@tomchentw  can you please let us know when this solution might be available? My use case is i want to clear the search box input value when i do an onClick of a cancel button. I do not have a way to access the searchbox input value to reset it. Please let us know your thoughts and thanks a ton for this library..!!

**Comment by JustFly1984** [comment]
@akhilmr95 this repo is unmaintained about a year, please look at https://github.com/JustFly1984/react-google-maps-api instead

**Comment by akhilmr95** [comment]
@JustFly1984  i do not see any example for searching and plotting a marker in your examples. Is this something in your pipeline? or am i looking at the wrong place? i am referring the examples here:- https://github.com/JustFly1984/react-google-maps-api/tree/master/examples/react-google-maps-api-gatsby/src/examples

**Comment by JustFly1984** [comment]
@akhilmr95 You could try to make an example yourself. Maintainers are welcome

**Comment by akhilmr95** [comment]
@tomchentw  Can you please look into this issue? It would be of great help if we can access the value of the search box. Also it would be very helpful to provide an onSelect which would return the address selected from the dropdown when we search. Please look into this. Thanks..!!
