### ISSUE TITLE
Question: how to use "panel" with DirectionsRenderer?

### ISSUE THREAD

**Issue by antoinechalifour** [tomchentw/react-google-maps#201]
Hi there!
First of all, fantastic work on this project, thank you!

Here is my question: How to render the "panel" part of the DirectionsRenderer? In the original library, you can do it using the following configuration:

```javascript
const directions = new google.maps.DirectionsRenderer({
  map,
  panel // where panel is a reference to some DOM node
});
```

Is there a similar functionality with this React port?

**Comment by tomchentw** [comment]
Hmmm interesting, would you try to pass in `panel` as props of `< DirectionsRenderer>`?

**Comment by tomchentw** [comment]
Feel free to submit a PR. Close for now

We're also looking for maintainers. Involve in #266 to help strengthen our community!
