### ISSUE TITLE
Define OverlayView position using bound

### ISSUE THREAD

**Issue by uriklar** [tomchentw/react-google-maps#205]
Hi, and thanks for the great library!
My question is: Can an OverlayView position be defined by passing bounds like in google's example:
https://developers.google.com/maps/documentation/javascript/examples/overlay-simple

My issue is that when I zoom out the overlay grows instead of shrinking. I would like to define bounds and have it stick to them. Is that possible? Any suggestions?

I will happily supply any necessary code. 
Thanks!

**Comment by uriklar** [comment]
@tomchentw I create a PR adding the bounds param. Let me know what you think.
https://github.com/tomchentw/react-google-maps/pull/206

**Comment by tomchentw** [comment]
Thanks! Released [v4.9.0](https://github.com/tomchentw/react-google-maps/releases/tag/v4.9.0)
