### ISSUE TITLE
How to use the streetView attribute of GoogleMap component.

### ISSUE THREAD

**Issue by rohangeorge91** [tomchentw/react-google-maps#207]
Hello,

First off, I am new to both React and Google-Maps, so pardon my ignorance. I wanted to know how to pass a 'google.maps.StreetViewPanorama' object to the streetView attribute of <GoogleMap>. I check the google streetView example and figured out that we need to pass 'google.maps.StreetViewPanorama' to the setStreetView method with the appropriate lat, lng and other value parameters.

I used the below example to understand google-street-views
https://developers.google.com/maps/documentation/javascript/examples/streetview-embed

Thank you in advance

**Comment by tomchentw** [comment]
`google.maps.StreetViewPanorama` is currently not supported. Wanna open a PR?

**Comment by rohangeorge91** [comment]
It would be really nice, if you could. :) ..If you can't no problem, I always have plan B (Using IFrames via dangerouslysetinnerhtml, not a big fan of this approach... But it should work..)

**Comment by tomchentw** [comment]
Feel free to submit a PR. Close for now

We're also looking for maintainers. Involve in #266 to help strengthen our community!

**Comment by elcsiga** [comment]
A simple tandalone Google Street View component for React.js can be found here: https://github.com/elcsiga/react-streetview

**Comment by roeib** [comment]
@tomchentw is google.maps.StreetViewPanorama is still not available??
