### ISSUE TITLE
Help using map with react-redux boilerplate

### ISSUE THREAD

**Issue by OkuraSt** [tomchentw/react-google-maps#208]
Hi everyone,
Im trying to use this package with react-redux boilerplate https://github.com/erikras/react-redux-universal-hot-example, however I get an error like this:

Warning: setState(...): Can only update a mounted or mounting component. This usually means you called setState() on an unmounted component. This is a no-op. Please check the code for the undefined component.

On that repository I read an issue suggesting that, the map rendering should be made only on client side, so I added a state variable to modify on componentDidMount but the error persist. I made a gist with the example: https://github.com/OkuraSt/example-maps

The map component name is AsyncMap and it is added on Home.js. I hope someone could give a hint.
Thanks for your time

**Comment by tomchentw** [comment]
Link to https://github.com/OkuraSt/example-maps is dead.

**Comment by OkuraSt** [comment]
Sorry for the late response,
I was able to make the map appear by setting the height and witdh to a number of pixels. My problem now is to resize to 100% height after the map has loaded, I was seeing this post, https://github.com/tomchentw/react-google-maps/issues/161 where you indicate new functionality with the triggerEvent but the error I get on my code is that "react-google-maps/libs/utils" is not found.
Could you help me with some directions on how to do this?
Thanks in advance for your time.

**Comment by tomchentw** [comment]
Please update your version of `react-google-maps`. https://github.com/tomchentw/react-google-maps/blob/v4.10.3/lib/utils/index.js
