### ISSUE TITLE
DirectionsRenderer apply props

### ISSUE THREAD

**Issue by kifahhk** [tomchentw/react-google-maps#211]
Hello, 

DirectionsRenderer doesn't seem to pass props to map options.
For example: `<DirectionsRenderer  suppressMarkers={true} .../>`
 does not hide markers.
etc..

am I doing something wrong?

**Comment by tomchentw** [comment]
Could you be more elaborate?
https://tomchentw.github.io/react-google-maps/#basics/directions

**Comment by kifahhk** [comment]
Sorry, I forgot code pattern. ^^
`<DirectionsRenderer` suppressMarkers={true} markerOptions.../>`

Idea?

**Comment by tomchentw** [comment]
Set it in the `options` props:

```js
<DirectionsRenderer
  options={{suppressMarkers: true}}
/>
```

See `README.md` for more information.

**Comment by tomchentw** [comment]
We're working on this to make it clearer.

We're also looking for maintainers. Involve in #266 to help strengthen our community!
