### ISSUE TITLE
geolocation example code doesn't seem to correspond with behavior

### ISSUE THREAD

**Issue by jedwards1211** [tomchentw/react-google-maps#212]
The Geolocation example passes `center` in as a controlled prop, and only changes it when the location service responds -- it doesn't register any `onCenterChanged` handler.  Thus it shouldn't be possible to move the map away from the original position, and I conclude that the example code isn't what the demo actually uses.

**Comment by tomchentw** [comment]
Yeah it will be better if we pass uncontrolled `defaultCenter` to `<GoogleMaps>`. Wanna help for a PR?
https://tomchentw.github.io/react-google-maps/#basics/geolocation

**Comment by tomchentw** [comment]
We're working on this to make it clearer.

We're also looking for maintainers. Involve in #266 to help strengthen our community!
