### ISSUE TITLE
How to display infowindow????

### ISSUE THREAD

**Issue by ga12ru12** [tomchentw/react-google-maps#213]
I can't see any document about **infowindow**. Please give me some tutorial, document or example to display a infowindow when click a marker pls. Tks :)

**Comment by amitkothari** [comment]
@ga12ru12 Here is an example with InfoWindow - https://tomchentw.github.io/react-google-maps/#events/event-closure

**Comment by tomchentw** [comment]
Thanks @amitkothari !
