### ISSUE TITLE
Click on map to add marker one step state behind

### ISSUE THREAD

**Issue by azamuddin** [tomchentw/react-google-maps#217]
Trying your example page on clicking map to add marker, after several markers, ot starts to lag one step state behind. 

Trying on my project and it has the same behaviour.

**Comment by sebastialonso** [comment]
Does it happens every time? Only when you have several markers?

`state` is updated asynchronously, so if you are rendering the markers the line after `setState`, you might be experiencing the 'back to the past' event.

**Comment by tomchentw** [comment]
We're going to look into this shortly. Feel free to submit a gif to demonstrate the behaviour.

We're also looking for maintainers. Involve in #266 to help strengthen our community!
