### ISSUE TITLE
InfoWindow DOM element leak

### ISSUE THREAD

**Issue by Coobaha** [tomchentw/react-google-maps#218]
Hi!
It seems that InfoWindow is creating DOM element, but it doesnt remove it on unmount cycle.
You can see this on a screenshot from [this example](https://tomchentw.github.io/react-google-maps/#/basics/pop-up-window?_k=lrnn4p)
<img width="1041" alt="screenshot 2016-02-27 10 46 34" src="https://cloud.githubusercontent.com/assets/2446638/13371795/b87c6534-dd3f-11e5-8df1-b9d0c3251c1e.png">

**Comment by zlwaterfield** [comment]
Having same issue @Coobaha have you found a fix or a way around it?

**Comment by tomchentw** [comment]
We're going to look into this shortly. Close for now.

We're also looking for maintainers. Involve in #266 to help strengthen our community!
