### ISSUE TITLE
Usage with React-router?

### ISSUE THREAD

**Issue by richtier** [tomchentw/react-google-maps#219]
According to a [few sources](https://code.google.com/p/gmaps-api-issues/issues/detail?id=3803#c32), it looks like google maps instances cannot be cleanly destroyed and re-created, and the expectation is for the developer to 'reuse' the existing google maps instance.

This is problematic because when using google maps in an app with a router, the default behaviour is for the existing view to be destroyed.

Before I reinvent the wheel - has this problem been encountered before for `react-google-maps`?

**Comment by tomchentw** [comment]
Not sure if it's related to #11 . But we didn't handle it in `react-google-maps`

**Comment by richtier** [comment]
a pool looks like it would also solve this problem. I will close this issue and get involved in #11.
