### ISSUE TITLE
Only one direction shows on map

### ISSUE THREAD

**Issue by Tjorriemorrie** [tomchentw/react-google-maps#221]
I'm calling the DirectionsService with:
> provideRouteAlternatives: true,

which gives me 3 routes back.

I pass that array into `<DirectionsRenderer directions={directions} />` but only the first route is shown on the map, and not all 3. Is there a specific way to get the map to show all the routes and you can click on them like on Google Maps?

**Comment by tomchentw** [comment]
We're going to look into this shortly. In the meantime, feel free to submit a minimal repository that can fully reproduce this error so that anyone can try to help out. Thanks.

We're also looking for maintainers. Involve in #266 to help strengthen our community!

**Comment by aneraosiddhesh** [comment]
Any solution found for above...?
