### ISSUE TITLE
ERR_BLOCKED_BY_CLIENT: Any specific reason why Chrome is blocking the script?

### ISSUE THREAD

**Issue by sebastialonso** [tomchentw/react-google-maps#222]
I'm loading the Google Maps library using ScriptjsLoader

~~~
<ScriptjsLoader
          hostname={"maps.googleapis.com"}
          pathname={"/maps/api/js"}
          query={{v: 3, libraries: 'geometry,drawing,places'}}
          loadingElement={
            <div>
              <p>loading</p>
            </div>
          }
          containerElement={
            <div />
          }
          googleMapElement={
            <GoogleMap
              defaultZoom={3}
              defaultCenter={{lat: -25.363882, lng: 131.044922}}
            />
          }
        />
~~~

But I'm getting this error on the console
~~~
v=2&s=mapsapi3&v3v=23.7&action=apiboot2&libraries=geometry%2Cdrawing%2Cplaces&rt=main.16:1 GET http://csi.gstatic.com/csi?v=2&s=mapsapi3&v3v=23.7&action=apiboot2&libraries=geometry%2Cdrawing%2Cplaces&rt=main.16 net::ERR_BLOCKED_BY_CLIENT
~~~

The `<p>loading</p>` element appears briefly so the map is being loaded correctly.

I also tried loading the script manually from index.html, but it's the same. Is my Chrime guilty of this behaviour?

**Comment by riaan53** [comment]
Do you use addblock in chrome? I had some issues with that.

On Friday, 04 March 2016, Sebastián González <notifications@github.com>
wrote:

> I'm loading the Google Maps library using ScriptjsLoader
>
> <ScriptjsLoader
>           hostname={"maps.googleapis.com"}
>           pathname={"/maps/api/js"}
>           query={{v: 3, libraries: 'geometry,drawing,places'}}
>           loadingElement={
>             <div>
>               <p>loading</p>
>             </div>
>           }
>           containerElement={
>             <div />
>           }
>           googleMapElement={
>             <GoogleMap
>               defaultZoom={3}
>               defaultCenter={{lat: -25.363882, lng: 131.044922}}
>             />
>           }
>         />
>
> But I'm getting this error on the console
>
> v=2&s=mapsapi3&v3v=23.7&action=apiboot2&libraries=geometry%2Cdrawing%2Cplaces&rt=main.16:1 GET http://csi.gstatic.com/csi?v=2&s=mapsapi3&v3v=23.7&action=apiboot2&libraries=geometry%2Cdrawing%2Cplaces&rt=main.16 net::ERR_BLOCKED_BY_CLIENT
>
> I also tried loading the script manually from index.html, but it's the
> same. Is my Chrime guilty of this behaviour?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/tomchentw/react-google-maps/issues/222>.
>


-- 
Riaan Jacobs
riaan53@gmail.com

**Comment by sebastialonso** [comment]
I use uBlock yes. How can I bypass something like this?

Removing uBlock is obviously not an option, since many users the tool.

**Comment by tomchentw** [comment]
I don't know how to deal with adBlock. Sorry about that. Close for now.

We're also looking for maintainers. Involve in #266 to help strengthen our community!

**Comment by drallieiv** [comment]
For now you can add csi.gstatic.com to the exclusion of your adblocker

**Comment by RFlintstone** [comment]
Had the same problem on my subdomain. I turned UBlock Origin off (this will exclude that (sub)domain from (ad)blocking certain content) and now it works again!

So for developers: Maybe search for an API or create some code that detects these errors and tell the user/admin that they need to disable an adblocker to use the (sub)domain / script effectively.

**Comment by Chetabahana** [comment]
If you are running multiple extensions that perform ad or script blocking you will need to individually update [_each one to your whitelist_](https://stackoverflow.com/a/50151073/4058484).

**Comment by i1u5** [comment]
An easy fix is to [whitelist your site on the ad blocker](https://www.wikihow.com/Whitelist-wikiHow-on-an-Ad-Blocker#Using_uBlock_Origin_sub). After all, it's just _your_ website.
