### ISSUE TITLE
center and zoom controlled parameter not always working

### ISSUE THREAD

**Issue by joostaafjes** [tomchentw/react-google-maps#223]
hi Tom

First of all, thanks for all the effort you have put into this component.

I have an issue with the center and zoom property:
I have made center and zoom parameters controlled.The same as you did in the simple click event example. This works fine in all browsers except on any device with a touchscreen (iPad, phone). When I do a two finger pinch to zoom this is directly undone. The same happens also with you simple click event example.

Do you have any clue what causes this? And how to fix it?

br
Joost

**Comment by tomchentw** [comment]
I don't know. Sorry about that. Close for now

We're also looking for maintainers. Involve in #266 to help strengthen our community!
