### ISSUE TITLE
Extending OverlayView

### ISSUE THREAD

**Issue by Tux1** [tomchentw/react-google-maps#225]
Hi guys,

I would like to extend the OverlayView to create my own kind of marker with style.
It would be very convenient to be able to extend OverlayView and make it as a React Component. Or a kind of wrapper around OV

What do you recommend to do that ? 
How would you do ?

Thanks

**Comment by Tux1** [comment]
Finally I just did that :
```
const Marker = (props) => {
  const color = colorMap(props.price);
  return (
    <OverlayView
      getPixelPositionOffset={getPixelPositionOffset}
      position={props.position}
      mapPaneName={OverlayView.OVERLAY_LAYER}
      mapHolderRef={props.mapHolderRef}>
      <div className={'marker-container z-depth-1 ' + color}>
        <div className="marker-content">{props.price}</div>
      </div>
    </OverlayView>
  );
};
```

**Comment by tomchentw** [comment]
Glad it's resolved! We're also looking for maintainers. Involve in #266 to help strengthen our community!
