### ISSUE TITLE
Map is disappearing at zoom level 17 when I have a bunch of markers.

### ISSUE THREAD

**Issue by figalex** [tomchentw/react-google-maps#226]
My map displays correctly from zoom levels 0 to 16, but when I zoom in to level 17 the whole HTML element that contains the map just disappears.

I have no clue of why is this happening, it would be great if somebody could tell me what should I check to debug this problem.

**Comment by tomchentw** [comment]
We're going to look into this shortly. In the meantime, feel free to submit a minimal repository that can fully reproduce this error so that anyone can try to help out. Thanks.

We're also looking for maintainers. Involve in #266 to help strengthen our community!
