### ISSUE TITLE
`bounds` property on OverlayView doesn't work

### ISSUE THREAD

**Issue by atomanyih** [tomchentw/react-google-maps#227]
if you pass in a bounds object you get the error `this.bounds.getSouthWest() is not a function`

I think it's because of these lines: https://github.com/tomchentw/react-google-maps/blob/master/src/creators/OverlayViewCreator.js#L154-L155

should it be `bounds.getSouthWest()` instead of `this.bounds.getSouthWest()`?

side note: the example on http://tomchentw.github.io/react-google-maps/#/basics/overlay-view?_k=pyb6k6 has extra curlies brace for `sw`

```
bounds={
  {
    ne: { lat: 62.400471, lng: -150.005608 },
    sw: { { lat: 62.281819, lng: -150.287132 } }
  }
```

**Comment by tomchentw** [comment]
We're going to look into this shortly. 

We're also looking for maintainers. Involve in #266 to help strengthen our community!

**Comment by jj117** [comment]
Anyone have a fix?
