### ISSUE TITLE
Bug in the "closure listeners" example

### ISSUE THREAD

**Issue by idolize** [tomchentw/react-google-maps#228]
https://tomchentw.github.io/react-google-maps/#/events/closure-listeners

Clicking the markers with react elements in the popups causes weird behavior (ex: opens other popups simultaneously).

I haven't bug too deep to figure out the root cause, but I thought I'd report the issue.

**Comment by tomchentw** [comment]
We're going to look into this shortly.

We're also looking for maintainers. Involve in #266 to help strengthen our community!
