### ISSUE TITLE
'Warning: owner-based and parent-based contexts differ'

### ISSUE THREAD

**Issue by grav** [tomchentw/react-google-maps#23]
Using React 0.13, I get several warnings about `owner-based and parent-based contexts differ`. 

I haven't been using the Context-feature of React myself, but it seems that components using owner-based context (which react-google-maps apparently is), won't be compatible with the next release of React, which is why React 0.13 is issuing warnings. There's more info here: http://facebook.github.io/react/blog/#owner

**Comment by grav** [comment]
Hmm, currently I cannot even get react-google-maps to work with React 0.13. I get the error `Uncaught TypeError: Can't add property context, object is not extensible`

**Comment by tomchentw** [comment]
Released [v1.0.0](https://github.com/tomchentw/react-google-maps/releases/tag/v1.0.0) and closed this now.
