### ISSUE TITLE
Turn draggable, scrollwheel options to false. 

### ISSUE THREAD

**Issue by sohilpandya** [tomchentw/react-google-maps#230]
Hi, I want to be able to turn off the zoomonscroll option for the map, and am unable to do so, have tried a few different ways to go about it, but no luck

Would like some help trying to solve this.

**Comment by sohilpandya** [comment]
Sorry, I figured it out, had to put it as options.
`                 <GoogleMap options={{ scrollwheel: false}} >
`

**Comment by tomchentw** [comment]
Glad it's resolved! We're also looking for maintainers. Involve in #266 to help strengthen our community!
