### ISSUE TITLE
Seems to unmount incorrectly

### ISSUE THREAD

**Issue by frazr** [tomchentw/react-google-maps#234]
I've run into an issue when re-rendering the component.
Please check http://stackoverflow.com/questions/36202623/react-google-maps-re-rendering-issue
To confirm if it's a bug or if i'm misunderstanding the use of the component.

**Comment by tomchentw** [comment]
Seems fixed on SO. Close for now.

We're also looking for maintainers. Involve in #266 to help strengthen our community!
