### ISSUE TITLE
Error communication with api

### ISSUE THREAD

**Issue by KaueMre** [tomchentw/react-google-maps#236]
I am trying open the react-google-maps in my application but the request for the maps API doesn't work, this is my code:

`var React = require('react');

var GoogleMapLoader = require('react-google-maps/lib/GoogleMapLoader'); 
var GoogleMap = require('react-google-maps/lib/GoogleMap'); 

var GoogleMap = React.createClass(
{
	
	/** React mount
	 *  Todas as funções chamadas na montagem do componente
	 *  getInitialState, getDefaultProps, propTypes, mixins, statics, displayName
	 */
	getInitialState: function () {
		return {
		}
	}, 

	render: function() 
	{ 
		return (
   
						    
			<GoogleMapLoader 
	          containerElement={ <div style={{height: "100%"}} /> }
	          googleMapElement={ <GoogleMap defaultZoom={3} defaultCenter={{lat: -25.363882, lng: 131.044922}}> </GoogleMap> }
	        /> 
 

		);
	} 

});

module.exports = GoogleMap;

`

This is what happend in firefox:

[http://i.imgur.com/ukBt38H.png](http://i.imgur.com/ukBt38H.png)

**Comment by tomchentw** [comment]
I believe this is an issue of googles' own servers. Close for now.

We're also looking for maintainers. Involve in #266 to help strengthen our community!
