### ISSUE TITLE
Accessing google.maps.Map Object, yet another case

### ISSUE THREAD

**Issue by deflexor** [tomchentw/react-google-maps#239]
For example i has one component `<MyMap/>`, which contains `<GoogleMap/>`. And now i need another component `<PlaceFineder/>` which uses `google.maps.places.PlacesService` which requires `google.maps.Map` object. So is there possibility to pass `google.maps.Map` from `<MyMap/> ` component to `<PlaceFineder/>` component ? Something like:
```
<MyMap ref="mymap" />
...
<PlaceFinder map={this.refsmymap.props.map} />
```
this although should work, but not applicable in my case, is there another way ?

**Comment by indurnath** [comment]
If you need a reference of map object, You  can try like this:
ref={googleMap => {
                        if (!googleMap) {
                        return ;
                        }
                            console.log(googleMap);
                            this.gmap = googleMap;
                        } }
                  this.gmap.props.map   will give you the reference to map .

**Comment by tomchentw** [comment]
We're going to look into this shortly.

We're also looking for maintainers. Involve in #266 to help strengthen our community!
