### ISSUE TITLE
React-google-maps and React 15.0.x

### ISSUE THREAD

**Issue by n0ne** [tomchentw/react-google-maps#243]
I can't even install with React 15.0.1
How I can solve it?

**Comment by kgcmd** [comment]
+1

**Comment by roocell** [comment]
+1 that'd be real nice.

**Comment by tomchentw** [comment]
Published [v4.10.0](https://github.com/tomchentw/react-google-maps/releases/tag/v4.10.0)

**Comment by andrewsuzuki** [comment]
Looks like react-prop-types-element-of-type is still on 1.0.2 instead of 2.1.0, so npm is still issuing an unmet peer dep for me.

**Comment by tomchentw** [comment]
Published [v4.10.1](https://github.com/tomchentw/react-google-maps/releases/tag/v4.10.1)

@andrewsuzuki
