### ISSUE TITLE
What is AsyncGettingStarted ?

### ISSUE THREAD

**Issue by MoOx** [tomchentw/react-google-maps#247]
I saw this in react-google-maps/lib/async/ScriptjsLoader examples.
I found this https://github.com/tomchentw/react-google-maps/blob/5e672b92f3e47861126349a5691c33b9b1d1eb88/examples/gh-pages/src/pages/AsyncGettingStarted.js#L16 but this sound unreal.

Why ScriptjsLoader does not provide default values for hostname, pathname etc?

**Comment by tomchentw** [comment]
Good question! Yeah! `ScriptjsLoader` should provide some default values for `hostname/pathname` since they're rarely changed.

For the random `version` in example, it's used in development of `ScriptjsLoader` but I should remove it.

**Comment by tomchentw** [comment]
We're also looking for maintainers. Involve in #266 to help strengthen our community!
