### ISSUE TITLE
TypeError: Failed to execute 'getComputedStyle' on 'Window'

### ISSUE THREAD

**Issue by nvtcp9x** [tomchentw/react-google-maps#249]
I'm have a bug when i use google maps component: **"Uncaught TypeError: Failed to execute 'getComputedStyle' on 'Window': parameter 1 is not of type 'Element'"** (in Firefox: TypeError: Argument 1 of Window.getComputedStyle does not implement interface Element)
And here is the code:
 ```
 <GoogleMapLoader
        containerElement={
          <div
            {...this.props}
            style={{
              height: `100%`,
            }}
          />
        }
        googleMapElement={
          <GoogleMap
            ref={(map) => (this._googleMapComponent = map) && console.log(map.getZoom())}
            defaultZoom={3}
            defaultCenter={{ lat: -25.363882, lng: 131.044922 }}
          >
          </GoogleMap>
        }
      />
```
This code is very simple, and in the other project i can run it normaly, but in this project is not, so i really don't know why, please help me fix this problem

**Comment by tomchentw** [comment]
We're going to look into this shortly. In the meantime, feel free to submit a minimal repository that can fully reproduce this error so that anyone can try to help out. Thanks.

We're also looking for maintainers. Involve in #266 to help strengthen our community!
