### ISSUE TITLE
Allow React component as InfoWindow content 

### ISSUE THREAD

**Issue by sslash** [tomchentw/react-google-maps#25]
It seems that the content in the InfoWindow has to be a String. 
However it would be nice to allow more complex UI's here, like a React component as the content.

**Comment by tomchentw** [comment]
Kind of interesting. What's your expected API ?

**Comment by tomchentw** [comment]
Since #32 is landed, currently the `InfoWindow` API would look like this:
`<InfoWindow title="Blabla" onClick={this.handleClick} />`

Combined with marker:
```js
<Marker lat={lat} lng={lng}>
  <InfoWindow title="Blabla" onClick={this.handleClick}>
</Marker>
```

## Proposed API for `InfoWindow` with React component:
```js
<InfoWindow title="Blabla" onClick={this.handleClick}>
  <MyFancyReactComponent>
    <ItShouldAlsoSupportDiffAlgorithmHere />
  </MyFancyReactComponent>
</InfoWindow>
```
Is this what you want?

**Comment by wuct** [comment]
:+1: This API is exactly what I want. But a content of `InfoWindow` is not in a react shadow DOMs tree, how will you implement this?

**Comment by MetalMatze** [comment]
This would be exactly what I need. It's crucial for my application!

**Comment by tomchentw** [comment]
This can be implement by the following:

1. Create a detached DOM using `document.createElement`
2. Render the passed in child using `React.render(React.Children.only(props.children), detachedDOM)`
3. Pass the `detachedDOM` into InfoWindow({content: detachedDOM})

What do you guys think?

**Comment by wuct** [comment]
After passing the `detachDOM` to a `InfoWindow`,  a `InfoWindow` will can [setOptions](https://github.com/tomchentw/react-google-maps/blob/master/src%2Finternals%2FSimpleChildComponent.js#L35) to set the content internally. So the content of `InfoWindow` will remount into GoogleMaps DOM tree every time when the `InfoWindow` is update and won't utilize React diff right?

**Comment by tomchentw** [comment]
No. As long as the `detachedDOM` is the same instance, React will recognize it.

**Comment by MetalMatze** [comment]
I know it's impolite to ask if anyone has implemented this feature, but I want to do it anyway since I would need this feature. Is there any progress? I'm just building my first app with react and I'm not quite sure if I could implement this feature myself. Sorry.

**Comment by tomchentw** [comment]
Released [v2.0.0] and [v2.0.1].

[v2.0.0]: https://github.com/tomchentw/react-google-maps/releases/tag/v2.0.0
[v2.0.1]: https://github.com/tomchentw/react-google-maps/releases/tag/v2.0.1

**Comment by ashishchoudhary12** [comment]
how to hide infow window close buttom???

**Comment by ashishchoudhary12** [comment]
how to hide infow window close buttom???

**Comment by sriniss13** [comment]
how to customize info window

**Comment by umair-khanzada** [comment]
what about the Marker, can we pass jsx element against marker's icon props ?
