### ISSUE TITLE
For marker cluster,  If you called it twice, The cluster will disappear.

### ISSUE THREAD

**Issue by bibobibo** [tomchentw/react-google-maps#250]
I add event handdler `this.refs.map.fitBounds(bounds)` once the page size changed.
Sometimes, the page size is changed, but the map container size is not changed(this is our requirement, we have a max map size limitation for huge screen), In this case, the cluster will disappear.
I also try to call `this.refs.map.fitBounds(bounds)` twice and then I find the cluster is also disappeared.

**Comment by bibobibo** [comment]
Is there anyone focusing on this issue?

**Comment by tomchentw** [comment]
We're going to look into this shortly.


We're also looking for maintainers. Involve in #266 to help strengthen our community!
