### ISSUE TITLE
Instructions for using infoBox addon

### ISSUE THREAD

**Issue by corbpaul** [tomchentw/react-google-maps#253]
I'm trying to use the infoBox addon but am coming across several issues:

1. InfoBox always shows to bottom left of marker - how do I change to be top center?
2. Setting z-index does nothing so any links within the content aren't clickable
3. Adding a component in the 'content' parameter renders [object Object] rather than the content
4. Can I add extra class names to infoBox to attach separate styling?

**Comment by tomchentw** [comment]
Glad it's resolved! We're also looking for maintainers. Involve in #266 to help strengthen our community!
