### ISSUE TITLE
Infobox Styling

### ISSUE THREAD

**Issue by carlosperalta88** [tomchentw/react-google-maps#254]
I have a couple of questions about the infobox component, the first one is that I have a map with several markers and the infobox displays whenever I hover on the marker, but if I hover the infobox and there's a marker behind it, it will close the current infobox and display the new one instead. 

The second one is how to I change the close image from the infobox?

Thank you.

**Comment by corbpaul** [comment]
For the close image I think you need to do something like this:
`<InfoBox
                options={
                    {
                        closeBoxURL: 'url-to-image.jpg '
                    }
                }
            >`

Maybe zIndex option would solve the hover issue. I found more at the [official docs](http://google-maps-utility-library-v3.googlecode.com/svn/trunk/infobox/docs/reference.html)

**Comment by tomchentw** [comment]
We're going to look into this shortly.

We're also looking for maintainers. Involve in #266 to help strengthen our community!

**Comment by lako90** [comment]
Someone resolved the infoBox over other markers issue?
