### ISSUE TITLE
MarkerClusterer images and others are broken due to google-maps-utility-library-v3 moving to github

### ISSUE THREAD

**Issue by pirate** [tomchentw/react-google-maps#255]
Since google code is shutting down, google has moved their utility library from Google Code to github:

Images urls pointing to their old library no longer work, and will have to be changed, e.g.:

`http://google-maps-utility-library-v3.googlecode.com/svn/trunk/markerclustererplus/images/m2.png`
<img src="http://google-maps-utility-library-v3.googlecode.com/svn/trunk/markerclustererplus/images/m2.png"/>

to
`https://raw.githubusercontent.com/googlemaps/v3-utility-library/master/markerclustererplus/images/m2.png`

<img src="https://raw.githubusercontent.com/googlemaps/v3-utility-library/master/markerclustererplus/images/m2.png"/>

Although ideally there should be an option to let the user self-host them so this doesn't happen again.

**Comment by 11th** [comment]
There is option to self-host the markers. Just set the `imagePath` prop.

From docs:
> @property {string} [imagePath=MarkerClusterer.IMAGE_PATH]
>  *  The full URL of the root name of the group of image files to use for cluster icons.
>  *  The complete file name is of the form `imagePath`n.`imageExtension`
>  *  where n is the image file number (1, 2, etc.).

This works for me:
```cjsx
			<MarkerCluster imagePath="./images/map/clusters/m" />
```

**Comment by pirate** [comment]
Cool, thanks!  I should've checked the docs before mentioning the self-hosting bit.  The default URLs are still broken though, so I'll leave this ticket open for now.

**Comment by wedneyyuri** [comment]
Is there any open pull request about this?

**Comment by pirate** [comment]
What's curious is that the string `google-maps-utility-library-v3.googlecode.com` only exists in commented form in this repo, which makes me think the URL is being dynamically loaded somehow through some google library.  I think we have to find the source of whatever library is loading it and fix it there instead of in this repo.

**Comment by 11th** [comment]
@wedneyyuri nope

@pirate This project has (marker-clusterer-plus)[https://www.npmjs.com/package/marker-clusterer-plus] as a dependency. There you can find the hardcoded, dead url.

**Comment by pirate** [comment]
@11th @wedneyyuri I just opened: https://github.com/mikesaidani/marker-clusterer-plus/pull/2

**Comment by pirate** [comment]
https://github.com/tomchentw/react-google-maps/pull/259

**Comment by mikesaidani** [comment]
Hello guys,

I just published the new version to NPM. Sorry for the inconvenience.
@pirate Thanks for all the efforts :)

Cheers,
Mike

**Comment by tomchentw** [comment]
Published [v4.10.2](https://github.com/tomchentw/react-google-maps/releases/tag/v4.10.2). Thanks to @11th, @pirate, @wedneyyuri and @mikesaidani !

We're also looking for maintainers. Involve in #266 to help strengthen our community!

**Comment by doubleoevan** [comment]
Might want to update this example page so people know that cluster markers are back :) http://react-google-maps.tomchentw.com/#/addons/marker-clusterer?_k=zvrnxa

**Comment by tomchentw** [comment]
@doubleoevan a PR is welcomed!
