### ISSUE TITLE
Is this repo dead ?

### ISSUE THREAD

**Issue by cristiandley** [tomchentw/react-google-maps#256]
There is a nice PR about 

#[PERFORMANCE](https://github.com/tomchentw/react-google-maps/pull/224)
and
 #[HEATMAP](https://github.com/tomchentw/react-google-maps/pull/248)

The performance one is a cool feature... And the only PR being accepted are the ones for typo or documentation.

Thanks

**Comment by windgaucho** [comment]
Yes, would be great if you accept the prs!!

**Comment by cristiandley** [comment]
I created a based version of this repo just to quickly go to production with the new features. If this repo comes active again i will be glad to close mine [https://github.com/cristiandley/react-gl-maps](https://github.com/cristiandley/react-gl-maps)

**Comment by aight8** [comment]
I really would be happy when this library can be passed to someone who have time for it and can manage this repository. It's a good library but one of the popular projects which is going to die sadly.

Any ideas from the author?

**Comment by aight8** [comment]
For all who are interested we are now actively develop on the fork which cristiandley posted (https://github.com/cristiandley/react-gl-maps)
PR's welcome!

**Comment by tomchentw** [comment]
Hi guys, I want to thank you for raising up this. I've created #266 to help organize/clean up issues. Evolve in #266 and please definitely let me know if you like to be part of the maintainers! Thanks @cristiandley , @windgaucho and @aight8 .
