### ISSUE TITLE
onCenterChanged too slow

### ISSUE THREAD

**Issue by Tux1** [tomchentw/react-google-maps#257]
Hi,
I try to make the map controlled but onCenterChanged is very slow because it runs the handling function on each move. Do you have a tips to avoid this issue ?

Many thanks,

**Comment by dyyylan** [comment]
Have you tried using onIdle and just doing a simple comparison to see if the center changed (if you need that)?

**Comment by Tux1** [comment]
Oh good idea. I didn't know this event. Many thanks

**Comment by tomchentw** [comment]
Glad it's resolved! We're also looking for maintainers. Involve in #266 to help strengthen our community!
