### ISSUE TITLE
React > 0.13 cannot work correctly

### ISSUE THREAD

**Issue by elct9620** [tomchentw/react-google-maps#26]
I using babel and React 0.13.1 to build my webapp.
But when I try to add react-google-maps, it break.
I switch back to React 0.12.2 it works, I use `console.log` to track reason, it seems the react-google-maps generate some different code with React 0.13.

Note: material-ui seems to use `react >= 0.12` not `react ^0.12` to let it work with 0.13.

**Comment by tomchentw** [comment]
Thanks for your report! I believe this is a know issue related to  #21.

**Comment by wuct** [comment]
+1

**Comment by tomchentw** [comment]
Released [v1.0.0](https://github.com/tomchentw/react-google-maps/releases/tag/v1.0.0) and closed this now.
