### ISSUE TITLE
Unable to display most basic Map

### ISSUE THREAD

**Issue by padsbanger** [tomchentw/react-google-maps#261]
Hello,

 I am building an app and I was trying out this library by creating most basic map component:

```
import React from 'react'
import { GoogleMapLoader, GoogleMap} from "react-google-maps";

export default (props) => {
  return (
    <GoogleMapLoader
      containerElement={
        <div
          style={{
            height: `100%`,
          }}
        />
      }
      googleMapElement={
        <GoogleMap
          defaultZoom={3}
          defaultCenter={{ lat: -25.363882, lng: 131.044922 }}>
        </GoogleMap>
      }
    />
  )
}

```

Then in my `index.html` I have added:

`<script src="https://maps.googleapis.com/maps/api/js?key=XXXXXXXXXXX"></script>`

But the map is not showing, no error, nothing. Testing in Chrome, FF. Am I missing something ?

Cheers

**Comment by blaind** [comment]
Try setting height in px instead of %

**Comment by padsbanger** [comment]
Ok, stupid me, I had a trailing comma which was breaking the whole component: 

```
        <div
          style={{
            height: `100%`,
          }}
```

Sorry for bothering.

**Comment by tomchentw** [comment]
Glad it's resolved! We're also looking for maintainers. Involve in #266 to help strengthen our community!
