### ISSUE TITLE
Clustered image square tint

### ISSUE THREAD

**Issue by bureku** [tomchentw/react-google-maps#262]
I get this square tint whenever markers are loaded. Sometimes all the clustered markers have this, sometimes only 1 of them has it. It also changed location whenever I zoom in or zoom out. Any ideas on how to avoid this? Thanks. 

![image](https://cloud.githubusercontent.com/assets/316135/15469678/e66b9f5e-20fc-11e6-8329-766384ee03e8.png)

**Comment by tomchentw** [comment]
There's nothing I can do for now.

We're also looking for maintainers. Involve in #266 to help strengthen our community!
