### ISSUE TITLE
Can't run examples locally

### ISSUE THREAD

**Issue by TrangNguyen** [tomchentw/react-google-maps#263]
Hi,
I'm using Mac OSX El Capitan and npm 4. I followed readme instruction for workflow without Docker as
``` 
git clone ...
npm install
cd examples/gh-pages
npm install
npm start 
```
And got this `Error: Couldn't find preset "babel-preset-syntax-from-presets" relative to directory "../react-google-maps/examples/gh-pages"`.
Can anyone point me to further clue? Why does it need this lib? Thanks.

**Comment by tomchentw** [comment]
We're going to look into this shortly.

**Comment by tomchentw** [comment]
We're going to look into this shortly.

We're also looking for maintainers. Involve in #266 to help strengthen our community!

**Comment by matanhalevy** [comment]
i've had the same issue, wondering if this issue is closed was a solution found?

**Comment by tomchentw** [comment]
@matanhalevy did you try to run with latest `master`?

**Comment by matanhalevy** [comment]
@tomchentw i did and it still didn't work, although i was able to implement the library in my own project, big thanks for the great resource!
