### ISSUE TITLE
fitBounds with async js loader: google object not found

### ISSUE THREAD

**Issue by aight8** [tomchentw/react-google-maps#264]
I lazy load the google maps api with the async component.

I want to set the bounds (fitBounds) trough the public api since that is the way instead when I understand it correctly.

But since I load the google maps lib async I can't create a list of LatLngBound since it's in the google maps library which is not loaded.

**Comment by tomchentw** [comment]
Since `google` is asynchronously loaded, you have to handle the logic yourself.

**Comment by tomchentw** [comment]
Since `google` is asynchronously loaded, you have to handle the logic yourself.

We're also looking for maintainers. Involve in #266 to help strengthen our community!
