### ISSUE TITLE
Drawing Manager public APIs

### ISSUE THREAD

**Issue by TrangNguyen** [tomchentw/react-google-maps#265]
Is there a reason why only `getDrawingMode()` is exposed as [public API](https://github.com/tomchentw/react-google-maps/blob/master/src/DrawingManager.js)? Is it a bad practice to expose other methods, like `setDrawingMode()`, `setOptions()`, etc, basically complete reference to drawingManager?
Thanks

**Comment by tomchentw** [comment]
We're working on this to make it clearer.

We're also looking for maintainers. Involve in #266 to help strengthen our community!
