### ISSUE TITLE
Move away from mixins and to wrapper components

### ISSUE THREAD

**Issue by idolizesc** [tomchentw/react-google-maps#27]
React is moving to ES6 classes and away from `React.createClass()`, [but mixins do not work with ES6 classes and are being deprecated](https://facebook.github.io/react/blog/2015/01/27/react-v0.13.0-beta-1.html#mixins).

**The solution? [Move to wrapper components](https://medium.com/@dan_abramov/mixins-are-dead-long-live-higher-order-components-94a0d2f9e750)**.

**Comment by tomchentw** [comment]
Agreed.

**Comment by tomchentw** [comment]
Released [v1.0.0](https://github.com/tomchentw/react-google-maps/releases/tag/v1.0.0) and closed this now.
