### ISSUE TITLE
access to the map instance?

### ISSUE THREAD

**Issue by brigand** [tomchentw/react-google-maps#272]
I want access to the map instance, specifically to call setCenter and setZoom in response to an autocomplete input selection. Is there any way to access it?

I know there are props for zoom/center but I just want to set them once in response to the event and then not manage them.

**Comment by rewop** [comment]
Related to #239

**Comment by agilgur5** [comment]
I actually am managing the center myself, but changing the `center` prop doesn't seem to actually move the map in any way. Not sure if this is a bug, but to workaround this, I would need to call `setCenter` and I can't right now...

**Comment by nbergseng** [comment]
Another use case: accessing the map.data property.  The current GeoJSON example generates shapes and paths instead of using the built in load/addGeoJson functions.  Exposing those properties could make a few things quite a bit easier.

**Comment by nodegin** [comment]
you can do:
```
<GoogleMap ref={ref => {
    ref.props.map.setCenter(latlng)
}}>
```

**Comment by tomchentw** [comment]
This related to #188 where @nodegin said:

> @tomchentw I'm not sure if I was using it in a correct way, I specify a center prop object which contains the initial coordinate, then I modify the center coordinate in a click event which opens a panel, but once I dismiss the panel the map should able for dragging. However, the center variable locks my map movement.

> If I use mapRef.panTo then the problem is solved perfectly by just calling it when my panel is being opened, but I don't want the panning animation (since it's causing lag on mobile).

Does anyone get a good solution for this except for `setCenter`?

**Comment by nat-n** [comment]
It seems to me that a good solution might be for withGoogleMap to provide the map object as a prop to its child?

**Comment by tomchentw** [comment]
Please refer to [Getting Help](https://github.com/tomchentw/react-google-maps#getting-help) section in the README (or #469).

**Comment by fibo** [comment]
for the future me or the future developer with my same issue: @agilgur5 solution worked for me, use `center` instead of `defaultCenter`.
