### ISSUE TITLE
Map should use context to pass map reference to child components

### ISSUE THREAD

**Issue by natorious** [tomchentw/react-google-maps#277]
Right now, Map passes itself as "mapHolderRef" through props to child components via cloning of children. This gets dicey when creating subclasses. For example, this doesn't work:

```
class GeoJsonPolygon extends React.Component {
  render(){
    const {paths} = this.props;
    const newpaths = convertGeoJsonPaths(paths);

    return <Polygon paths={newpaths}/>
  }
}
```

It breaks (without a good error message) because secret mapHolderRef prop is not passed down to Polygon. The fix is easy (pass rest of props using rest-spread) but I had to dig into the code to figure out the problem. 

It would be much easier to use the library, and to compose components, if map reference was passed to the whole subtree behind-the-scenes using react's Context feature: https://facebook.github.io/react/docs/context.html

**Comment by tomchentw** [comment]
Merged in #224
