### ISSUE TITLE
Certain mapOptions don't seem to work

### ISSUE THREAD

**Issue by mtimofiiv** [tomchentw/react-google-maps#279]
Here are the props passed into the component:

<img width="295" alt="screen shot 2016-06-09 at 20 23 44" src="https://cloud.githubusercontent.com/assets/428948/15941435/6976e3e6-2e80-11e6-89c6-fee1c3c5a558.png">

And yet, the map still renders with type control and zoom control:

![screen shot 2016-06-09 at 20 27 29](https://cloud.githubusercontent.com/assets/428948/15941489/b0b8a9a6-2e80-11e6-9dac-85813d482366.png)

Not quite sure what's causing it, as those props match the options provided here:
https://developers.google.com/maps/documentation/javascript/3.exp/reference#MapOptions

Other properties like `center` and `zoom` are respected, however.

Am I doing something wrong?

PS here's the code in question:

```jsx
          <GoogleMapLoader
            containerElement={
              <div
                style={{
                  height: "100%"
                }} />
            }
            googleMapElement={
              <GoogleMap
                ref={(map) => (this._map = map)}
                center={center}
                zoom={store.zoom}
                minZoom={5}
                onDragend={this.dragEnded.bind(this)}
                onZoomChanged={this.zoomHasChanged.bind(this)}
                zoomControl={false}
                scaleControl={false}
                mapTypeControl={false}>
                
              </GoogleMap>
            }
          />

**Comment by mtimofiiv** [comment]
Never mind, sorry, I really should have read "Rule 4". Putting them in the `options` object helped.

But I guess my question is, why an `options` object?

**Comment by cristiandley** [comment]
Thanks @mtimofiiv Im not an expert on this, but my notion says its to achieve a better handling on them.
