### ISSUE TITLE
Use React Storybook to demonstrate components

### ISSUE THREAD

**Issue by pahans** [tomchentw/react-google-maps#282]
Hi @tomchentw , 
We can use [react-storybook](https://github.com/kadirahq/react-storybook/) to demonstrate some use cases for each component. I can work on this issue if you're interested.

**Comment by tomchentw** [comment]
Yes! Please feel free to open up a PR!

**Comment by tomchentw** [comment]
Just to let you know  [6.0.0](https://github.com/tomchentw/react-google-maps/issues/318) is released on npm beta tag now. See the changelog [here](https://github.com/tomchentw/react-google-maps/blob/master/CHANGELOG.md#600-2016-10-04). We also have a new demo page. Feel free to try it:
https://tomchentw.github.io/react-google-maps/

**Comment by tomchentw** [comment]
Anyone interested?

**Comment by Stupidism** [comment]
This stuff is so cool!

**Comment by stereobooster** [comment]
[styleguidist](https://github.com/styleguidist/react-styleguidist) is alternative option for this

**Comment by tomchentw** [comment]
Yeah I like styleguidist.

**Comment by tomchentw** [comment]
Switched to `react-styleguidist` in v8.0.0

https://tomchentw.github.io/react-google-maps/
