### ISSUE TITLE
InfoWindow cannot be used with Polyline

### ISSUE THREAD

**Issue by SantanMaddi** [tomchentw/react-google-maps#283]
`<Polyline {...l} onClick={this.handlePolylineClick.bind(this, l)}>
  <InfoWindow key={l.id}>
    <div className="info">
      <h3>{l.name}</h3>
    </div>
  </InfoWindow>
</Polyline>`

Using InfoWindow with polyline instead of marker. But I do not see InfoWindow on map. Any help is much appreciated.

**Comment by tomchentw** [comment]
Yes, it's not supported at the moment.

**Comment by varun-raj** [comment]
Any idea when this can be supported?

**Comment by oshalygin** [comment]
@varun-raj I can open it up as a new feature request but it's not on the roadmap atm unless other contributors would like to implement this.
