### ISSUE TITLE
Marker image screwed up on draggable=false

### ISSUE THREAD

**Issue by jamaica474** [tomchentw/react-google-maps#288]
Strange behaviour of Marker component. When I set draggable = true it looks just fine, but draggable = false, and it suddenly stops showing properly.

This is how it looks on chrome. On FF markers just disappear.

Marker options:
Object {draggable: true, mapHolderRef: GoogleMapHolder, position: Object}
![image](https://cloud.githubusercontent.com/assets/7143553/16360565/3bf1e8e8-3b38-11e6-8e38-d257e1c2df95.png)

Marker options:
Object {draggable: false, mapHolderRef: GoogleMapHolder, position: Object}
![4j5qag](https://cloud.githubusercontent.com/assets/7143553/16360545/ac7c789a-3b37-11e6-8b6b-56c126afde31.jpg)
G.jpg

**Comment by tomchentw** [comment]
Weird…

**Comment by tomchentw** [comment]
Try using Symbol to define your icon instead of png?

**Comment by jamaica474** [comment]
What do you mean? My icon is base64 encoded svg.

**Comment by tomchentw** [comment]
Sorry, I don't know why this would happen. Could you try native Google Maps JavaScript API v3 and see if it's still have the same bug?

**Comment by tomchentw** [comment]
Close for inactivity.

Also,  [6.0.0](https://github.com/tomchentw/react-google-maps/issues/318) is released on npm beta tag now. See the changelog [here](https://github.com/tomchentw/react-google-maps/blob/master/CHANGELOG.md#600-2016-10-04). We also have a new demo page. Feel free to try it:
https://tomchentw.github.io/react-google-maps/

**Comment by devantic** [comment]
Have/had same issue. Removing this from the icon definition worked although I had to edit the svg setting height and width to 32 to compensate.
scaledSize: new google.maps.Size(32,32)
