### ISSUE TITLE
Custom InfoWindow

### ISSUE THREAD

**Issue by davidpelayo** [tomchentw/react-google-maps#290]
Do you know how can I customize the InfoWindow markup to fully customize it? Not only the content of the InfoWindow but also the wrapper divs and so.

Thanks in advance.

Edit: I guess we should reproduce [this example](https://github.com/googlemaps/js-samples/tree/gh-pages/infowindow_custom) Google provides: [Demo](http://googlemaps.github.io/js-samples/infowindow_custom/infowindow-custom.html).

**Comment by davidpelayo** [comment]
Just to point out. I realized google examples as well as the AirBnb implementation are using the `OverlayView` abstraction to achieve this, setting the position when it comes to render the fake "InfoWindows".

Therefore, this is the only way to go. Even [`angular-google-maps` repo is using the google `InfoBox` abstraction](https://github.com/angular-ui/angular-google-maps/blob/master/src/js/wrapped/google-maps-util-v3.js) (using [OverlayViews underneath](https://github.com/googlemaps/js-samples/blob/gh-pages/infowindow_custom/infobox.js)) to achieve this.

**Comment by davidpelayo** [comment]
However, I think we should add classes inheritance by props at least or any data attribute to be able to style elements, in case needed, via CSS the component.

**Comment by tomchentw** [comment]
We have custom `OverlayView` component as well as pulling support for `InfoBox` as a addon. Could you see if that fits your needs?


Also,  [6.0.0](https://github.com/tomchentw/react-google-maps/issues/318) is released on npm beta tag now. See the changelog [here](https://github.com/tomchentw/react-google-maps/blob/master/CHANGELOG.md#600-2016-10-04). We also have a new demo page. Feel free to try it:
https://tomchentw.github.io/react-google-maps/

**Comment by ashishchoudhary12** [comment]
how to hide infow window close button???

**Comment by teksrc** [comment]
@ashishchoudhary12 and even over a year later that answer has yet to be answered. lol

**Comment by pruhstal** [comment]
@Frankcarvajal `InfoBox` is probably the way to go. Way more customizable.

**Comment by teksrc** [comment]
@pruhstal The only issue is there aren't any great examples of it being used via React and not using the 'composable' package used in the examples.

**Comment by pruhstal** [comment]
@Frankcarvajal here's an example of how I'm using it within one of my custom components (`WrappedCard`)

```
 const MapComponent = compose(
  withStateHandlers(
    () => ({
      isOpen: false
    }),
    {
      onToggleOpen: ({ isOpen }) => () => ({
        isOpen: !isOpen
      })
    }
  ),
  withScriptjs,
  withGoogleMap
)(props => (
  <GoogleMap
    onClick={props.onToggleOpen}
    defaultZoom={12}
    defaultOptions={{
      fullscreenControl: false,
      mapTypeControl: false,
      streetViewControl: false
    }}
    defaultCenter={{ lat: this.props.lat, lng: this.props.lng }}
  >
    <Marker
      key={item.id}
      icon={markerIcon}
      position={{
        lat: item.geom.coordinates[0],
        lng: item.geom.coordinates[1]
      }}
      onClick={props.onToggleOpen}
    >
      {props.isOpen && (
        <InfoBox
          onCloseClick={props.onToggleOpen}
          options={{
            alignBottom: true,
            pane: 'mapPane',
            pixelOffset: new google.maps.Size(-130, 0),
            boxStyle: {
              width: '300px'
            },
            closeBoxURL: ``,
            enableEventPropagation: true
          }}
        >
          <WrappedCard className={cardWrapperClass}>
            <div className={contentClass}>
              <img
                className={imageClass}
                src={getResizedPhoto(item.photo, 60, 60)}
              />
              <WrappedLink
                className={itemLinkClass}
                to={`/item/${item.slug}`}
                href={`/item/${item.slug}`}
              >
                {item.name}
              </WrappedLink>
            </div>
          </WrappedCard>
        </InfoBox>
      )}
    </Marker>
  </GoogleMap>
));
```
To be honest, I've found using the `compose` package nicely encapsulates props into the component itself.

**Comment by lortschi** [comment]
I have to say I never struggled with an other Google Maps Wrapper implementation MORE like with react-google-maps/api module. Everything it has been in this module implemented it's against common software engineering sense. It gives you a feeling to work with this api, like you will go to barber and he will bake you a cake instead of cut your hair.
