### ISSUE TITLE
Marker offset available?

### ISSUE THREAD

**Issue by kirkstrobeck** [tomchentw/react-google-maps#292]
Like http://stackoverflow.com/a/10666030/537998

**Comment by tomchentw** [comment]
Nope.

Also,  [6.0.0](https://github.com/tomchentw/react-google-maps/issues/318) is released on npm beta tag now. See the changelog [here](https://github.com/tomchentw/react-google-maps/blob/master/CHANGELOG.md#600-2016-10-04). We also have a new demo page. Feel free to try it:
https://tomchentw.github.io/react-google-maps/

**Comment by hdrdavies** [comment]
@kirkstrobeck did you find an appropriate solution? I take it you were trying to handle markers on the same location or...?

**Comment by kirkstrobeck** [comment]
Thx, yes just an anchor offset

**Comment by tomchentw** [comment]
Please refer to [Getting Help](https://github.com/tomchentw/react-google-maps#getting-help) section in the README (or #469).
