### ISSUE TITLE
Fix description how to start examples without docker

### ISSUE THREAD

**Issue by rewop** [tomchentw/react-google-maps#293]
I tried the instructions in the [README.md](https://github.com/tomchentw/react-google-maps#without-docker) to start the examples without docker, and the url http://localhost:8080/webpack-dev-server/ doesn't work when the example start.

It works though with http://localhost:8080/.

I suggest anyway to only use docker, and make sure the examples can be run with the published version in npm, and optionally with the repository itself for development purposes

**Comment by rewop** [comment]
I am also noticing that the examples pages are not working properly. There are crashes happening.

**Comment by tomchentw** [comment]
This is no longer needed given 6.0.0 removes the docker example. We could put it in somehow. Feel free to open another ticket there.

 [6.0.0](https://github.com/tomchentw/react-google-maps/issues/318) is released on npm beta tag now. See the changelog [here](https://github.com/tomchentw/react-google-maps/blob/master/CHANGELOG.md#600-2016-10-04). We also have a new demo page. Feel free to try it:
https://tomchentw.github.io/react-google-maps/
