### ISSUE TITLE
How to update line strokeWidth on hover

### ISSUE THREAD

**Issue by vedran-maestral** [tomchentw/react-google-maps#294]
I am trying to change line.strokeWeigth based on mouse hover. So I have this line renderer:

                              {this.state.lines.map((line, index) => {
                                return (                               `
                                <Polyline
                                  key={line.relationId}
                                  {...line}
                                  ref="currentline"
                                  options={line.options? line.options : lineOptions}
                                  onClick={function(e){self.onLineClick(e, line); }}
                                  onMouseover={function (e) {self.onLineHover(e, line)}}
                                  onMouseout={function (e) {self.onLineLeaveHover(e, line)}}
                                  />`

Then I have a listener on mouse over:

                           `onLineHover: function (e, line) {
                            var lines = this.state.lines;
                            var linePosition = lines.map(function (x) {
                            return x.relationId;
                           }).indexOf(parseInt(line.relationId, 10));
                          console.log(linePosition); 
                          this.refs.currentline.state.polyline.setOptions({strokeWeigth: 7})
       
    }`

How do I change the strokeWeigth in my hover event?

**Comment by RishabhJain96** [comment]
I suggest not setting options, rather setting a boolean in the state and using that boolean when rendering the options of the polyline. You may wish to use something such as MobX to avoid re-rendering all components.

**Comment by nishankkumar1994** [comment]
@RishabhJain96 : can we set options somehow, on hover.

**Comment by RishabhJain96** [comment]
Yes, create a PolyLineWrapper object (make sure you are handling the mapHolderRef correctly) that contains a polyline. Then pass in style as a property to the PolyLineWrapper object and use that style in your polyline. Attach an onHover event to the polyline and simply update state (you may want to attach the style property to state)

**Comment by nishankkumar1994** [comment]
But in case of large data it is very slow. Every time you hover over a poly line it updates its state and the main object is updated and renders all polylines again. Is there any way to handle using something like this.setOption on hover.

**Comment by RishabhJain96** [comment]
Read through https://facebook.github.io/react/docs/multiple-components.html.

Make sure to use shouldComponentUpdate(). Alternatively, you can use another state management tool such as MobX.

**Comment by tomchentw** [comment]
@vedran-maestral @nishankkumar1994 @RishabhJain96 Just use the `options` props:

```js
<Polyline options={{ strokeWeigth: this.state.strokeWeigth }} />
```

Also,  [6.0.0](https://github.com/tomchentw/react-google-maps/issues/318) is released on npm beta tag now. We also have a new demo page. Feel free to try it:
https://tomchentw.github.io/react-google-maps/
