### ISSUE TITLE
Warnings with react v0.15.2

### ISSUE THREAD

**Issue by oliviertassinari** [tomchentw/react-google-maps#295]
I'm seeing the following warnings when upgrading to React v0.15.2
```diff
-Warning: Unknown prop `mapHolderRef` on <span> tag.
-Remove this prop from the element.
-For details, see https://fb.me/react-unknown-prop
```

<details>
  <summary>Stack trace</summary>
```diff
-    in span (created by ReactTransitionGroup)
-    in ReactTransitionGroup (created by ReactCSSTransitionGroup)
-    in ReactCSSTransitionGroup (created by ProfilesMap)
-    in div (created by GoogleMapHolder)
-    in GoogleMapHolder (created by GoogleMap)
-    in GoogleMap (created by Map)
-    in Map (created by ProfilesMap)
```
</details>

**Comment by mcmar** [comment]
![screen shot 2016-07-05 at 12 07 32 pm](https://cloud.githubusercontent.com/assets/8251430/16596507/2107a98c-42a9-11e6-9dfa-432ec429e523.png)

**Comment by WellyShen** [comment]
I have the same problem

`Warning: Unknown props `lat`, `lng`, `$hover`, `$getDimensions`, `$dimensionKey`, `$geoService`, `$onMouseAllow`, `$prerender` on <div> tag. Remove these props from the element. For details, see https://fb.me/react-unknown-prop
    in div (created by GMap)
    in div (created by GoogleMapMarkers)
    in div (created by GoogleMapMarkers)
    in GoogleMapMarkers (created by Unknown)
    in div (created by Unknown)
    in Unknown (created by GoogleMap)
    in div (created by GoogleMap)
    in GoogleMap (created by GMap)
    in GMap (created by ContactInfo)
    in div (created by ContactInfo)
    in section (created by ContactInfo)
    in ContactInfo (created by Contact)
    in div (created by Contact)
    in div (created by Contact)
    in div (created by Contact)
    in Contact (created by Connect(Contact))
    in Connect(Contact) (created by Root)
    in div (created by StyleRoot)
    in StyleRoot (created by Root)
    in Root (created by Connect(Root))
    in Connect(Root)
    in Provider`

**Comment by tomchentw** [comment]
This should be fixed in 6.0.0. Please consider upgrading.

Also,  [6.0.0](https://github.com/tomchentw/react-google-maps/issues/318) is released on npm beta tag now. See the changelog [here](https://github.com/tomchentw/react-google-maps/blob/master/CHANGELOG.md#600-2016-10-04). We also have a new demo page. Feel free to try it:
https://tomchentw.github.io/react-google-maps/

**Comment by kunokdev** [comment]
This is still isssue in present?
Is it updated in main branch of npm install?

**Comment by rivyx** [comment]
I'm still getting this issue in 6.0.1
