### ISSUE TITLE
Warnings wordings for #168

### ISSUE THREAD

**Issue by tomchentw** [tomchentw/react-google-maps#296]
Thanks to @aug-riedinger in https://github.com/tomchentw/react-google-maps/pull/168#issuecomment-225692098

> Make sure you've put the <script src="https://maps.googleapis.com/maps/api/js?key=YOUR_API_KEY" ></script>  tag in your <head> element to load Google Maps JavaScript API v3.
> Careful the `async defer` options as suggested (here)[http://googlegeodevelopers.blogspot.fr/2015/09/map-tips-speeding-up-page-load-times.html] doesn't work.
> If you're looking for built-in support to load it for you, use the "async/ScriptjsLoader" instead.
> See https://github.com/tomchentw/react-google-maps/pull/168

**Comment by aug-riedinger** [comment]
Cheers. :smile: 
Do you expect me to PR this?

**Comment by tomchentw** [comment]
@aug-riedinger if you like that'd be great! Also, #266

**Comment by aug-riedinger** [comment]
Regarding your search for maintainers, I shall consider helping if I dive further into the projet that uses this repo. But this won't be before september because I'll be off this summer.
Cheers

**Comment by tomchentw** [comment]
Just to let you know  [6.0.0](https://github.com/tomchentw/react-google-maps/issues/318) is released on npm beta tag now. See the changelog [here](https://github.com/tomchentw/react-google-maps/blob/master/CHANGELOG.md#600-2016-10-04). We also have a new demo page. Feel free to try it:
https://tomchentw.github.io/react-google-maps/

**Comment by finetype** [comment]
Seems like it should point to this instead: https://github.com/tomchentw/react-google-maps/blob/master/src/app/pages/async/AsyncGettingStartedExample.js

**Comment by tomchentw** [comment]
Please refer to [Getting Help](https://github.com/tomchentw/react-google-maps#getting-help) section in the README (or #469).
