### ISSUE TITLE
Map is a global object in ES6

### ISSUE THREAD

**Issue by wuct** [tomchentw/react-google-maps#30]
Since Map is a global object in ES6, redefining it to a React class may have some side effects.

**Comment by frodosamoa** [comment]
When you initially get the component from the module, you can do something as follows:

    var {GoogleMapsMixin, Map: GoogleMap} = require("react-google-maps");

So that from now on the component's name has been renamed to `GoogleMap` as opposed to `Map`. And then JSHint won't complain about a redeclaration of Map, or other side effects.

**Comment by wuct** [comment]
@frodosamoa Thanks, I know I can rename it when I use it. But as long as I want to modify or contribute to this repo, I do not believe use the word "Map" is a good solution.

**Comment by tomchentw** [comment]
Thanks @wuct and @frodosamoa. I would appreciate a better naming for `Map`, maybe, `MapContainer`?

**Comment by frodosamoa** [comment]
I personally like `GoogleMap`. `MapContainer` isn't bad either!

**Comment by tomchentw** [comment]
Released [v1.0.0](https://github.com/tomchentw/react-google-maps/releases/tag/v1.0.0) and closed this now.
