### ISSUE TITLE
Custom marker

### ISSUE THREAD

**Issue by SVITY** [tomchentw/react-google-maps#303]
Hello,
Could I make custom markers using this maps component?
Custom markers are like these http://take.ms/SB6v6 . Marker has two state, red arrow points to normal state, blue one points to state after click.

Thx for help

**Comment by camiel** [comment]
I created custom markers using an OverlayView: http://react-google-maps.tomchentw.com/#/basics/overlay-view.

**Comment by tomchentw** [comment]
Thanks @camiel for answering!

Also,  [6.0.0](https://github.com/tomchentw/react-google-maps/issues/318) is released on npm beta tag now. See the changelog [here](https://github.com/tomchentw/react-google-maps/blob/master/CHANGELOG.md#600-2016-10-04). We also have a new demo page. Feel free to try it:
https://tomchentw.github.io/react-google-maps/

**Comment by KorySumsion** [comment]
Have a great solution for this without having to do an overlay view! Check it out:
https://github.com/tomchentw/react-google-maps/pull/501

**Comment by ejswenson15** [comment]
@tomchentw  thank you so much for creating react google maps you are literally a god amongst men
