### ISSUE TITLE
How to get directions from <DirectionsRenderer>

### ISSUE THREAD

**Issue by jeneg** [tomchentw/react-google-maps#309]
Hi! @tomchentw!
I'm new to React, and I'm trying to get current directions from DirectionsRenderer after user moves route waypoints, but  #have no success yet.
Please advise

```
<GoogleMap
    defaultZoom={13}
    defaultCenter={{ lat: 50.4285797, lng: 30.5080538 }}
    onClick={actions.addMarker}>
    
    {mapRoute.route ? <DirectionsRenderer
    options={{draggable:true}}
    onDirectionsChanged={getDirections}
    directions={mapRoute.route} /> : null}
</GoogleMap>
```

**Comment by jeneg** [comment]
Ok, I solved this using ref prop
```
<DirectionsRenderer
  options={{draggable:true}}
  ref={(r) => directionsRef = r}
  onDirectionsChanged={getDirections}
  directions={mapRoute.route} />
```
```
 function getDirections() {
   console.log(directionsRef.getDirections());
 }
```
Maybe someone will find this helpful

**Comment by tomchentw** [comment]
@jeneg does `ondirectionsChanged` not work as expected?

Also,  [6.0.0](https://github.com/tomchentw/react-google-maps/issues/318) is released on npm beta tag now. We also have a new demo page. Feel free to try it:
https://tomchentw.github.io/react-google-maps/

**Comment by feynmanish** [comment]
Hey guys, I keep getting errors, do you have an example with working getDirections? I keep getting either an error or undefined.

**Comment by hamza3e** [comment]
> Ok, I solved this using ref prop
> 
> ```
> <DirectionsRenderer
>   options={{draggable:true}}
>   ref={(r) => directionsRef = r}
>   onDirectionsChanged={getDirections}
>   directions={mapRoute.route} />
> ```
> 
> ```
>  function getDirections() {
>    console.log(directionsRef.getDirections());
>  }
> ```
> 
> Maybe someone will find this helpful

directionsRef.getDirections() gives error:
Uncaught TypeError: _directionsRef.getDirections is not a function
