### ISSUE TITLE
How to add custom block on hover over polygon by using the polygon component

### ISSUE THREAD

**Issue by nishankkumar1994** [tomchentw/react-google-maps#311]

**Comment by RishabhJain96** [comment]
Provide a function to onMouseover as provided by the [event list](https://github.com/tomchentw/react-google-maps/blob/master/src/eventLists/PolygonEventList.js).

**Comment by nishankkumar1994** [comment]
Thanks @RishabhJain96 , Also custom block is not working for markers when i am using it inside <MarkerClusterer /> component, any idea how we can add info window on it. Thanks for the help.

**Comment by RishabhJain96** [comment]
Could you provide some code?

**Comment by nishankkumar1994** [comment]
import React from "react"
import { Marker,  InfoWindow } from "react-google-maps"
import { default as MarkerClusterer }
  from 'google-react/lib/addons/MarkerClusterer';

export default React.createClass({

    getInitialState() {
        return { showInfoWindow: false }
    },

    render() {

        const { marker } = this.props

        return (
            <MarkerClusterer
              averageCenter
              enableRetinaIcons
              gridSize={60}
              minimumClusterSize={1}
              imagePath={hexToRGBValue(MAP_GEO_COLOR_BY_TYPE.lens_item_of_interest)}
            >
                <Marker
                    {...marker}
                    onClick={(e) => { this.setState({ showInfoWindow: true }) }}
                >
                    { this.state.showInfoWindow ?
                        <InfoWindow onCloseclick={(e) => { this.setState({ showInfoWindow: false }) }}>
                            //content
                        </InfoWindow>
                        : null
                    }
                </Marker>
            </MarkerClusterer>
        )

    }

})

**Comment by nishankkumar1994** [comment]
@RishabhJain96 : In my code it's not showing info window on click on a clustered marker. any idea how we can do it. Thanks

**Comment by nishankkumar1994** [comment]
HI @RishabhJain96 , i am using code below and it's not working. thanks for the help
<Polygon
                options={{
                  fillColor: THREAT_LEVELS_LIST_COLOR[this.props.threatLevelIndexSelected],
                  fillOpacity: 0.7,
                  strokeColor: THREAT_LEVELS_LIST_COLOR[this.props.threatLevelIndexSelected],
                  strokeOpacity: 0.7,
                  strokeWeight: 1,
                }}
                onClick={(e) => { console.log('1'); this.setState({ showInfoWindow: true }) }}
                onMouseover={(e) => { console.log('2'); this.setState({ showInfoWindow: true }) }}
                onMouseout={(e) => { console.log('3'); this.setState({ showInfoWindow: false }) }}
                paths={this.getCountryCoordinates('TJ')}
              >
                { this.state.showInfoWindow ?
                    <InfoWindow onCloseclick={(e) => { this.setState({ showInfoWindow: false }) }}>
                        <div>
                          info window data will goes here
                        </div>
                    </InfoWindow>
                    : null
                }
              </Polygon>

**Comment by nishankkumar1994** [comment]
Hi @tomchentw  I am trying to use InfoWindow component inside the Polygon component, it's not working. Can you please tell me how can i fix this. Thanks

**Comment by tomchentw** [comment]
@nishankkumar1994 `<InfoWindow>` expects to have an anchor component when it is placed inside something (which is often a `<Marker>`). The `<Polygon>` cannot be served as an anchor by design. However, you can render the `<InfoWindow>` separately by just giving it `props.position`.

Also,  [6.0.0](https://github.com/tomchentw/react-google-maps/issues/318) is released on npm beta tag now. See the changelog [here](https://github.com/tomchentw/react-google-maps/blob/master/CHANGELOG.md#600-2016-10-04). We also have a new demo page. Feel free to try it:
https://tomchentw.github.io/react-google-maps/

**Comment by sujanmah062** [comment]
hello 

creating an Info Window for polygons, How we can render Info window for polygons. Is this possible?
