### ISSUE TITLE
defaultCenter and defaultZoom not working

### ISSUE THREAD

**Issue by fishnugget** [tomchentw/react-google-maps#315]
Does anyone know how to access the map object to set the center and the zoom?  This will need to happen after the map renders.  Adding the values to the defaultZoom and/or defaultCenter in the render doesn't affect the view.

**Comment by amangeot** [comment]
You have to use [controlled props](https://facebook.github.io/react/docs/forms.html#controlled-components) (center, zoom), defaultCenter and defaultZoom are [uncontrolled](https://facebook.github.io/react/docs/forms.html#uncontrolled-components) props.

One solution that's working for me is passing (center, zoom) props only when they are defined `<GoogleMap ref='map' {...this.optionalProps} ...` and using `shouldComponentUpdate` to control map re-renders

**Comment by iamgutz** [comment]
Does anyone knows how to remove map controls? 
For example I don't want to have the streetViewControl, I am setting the property to the map like:
`<GoogleMap
          zoom={zoom}
          center={center}
          streetViewControl={false}`

but it doesn't work, still shows the man icon for streetview..
any thoughts @tomchentw ?

Thanks!

**Comment by amangeot** [comment]
Have you tried using `defaultOptions` props ? 

That is where you can pass map styles, an object like:
```
{
  minZoom: 3,
  fullscreenControl: false,
  // zoomControl: false,
  streetViewControl: false,
  scaleControl: true,
  mapTypeControl: true,
  mapTypeControlOptions,
  styles: [...administrative, ...landscape, ...poi, ...road, ...transit, ...water]
}
```
where administrative, landscape, etc. are objects with featureType, elementType, stylers properties

You can probably pass a `streetViewControl: true`

**Comment by iamgutz** [comment]
@amangeot  thanks! it worked for me.

**Comment by tomchentw** [comment]
Thanks @amangeot for answering!

Also, [6.0.0](https://github.com/tomchentw/react-google-maps/issues/318) is released on npm beta tag now. We also have a new demo page. Feel free to try it:
https://tomchentw.github.io/react-google-maps/

**Comment by ducminhn** [comment]
@amangeot's solution works. Or you can use the `options ` prop
