### ISSUE TITLE
Adding position absolute onto the map container gets overwritten

### ISSUE THREAD

**Issue by deadlocked247** [tomchentw/react-google-maps#316]
Whenever I try to pass any `position` attribute into the styling for the container element, it gets overwritten by `position: relative`

**Comment by nodegin** [comment]
try adding `!important` after `absolute`

**Comment by ASpehler** [comment]
I'm having the same issue, the mapElement div has a `position: relative` and the map does not show up on my page
And override with `!important` is not possible in React

**Comment by tomchentw** [comment]
@ASpehler would it possible to put it in `containerElement` with v6.0.0 and still work? I'm asking because `mapElement` is the actual DOM that `Google Maps JavaScript API` will render its DOMs on, and `containerElement` is just a wrapper around it.

**Comment by ASpehler** [comment]
@tomchentw yes it works too

```javascript
containerElement={
   <div style={{ height: '100vh' }} />
}
mapElement={
   <div style={{ height: '100%' }} />
}
```

**Comment by tomchentw** [comment]
Thanks @ASpehler for the feedback!

@nodegin @deadlocked247 did this solve your issue?

**Comment by tomchentw** [comment]
Please refer to [Getting Help](https://github.com/tomchentw/react-google-maps#getting-help) section in the README (or #469).
