### ISSUE TITLE
How to integrate Traffic data?

### ISSUE THREAD

**Issue by CharlieIGG** [tomchentw/react-google-maps#322]
I've been trying to figure out how to integrate Traffic data from the maps API into these maps, but to no avail... Anyone can point me in the right direction?  My best guess is to have it render somehow via the overlay function, but no luck so far.

**Comment by tomchentw** [comment]
Please check StackOverflow and Google Maps JavaScript API for more information. `react-google-maps` is simply a wrapper around it.
