### ISSUE TITLE
Can this be used with React-Native?

### ISSUE THREAD

**Issue by CharlieIGG** [tomchentw/react-google-maps#326]
Has anyone successfully tried this on React-Native? I'm not liking react-native's current only choice for maps.

**Comment by nodegin** [comment]
No since you'll have to put a `<script>` tag in your html file in order to loads the Google Maps library. Have you looked up on ![airbnb/react-native-maps](https://github.com/airbnb/react-native-maps)?

**Comment by tomchentw** [comment]
Thanks @nodegin for pointing the right direction!
