### ISSUE TITLE
Error when upgrading from 3.0.0 to 5.0.0

### ISSUE THREAD

**Issue by jerefrer** [tomchentw/react-google-maps#327]
I'm trying to upgrade from 3.0.0 to 5.0.0, which requires that I also upgrade React from 0.13.3 to 15.1.0.

I've dealt with a number of things, like the need to wrap `GoogleMap` inside a `GoogleMapLoader`.

I got things *almost* working, but now I'm struggling with this error:

    common.js:230 Uncaught RangeError: Maximum call stack size exceeded
      _.m.zoom_changed._.dy.zoomRange_changed @ common.js:230
      xb @ js:37
      _.m.set @ js:97
      (anonymous function) @ js:47
      _.m.zoom_changed._.dy.zoomRange_changed @ common.js:230
      xb @ js:37
      _.m.set @ js:97
      (anonymous function) @ js:47
      _.m.zoom_changed._.dy.zoomRange_changed @ common.js:230
      xb @ js:37

whenever move the map or zoom in/out **after** I started to fiddle with markers, like hiding or showing some of them or opening an `InfoWindow`.

I found a few possible explanations on SO posts : [like this one](http://stackoverflow.com/questions/31866535/uncaught-rangeerror-maximum-call-stack-size-exceeded-when-i-use-google-maps), or [that one](http://stackoverflow.com/questions/15671480/uncaught-rangeerror-maximum-call-stack-size-exceeded-google-maps-when-i-try-to).

Any idea from your perspective ?

**Comment by wnoveno** [comment]
I'm having the same problem. It's actually really weird since I'm not passing any data to the component yet. Would love to know the solution to this as well

**Comment by jerefrer** [comment]
I gave up using `react-google-map` and went to vanilla Google Map.
Everything went well and I decided to add a feature related to the zoom.
Then I encountered the same error when I passed an `undefined` zoom when initializing the map.

So maybe there is some issue while passing the `defaultZoom` prop ?

**Comment by tomchentw** [comment]
@jerefrer @wnoveno don't use `5.0.0`. Please try `6.0.0` instead. This bug is fixed now.

[6.0.0](https://github.com/tomchentw/react-google-maps/issues/318) is released on npm beta tag now. We also have a new demo page. Feel free to try it:
https://tomchentw.github.io/react-google-maps/
