### ISSUE TITLE
Error on onRadiusChanged in Circle component

### ISSUE THREAD

**Issue by crisys11** [tomchentw/react-google-maps#328]
When set onRadiusChanged attribute in Circle component google maps throw an exception

``` jsx
<Circle
    clickable
    draggable
    editable
    center={coordinates}
    radius={this.state.radius}
    ref={circle => { this.circle = circle; }}
    onCenterChanged={this.onCenterChanged}
    onRadiusChanged={this.onRadiusChanged}
   options={{
     fillColor: '#f00',
     strokeColor: '#f00',
   }}
 />
```

Uncaught TypeError: Cannot read property 'apply' of undefined

**Comment by tomchentw** [comment]
Could you check if this still exists for 6.0.0?

[6.0.0](https://github.com/tomchentw/react-google-maps/issues/318) is released on npm beta tag now. See the changelog [here](https://github.com/tomchentw/react-google-maps/blob/master/CHANGELOG.md#600-2016-10-04). We also have a new demo page. Feel free to try it:
https://tomchentw.github.io/react-google-maps/

**Comment by tomchentw** [comment]
Please refer to [Getting Help](https://github.com/tomchentw/react-google-maps#getting-help) section in the README (or #469).

**Comment by matheuspalmeir** [comment]
@crisys11 Did you solve this problem? I just need to get the new radius and center of a editable circle, after the user changed him, and i can't find a way. Is there any example in documentation? I didnt understand what is different in Released (6.0.0):

`<Circle
          radius={this.state.radiusCircle}
          center={this.state.centerCircle}
          options={
            {
              fillColor: "#ff0000",
              fillOpacity: 0.2,
              strokeColor: "#ff0000",
              strokeOpacity: 1,
              strokeWeight: 2,
              visible: this.state.circleVisible,
              editable: true,
              draggable: true
            }
          }
          onCenterChanged={this.handleCircleCenterChange} //Error 
          onRadiusChanged={this.handleCircleRadiusChange}
        />`

**Comment by JustFly1984** [comment]
@matheuspalmeir This library is unmaintained more than a year, please refer to new npm @react-google-maps/api

We have docs, examples and community at spectrum.

**Comment by naveensomanna** [comment]
onRadiusChanged it's not triggering can anyone help me out

**Comment by JustFly1984** [comment]
@naveensomanna The repo of this project is unmaintained more than a year, and we had build new version https://www.npmjs.com/package/@react-google-maps/api

We had rewrite it to TypeScript, and updating it frequently: https://github.com/JustFly1984/react-google-maps-api/tree/master/packages/react-google-maps-api
You can enjoy autocomplete.

You can see our docs: https://react-google-maps-api-docs.netlify.app

Also a lot of examples: https://react-google-maps-api-gatsby-demo.netlify.app/ https://github.com/JustFly1984/react-google-maps-api/tree/master/packages/react-google-maps-api-gatsby-example/src/examples

The bundle size is much smaller: https://bundlephobia.com/result?p=@react-google-maps/api

Our Spectrum community: https://spectrum.chat/react-google-maps Our Slack channel: https://join.slack.com/t/react-google-maps-api/shared_invite/enQtODc5ODU1NTY5MzQ4LTBiNTYzZmY1YmVjYzJhZThkMGU0YzUwZjJkNGJmYjk4YjQyYjZhMDk2YThlZGEzNDc0M2RhNjBmMWE4ZTJiMjQ

Enjoy!
