### ISSUE TITLE
Context for redux and intl inside of GoogleMap?

### ISSUE THREAD

**Issue by momirov** [tomchentw/react-google-maps#329]
Hi, I have some trouble getting react-intl and redux to work with components rendered into GoogleMap component.

I get:
``
Uncaught Invariant Violation: Could not find "store" in either the context or props of "Connect(FollowContainer)". Either wrap the root component in a <Provider>, or explicitly pass "store" as a prop to "Connect(FollowContainer)"
``

It seems that store and intl are not available on context so this doesn't work.

**Comment by pukapukan** [comment]
There are some react-google-maps components rendered in a different context internally.

Refer to #258 for more info.

**Comment by brandonmp** [comment]
i'm able to fire redux actions by passing them down to components like `InfoWindow` from the parent. not sure if that meets your needs though :/

**Comment by tomchentw** [comment]
@momirov @pukapukan @brandonmp this is duplicated of #258 . Close now. Discuss there.

Also, [6.0.0](https://github.com/tomchentw/react-google-maps/issues/318) is released on npm beta tag now. We also have a new demo page. Feel free to try it:
https://tomchentw.github.io/react-google-maps/
