### ISSUE TITLE
Disabling scrollwheel

### ISSUE THREAD

**Issue by timkraut** [tomchentw/react-google-maps#332]
Hi,

is there a way to disable the scroll wheel? In the [MapOptions object specification](https://developers.google.com/maps/documentation/javascript/reference#MapOptions) is a property `scrollwheel` which can be set to false to disable zooming when the scroll wheel is used. I'm not sure how to integrate this option into react-google-maps.

It would be awesome if you could help me! Thanks in advance!

**Comment by kkribakaran** [comment]
I was able to disable the scroll wheel by doing this:

```
<GoogleMap
...
  defaultOptions={{
    scrollwheel: false,
  }}
...
/>
```

Hope this helps! :)

**Comment by timkraut** [comment]
@kkribakaran It does! Thanks! :)

**Comment by tomchentw** [comment]
Thanks @kkribakaran for answering!

Also, [6.0.0](https://github.com/tomchentw/react-google-maps/issues/318) is released on npm beta tag now. We also have a new demo page. Feel free to try it:
https://tomchentw.github.io/react-google-maps/
