### ISSUE TITLE
is is possible to use searchBox component with Redux-form field? 

### ISSUE THREAD

**Issue by jasan-s** [tomchentw/react-google-maps#336]

**Comment by alvelig** [comment]
SearchBoxInstance.refs.inputElement

**Comment by tomchentw** [comment]
You'll need to manually connect to `redux-form` `<Field>` component yourself, but I haven't tried it.

@alvelig this is no longer available in 6.0.0.

Also, [6.0.0](https://github.com/tomchentw/react-google-maps/issues/318) is released on npm beta tag now. We also have a new demo page. Feel free to try it:
https://tomchentw.github.io/react-google-maps/
