### ISSUE TITLE
triggerEvent('resize') does...what?

### ISSUE THREAD

**Issue by joefraley** [tomchentw/react-google-maps#337]
http://react-google-maps.tomchentw.com/#/?_k=vkf06f

If you load this in Chrome nightly and open the console, you can see the logs dump on the window resize event, but the map is not being updated to reflect the changing screen size.

The example code just logs the component instance on resize. But how does one actually trigger the resize _on the map_, with access only to the _component_? Looking at the source code, it looks like `triggerEvent` just spreads the args, but my understanding of the gMaps API is that I need to run something like `map.setCenter` or `setBounds` or something on the event?

What's the way to do this on the given implementation? I wouldn't ask, but it just doesn't seem to be working in the demo example.

Thanks!

**Comment by tomchentw** [comment]
Could you check if this issue still exists on [6.0.0](https://github.com/tomchentw/react-google-maps/issues/318)? It's released on npm beta tag now. We also have a new demo page. Feel free to try it:
https://tomchentw.github.io/react-google-maps/

**Comment by r2dev** [comment]
I have updated to v6, and used ref to expose the google map element. since there is no 'util/triggerEvent' any more, I just call the google.map.event.trigger to trigger 'resize' on the element, unfortunately it doesnt work correctly. I assume the google map element i got is modified by library because I saw there is no setCenter and setZoom.

Is there any implementation related to this issue, much appreciated!

**Comment by reintroducing** [comment]
I'm also looking for setZoom which used to be available and no longer is. What is the new implementation of this in v6.x?

**Comment by uniquoooo** [comment]
@reintroducing You can change the zoom with the `zoom` prop on your `GoogleMap`.

**Comment by reintroducing** [comment]
@uniquoooo I could have sworn I tried that and it was causing performance issues but I may be thinking of a different library I tried (these past few days have been a nightmare of Google Maps for me :)  Thanks, when I can I'll circle back to upgrading and see if that works.

**Comment by tomchentw** [comment]
Please refer to [Getting Help](https://github.com/tomchentw/react-google-maps#getting-help) section in the README (or #469).

**Comment by danadn** [comment]
@r2dev could you please share a code snippet about how/where to make the ref for example in the main sample?
https://github.com/tomchentw/react-google-maps#withgooglemap
