### ISSUE TITLE
How can I disable map repeat?

### ISSUE THREAD

**Issue by khalid3n** [tomchentw/react-google-maps#339]

**Comment by tomchentw** [comment]
Check out if you can find any options for Map: https://developers.google.com/maps/documentation/javascript/3.exp/reference#MapOptions
react-google-maps just delegate everything to Google Maps JavaScript API. Please check on StackOverflow if you can't find any solution.

Also, [6.0.0](https://github.com/tomchentw/react-google-maps/issues/318) is released on npm beta tag now. We also have a new demo page. Feel free to try it:
https://tomchentw.github.io/react-google-maps/
