### ISSUE TITLE
5.0.0 isn't available on npm

### ISSUE THREAD

**Issue by jaux** [tomchentw/react-google-maps#340]
The latest version on npm is still 4.11.0, please update.

**Comment by amangeot** [comment]
There is no intention for such thing:
https://github.com/tomchentw/react-google-maps/issues/267#issuecomment-231095919

**Comment by tomchentw** [comment]
Thanks @amangeot for answering.

Also,  [6.0.0](https://github.com/tomchentw/react-google-maps/issues/318) is released on npm beta tag now. See the changelog [here](https://github.com/tomchentw/react-google-maps/blob/master/CHANGELOG.md#600-2016-10-04). We also have a new demo page. Feel free to try it:
https://tomchentw.github.io/react-google-maps/
