### ISSUE TITLE
Marker : No action on handleMarkerClick

### ISSUE THREAD

**Issue by mika75** [tomchentw/react-google-maps#341]
Hi, 

I tried this example 

http://react-google-maps.tomchentw.com/#/basics/pop-up-window?_k=ylwfg9

But i can't handle click on Marker 
I see no event. Any idea ?

```

return ( <Marker 
                key={index}
                ref={ref}
                position={marker.position}
                onClick={this.handleMarkerClick.bind(this,marker)} >
                
                {/* 
                  Show info window only if the 'showInfo' key of the marker is true. 
                  That is, when the Marker pin has been clicked and 'handleMarkerClick' has been
                  Successfully fired.
                */}
                {marker.showInfo ? this.renderInfoWindow(ref, marker) : null}
                
              </Marker>


```

**Comment by rokimoto** [comment]
@mika75 Also having the same issue adding click handlers to markers.  Have you found any solution to this?

**Comment by mika75** [comment]
@rokimoto Sorry I have no solution and you ? are you on Async Mode ?

**Comment by rokimoto** [comment]
@mika75 No solution over here either unfortunately.  😞   But no I was not.

**Comment by tomchentw** [comment]
@mika75 @rokimoto Since [6.0.0](https://github.com/tomchentw/react-google-maps/issues/318) is released on npm beta tag now and we have a new demo page, could you try it here again?
https://tomchentw.github.io/react-google-maps/basics/pop-up-window
