### ISSUE TITLE
InfoWindow clears on update

### ISSUE THREAD

**Issue by uniquoooo** [tomchentw/react-google-maps#342]
Hi guys,

I'm currently using `react-google-maps` to create a public transit map and I'm using the `InfoWindow` component to display stop timetables.

When I open the `InfoWindow` component through a marker, the window opens as normal, however, I am using JQuery and Ajax to load the data from a server into the React element.  When the Ajax request finishes and the data is stored in the React element state, the `InfoWindow` clears and empties.

My code is here: https://gist.github.com/uniquoooo/c80e6bda7bc901d8a53753c2d10e15a1

I'm not sure why this is happening, could someone look at my code and see if I am doing anything wrong?

Thanks

**Comment by tomchentw** [comment]
@uniquoooo this is weird, seems to be a bug. Could you try 6.0.0 and see if it's still the same?

[6.0.0](https://github.com/tomchentw/react-google-maps/issues/318) is released on npm beta tag now. We also have a new demo page. Feel free to try it:
https://tomchentw.github.io/react-google-maps/

**Comment by uniquoooo** [comment]
@tomchentw I'm getting the following error while trying to transform ES6 code:
```
[Error: Couldn't find preset "es2015-loose" relative to directory "./node_modules/react-display-name" while parsing file: ./node_modules/react-display-name/lib/getDisplayName.js]
```

**Comment by tomchentw** [comment]
@uniquoooo what do you mean transform ES6 code? Are you importing from `react-google-maps/src`?

**Comment by uniquoooo** [comment]
Yep, I'm importing with `import { withScriptjs, withGoogleMap, GoogleMap } from 'react-google-maps/src';`.

**Comment by tomchentw** [comment]
@uniquoooo 

1. could you setup a minimal repository that uses this feature? I'm not familiar with the toolchain like `rollup` that pulls directly from ES2015 modules.
2. `withScriptjs` needs to be imported separately. Check out the "async" example

**Comment by uniquoooo** [comment]
For some reason `react-display-name` was not downloading the required Babel transformers, but after I installed them it seemed to work fine. The `InfoWindow` is also fixed. Thanks for your help!
