### ISSUE TITLE
Unable to set options on map?

### ISSUE THREAD

**Issue by imperat0r** [tomchentw/react-google-maps#348]
I tried this
  <GoogleMap    options={this.createMapOptions}   ....
where createMapOptions is function defined as:

  createMapOptions (maps) {
        return {
            panControl: false,
            mapTypeControl: false,
            scrollwheel: false,
            styles: [{ stylers: [{ 'saturation': -100 }, { 'gamma': 0.8 }, { 'lightness': 4 }, { 'visibility': 'on' }] }]
        }
    }

**Comment by nodegin** [comment]
` options={this.createMapOptions()} `

**Comment by tomchentw** [comment]
Thanks @nodegin ! Or you can use an object literal:

```js
<GoogleMap options={{ panControl: false }} />
```

Also,  [6.0.0](https://github.com/tomchentw/react-google-maps/issues/318) is released on npm beta tag now. We also have a new demo page. Feel free to try it:
https://tomchentw.github.io/react-google-maps/

**Comment by finetype** [comment]
@tomchentw, I've been pulling my hair out trying to figure out how to use geojson with this plugin for the last two days. The last example I could find seems to be quite old, and I can't seem to get it working... What's the best way to get at the map object to use the native map.data.loadGeoJson ? Or do you have a working geoJsonToLatLang component in the most recent version? (Still, converting geojson to latlang seems a bit odd--curious why that decision was made)

Thanks for an excellent library. Just having a bit of trouble figuring out how it works, given the state of documentation right now, what with the new release, I guess. :/
