### ISSUE TITLE
6.0.0 [Error: Cannot find module 'react-google-maps/lib/async/ScriptjsLoader]

### ISSUE THREAD

**Issue by mika75** [tomchentw/react-google-maps#350]
Hi

Is it normal that module react-google-maps/lib/async/ScriptjsLoader is not present ?

**Comment by tomchentw** [comment]
Yes, it's replaced by a new HOC. See the changelog:
https://github.com/tomchentw/react-google-maps/blob/master/CHANGELOG.md#600-2016-10-04
