### ISSUE TITLE
 Cannot find module 'react-google-maps'

### ISSUE THREAD

**Issue by Youcef2015** [tomchentw/react-google-maps#359]
I installed 

https://www.npmjs.com/package/react-google-map

in my code 
const GooglePlacesSuggest = require('react-google-map');

i have an error

Module not found: Error: Cannot resolve module 'react-google-map'

**Comment by brandonmp** [comment]
Wrong repo - - that module's repo  is at https://github.com/cedricdelpoux/react-google-map

But it looks like it's not maintained currently

**Comment by tomchentw** [comment]
Thanks @brandonmp . Close now!
