### ISSUE TITLE
Getting TypeError: Cannot read property 'addEventListener' of undefined

### ISSUE THREAD

**Issue by prewk** [tomchentw/react-google-maps#360]
Hi, I'm using `ScriptjsLoader` to load the map. When loading the map it seems to work at first, but when the component gets dismounted (I navigate to another page in our SPA) and go back again I get this error from within the minified Google Maps API JS: `TypeError: Cannot read property 'addEventListener' of undefined`

![screen shot 2016-10-11 at 16 25 57](https://cloud.githubusercontent.com/assets/640102/19274143/776af32e-8fcf-11e6-836d-d57c98dd3abe.png)

Important disclaimer: We're not currently rendering the maps correctly at all because of API key problems we're working out with Google. I would however love to know if this is a problem entirely caused by missing API keys or if something else obvious is amiss.

Thanks!

**Comment by tomchentw** [comment]
missing API keys is pretty annoying stuff, and it may cause map not rendering. Please try to fix it.

Also, we're releasing 6.0.0 now. Please try to upgrade because there are various bugs in <6.0.0 and we won't fix them. See #318

**Comment by prewk** [comment]
Oh, I wasn't aware that we were so far behind with the versions. I'll try v6 and get back to you.

**Comment by tomchentw** [comment]
It's still in the `beta` channel btw. Also, check out the changelog file. Let me know if you have any questions.

**Comment by prewk** [comment]
It solved my problem. Thanks!

I think you should look over [this async part](https://github.com/tomchentw/react-google-maps#asyncwithscriptjs) in the readme. I _think_ `GettingStartedGoogleMap` is supposed to be `AsyncGettingStartedExampleGoogleMap`, and the imports weren't obvious to figure out so might as well include them:

```
import withGoogleMap from 'react-google-maps/lib/withGoogleMap';
import withScriptjs from 'react-google-maps/lib/async/withScriptjs';
```

**Comment by tomchentw** [comment]
@prewk Good catch! I'll update the README. Thanks a lot
