### ISSUE TITLE
Advantages of updating to Version 5/6?

### ISSUE THREAD

**Issue by eljefejames** [tomchentw/react-google-maps#362]
I currently use version 4, it's great. Where can  I find a list of new changes/features for version 5 or 6? I'm somewhat hesitant to update as it took quite some time to make it play nicely with Meteor...

**Comment by rewop** [comment]
Check the [changelog](https://github.com/tomchentw/react-google-maps/blob/master/CHANGELOG.md)

**Comment by tomchentw** [comment]
Thanks @rewop ! Also noticing that v6 fixes a serious bug (#338) in `React@^15`.

**Comment by eljefejames** [comment]
thanks for the link to changelog!
