### ISSUE TITLE
Create TypeScript definitions

### ISSUE THREAD

**Issue by tomchentw** [tomchentw/react-google-maps#363]

**Comment by tomchentw** [comment]
Anyone interested?

**Comment by dvlasenko96** [comment]
@tomchentw Yes. Please create definition. I am using typescript on my project, but there are no .d.ts gile for maps. Thank you.

**Comment by mxl** [comment]
Should I create PR here or in https://github.com/DefinitelyTyped/DefinitelyTyped?

**Comment by tomchentw** [comment]
@mxl you can create PR here.

**Comment by AAllport** [comment]
Any update on this?

**Comment by oshalygin** [comment]
I haven't used typescript in about a year, going to defer this to someone else thats more familiar and can crank it out without reading alot of docs

**Comment by mxl** [comment]
I'm almost done writing definitions and will submit PR this weekend.

**Comment by tomchentw** [comment]
@mxl you're awesome!

**Comment by mxl** [comment]
@tomchentw Sorry, I was busy on that weekend. I will finish the work this week.

**Comment by tomchentw** [comment]
No rush.

**Comment by kenjiru** [comment]
@mxl no rush, but please keep us posted regarding the progress on this issue.

**Comment by simran5** [comment]
also interested in this

**Comment by tomchentw** [comment]
PR's are welcomed!
Also, you may be interested to generate typed code from `src/macro` directly using `jscodeshift` API. That could save you lots of time.

**Comment by mxl** [comment]
Guys, sorry for late response. I've continued my work on definitions. See #646.

**Comment by mxl** [comment]
I've almost finished definitions. You can test them by installing `react-google-maps` with `npm install github:mxl/react-google-maps#typescript-definitions`.

**Comment by abhilashcf** [comment]
Hello,
   Could you please share an example of usage for typescript ? I wanted to try out the 
 
    I tried `yarn add github:mxl/react-google-maps#typescript-definitions`.

     getting 'expecting 1 arguements, got 3'.. 'withProps' error underlined

**Comment by ChuckJonas** [comment]
also interested

**Comment by tomchentw** [comment]
Released [v9.3.0](https://github.com/tomchentw/react-google-maps/releases/tag/v9.3.0)

**Comment by israellev** [comment]
If you has an error like - Cannot find namespace 'google' or  Cannot find name 'Calculator':
pay attention that in library in node_modules/react-google-maps/package.json it's a peerDependencies that you relay need:
`npm i --save @types/googlemaps`
`npm i --save @types/markerclustererplus`

and it's spouse to work.

**Comment by afholderman** [comment]
Has anyone been able to get this to work that can share an example? Using examples from the documentation I'm still met with TS errors.

**Comment by mxl** [comment]
@afholderman What errors do you have?

**Comment by afholderman** [comment]
Given this component (imports left out to keep it shorter):

`export const MyGoogleMap = compose(
  withProps({
    googleMapURL: 'https://maps.googleapis.com/maps/api/js?key=[removed]&v=3.exp&libraries=geometry,drawing,places',
    loadingElement: <div style={{ height: `100%` }} />,
    containerElement: <div style={{ height: `400px` }} />,
    mapElement: <div style={{ height: `100%` }} />,
  }),
  withScriptjs,
  withGoogleMap
  )( (props) => (
    <GoogleMap
      defaultZoom={8}
      defaultCenter={{ lat: -34.397, lng: 150.644 }}
      center={props.center}
    />
  )
);

<MyGoogleMap
  center={{ lat: 38.6270, lng: -90.1994 }}
/>`

Typescript throwing the error: `TS2339: Property 'center' does not exist on type '{ children?: ReactNode; }'.`
Even though center is a documented prop on the GoogleMap component. I tested this same component in a non-Typescript create-react-app and it works as expected.

**Comment by afholderman** [comment]
@mxl 

Given this component (imports left out to keep it shorter):

```
export const MyGoogleMap = compose(
  withProps({
    googleMapURL: 'https://maps.googleapis.com/maps/api/js?key=[removed]&v=3.exp&libraries=geometry,drawing,places',
    loadingElement: <div style={{ height: '100%' }} />,
    containerElement: <div style={{ height: '400px' }} />,
    mapElement: <div style={{ height: '100%' }} />,
  }),
  withScriptjs,
  withGoogleMap
  )( (props) => (
    <GoogleMap
      defaultZoom={8}
      defaultCenter={{ lat: -34.397, lng: 150.644 }}
      center={props.center}
    />
  )
);

<MyGoogleMap
  center={{ lat: 38.6270, lng: -90.1994 }}
/>
```

Typescript throwing the error: `TS2339: Property 'center' does not exist on type '{ children?: ReactNode; }'.`
Even though center is a documented prop on the GoogleMap component. I tested this same component in a non-Typescript create-react-app and it works as expected.

**Comment by mxl** [comment]
@afholderman I think that this error is about `props` that you pass to closure that returns `GoogleMap` element, not about `GoogleMap` props.

**Comment by bharney** [comment]
In addition to installing the type definitions for `@types/googlemaps @types/markerclustererplus` I also needed to add them to my configuration to resolve errors related to: 'Cannot find name 'Calculator'.  or 'Cannot find module 'google'. 
I added the following to my `tsconfig.json`
```
"types": [
      "googlemaps",
      "markerclustererplus"
 ],
```
And it works now!

**Comment by atrauzzi** [comment]
You shouldn't have to do that, the types should auto-discover once in the `node_modules` folder.  Any chance you can show the rest of your `tsconfig.json`?

**Comment by laukaichung** [comment]
Anyone using Webstorm? I'm getting a warning about `Cannot find parent 'tsconfig.json'` from /.../node_modules/@ types/googlemaps/index.d.ts

**Comment by AAllport** [comment]
I'm on Webstorm, what steps did you take to reproduce

**Comment by laukaichung** [comment]
@AAllport 
I installed the type file with `npm i --save @types/googlemaps`
I think the problem comes from the `exclude` settings in tsconfig.json
````
{
  "compileOnSave": true,
  "compilerOptions": {
    "module": "commonjs",
    "target": "es2015"
  },
  "exclude": [
    "node_modules"
  ]
}
````
The warning disappears after "node_modules" is removed.

**Comment by AAllport** [comment]
are you using webpack or any bundler?

**Comment by Anees-Raja** [comment]
Do I need webpack or a bundler to use this component? I keep getting the following error:

`./src/app/components/CustomMap/CustomMap.js
Module parse failed:
\src\app\components\CustomMap\CustomMap.js Unexpected token (6:4)
You may need an appropriate loader to handle this file type.
| 
| const CustomMap = withScriptjs(withGoogleMap((props) => 
|     <GoogleMap
|     defaultZoom={8}
|     defaultCenter={{ lat: -34.397, lng: 150.644 }}`

**Comment by baughmann** [comment]
Why is this closed?

**Comment by digital-nomad17** [comment]
@mxl 
Has your type definitions for react-google-maps been merged? I can't find on npm.

**Comment by mxl** [comment]
@digital-nomad17 Yes, they are installed with this module. Also you need definitions for googlemaps and markerclustererplus modules:

```
npm i --save react-google-maps @types/googlemaps @types/markerclustererplus
```

**Comment by digital-nomad17** [comment]
@mxl 
Thank you! 

Can we add notes to the github page for the typedefiniton file so people can find them?

**Comment by mxl** [comment]
@digital-nomad17 Actually it's better to move definitions to separate module and make it depend on `@types/googlemaps` and `@types/marlerclustererplus` or add them to dependencies for this module. @tomchentw what is your decision?

**Comment by baughmann** [comment]
@mxl running `npm i --save react-google-maps @types/googlemaps @types/markerclustererplus` and then importing `import {GoogleMap, withGoogleMap, withScriptjs} from 'react-google-maps'` results in a bunch of `TS2503: Cannot find namespace 'google'.`. Is this the expected result? Is there more work to do on my end?

**Comment by digital-nomad17** [comment]
@nickdb93 
You have to declare `/*global googlemap*/` in the first line of the file. It's defined in the google-maps package but can't resolve it.

**Comment by williamsb** [comment]
Just an FYI for anyone having trouble importing snazzymaps styles (on typescript), make sure you are using the correct type for "stylers"
**snazzymaps default:**

`
           "stylers": [
               {
                   "saturation": "13"
               },
               {
                   "lightness": "4"
               }
           ]
`

**should be:** 

`
           "stylers": [
               {
                   "saturation": 13
               },
               {
                   "lightness": 4
               }
           ]
`

**types based on:**

```

export interface MapTypeStyler {
   color?: string;
   gamma?: number;
   hue?: string;
   invert_lightness?: boolean;
   lightness?: number;
   saturation?: number;
   visibility?: string;
   weight?: number;
}

```

**Comment by alamothe** [comment]
Impressive type definitions!
