### ISSUE TITLE
Using Marker component in a file separate from GoogleMaps component

### ISSUE THREAD

**Issue by michael-daly** [tomchentw/react-google-maps#365]
I'm trying to make a component that's an Marker/InfoWindow combo component. It's a child of the GoogleMap component, but it's in its own separate file.

When I try to use it I get `Uncaught TypeError: Cannot read property 'getMap' of undefined`

Is this not possible or am I doing something wrong?

**Comment by michael-daly** [comment]
five seconds of searching later...
https://github.com/tomchentw/react-google-maps/issues/165#issuecomment-206440454

whoops fixed

**Comment by tomchentw** [comment]
@michael-daly Try using v6?

**Comment by michael-daly** [comment]
sorry, I forgot to mention that I was able to solve it with the comment I linked
