### ISSUE TITLE
Wait for the component to be in view before rendering

### ISSUE THREAD

**Issue by Unforgiven-wanda** [tomchentw/react-google-maps#366]
Hello,
In my use case, I have a single, long page, with the google map component at the very bottom. I'd like to only initialize the map once it is in view to speed up the initial page load. I had the same use case in an older project (with simple Jquery) and the results were astounding. 

Is it possible?
Thank you

**Comment by rewop** [comment]
When you say *in view*, you mean the component is visible in the viewport?

If so, you should get control of the scrolling, and use the state to initialise your map only when the map component enters the viewport.

There are many utility components that help with this in react: [react-visibility-sensor](https://github.com/joshwnj/react-visibility-sensor), [react-component-visibility](https://github.com/Pomax/react-component-visibility).

**Comment by Unforgiven-wanda** [comment]
> When you say in view, you mean the component is visible in the viewport?

Indeed. However, is there a prop to this end in react-google-map? Knowing I use the `async/withScriptjs` variant, something along the lines of:
```
<AsyncGettingStartedExampleGoogleMap
...
ready={this.state.Visible}
...
/>
```

And as for the view utility component, this isn't an issue. I already have it working with other components.

**Comment by rewop** [comment]
So basically you would like to load at page load, but showing it only, when it enters the viewport?

**Comment by rewop** [comment]
Also what version are you using?

**Comment by Unforgiven-wanda** [comment]
Yes, exactly. I am using the beta, v6.0.

**Comment by rewop** [comment]
I would suggest just hide the root component with css. And show it once the component becomes visible.

**Comment by Unforgiven-wanda** [comment]
> I would suggest just hide the root component with css. And show it once the component becomes visible.

In fact what I'm trying to avoid here are the initial google maps requests, both the js file and countless other requests. In fact, the number of initial requests on first page load went from something like 30 to 65/70 when adding the map component, and that here is what I'm trying to avoid. I've noticed in older projects that initializing the map only once it is in view did wonders to the initial page load, and that's what I'm trying to emulate here.

I'll look into appending React components dynamically (e.g: when container is in view, append the map component, something like that). If I find a viable solution I'll update this issue for posterity.

**Comment by rewop** [comment]
Since this is not a problem with the map. I will close this issue.

**Comment by tomchentw** [comment]
A typical approach would be wrapped this `container is in view` logic into an HOC:

```
const whenInView = (WrappeedComponent) => {
  return class X extends React.Component {
    // implement state changes for `isInView`
    render() {
      return this.state.isInView ? <WrappeedComponent {...props} /> : null
    }
  }
}

const GoogleMapComp = withGoogleMaps((props) => /* <GoogleMap … /> */)
const Map = whenInView(GoogleMapComp)

ReactDOM.render(<Map />, document.getElementById('root'));
```

**Comment by wedneyyuri** [comment]
It makes sense, we can change the state using any jQuery plugin or similar
