### ISSUE TITLE
react-google-maps- InfoWindow adding content as string 

### ISSUE THREAD

**Issue by itayb8** [tomchentw/react-google-maps#368]
My issue started when I couldnt remove scrollbar from the InfoWindow using a InfoWindow component's child node (as the content of the InfoWindow). 
When I am using the builtIn props - 'content' to pass the content I am having another issue.
I create a list of items in the info window and each one of them has to be clickable. everything works fine except for the onclick event - shows me an error - Uncaught SyntaxError: Unexpected token (.
Can someone help me find whats wrong. thanks

getInfoWindow(items, i) {
    if (i === this.state.clickedMarker) {
      const content = `<div class="info-window-partner">${this.getInfoWindowContent(items)}</div>`;
      return (
        <InfoWindow
          disableAutoPan={true}
          content={content}
          onCloseclick={this.handleMarkerClose.bind(this)}
          key={`${i}_info_window`}>
        </InfoWindow>
      );
    }
  }

  getInfoWindowContent(items) {
    let htmlText = '<ul>';
    map(items, (item) => {
      htmlText = htmlText + `<li> 
        <span onclick=${this.onClickItem(itemId)}>
          some text
        </span>
      </li>`
    });
    htmlText = htmlText + '</ul>';
    return htmlText;
  }

  onClickItem(itemId) {
    return `function(){FlowRouter.go('/items/${itemId}')}`
  }

**Comment by danielehrlich** [comment]
I formatted your code so it looks more readable here: [https://jsfiddle.net/hoottkf0/](https://jsfiddle.net/hoottkf0/).

From at least this code, it looks like your issue is an extra greater-than-sign near the end of the first function where you are defining the key attribute:

```
key={`${i}_info_window`}>

);
```

Remove that extra sign and see if it works.

**Comment by itayb8** [comment]
Sorry, something in the copy paste went wrong from the first place. this is the complete version: 
getInfoWindow(items, i) {
    if (i === this.state.clickedMarker) {
      const content = `<div class="info-window-partner">${this.getInfoWindowContent(items)}</div>`;
      return (
        <InfoWindow
          disableAutoPan={true}
          content={content}
          onCloseclick={this.handleMarkerClose.bind(this)}
          key={`${i}_info_window`}>
        </InfoWindow>
      );
    }
  }

  getInfoWindowContent(items) {
    let htmlText = '<ul>';
    map(items, (item) => {
      htmlText = htmlText + `<li> 
        <span onclick=${this.clickedItem(item.itemId)}>
          some text
        </span>
      </li>`
    });
    htmlText = htmlText + '</ul>';
    return htmlText;
  }

  clickedItem(itemId) {
    return `function(){FlowRouter.go('/items/${itemId}')}`
  }

**Comment by tomchentw** [comment]
No. You can't use `HTML as string` for `content` nor `children` property for `InfoWindow`. The only thing allowed is React Element (JSX). Check the example here:
https://tomchentw.github.io/react-google-maps/basics/pop-up-window

Please notice that the example uses `react-google-maps@^6.0.0` version.

**Comment by itayb8** [comment]
How would you recommend me to avoid scrollbar in the InfoWindow?

**Comment by tomchentw** [comment]
Fix it via css styles `overflow: hidden` or giving it a fixed `width/height`?

**Comment by itayb8** [comment]
InfoWindow doesnt get styling props.

**Comment by tomchentw** [comment]
Would setting styles in `children` element work? Could you provide a minimal repository to demonstrate this?

**Comment by itayb8** [comment]
It wont work, that's where my issue started from. 
I understand why it doesnt work. I can see in chrome dev tool that the parent  element of my children element has attribute over-flow: auto. 
If instead I pass to InfoWindow content as props I can control the styling of the parent element but then I have problem mentioned previously.

**Comment by tomchentw** [comment]
@itayb8 I bet you mean `overflow: auto` on the element I highlighted below, right?

<img width="357" alt="screen shot 2016-10-23 at 9 12 42 pm" src="https://cloud.githubusercontent.com/assets/922234/19626467/8329de10-9965-11e6-87e1-319bc00da3ae.png">

In fact, **that** dom is created and managed by `Google Maps JavaScript API`. The only thing I can control is the dom of `data-reactroot` and its parent node (`<div>`). So even I allow you to pass content as string, it won't help.

You can validate on a plain JSFiddle with native Google Maps JavaScript API library.

**Comment by itayb8** [comment]
It did work with the code I provided earlier.

**Comment by itayb8** [comment]
Do you have another idea?

**Comment by tomchentw** [comment]
I remembered an old issue, #93, may help. Do you want to fork this project and try to make it work?

**Comment by itayb8** [comment]
I wish I could. it's a bit sensitive. The old issue seems to be very relevant. I'll try to work it though, with the help of issue #93.
