### ISSUE TITLE
6.0.0 and  Custom controls

### ISSUE THREAD

**Issue by n0ne** [tomchentw/react-google-maps#371]
Hi everyone.
How to create one small button with two states and one onClick event? 
I have no idea...Are there some examples or tuts?
It'll be great...
Thank you!

**Comment by amangeot** [comment]
Have you seen these demos: http://tomchentw.github.io/react-google-maps/basics/overlay-view ?

**Comment by n0ne** [comment]
Yees....why are you asking? I don't see any buttons on this map...

**Comment by RishabhJain96** [comment]
I believe you can either use an OverlayView, or try something like this: https://developers.google.com/maps/documentation/javascript/examples/control-custom.

**Comment by kstratis** [comment]
@n0ne I was wondering the exact same thing.  

It seems however that we are out of lack. Peeking at the [SearchBox](https://github.com/tomchentw/react-google-maps/blob/master/lib/places/SearchBox.js) code, I see hints everywhere that it's custom designed for maps usage  (google maps specific `controlPosition` prop) and as such no plain react component can be used. 

Any thoughts on that @tomchentw ?

or even a workaround for such a common scenario? 

Thanks.

**Comment by jm90m** [comment]
@kstratis Were you able to find a solution to this / workaround? I am trying to add a legend on the map

**Comment by kstratis** [comment]
@jm90m None I'm afraid...

**Comment by jm90m** [comment]
@kstratis Oh ok thanks for the reply

**Comment by tomchentw** [comment]
Please refer to [Getting Help](https://github.com/tomchentw/react-google-maps#getting-help) section in the README (or #469).
