### ISSUE TITLE
HeatmapLayer Broken

### ISSUE THREAD

**Issue by RishabhJain96** [tomchentw/react-google-maps#375]
HeatmapLayer should use `google.maps.visualization.HeatmapLayer` instead of just `google.maps.HeatmapLayer` in order to construct a HeatmapLayer.

**Comment by tomchentw** [comment]
Closed by #376

**Comment by tomchentw** [comment]
Released [6.0.3](https://github.com/tomchentw/react-google-maps/releases/tag/v6.0.3)

**Comment by tomchentw** [comment]
For better namespacing, I've moved it to under `visualization/` folder. See #470 for more details about the changes.

Released [6.1.0](https://github.com/tomchentw/react-google-maps/releases/tag/v6.1.0)
