### ISSUE TITLE
Change marker icon size

### ISSUE THREAD

**Issue by raysmithdev** [tomchentw/react-google-maps#377]
Is there a way to adjust the marker icon size ? I have alot of images which i am using as the marker icon but the sizes are too big so was wondering how to change the size and possibly make them rounded like normal CSS. Suggestions ?

**Comment by bulteau** [comment]
Do you try this method to adjust the size ? https://github.com/tomchentw/react-google-maps/issues/306

**Comment by tomchentw** [comment]
Please refer to [Getting Help](https://github.com/tomchentw/react-google-maps#getting-help) section in the README (or #469).
