### ISSUE TITLE
InfoWindow No OnCloseClick Event for React Google Maps v 4.11.0 and also in v.5.1.1.

### ISSUE THREAD

**Issue by akosialz** [tomchentw/react-google-maps#379]
So I am following this tutorial of yours

https://tomchentw.github.io/react-google-maps/basics/pop-up-window

basically the InfoWindow has this onCloseClick() event for capturing the, as the name of the method implies, close click in InfoWindow. Now when I installed v 4.11.0 and up to v.5.1.1. there's no onCloseClick event but according in your repo, there is.

How should I work on it? I cannot use v.5.1.1. because somehow when passing array of points to Marker class, it produces a "Not an array" error. Any aid would do

**Comment by akosialz** [comment]
Forgot to comment in here. Found out that onCloseClick event in InfoWindow exists in version 6.0.1. My bad.

**Comment by tomchentw** [comment]
Please refer to [Getting Help](https://github.com/tomchentw/react-google-maps#getting-help) section in the README (or #469).
