### ISSUE TITLE
Uncaught Error: Cannot find module "warning"

### ISSUE THREAD

**Issue by 7s4r** [tomchentw/react-google-maps#380]
I got this error with 6.0.1 version:

`./~/react-google-maps/~/warning/browser.js
Module build failed: Error: ENOENT: no such file or directory, open '/app/node_modules/react-google-maps/node_modules/warning/browser.js'
    at Error (native)
 @ ./~/react-google-maps/lib/withGoogleMap.js 37:15-33`

It seems that warning package isn't added in react-google-maps dependencies.

**Comment by 7s4r** [comment]
I fixed it. It was issue with docker & npm cache.

**Comment by tomchentw** [comment]
Please refer to [Getting Help](https://github.com/tomchentw/react-google-maps#getting-help) section in the README (or #469).
