### ISSUE TITLE
Can we add custom labels to markers?

### ISSUE THREAD

**Issue by anvk** [tomchentw/react-google-maps#383]
https://developers.google.com/maps/documentation/javascript/examples/marker-labels

**Comment by TerjeNorderhaug** [comment]
Just include a label attribute for the marker: 

`<Marker label="Hello" position= {{ lat: 12.97, lng: 77.59 }}>`

**Comment by tomchentw** [comment]
Please refer to [Getting Help](https://github.com/tomchentw/react-google-maps#getting-help) section in the README (or #469).

**Comment by kyawzinthant-coding** [comment]
how to styled?
