### ISSUE TITLE
event object in search box

### ISSUE THREAD

**Issue by kstratis** [tomchentw/react-google-maps#384]
Hi, 

Looking at [the examples page](https://tomchentw.github.io/react-google-maps/places/search-box), is there a way to access the event from within the `handlePlacesChanged()` method?
 
It accidentally triggers a form submit in my code and I'd like to `e.preventDefault()` it.

Thanks

**Comment by tomchentw** [comment]
Please refer to [Getting Help](https://github.com/tomchentw/react-google-maps#getting-help) section in the README (or #469).

**Comment by TimNZ** [comment]
For anyone else stumbling across this, add this to the &lt;input&gt;

```
onKeyDown={(e) => { 
                            if (e.keyCode == '13') 
                                e.preventDefault()
                        }}
```

https://stackoverflow.com/questions/11388251/google-autocomplete-enter-to-select/28373354
