### ISSUE TITLE
DrawingManager is undefined when imported from "react-google-maps"

### ISSUE THREAD

**Issue by prashantgaikwad** [tomchentw/react-google-maps#386]

**Comment by Falconerd** [comment]
I have this issue as well, not sure if I'm being dense. I ended up modifying the library to export it, but would like to know if there is some other way of getting access to DrawingManager. I would prefer not to have to modify it on other machines or include the package in my project.

I added this to `lib/index.js`:

```javascript
var _DrawingManager = require("./drawing/DrawingManager");

Object.defineProperty(exports, "DrawingManager", {
  enumerable: true,
  get: function get() {
    return _interopRequireDefault(_DrawingManager).default;
  }
});
```

**Comment by thejsn** [comment]
You have to import it from the `lib` directory:

`import DrawingManager from 'react-google-maps/lib/drawing/DrawingManager'`

**Comment by tomchentw** [comment]
Please refer to [Getting Help](https://github.com/tomchentw/react-google-maps#getting-help) section in the README (or #469).

**Comment by s9eenk** [comment]
DrawingManager not working at all....

![image](https://user-images.githubusercontent.com/23517231/43262803-03c70182-90ff-11e8-94ea-5940185a8e74.png)
![image](https://user-images.githubusercontent.com/23517231/43262990-98a3590e-90ff-11e8-9fc1-0931bee64106.png)
