### ISSUE TITLE
MarkerCluser view OverlayView in v4.11.0 - how to merge PR?

### ISSUE THREAD

**Issue by mariusandra** [tomchentw/react-google-maps#387]
Hey,

I had an issue with putting OverlayViews inside a MarkerCluster. The following changes, which I copied from a similar fix to Marker fix the problem:

https://github.com/tomchentw/react-google-maps/compare/v4.11.0...mariusandra:markercluster-overlayview

However, how can I merge this back into the v4? Github doesn't allow me to do a PR against a tag...?

Thanks! :)

Marius

**Comment by tomchentw** [comment]
Please use your own branch & repository.

**Comment by tomchentw** [comment]
Please refer to [Getting Help](https://github.com/tomchentw/react-google-maps#getting-help) section in the README (or #469).
