### ISSUE TITLE
Adding points to polylines.

### ISSUE THREAD

**Issue by ElGoorf** [tomchentw/react-google-maps#388]
I have polyline data in a store and trying to figure out how to have the line update as points are added to the _observablearray_ (I'm using MobX).

I tried modifying the markers example, but have no luck. It's going to take me a while to extract the relevant parts of my code, but wondering if in the mean time, anyone has a working example of something similar they could show me?

Thanks

**Comment by tomchentw** [comment]
Please refer to [Getting Help](https://github.com/tomchentw/react-google-maps#getting-help) section in the README (or #469).
