### ISSUE TITLE
Missing functionality to trigger a resize event

### ISSUE THREAD

**Issue by twanschik** [tomchentw/react-google-maps#392]
Hi,
it seems like there is no official way to trigger a resize event. Before i could use `triggerResize()`, however I can't find such a helper method anymore. The only way I can trigger a resize event is via `google.maps.event.trigger(this.map.context[__SECRET_MAP_DO_NOT_USE_OR_YOU_WILL_BE_FIRED], 'resize')` with this.map being the instance passed in `onMapMounted`. This seems really dirty. Is there a proper way to trigger a resize event?

**Comment by r2dev** [comment]
Oh my, this is a thing! Thanks for pointing out this 'secret' map object. I finally can do resize on this library

**Comment by Stupidism** [comment]
try this one
```

import ReactResizeDetector from 'react-resize-detector';
...
    <GoogleMap>
      <ReactResizeDetector handleWidth handleHeight onResize={onResize} />
    </GoogleMap>
```

**Comment by karthikkncs14** [comment]
Any where i can see the full implementation of resize of map on window resize

**Comment by tomchentw** [comment]
Please refer to [Getting Help](https://github.com/tomchentw/react-google-maps#getting-help) section in the README (or #469).
