### ISSUE TITLE
Async example doesn't work

### ISSUE THREAD

**Issue by andriytyurnikov** [tomchentw/react-google-maps#393]
```
withScriptjs(
  withGoogleMap(
```
fils with error `TypeError: (0 , _withScriptjs.withScriptjs) is not a function`

**Comment by finetype** [comment]
https://github.com/tomchentw/react-google-maps/blob/master/src/app/pages/async/AsyncGettingStartedExample.js

They are requiring from '../../../libs' or something, you have to switch that to 'react-google-maps' if you're using it in your own project. I had to tweak a few small things iirc, but it did finally work.

**Comment by Novex** [comment]
Try `import withScriptjs from 'react-google-maps/lib/async/withScriptjs';` - I'm not sure why it's not part of the default exports but that seems to pull it out for me.

**Comment by batjko** [comment]
I'm having the same issue. It used to work, but recently stopped (change in a new version?).
We're using react-google-maps v4.11.0 (not sure what it used to be when it still worked).

Looking into the node_modules/react-google-maps folder, the `withScriptjs` file simply doesn't seem to exist anymore?
Instead there is "ScriptjsGoogleMap.js" and "ScriptjsLoader.js" only:
![image](https://cloud.githubusercontent.com/assets/7287076/21261762/474c073e-c385-11e6-8d85-16325abcd468.png)

This is how we currently import, which as I said used to work:
```js
import { withGoogleMap, GoogleMap, Polyline, Marker } from 'react-google-maps';
import withScriptjs from 'react-google-maps/lib/async/withScriptjs';
```

**Comment by Novex** [comment]
Did you possibly miss the `@beta` tag when you npm installed?

I get those files if I do a straight `npm install react-google-maps`, but if I `npm install react-google-maps@beta` I get the expected withScriptjs files.

**Comment by batjko** [comment]
@Novex Yes, that's it! I wasn't aware of this and apparently the previous developer forgot to add it to our shrinkwrap.

Thanks a lot!

**Comment by tomchentw** [comment]
Please refer to [Getting Help](https://github.com/tomchentw/react-google-maps#getting-help) section in the README (or #469).
