### ISSUE TITLE
[MarkerClusterer] Repaints the map for every marker to add / remove

### ISSUE THREAD

**Issue by amangeot** [tomchentw/react-google-maps#395]
Hello,
I think this issue still exists in v6: https://github.com/tomchentw/react-google-maps/issues/210

The issue is that `MarkerClusterer` is passed down to `Marker`s within the context, so that `Marker` can add itself to the `MarkerClusterer`. Then the underlying `addMarker` or `removeMarker` forces a redraw on the map, for each added or removed marker.

From [Marker.js](https://github.com/tomchentw/react-google-maps/blob/master/src/lib/Marker.js): 
In  `getInitialState()`:  `markerClusterer.addMarker(marker);`
In `componentWillUnmount()`: `markerClusterer.removeMarker(marker)`

Now from [markerclustererplus.js](https://github.com/mahnunchik/markerclustererplus/blob/master/src/markerclusterer.js#L1194):
```
MarkerClusterer.prototype.addMarker = function (marker, opt_nodraw) {
  this.pushMarkerTo_(marker);
  if (!opt_nodraw) {
    this.redraw_();
  }
}
```

Not sure to be competent enough for this job, but I'll try my best to add a pull request that solves this issue.

**Comment by amangeot** [comment]
I forked the project and edited these two lines in Marker.js to prevent every added / removed `Marker`s from redrawing clusters:
In `getInitialState()`: `markerClusterer.addMarker(marker, true);`
In `componentWillUnmount(): `markerClusterer.removeMarker(marker, true)`

**Comment by tomchentw** [comment]
Please refer to [Getting Help](https://github.com/tomchentw/react-google-maps#getting-help) section in the README (or #469).
