### ISSUE TITLE
Responsive Map

### ISSUE THREAD

**Issue by michaelcpuckett** [tomchentw/react-google-maps#396]
Is there any way to make the center stay centered when resizing the window?

I found a simple responsive example, but the new center has already been calculated by the time I try to access it when using the component API.

https://codepen.io/hubpork/pen/xriIz

**Comment by tomchentw** [comment]
Please refer to [Getting Help](https://github.com/tomchentw/react-google-maps#getting-help) section in the README (or #469).

**Comment by andreivictor** [comment]
@michaelcpuckett, I have the same problem.
Did you find a solution for this?

**Comment by andreivictor** [comment]
I've tried with something like this, but it doesn't seem to work.

```javascript
class GoogleMapPickup extends Component {

    constructor() {
        //...
       this.handleWindowResize = debounce(this.handleWindowResize.bind(this), 500);
    }
    
    componentDidMount() {
        window.addEventListener('resize', this.handleWindowResize);
    }

    handleWindowResize() {
        const nextCenter = this._map.getCenter();
        console.log( 'nextCenter: ' + JSON.stringify(nextCenter) );
        google.maps.event.trigger(this._mapComponent, "resize");
        this.setState({
            center: nextCenter
        });
    }

}
```

However, in console I get different values for nextCenter on every resize.

**Comment by tommerbomb** [comment]
@andreivictor @michaelcpuckett Something like this worked for me:

```js
constructor(props) {
    super(props);
    this.state = {
      latitude: null,
      longitude: null,
    };
  }

setMapCenter = () => {
   // pull out latitude longitude from wherever you're getting it from
    const { latitude, longitude } = this.props; 
    this.setState({ latitude, longitude });
  };

  componentDidMount() {
    window.addEventListener('resize', this.setMapCenter);
  }
  componentWillUnmount() {
    window.removeEventListener('resize', this.setMapCenter);
  }
```


Then in your map component, set the `defaultCenter` to `{lat: latitude, lng: longitude}`. Just make sure to set the state when you receive the latitude and longitude values you want to use
