### ISSUE TITLE
V5/V6 with Meteor

### ISSUE THREAD

**Issue by eljefejames** [tomchentw/react-google-maps#398]
Has anyone successfully managed to use V5 or 6 with Meteor? I currently use V4 which works pretty smoothly, but I haven't been able to get V5 or 6 to run with Meteor 1.3 or higher. Would love to see an example of the two working together... Cheers

**Comment by tomchentw** [comment]
Please refer to [Getting Help](https://github.com/tomchentw/react-google-maps#getting-help) section in the README (or #469).
