### ISSUE TITLE
InfoBox children with onClick event

### ISSUE THREAD

**Issue by mychalvlcek** [tomchentw/react-google-maps#399]
Anyone experiencing issue with adding onClick event to InfoBox children?

```js
import InfoBox from 'react-google-maps/lib/addons/InfoBox';

<InfoBox>
    <div onClick={() => {console.log('clicked')}}>
        lorem ipsum
    </div>
</InfoBox>
```

**Comment by mychalvlcek** [comment]
ok i figured it out.. the problem wasnt here but in infobox library (https://github.com/lucasfs7/google-maps-infobox-module)

solution: infobox has disabled mouse event propagation by default..
so just set it up by option `enableEventPropagation`

```
const infoBoxProps = {
    position: new google.maps.LatLng(1,2),
    options: {
        enableEventPropagation: true
    },
};

<InfoBox {...infoBoxProps}>
    <div onClick={() => {console.log('clicked')}}>
        lorem ipsum
    </div>
</InfoBox>
```

**Comment by tomchentw** [comment]
Please refer to [Getting Help](https://github.com/tomchentw/react-google-maps#getting-help) section in the README (or #469).
