### ISSUE TITLE
GeoJson support in current version, or at least access to map.data.loadGeoJson?

### ISSUE THREAD

**Issue by finetype** [tomchentw/react-google-maps#400]
@tomchentw, I've been pulling my hair out trying to figure out how to use geojson with this plugin for the last two days. The last example I could find seems to be quite old, and I can't seem to get it working... What's the best way to get at the map object to use the native map.data.loadGeoJson ? Or do you have a working geoJsonToLatLang component in the most recent version? (Still, converting geojson to latlang seems a bit odd--curious why that decision was made)

Thanks for an excellent library. Just having a bit of trouble figuring out how it works, given the state of documentation right now, what with the new release, I guess. :/

It seems like there might be a solution to my question here, but the answer is a little too terse, and my understanding of the library too poor, to grok the context he's assuming I have... https://github.com/tomchentw/react-google-maps/issues/239

I see the old geojson component back in the 4.0.0 code here, but can't get it working:
https://github.com/tomchentw/react-google-maps/blob/67895ab6527e59354c7b6a414fc5651adec97483/examples/gh-pages/scripts/components/GeojsonToComponents.js#L74-L101

"ElementClass" is ending up as undefined in the render function, since importing Marker and InfoWindow seem to result in undefined in the current project.

Thanks for your help, and again, for the library. Just wish there were some more documentation!

**Comment by finetype** [comment]
I've got the imports 'working' for now, not sure if their api has changed (probably has), but was getting erors because I wasn't wrapping it in withGoogleMap(). So, I've tried refactoring it to use that, but now I'm getting `WGM(...): A valid React element (or null) must be returned. You may have returned undefined, an array, or some other invalid object.`

Here's my refactored render:

```
render () {
    const {props, state} = this,
          {initialGeoJson, googleMapsApi, ...otherProps} = props,
          {geoStateBy} = state,
          {features} = state.geoJson,
          mapFeature = features[0],
          mapGeometry = geometryToComponentWithLatLng(mapFeature.geometry),
          mapState = geoStateBy[0];

    const children = features.reduce((array, feature, index) => {
          if (index === 0) {
            return array;
          }
          const {properties} = feature,
                {ElementClass, ChildElementClass, ...geometry} = geometryToComponentWithLatLng(feature.geometry),
                {visible, child, ...featureState} = geoStateBy[feature.id] || {};
          if (visible !== false) {
            console.log('classes', ElementClass, !!child, ChildElementClass)
            array.push(
              <ElementClass key={`json-${feature.id}`} {...properties} {...geometry} {...featureState}>
                {child ? <ChildElementClass {...child} /> : null}
              </ElementClass>
            );
          }
          return array;
        }, [], this)

    return (
      <WGM
        containerProps={{
          ...otherProps,
          style: {
            height: "100%",
          },
        }}
        {...mapFeature.properties}
        {...mapState}
        center={mapGeometry.position}
        children={children}
      />
    );
  }
```

And here's the attempt at a wrapper:
`
const WGM = props => withGoogleMap(<GoogleMap { ...props } >...props.children</GoogleMap>);
`

This usage of ES6/7 and React in the way entailed here is really stretching my brain... So I could be doing something wrong... And it might all be for nothing, no clue whether this is going to be compatible with current stuff. -_-;;

**Comment by tomchentw** [comment]
Please refer to [Getting Help](https://github.com/tomchentw/react-google-maps#getting-help) section in the README (or #469).
