### ISSUE TITLE
SearchBox out of map

### ISSUE THREAD

**Issue by TrejGun** [tomchentw/react-google-maps#404]
I'd like to have SearchBox separated from the map, how can I do this?

**Comment by r2dev** [comment]
I am using [react-geosuggest](https://github.com/ubilabs/react-geosuggest). This library require to load the google map script manually, what i did was combine with "withScriptJS" from this library, it works perfectly.
`const GoogleSearchBox = withScriptJs( props => (<Geosuggest ....... />))`

**Comment by tomchentw** [comment]
Please refer to [Getting Help](https://github.com/tomchentw/react-google-maps#getting-help) section in the README (or #469).

**Comment by trungnguyencmu** [comment]
+1 Same issues, I have try search but got solution

**Comment by bidva** [comment]
@r2dev Can you provide more information how set this GoogleSearchBox to GoogleMap component?

**Comment by r2dev** [comment]
@bidva 
`const GMapApp = withScriptJs(props => (<Fragment><Geosuggest /><GoogleMap /></Fragment>))`
