### ISSUE TITLE
Property mapPanes is null

### ISSUE THREAD

**Issue by janprasil** [tomchentw/react-google-maps#405]
Hello,

I have a problem with overlayView - a property mapPanes becomes null when a component is rerendered (by incoming items that create new overlayViews) and i am still giving this error message:
`TypeError: Cannot read property 'overlayMouseTarget' of null`

from react-google-maps/lib/utils/OverlayViewHelper in mountContainerElementToPane

Here is my code:
```javascript
const clusterMarkers = cluster && cluster.map((x, key) => <OverlayView
     position={{ lat: x.lat, lng: x.lng }}
     mapPaneName={OverlayView.OVERLAY_MOUSE_TARGET}
     getPixelPositionOffset={getPixelPositionOffset}
     key={key}
    >
      <div onClick={...}>
        {x.title}
      </div>
    </OverlayView>);
<GoogleMap
      ref={setMap}
      center={c}
      zoom={z}
      onZoomChanged={zoomChangedHandler}
      onDragEnd={centerChangedHandler}
>
    {clusterMarkers}
</GoogleMap>
```
Please, do you have any idea to fix it?

I am using v6.0.0

**Comment by janprasil** [comment]
I found the answer - the overlay key was not unique.

**Comment by jtiscione** [comment]
Doesn't fix it for me...

**Comment by janprasil** [comment]
Add a random uuid to every key prop and change it every rerendering..

**Comment by techsev** [comment]
this solves the error messages BUT causes flickering on any setState that rerenders the map.

**Comment by hypersolo** [comment]
Did anyone come up with any solutions?

**Comment by urikphytech** [comment]
+1

**Comment by eforkin** [comment]
+1

**Comment by tomchentw** [comment]
Please refer to [Getting Help](https://github.com/tomchentw/react-google-maps#getting-help) section in the README (or #469).
