### ISSUE TITLE
KML preserveViewport bug (Temp Fix Inside) 

### ISSUE THREAD

**Issue by techsev** [tomchentw/react-google-maps#406]
Plugin is great, does everything I needed but when I load a KML, map recenters to fit the container. 

an old closed issue says to use

`<KmlLayer options={{preserveViewport: true}} />`

but it still didn't prevent the map from shifting. I was able to fix it by modifying the "KmlLayers.js" file to add the missing propType.

> var controlledPropTypes = {
>   // NOTICE!!!!!!
>   //
>   // Only expose those with getters & setters in the table as controlled props.
>   //
>   // [].map.call($0.querySelectorAll("tr>td>code", function(it){ return it.textContent; })
>   //    .filter(function(it){ return it.match(/^set/) && !it.match(/^setMap/); })
>   //
>   // https://developers.google.com/maps/documentation/javascript/3.exp/reference#KmlLayer
>   defaultViewport: _react.PropTypes.any,
>   preserveViewport: _react.PropTypes.any,
>   metadata: _react.PropTypes.any,
>   status: _react.PropTypes.any,
>   url: _react.PropTypes.string,
>   zIndex: _react.PropTypes.number
> }; /* global google */

I added `preserveViewport: _react.PropTypes.any,` and now it works perfectly!

thanks, again, great plugin

**Comment by jsmapr1** [comment]
Put in a pull request to address this issue: https://github.com/tomchentw/react-google-maps/pull/428

**Comment by tomchentw** [comment]
Please refer to [Getting Help](https://github.com/tomchentw/react-google-maps#getting-help) section in the README (or #469).

**Comment by tomchentw** [comment]
Released [6.2.0](https://github.com/tomchentw/react-google-maps/releases/tag/v6.2.0)
