### ISSUE TITLE
Differentiate ref's onMapLoad and onMapRender

### ISSUE THREAD

**Issue by ZephD** [tomchentw/react-google-maps#407]
When using the ref from the GoogleMap component, the function gets triggered every time the map renders.

I'm currently using fit to bounds during this function, but it means if I re-render the map the map gets re fitted to bounds.

Is there a way to differentiate the initial load (the first time the map object is created) from a re-render?

**Comment by tomchentw** [comment]
Please refer to [Getting Help](https://github.com/tomchentw/react-google-maps#getting-help) section in the README (or #469).
