### ISSUE TITLE
[Info Window] blink/glintch/twinkle when opening big InfoWindow

### ISSUE THREAD

**Issue by Stupidism** [tomchentw/react-google-maps#408]
## Behaviour
like the title saied

## Way to reproduce
a little modify on the demo app:
```
          <InfoWindow onCloseClick={() => props.onMarkerClose(marker)}>
            <div>
              {marker.infoContent}
              <div>can you see this below the pin</div>
              <div>can you see this below the pin</div>
              <div>can you see this below the pin</div>
              <div>can you see this below the pin</div>
              <div>can you see this below the pin</div>
              <div>can you see this below the pin</div>
              <div>can you see this below the pin</div>
              <div>can you see this below the pin</div>
              <div>can you see this below the pin</div>
              <div>can you see this below the pin</div>
              <div>can you see this below the pin</div>
              <div>can you see this below the pin</div>
            </div>
          </InfoWindow>
```

## Version
As I can know, not happened in v4.

## Others
I don't know if these would help. I didn't find a solution myself yet.

http://stackoverflow.com/questions/15399585/infowindow-blinks-when-calling-setcontent-on-google-maps-api-v3

http://stackoverflow.com/questions/20219179/google-map-js-api-version-3-infowindow-glitch

**Comment by Stupidism** [comment]
Anybody tracking this?

**Comment by Stupidism** [comment]
@tomchentw Do you know where the bug locates in this repo? If you can tell me, maybe I can help you fix this.

**Comment by AdamFrey** [comment]
@Stupidism the InfoWindow module is here: https://github.com/tomchentw/react-google-maps/blob/f1712f229429a5d184e968c09a1b2ff8f50be08c/src/lib/InfoWindow.js

As you can see in this line (https://github.com/tomchentw/react-google-maps/blob/3163a995adb5400f9324d24f24491ba261a6e469/src/lib/InfoWindow.js#L127), the original content of the info window is just a blank div, and then later the content is replaced with the React children, causing the flickering resize. The content of the `InfoWindow` should probably be set to the correct html initially instead of a blank div to avoid the flickering.

**Comment by Stupidism** [comment]
Maybe add a style `overflow: hidden` will do the trick.

**Comment by Stupidism** [comment]
Tried
```
    const content = document.createElement(`div`);
    content.style.cssText = 'overflow:hidden;';

    const infoWindow = new google.maps.InfoWindow({
      ///...
      content,
      children: undefined,
    });
```
Not working

**Comment by Stupidism** [comment]
Not working even with 
```css
.gm-style-iw > div, .gm-style-iw > div > div {
  overflow: hidden !important;
}
```

**Comment by Stupidism** [comment]
Actually, first time to open the InfoWindow, there's no flicker. Only happens when close it and open it again.

**Comment by feux07** [comment]
I also have same problem, I didn't find a solution yet.

**Comment by ztanner** [comment]
I've attempted to fix this with https://github.com/tomchentw/react-google-maps/issues/449. Let me know if it worked for you. I tested with your example and it seems to have.

**Comment by tomchentw** [comment]
Please refer to [Getting Help](https://github.com/tomchentw/react-google-maps#getting-help) section in the README (or #469).
