### ISSUE TITLE
Testing <GoogleMap/> inside withScriptjs and withGoogleMap

### ISSUE THREAD

**Issue by ZephD** [tomchentw/react-google-maps#410]
The element is as follows:

```
import React from 'react';
import { withGoogleMap, GoogleMap } from 'react-google-maps';
import withScriptjs from 'react-google-maps/lib/async/withScriptjs';

const AsyncGoogleMap = withScriptjs(withGoogleMap(({ onMapLoad }) => (
    <GoogleMap
      ref={onMapLoad}
      defaultZoom={1}
      defaultCenter={{ lat: 0, lng: 0 }}
    />
  )));
export default AsyncGoogleMap;
```

The test is as follows:
```
import React from 'react';
import { mount } from 'enzyme';
import expect from 'expect';

import AsyncGoogleMap from './AsyncGoogleMap';

describe('AsyncGoogleMap component', () => {
  let wrapper;
  before((done) => {
    wrapper = mount(<AsyncGoogleMap
      googleMapURL={'https://maps.googleapis.com/maps/api/js'}
      loadingElement={<div>Loading</div>}
      containerElement={<div>Container</div>}
      mapElement={<div>Map</div>}
      onMapLoad={done}
    />);
  });

  it('renders without throwing', () => {
    expect(wrapper).toExist();
  });
});
```

I get the error:
> Warning: Make sure you've put a <script> tag in your <head> element to load Google Maps JavaScript API v3.
> If you're looking for built-in support to load it for you, use the "async/ScriptjsLoader" instead.
 See https://github.com/tomchentw/react-google-maps/pull/168

(Followed by the Mocha error:
> "before all" hook failed
> Error: Timeout of 2000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves.

)

Therefore, 'done' is not being called, because of the first error preventing the map from being created.

Now, I'm using withScriptjs, and therefore google.maps should be loaded for me. I should not be getting the first error.

Note that the element <AsyncGoogleMap/> works perfectly in a real environment, but it does not work when testing.

Is there anything I have missed?

**Comment by oshalygin** [comment]
@ZephD you ever get this resolved?

**Comment by ZephD** [comment]
Nope.

**Comment by oshalygin** [comment]
@ZephD I'm having the exact same issue, I tried it 5 different ways and even relaxed the timeout limit.   I can't get at the children of the component which Id really like to test because they contain `<Marker>`'s :(

I'll give it another whirl later in the day and let you know.

**Comment by petertdinh** [comment]
You don't need done to be called with this component, so just get rid of that in beforeEach and it should work.

**Comment by oshalygin** [comment]
@petertdinh care to share a snippet?  I couldn't get it working without the done call.  The script loads asynchronously, how is it that the done call isnt needed?  You mean return?  That does the same thing.

**Comment by ZephD** [comment]
The done is the most important bit, as it gets called once the map is ready, allowing the tests to continue.
Looking back at this code, it may be possible to increase the timeout, but I doubt that's the issue.

**Comment by oshalygin** [comment]
Increasing the timeout is a **very big** hack, we shouldn't be doing that, even if it works.  I've tried a few approaches to testing this and the best I can get is reading the props on the component(aka useless).

**Comment by tomchentw** [comment]
Don't do this. Use shallow rendering to test the inner component directly.

**Comment by tomchentw** [comment]
Please refer to [Getting Help](https://github.com/tomchentw/react-google-maps#getting-help) section in the README (or #469).

**Comment by christianrank** [comment]
How to test the GoogleMap and access the Marker elements using shallow rendering?
I can't figure out what you mean. Can you give an example please?

**Comment by tomchentw** [comment]
@christianrank short version

```jsx
const Inner = props => <GoogleMap><Marker ………

const Outer = withScriptjs(withGoogleMap((Inner)); // you __use__ with Outer
// test case
expect(<Inner {...props />).toMatchSnapshot(); // you __test__ on Inner
```

**Comment by toroduque** [comment]
@tomchentw please share a "non-short" version :)

**Comment by metr1ckzu** [comment]
@tomchentw @toroduque Can relate, would be much appreciated.

**Comment by tyewang** [comment]
@tomchentw testing the "inner component" with shallow rendering doesn't work for me. For example:
```
    const component = renderer.create(                                                                    
      <Inner containerElement={ <div id='containerElement'/> } mapElement={ <div id="mapElement"/> }/>
    );                                                                                                    
    let tree = component.toJSON();                                                                        
```
At this point, `tree` is simply
```
<div  id='containerElement'>
    <div id="mapElement">
    </div>
</div
```
which isn't meaningful.

**Comment by tomchentw** [comment]
Try using shallow rendering? @tyewang 
https://reactjs.org/docs/shallow-renderer.html

**Comment by tyewang** [comment]
Got it, didn't realize shallow rendering was different than the test renderer. Thanks!

**Comment by metr1ckzu** [comment]
@tyewang Hi sir, would you mind to share your tests? Can't figure out how to test react-google-maps, thanks in advance

**Comment by tyewang** [comment]
@metr1ckzu 

```
// component.js
const MapWithoutDOMInstances = class extends React.Component {
  render() {
      <GoogleMap ...>
        ...
      </GoogleMap>
  }
}

const MapWithDOMInstances = withGoogleMap(MapWithoutDOMInstances);
```

```
// component.test.js
test("renders correctly", () => {
  const renderer = new ShallowRenderer();

  const result = renderer.render(<MapWithoutDOMInstances ... />);

  expect(result).toMatchSnapshot();
});
```

**Comment by tomchentw** [comment]
@tyewang wanna make a PR adding these to the `src/docs` :) ?
