### ISSUE TITLE
withGoogleMap is not a function?

### ISSUE THREAD

**Issue by seansinflipflops** [tomchentw/react-google-maps#413]
I keep getting the error that Uncaught TypeError: (0 , _reactGoogleMaps.withGoogleMap) is not a function

does anyone else get this error, i am importing withGoogleMap from react-google-maps.

**Comment by cameronmoreau** [comment]
This happened to me earlier, make sure you have version 6.0.0 or above.
By default, npm downloaded v4, so you should look at [these docs instead](https://github.com/tomchentw/react-google-maps/tree/v4.1.0#documentation)

If you want to use the withGoogleMap method, run
`npm install --save react-google-maps@6.0`

**Comment by seansinflipflops** [comment]
Thanks @cameronmoreau !

**Comment by ajits731** [comment]
Its still not working!

**Comment by tomchentw** [comment]
Please refer to [Getting Help](https://github.com/tomchentw/react-google-maps#getting-help) section in the README (or #469).
