### ISSUE TITLE
google is not defined? 

### ISSUE THREAD

**Issue by sho13** [tomchentw/react-google-maps#414]
Hey, I keep getting a reference error for google in the withGoogleMap at line 101.

`Uncaught ReferenceError: google is not defined - withGoogleMap.js:101 `

Does anyone know how to remedy this error?

**Comment by max8hine** [comment]
withGoogleMap.js? withGoogleMap is higher order component wrapper, should not be a file name. 
```javascript
import {withGoogleMap, GoogleMap, Marker} from 'react-google-maps';
const GoogleMapHOC = withGoogleMap(
	props => ( <GoogleMap><Marker> </GoogleMap>)
)
```

**Comment by ZephD** [comment]
You must run the google amps script in your index.html
`<script src="https://maps.googleapis.com/maps/api/js?key=YOUR_KEY></script>`
Or wrap withGoogleMap() with withScriptjs()
`withScriptjs(withGoogleMap((props) => ( <GoogleMap />)))`

**Comment by josephmisiti** [comment]
@seansinflipflops as @ZephD said, insert 

```<script src="https://maps.googleapis.com/maps/api/js?key=YOUR_KEY></script>```

in the top of you index.html file and you should be good to go.

**Comment by Bazze** [comment]
One of my users got this error today as well actually, even though I'm wrapping it correctly. Or at least it has been working for months (see below). Could there be a possible race condition/timeout case which could cause this?

```javascript
const AsyncGoogleMap = _.flowRight(
  withScriptjs,
  withGoogleMap,
)(props => (
  <GoogleMap
    ref={props.onMapLoad}
    [...]
  >
    [...]
  </GoogleMap>
));

class MyComponent extends React.Component {
  <AsyncGoogleMap
    googleMapURL="https://maps.googleapis.com/maps/api/js?v=3.25&libraries=geometry,drawing,places&key=<key goes here>"
    [...]
  />
}
```

**Comment by sho13** [comment]
@Bazze i think @ZephD has the right idea.

**Comment by Bazze** [comment]
@sho13 I'm not so sure. The whole idea with the `withScriptJs` is to load the Google Maps SDK async and when done load the map, right? I only want to include the Google Maps stuff if the user actually visits that page where I display a map. It's working perfectly, but today 1 user encountered this error so something strange might be going on here?

**Comment by ZephD** [comment]
Can you found out where in withScripts google is used but not defined?

**Comment by Bazze** [comment]
@ZephD On the exact same line as reported in this issue.

```
node_modules/react-google-maps/lib/withGoogleMap.js in google at line 101:0
```

Which is:
```
var map = new google.maps.Map(node);
```

**Comment by davidpatters0n** [comment]
I ran into the same issue due to me using eslint. In order to over come this issue I had to add at the top of my file: `/* eslint-disable no-unde */`.

**Comment by nodox** [comment]
@davidpatters0n solution did the trick for me!

**Comment by ZephD** [comment]
eslint is an IDE warning/error. Should not have problems when running.
If there are problems when running, perhaps it can be changed to `window.google.maps.Map(node)`.

**Comment by oshalygin** [comment]
The eslint issue is _not_ the problem.  

you're likely not including the necessary google maps script.

**Comment by Karrsen** [comment]
@ZephD whenever I insert 
<script src="https://maps.googleapis.com/maps/api/js?key=YOUR_KEY></script>
I just get "unterminated string literal" and it messes with the rest of the code. Any ideas? I've tried to change "</script>" to "<\/script>" and also tried changing it to "</scr"+"ipt>" but neither worked. Thanks.

**Comment by oshalygin** [comment]
> @Karrsen 
> @ZephD whenever I insert

> <script src="https://maps.googleapis.com/maps/api/js?key=YOUR_KEY></script>
I just get "unterminated string literal" and it messes with the rest of the code. Any ideas? I've tried to change "</script>" to "</script>" and also tried changing it to "</scr"+"ipt>" but neither worked. Thanks.

Where are you trying to add this script? Please refer to the updated README documentation:
[Getting Starter](https://github.com/tomchentw/react-google-maps#getting-started)

**Comment by ZephD** [comment]
<script src="https://maps.googleapis.com/maps/api/js?key=YOUR_KEY**"**></script>

**Comment by subhamagr** [comment]
I am facing the exact same issue. Does anyone know the solution to it?
I followed [`the async`](https://tomchentw.github.io/react-google-maps/async) example. 

running react-google-maps@7.2.0.

**Comment by ZephD** [comment]
Wrap your component with withScriptjs() and it should only load if google is available.

**Comment by subhamagr** [comment]
@ZephD how? I have followed the async example. Can you please give an example?

**Comment by ZephD** [comment]
See https://github.com/tomchentw/react-google-maps/issues/414#issuecomment-270935666

**Comment by subhamagr** [comment]
@ZephD Still not able to solve. Here's my code:

```javascript
const AsyncGoogleMap = withScriptjs(withGoogleMap(props => (
  <GoogleMap
    ref={props.onMapLoad}
    zoom={props.zoom}
    center={props.center}
    onBoundsChanged={props.onBoundsChanged}
    onClick={props.onMapClick}
    googleMapURL={props.googleMapURL}
  >
    {props.children}
  </GoogleMap>
)));


export default class ZoneMap extends Component {
  ...
 render() {
  return (
      <AsyncGoogleMap
        googleMapURL={`https://maps.googleapis.com/maps/api/js?key=${GOOGLE_API_KEY}`}
        loadingElement={
          <p>Loading google map.</p>
        }
        containerElement={
          <div style={{ height: '100%' }} />
        }
        mapElement={
          <div style={{ height: '100%' }} />
        }
        bounds={this.state.bounds}
        center={this.state.center}
        onMapLoad={this.handleMapLoad}
        zoom={this.state.zoom}
        onBoundsChanged={this.handleBoundsChanged}
      >
        {this.props.markers.map((marker, i) =>
          <Marker
            position={marker}
            draggable={false}
            key={i}
          />,
        )}
      </AsyncGoogleMap>
    );
  }
}


```

**Comment by dylmye** [comment]
I'm getting errors about missing props using the aforementioned technique.

Code:
```
const Map = withScriptjs(withGoogleMap(props => (
  <GoogleMap
    defaultZoom={17}
    center={props.center}
  >
    { ... handling markers here, unrelated ... }
  </GoogleMap>
)));
```

I have the script reference in my index.html.

Here is the error message: `Uncaught Error: Required props loadingElement or googleMapURL is missing. You need to provide both of them.` It's also `The prop 'googleMapURL' is marked as required in 'withScriptjs(withGoogleMap(Component))', but its value is 'undefined'.` Were props added between now and 23 days ago?

**Comment by ZephD** [comment]
Where you use `Map`, you need to provide those two items (loadingElement used by withScriptjs, it gets rendered while it's async-loading the google scripts, url used by GoogleMap to download the script from, include your API key).

**Comment by ArtemKislov** [comment]
try adding `/* global google */`  to the top of the file

**Comment by dineshsdm** [comment]
Excellent!

**Comment by arunrajnov3** [comment]
I am getting the error google is not defined for following code:

```
`import {
  withScriptjs,
  withGoogleMap,
  GoogleMap,
  Marker
} from "react-google-maps";
import { compose, withProps } from "recompose";
import { MarkerWithLabel } from "react-google-maps/lib/components/addons/MarkerWithLabel";

export const Map = compose(
  withProps({
    googleMapURL:
      "https://maps.googleapis.com/maps/api/js?key=key&v=3.exp&libraries=geometry,drawing,places",
    loadingElement: <div style={{ height: `100%` }} />,
    containerElement: <div style={{ height: `400px`,width: '700px', marginLeft: '100px' }} />,
    mapElement: <div style={{ height: `100%` }} />
  }),
  withScriptjs,
  withGoogleMap
)(props => (
  <GoogleMap defaultZoom={4} defaultCenter={{ lat: 38.667140, lng: -99.406363 }}>
      <MarkerWithLabel
      position={{ lat: 38.667140, lng: -99.406363 }}
      labelAnchor={new google.maps.Point(0, 0)}
      labelStyle={{backgroundColor: "yellow", fontSize: "14px", padding: "5px"}}
    >
      <div>Opco</div>
    </MarkerWithLabel>
    
  </GoogleMap>
));`
```

**Comment by ZephD** [comment]
your `labelAnchor={new google.maps.Point(0, 0)}` is causing the issue. At this point, google may not be defined.
use a point literal `labelAnchor={{x:0,y:0}}`
https://developers.google.com/maps/documentation/javascript/reference#Point

**Comment by yoavgecht** [comment]
does anyone was able to solve this? i'm getting 

Cannot read property 'maps' of undefined
var map = new google.maps.Map(node)

withGoogleMap. js line 149

I tried to change this line to 

var map = new window.google.maps.Map(node)
didn't help
const DestinationsMapComponent = compose(
  withProps({
    googleMapURL: "https://maps.googleapis.com/maps/api/js key='MYKEY'&libraries=places",
    loadingElement: <div style={{ height: `100%` }} />,
    containerElement: <div style={{ height: `400px` }} />,
    mapElement: <div style={{ height: `100%` }} />,
  }),
  withScriptjs,
  withGoogleMap
)((props) =>
  <GoogleMap
   ....
   ....
   ....
 </GoogleMap>

**Comment by ZephD** [comment]
You solve it by not calling `google.maps.*` unless `google` and `google.maps` exists.
Or, do not load google maps asynchronously (i.e. do not use withScriptJs, but instead use a <script> tag in the html)

**Comment by yoavgecht** [comment]
ok I think I solved it.
call the maps api on the head of index.js

then on the map component just use it like this:

const yourComponent = withGoogleMap(props => (
  <GoogleMap
    defaultCenter={props.center}
    defaultZoom={props.zoom} 
   .....
   .....
/>
));

It solves the refresh google is not defined problem. app will no more crash on refresh

**Comment by ZephD** [comment]
You mean your error occurs here?
https://github.com/tomchentw/react-google-maps/blob/master/src/withGoogleMap.jsx#L59
If so, you should have got a warning.

Great you solved it, but the compose version should have done the same thing.

**Comment by yoavgecht** [comment]
With compose google was undefined on withGoogleMap.js file, because I didn't reference maps api on index head. Once I reference the maps api on the head it complained I called the maps api multipile times. and also was crahing every 2nd refresh. bad cycle.

**Comment by ZephD** [comment]
That's because you continued to use "withScriptjs". Either use the head script, or withScripjs.
It's still strange that the error occurred on that line with withScriptjs alone, though.

**Comment by yoavgecht** [comment]
I don't know I did exactly like step 5 in the documentation and still google was undefined. sorry it was not defined

**Comment by CodingToBeWithHer** [comment]
what worked for me: 
instead of just google, I have used window.google, hopefull it'll work for you

**Comment by yoavgecht** [comment]
It's still happening on every other page load
ReferenceError: google is not defined
    at n.value (withGoogleMap.js:149)
althought I'm using withGoogleMap(props => (

http://ec2-18-196-246-145.eu-central-1.compute.amazonaws.com/

Something wrong with this library

**Comment by ZephD** [comment]
you need withScriptjs(withGoogleMap( ... ))

**Comment by dylmye** [comment]
@oshalygin is this issue ok to lock as it's been solved?

**Comment by yoavgecht** [comment]
Looks like the issue is resolved when adding withScriptjs(withGoogleMap( ... ))

**Comment by jwm0** [comment]
Make sure you run the script without "async defer" flag, otherwise it might not load in the correct order.

**Comment by Alfreddatui** [comment]
If you already follow every comment in this page, you can try this solutions (IF you are using create-react-app)

Stackoverflow : https://stackoverflow.com/questions/43714895/google-is-not-defined-in-react-app-using-create-react-app?utm_medium=organic&utm_source=google_rich_qa&utm_campaign=google_rich_qa

**Comment by amangeot** [comment]
Our users have been receiving this error inconsistently in production. 

We use withScriptJs and withGoogleMap hoc, though for unknown reasons, following links will break the code here: https://github.com/tomchentw/react-google-maps/blob/master/src/withGoogleMap.jsx#L59
while loading or reloading the page works just fine.

Any suggestion will be greatly appreciated!

**Comment by Piemontez** [comment]
The withGoogleMap function doesn't prevent "google is not loaded" error.

I proposed a solution to this in
https://github.com/Piemontez/react-google-maps/blob/patch-1/src/withGoogleMap.jsx : 59.

In my case, my system operates offline too and this crash is right.

**Comment by AliIsmeal** [comment]
> Make sure you run the script without "async defer" flag, otherwise it might not load in the correct order.

It solved the problem,Thank you

**Comment by terabytes** [comment]
Adding `window` in front of google.maps() to make `window.google.maps()` did the trick for me. Thanks @ZephD !

**Comment by niiazemiluulu** [comment]
LoooooooL, I was trying to solve that issue for the last hour. Just make sure to `withScriptJs` goes before `withGoogleMaps`

**Comment by DavidAmyot** [comment]
Our app still has classes and I found the easiest way was to create a wrapper component that uses the useJsApiLoader hook.

**withGoogleMap.js**
```
import React from "react";
import { useJsApiLoader } from "@react-google-maps/api";

export const withGoogleMap = (Component) => {
  const ComponentWithGoogleMapProp = (props) => {
    const { isLoaded, loadError } = useJsApiLoader({
      googleMapsApiKey: process.env.GOOGLE_MAPS_KEY,
    });

    return <Component {...props} googleMap={{ isLoaded, loadError }} />;
  };

  return ComponentWithGoogleMapProp;
};
```

**SomeComponent.js**
```
import { withGoogleMap } from "@utils/withGoogleMap";

class SomeComponent extends PureComponent {
  // ...

  render() {
    const { isLoaded, loadError } = this.props.googleMap;  

    return (
      {!loadError ? (
          isLoaded ? (
             <GoogleMap {...mapProps}>{this.renderMapMarkers()}</GoogleMap>
          ) : (
            <MapLoadingSpinner />
          )
        ) : (
          <MapErrorView />
        )}
      }
    )
  }


export default withGoogleMap(SomeComponent);

```
