### ISSUE TITLE
typeError: (0 , _googleMapsReact.withGoogleMap) is not a function

### ISSUE THREAD

**Issue by jamesoliverband** [tomchentw/react-google-maps#418]
Hi,

I am getting this error: typeError: (0 , _googleMapsReact.withGoogleMap) is not a function 

My 'google-maps-react' version is 6.0.1

Please help me!

**Comment by mattcarlotta** [comment]
Not sure why you're getting this error, but here's a stripped down version of some code from a project I'm currently working on that should get you in the right direction (this works for 6.0.1 running React 15.4.1):

The "RenderGoogleMap" is a presentational component that will render the "CreateGoogleMap" component inside of a table. This way, you can control where to place it on the page and how large you want it.

RenderGoogleMap:
```
import React, { Component } from 'react';
import { connect } from 'react-redux';

import  CreateGoogleMap  from './CreateGoogleMap';


class RenderGoogleMap extends Component {
  render() {
   return (
     <table>
      <thead>
       <tr>
        <th> </th>
       </tr>
      </thead>
      <tbody>
        <CreateGoogleMap />
       </tbody>
      </table>
    );
  }
}

export default RenderGoogleMap;

```

CreateGoogleMap:
```
import React, { Component } from 'react';
import { withGoogleMap, GoogleMap, Marker } from 'react-google-maps';

class CreateGoogleMap extends Component {
  renderGoogleMap() {
    const key = "Yosemite Valley";
    const lat = 37.8651;
    const lng = 119.5383; 
    const markers = [{
      position: {
        lat,
        lng,
      },
      key,
      defaultAnimation: 2,
    }];

    const GettingStartedGoogleMap = withGoogleMap(props => (
      <GoogleMap
        ref={props.onMapLoad}
        defaultZoom={12}
        defaultCenter={{ lat, lng }}
        onClick={props.onMapClick}
      >
        {props.markers.map(marker => (
        <Marker
          {...marker}
          onRightClick={() => props.onMarkerRightClick(marker)}
        />
      ))}
      </GoogleMap>
    ));

    return (
      <div>
        <GettingStartedGoogleMap
          containerElement={
           <div style={{ height: `300px` }} />
          }
          mapElement={
            <div style={{ height: '100%' }} />
          }
          onMapLoad={this.handleMapLoad}
          onMapClick={this.handleMapClick}
          markers={markers}
          onMarkerRightClick={this.handleMarkerRightClick}
        />
      </div>
     );
    }

  render() {
    return (
      <tr>
        <td>
          {this.renderGoogleMap()}
        </td>
      </tr>
    );
  }
}

export default CreateGoogleMap;
```

If you don't want the map to be constrained within a table and you just want a Google Map to display over your entire presentational component, then remove the table,tbody,thead,...etc tags and replace them with a single div over the CreateGoogleMap tag inside the "RenderGoogleMap" component, then replace the above GettingStartedGoogleMap code inside "CreateGoogleMap" with this...

```
return (
      <div>
        <GettingStartedGoogleMap
          containerElement={
           <div style={{ height: '100%' }} />
          }
          mapElement={
           <div style={{
              position: 'absolute',
              top: 0,
              left: 0,
              right: 0,
              bottom: 0,
             }} />
           }
          onMapLoad={this.handleMapLoad}
          onMapClick={this.handleMapClick}
          markers={markers}
          onMarkerRightClick={this.handleMarkerRightClick}
        />
      </div>
    );
```
Constrained:
![weathermap](https://cloud.githubusercontent.com/assets/22607722/21669900/92384dd6-d2c4-11e6-9eba-dfe296f63461.png)

or...

Unconstrained:
![mapcomponent](https://cloud.githubusercontent.com/assets/22607722/21669892/70571d00-d2c4-11e6-8ace-b56e3de575fa.png)

**Comment by hazboun** [comment]
I'm facing the same error. I did `npm install --save react-google-maps@beta` and got `npm ERR! cb() never called!`, so I tried master `npm install --save react-google-maps' and then I started getting the same error above!

Any ideas?

**Comment by mattcarlotta** [comment]
`npm install --save react-google-maps@6` is what I used.

**Comment by metastew** [comment]
I'm getting the same error as well. I've tried installing version 6 via npm, but no go on that solution.

**Comment by TheRizzen** [comment]
Same here. The getting started would need a little refresh to be quickly understandable..

**Comment by Zetberg** [comment]
+1

**Comment by tomchentw** [comment]
This is `react-google-maps` not `google-maps-react`.

**Comment by tomchentw** [comment]
Please refer to [Getting Help](https://github.com/tomchentw/react-google-maps#getting-help) section in the README (or #469).
