### ISSUE TITLE
MarkerCluster

### ISSUE THREAD

**Issue by melyourhero** [tomchentw/react-google-maps#420]
Hello. I guess you can help me. There's any possibility of getting the markers inside a cluster?

**Comment by Stupidism** [comment]
https://tomchentw.github.io/react-google-maps/addons/marker-clusterer

**Comment by melyourhero** [comment]
No about this. For example, I want to get data inside cluster by clicking on it. It is possible to get markers inside this cluster?

**Comment by Stupidism** [comment]
Read the document of [MarkerCLuster](https://github.com/googlemaps/v3-utility-library/tree/master/markerclusterer). 

I tried once and it works but didn't leave any code usable.
I could only get the `GoogleMap markers` in the cluster. By some way, maybe you can add some custom meta data in the `GoogleMap markers`.

-----------------------------------------------------------

I recovered that `react-google-maps markers` blocked custom meta data. Maybe it needs the library to loose the restrictions

**Comment by noushad-pp** [comment]
@melyourhero were you able to figure out a solution for this?

**Comment by melyourhero** [comment]
@noushad-pp
@Stupidism  
Unfortunately, I have not found a way to get to the data markers in a cluster. Are there any suggestions?

**Comment by noushad-pp** [comment]
@melyourhero  I passed the ids of the data as the key of the  associated marker and was able to get the list of markers oncluster click. I had to manually recreate data from the returned marker keys and was unable to get the any custom data passed to the marker.


```import {default as React, Component} from "react";
import { withGoogleMap, GoogleMap, Circle, Marker} from "react-google-maps";
import MarkerClusterer from "react-google-maps/lib/addons/MarkerClusterer";

const GeolocationMap = withGoogleMap(props => (
    <GoogleMap defaultZoom={14} center={props.center} ref={props.onMapMounted} onDragEnd={props.onDragEnd} onMapMounted={props.onMapMounted} onZoomChanged={props.onZoomChanged} mapSparks={props.mapSparks} mapSparksLoaded={props.mapSparksLoaded}>
        <Marker position={props.myLoc} title="Click to zoom" onClick={props.onMarkerClick}/>
        { props.myLoc && ( <Circle center={props.myLoc} radius={props.radius} options={circleOptions}/> ) }
        <MarkerClusterer averageCenter enableRetinaIcons={true} gridSize={30} zoomOnClick={false} onClick={(cluster)=> props.onClusterClicked(cluster)}>
            {props.mapSparks.map(spark => (
                <Marker position={{ lat: spark.lat, lng: spark.lng }} key={spark._id} title={spark._id} spark={spark} />
            ))}
        </MarkerClusterer>
    </GoogleMap>
));

```

**Comment by melyourhero** [comment]
@noushad-pp The same thing. I can't get any data which I passed to marker component.

**Comment by melyourhero** [comment]
@noushad-pp The same thing. I can't get any data which I passed to marker component.

**Comment by noushad-pp** [comment]
@melyourhero you can JSON.stringify the data and pass it as title of the marker and later on parse it . This can be used as a dirty hack if you are not passing any actual title param to the marker.

**Comment by melyourhero** [comment]
@noushad-pp Yes, you were right. Thank you very much for your help. 
Closed.
