### ISSUE TITLE
KeyDragZoom

### ISSUE THREAD

**Issue by bansalrachita** [tomchentw/react-google-maps#423]
Hi, I am trying to implement a feature which can select a rectangular area on the map when a key is pressed with mouse being dragged and zooms in the map when the mouse is dropped. I found this functionality in this library - https://github.com/googlemaps/v3-utility-library/blob/master/keydragzoom

Will this functionality be available using react-google-maps anytime soon?

Thanks.

**Comment by tomchentw** [comment]
Please refer to [Getting Help](https://github.com/tomchentw/react-google-maps#getting-help) section in the README (or #469).
