### ISSUE TITLE
How selected and edited Polygon

### ISSUE THREAD

**Issue by rayozerets** [tomchentw/react-google-maps#425]
How to select and edit the desired polygons on the map? I wanted set 'ref', but it don't work, when I set ref 'react-google-maps' stops working.

**Comment by liorpr** [comment]
What exactly do you wish to edit? all I could find on the official docs is just a popup window
https://developers.google.com/maps/documentation/javascript/examples/polygon-arrays

**Comment by rayozerets** [comment]
For polygon need set prop editable={true}

**Comment by liorpr** [comment]
what do you actually want to do? can you give an example from the google maps api ?

**Comment by tomchentw** [comment]
Please refer to [Getting Help](https://github.com/tomchentw/react-google-maps#getting-help) section in the README (or #469).
