### ISSUE TITLE
Overlay example doesn't correctly resize on zoom change

### ISSUE THREAD

**Issue by peterdeka** [tomchentw/react-google-maps#426]
The example for the OverlayView doesn't behave as expected (or as Google maps overlay example behaves). When the map is zoomed the overlay doesn't resize accordingly, keeping always the same size. Also trying to use the bounds instead of the position, the outcome is the same. Any clue on this?

**Comment by tomchentw** [comment]
Are you talking about this one?
https://tomchentw.github.io/react-google-maps/basics/overlay-view

**Comment by tomchentw** [comment]
Please refer to [Getting Help](https://github.com/tomchentw/react-google-maps#getting-help) section in the README.
