### ISSUE TITLE
fitBounds() is not working properly

### ISSUE THREAD

**Issue by belliAndrea** [tomchentw/react-google-maps#427]
Hi,
i've tried to use fitBounds() through refs, but seem like is not working properly.
Every latlngBounds i pass to the method is not mantained as i pass it to.

so for example: 
i use: {sw:{lat: 14.200, lng: 41.200}....}
when i call map.getBounds() i find different values like {sw:{lat: 14.800, lng: 41.900}...}

how can it be?

**Comment by belliAndrea** [comment]
sorry my fault

**Comment by eforkin** [comment]
@belliAndrea I'm having a similar issue. What exactly did you put into fitBounds()?
