### ISSUE TITLE
Release new version on NPM

### ISSUE THREAD

**Issue by nicholasgonzalezsc** [tomchentw/react-google-maps#429]
The latest version in NPM is 4.11.0, which seems to be a more than a few versions behind.
@tomchentw could you publish the latest stable version to NPM? 

I believe either v5.1.1 or v6.0.1 is the latest stable version.

**Comment by jtomaszewski** [comment]
`npm i --save react-google-maps@6.0.1` worked for me

**Comment by shri3k** [comment]
@jtomaszewski I see that that version is still in a `beta` flag in the registry. As @nicholasgonzalezsc  stated, `4.11.0` is still tagged as latest version.

**Comment by tomchentw** [comment]
Will do.

**Comment by tomchentw** [comment]
6.0.1 published on npm as `latest`.

**Comment by nicholasgonzalezsc** [comment]
@tomchentw Thank you!
