### ISSUE TITLE
error 'google' is not defined no-undef

### ISSUE THREAD

**Issue by jwamsterdam** [tomchentw/react-google-maps#434]
This doc: https://tomchentw.github.io/react-google-maps/basics/directions isn't working at all. 

can't get around:  error 'google' is not defined no-undef

I did find a solution that is partly working, e.g. using 
 ```
   return (
        <GoogleMapLoader
                containerElement={mapContainer}
                googleMapElement={
                    <GoogleMap  
                        defaultZoom={12}
                        defaultCenter={this.props.center}
                        options={{ streetviewcontrol: false, mapTypeControl: true}}>
                    </GoogleMap>
                } 
```

But I have no idea how to match this to the tutorial  with componentDidMount etc. to get it to work with the direction service. Any help is greatly appreciated.

**Comment by jwamsterdam** [comment]
I am one step further, see this question: https://github.com/tomchentw/react-google-maps/issues/435

**Comment by davidpatters0n** [comment]
@jwamsterdam - Take a look at #414

**Comment by tomchentw** [comment]
Please refer to [Getting Help](https://github.com/tomchentw/react-google-maps#getting-help) section in the README (or #469).

**Comment by voquockhanh** [comment]
add this line to top of your file: /*global google*/ -> for disable ESLint

**Comment by johnanisere** [comment]
`const google=window.google` solves this problem.You see this because reactjs use a linting rule that forbids unknown global variables.

**Comment by quantuminformation** [comment]
What about putting it in your tsconfig?
