### ISSUE TITLE
MarkerClusterer returning 404 image by incorrectly handling icon filePath

### ISSUE THREAD

**Issue by josephdburdick** [tomchentw/react-google-maps#437]
Hello, I am requiring an image from Webpack and inserting into MarkerClusterer like so:
```
const clusterMarkerSrc = require('!file?name=[name].[ext]!../../../assets/images/marker-cluster--magenta.png'); // eslint-disable-line import/no-webpack-loader-syntax

<MarkerClusterer
        averageCenter
        enableRetinaIcons
        gridSize={60}
        maxZoom={12}
        imagePath={clusterMarkerSrc}
      >
        { renderMarkersOnMap(props) }
      </MarkerClusterer>
```

If I place `<img src={clusterMarkerSrc} />` in the view it renders properly with the file path. When I place it in the map however via the MarkerCluster `imagePath` option console reports the following 404: `http://localhost:3000/marker-cluster--magenta.png1.png 404 (Not Found)`. If I place an external link to an icon it renders properly, but this icon is local.

Please advise. Thank you very much!

**Comment by felipemfp** [comment]
`imagePath` should be the path to a folder where the MarkerClusterer can find images ([1-5].png).

See how it adds `1.png`: localhost:3000/marker-cluster--magenta.png**1.png**

**Comment by tomchentw** [comment]
Please refer to [Getting Help](https://github.com/tomchentw/react-google-maps#getting-help) section in the README (or #469).
