### ISSUE TITLE
this._mapComponent is not defined

### ISSUE THREAD

**Issue by michaeltheodore048** [tomchentw/react-google-maps#440]
I copy all the code you give, but "Uncaught ReferenceError: this._mapComponent is not defined" appear, can u tell me where's the _mapComponent?

**Comment by imdevan** [comment]
In my project I have something like the following to access the map component. 

```
const Map = React.createClass({
  handleMapMounted(map) {
    this._map = map;
  },
  render() {
    const GoogleMapComponent = withGoogleMap(props => (
      <GoogleMap>
         // other props
      </GoogleMap>
    ));

    return (
      <GoogleMapComponent
        // other props
        onMapMounted={this.handleMapMounted}
      />
    )
  }
});
```

Does that answer your question? (I'm a user not a contributor)

**Comment by tomchentw** [comment]
Please refer to [Getting Help](https://github.com/tomchentw/react-google-maps#getting-help) section in the README (or #469).
