### ISSUE TITLE
no GoogleMap API key

### ISSUE THREAD

**Issue by ElAnonimo** [tomchentw/react-google-maps#442]
The console pops up a 'TypeError: this.props.googleMapElement is undefined' error. Where do I put the API key? Version 4.7.1.

**Comment by faviouz** [comment]
I'm wondering the same

**Comment by oshalygin** [comment]
we definitely need to update the README with this, its fairly critical

**Comment by joaocrq** [comment]
Is there any solution or workaround at the moment? Thanks

**Comment by oshalygin** [comment]
@joaocrq you either include it in your `<head>` like you normally do or you pass
`googleMapURL={googleMapsUrl}`

```javascript
withScriptjs(withGoogleMap(props) => {
// your component.
```

**Comment by joaocrq** [comment]
Thank you very much @oshalygin!

**Comment by oshalygin** [comment]
@joaocrq anytime, let me know if you need more of a code snippet, sorry my code is very nested and I'd have to show you 3 components deep but I dont mind, lmk.

**Comment by tomchentw** [comment]
Please refer to [Getting Help](https://github.com/tomchentw/react-google-maps#getting-help) section in the README (or #469).
