### ISSUE TITLE
v5 Custom Cluster Icon

### ISSUE THREAD

**Issue by PaulieScanlon** [tomchentw/react-google-maps#443]
I need to use v5 rather than v6 (beta) for reasons i won't go in to. 

Is there a way to use custom cluster icons in this version? I've looked over the issues but can't seem to find anything.

Thanks.

**Comment by tomchentw** [comment]
Please refer to [Getting Help](https://github.com/tomchentw/react-google-maps#getting-help) section in the README (or #469).
