### ISSUE TITLE
Slow render InfoWindow

### ISSUE THREAD

**Issue by rayozerets** [tomchentw/react-google-maps#444]
Why so slow render InfoWindow? 
[See screenshot](https://sc-cdn.scaleengine.net/i/7a0b2675815294cbf367cdee9ddca5e3.png)

**Comment by ztanner** [comment]
I think this is related to https://github.com/tomchentw/react-google-maps/issues/408 and I don't think a working fix has been suggested yet.

**Comment by tomchentw** [comment]
Please refer to [Getting Help](https://github.com/tomchentw/react-google-maps#getting-help) section in the README (or #469).

**Comment by Prophet32j** [comment]
I'm experiencing this issue as well, and I didn't find any answers on how to resolve this. I'm on version 8.3.1

The same issue where the first time rendering the InfoWindow doesn't show the render lag, then every time after that, we see the InfoWindow content displayed before the InfoWindow has fully rendered on the map.
