### ISSUE TITLE
I want fix the window Map view.

### ISSUE THREAD

**Issue by XOneto9** [tomchentw/react-google-maps#447]
Hi,

I use react google maps @6.0.1 ver.
and I'm display on my web google maps 

I want show the view of google maps as a fixed View on the some location with Mark(lat, lng)
like as Zoom in/out function and dragging map location

but the mark on the maps should work to click to show information of location.

how can I do that???

**Comment by tomchentw** [comment]
Please refer to [Getting Help](https://github.com/tomchentw/react-google-maps#getting-help) section in the README (or #469).
