### ISSUE TITLE
Licensing issues

### ISSUE THREAD

**Issue by Anahkiasen** [tomchentw/react-google-maps#448]
Hey!

We've been using `react-google-maps` for a while now, however recently we've been made aware that some of its dependencies do not have any licenses which is causing issues on our end. The two packages involved are:

- [ ] [scriptjs](https://github.com/ded/script.js)
- [x] [google-maps-infobox-module](https://github.com/lucasfs7/google-maps-infobox-module)

My question is, would you consider switching to forks/alternatives to these packages in order to make this one possible to use on projects where licensing is of importance?

**Comment by faviouz** [comment]
I am curious. Aren't repositories on GitHub by default public domain? How does that work?

**Comment by Anahkiasen** [comment]
As far as I know no, it's the opposite, code without a license is considered to be copyrighted by default.

**Comment by scronide** [comment]
- scriptsjs is MIT
- google-maps-infobox-module is Apache v2

**Comment by faviouz** [comment]
google-maps-infobox-module was licensed only after this pull request was made.

Where can you see script.js is MIT?

**Comment by scronide** [comment]
@faviouz https://github.com/ded/script.js/blob/master/dist/script.js

**Comment by scronide** [comment]
I should point out that I believe google-maps-infobox is being used, not google-maps-infobox-module. Either way, it's the same core files which have had Apache v2.0 licenses in them for years. Apache is marginally more restrictive than MIT.

**Comment by tomchentw** [comment]
Thanks!
