### ISSUE TITLE
Infowindow - setting positions on top of marker (after clicking marker)

### ISSUE THREAD

**Issue by trag** [tomchentw/react-google-maps#452]
Is there any possibility to set position of infowindow - in pure google map I can do this: 

`infowindow.setPosition(marker.getPosition());` 

and infowindow is pointing exact same point as marker - how I can do this in infoWindowComponent ? Thanks for info. Regards

**Comment by tomchentw** [comment]
Please refer to [Getting Help](https://github.com/tomchentw/react-google-maps#getting-help) section in the README (or #469).
