### ISSUE TITLE
Infobox and enableEventPropagation

### ISSUE THREAD

**Issue by trag** [tomchentw/react-google-maps#457]
Hello there. I have problem with click events on infobox. I have many markers on the map, when I open infobox it will cover rest of markers (works as expected), I have `enableEventPropagation` set to true - in infobox I have one html layer, with onClick event - when I click this layer and underneath of infobox is some covered markers, than - first I'm getting onclick event on marker, and then I'm getting second click on layer but on new infobox. IMHO first click event should be fired on infobox, than maybe on marker - how ever it should be fired if it is underneath of infobox...  anther option, to set enableEventPropagation to false and create own listeners, but I dont know, how to reference infbox to ie `google.maps.event.addDomListener(infobox, "click", function (e)` - any help would be nice. thanks ;)

**Comment by rafath** [comment]
Same goes with overlay infowindow, when there is a marker underneath of infowindow layer - this marker is clickable

**Comment by feux07** [comment]
I have also same problem

**Comment by feux07** [comment]
I solved this by adding options={{ optimized: false }} to markers props.

**Comment by tomchentw** [comment]
Please refer to [Getting Help](https://github.com/tomchentw/react-google-maps#getting-help) section in the README (or #469).
