### ISSUE TITLE
Adding a Legend

### ISSUE THREAD

**Issue by jm90m** [tomchentw/react-google-maps#459]
Hello, I am trying to add a legend, I though about using the overlay view but I want something more like the example on here: https://developers.google.com/maps/documentation/javascript/adding-a-legend

Looks like that involves pushing to the current instance of map in`map.controls`? So is there any way to do this? Thanks

**Comment by tomchentw** [comment]
Please refer to [Getting Help](https://github.com/tomchentw/react-google-maps#getting-help) section in the README (or #469).

**Comment by aldorl** [comment]
Hey @jm90m, did you find a solution for adding a legend to the map? Would love to know if you did. Cheers.

**Comment by jm90m** [comment]
@aldorl nope, I just made my legend through a custom react component outside this library.

**Comment by anubhav0fnu** [comment]
@aldorl How you did that. Did you use overlay, or not?

**Comment by aldorl** [comment]
@anubhav0fnu I never figured out how to do it, so I just added the legend outside of the map

**Comment by DanielDouradoFsa** [comment]
Hi. i solve this based on https://developers.google.com/maps/documentation/javascript/adding-a-legend.
![Component_google](https://user-images.githubusercontent.com/60206918/194861098-4fc4f296-10ef-4e85-a304-f45361960458.png)
In onGoogleReady:
![onGoogleReady](https://user-images.githubusercontent.com/60206918/194861217-65afd582-3d7c-4478-887c-e3df86a69b46.png)
And it works great! The google prop we get from props is not the same as [google](https://developers.google.com/maps/documentation/javascript/adding-a-legend.), we should use google which is received from the second onReady parameter. Hope it helps y'all

**Comment by jhoanborges** [comment]
+1

**Comment by jhoanborges** [comment]
> Hi. i solve this based on https://developers.google.com/maps/documentation/javascript/adding-a-legend. ![Component_google](https://user-images.githubusercontent.com/60206918/194861098-4fc4f296-10ef-4e85-a304-f45361960458.png) In onGoogleReady: ![onGoogleReady](https://user-images.githubusercontent.com/60206918/194861217-65afd582-3d7c-4478-887c-e3df86a69b46.png) And it works great! The google prop we get from props is not the same as [google](https://developers.google.com/maps/documentation/javascript/adding-a-legend.), we should use google which is received from the second onReady parameter. Hope it helps y'all

Can you please share your code and the Legend component?
