### ISSUE TITLE
Prep for React v16 and removal for deprecation warnings (PropTypes & createClass)

### ISSUE THREAD

**Issue by stephen-last** [tomchentw/react-google-maps#463]
Are there any plans to prepare for React v16 as per this post: [React v15.5.0](https://facebook.github.io/react/blog/2017/04/07/react-v15.5.0.html) ..?

It means replacing all `React.PropTypes` and using the [prop-types](https://github.com/reactjs/prop-types) package, and repalcing all `React.createClass` using the [create-react-class](https://www.npmjs.com/package/create-react-class) package.

Doing this will also remove the deprecation warnings for anyone using React v15.5.0 which show in the console in development env.

**Comment by binjospookie** [comment]
> and using the prop-types package

**Comment by stephen-last** [comment]
Sure... So long as `React.PropTypes` and `React.createClass` are removed.

It is quite annoying to have these red warnings in my console all the time while in dev:

> Warning: Accessing PropTypes via the main React package is deprecated. Use the prop-types package from npm instead.

> Warning: GoogleMap: React.createClass is deprecated and will be removed in version 16. Use plain JavaScript classes instead. If you're not yet ready to migrate, create-react-class is available on npm as a drop-in replacement.

Other than this issue, this package is really good!

**Comment by tomchentw** [comment]
Will do.

**Comment by tomchentw** [comment]
Released [7.0.0](https://github.com/tomchentw/react-google-maps/releases/tag/v7.0.0)

**Comment by ffxsam** [comment]
@tomchentw Could you (or someone) please publish 7.0 to the npm registry? (or is it not ready yet?)

**Comment by tomchentw** [comment]
Published 7.0.0 to npm as latest.
