### ISSUE TITLE
HeatmapLayer throws getMap() error!

### ISSUE THREAD

**Issue by krypton97** [tomchentw/react-google-maps#464]
I'm trying to render a HeatmapLayer with react-google-map@v5.0.1 module, but I get the following error:

Uncaught TypeError: Cannot read property 'getMap' of undefined

I added the visualization library, but still got the error. This is how my main.js file looks like..It renders the map, but doesn't add the heatmap-layer. Looking for a fix if somebody managed to get it working, thank you!

	import React, { PropTypes } from 'react';
	import ReactDOM from 'react-dom';
	import { GoogleMapLoader, GoogleMap, Marker, HeatmapLayer, withGoogleMap } from "react-google-maps";
	
	const Map = props => {
	  return (
	      <GoogleMapLoader
	        containerElement={
	          <div
	            style={{
	              height: "100%",
	              width: "100%",
	              position: "absolute"
	            }}
	          />
	        }
	        googleMapElement={
	          <GoogleMap
	            defaultZoom={13}
	            defaultCenter={{ lat: 37.78, lng: -122.44 }}
	          >
	            <HeatmapLayer data = {[37.782551, -122.445368,
	              37.782745, -122.444586,
	              37.782842, -122.443688,
	              37.782919, -122.442815,
	              37.782992, -122.442112,
	              37.783100, -122.441461,
	              37.783206, -122.440829,
	              ]} />
	          </GoogleMap>
	        }
	      />
	  );
	}
	
	ReactDOM.render(<Map />, document.getElementById('app'))

**Comment by tomchentw** [comment]
Please refer to [Getting Help](https://github.com/tomchentw/react-google-maps#getting-help) section in the README (or #469).
