### ISSUE TITLE
How to turn of zoom increase/decrease when scrolling over map

### ISSUE THREAD

**Issue by vorlov** [tomchentw/react-google-maps#465]
<div />
<GoogleMap>
<div />

if I scroll from top to down and mouse pointer hits map zoom event is called.
how to turn of zooming and just continue scrolling over map

**Comment by vorlov** [comment]
```javascript
<GoogleMap
...
  defaultOptions={{
    scrollwheel: false,
  }}
...
/>
```
that hepled

**Comment by tomchentw** [comment]
Please refer to [Getting Help](https://github.com/tomchentw/react-google-maps#getting-help) section in the README (or #469).
