### ISSUE TITLE
use getCenter function and others

### ISSUE THREAD

**Issue by alex-brain** [tomchentw/react-google-maps#466]
How can I use getCenter?
I try 
<GoogleMap
    defaultZoom={14}
    center={{lat: props.mapCenter.lat, lng: props.mapCenter.lng}}
    onCenterChanged={getCenter()}
>
But I get message getCenter is undefined

**Comment by tomchentw** [comment]
Please refer to [Getting Help](https://github.com/tomchentw/react-google-maps#getting-help) section in the README (or #469).

**Comment by DavidVaini** [comment]
you would figure basic usage would be covered under the documentation. There seems to be no mention of the switch from refs to whatever it currently uses:
In the change log it doesnt mention the change from ref="map" to ref={props.onMapLoad}

considering all previous ways of calling functions like getCenter() used ref.map.getCenter() it breaks existing code. Then when you try to set the ref, you get "Stateless function components cannot have refs."

so they got rid of refs entirely? This question has been asked on stackoverflow but considering there is no documentation for this change, there is no good answer yet on how to do basic map handling. I will be digging through the source code to figure it out... ugh.

**Comment by tomchentw** [comment]
Breaking change in 6.0.0.
https://github.com/tomchentw/react-google-maps/blob/master/CHANGELOG.md#600-2016-10-04

**Comment by DavidVaini** [comment]
Sure, I see that line change, but it doesnt mention the Ref's and how calling the refs are broken. Typically with broken changes, you specify the new way of handling it. So whats the new way of handling this.refs.map.getBounds(); ?

**Comment by tomchentw** [comment]
It's defined in the public method of the `<GoogleMap>` component. So get the ref and call `getBounds`
https://github.com/tomchentw/react-google-maps/blob/master/src/lib/GoogleMap.js#L97

**Comment by jkranking** [comment]
Can anyone explain how to properly access the refs and how to subsequently call a function off of it per DavidVaini's question above?

**Comment by Y-Taras** [comment]
https://github.com/jkranking
here's a nice example from official documentation
https://tomchentw.github.io/react-google-maps/places/search-box

**Comment by Pegahkeshavarz** [comment]
none of these examples are working?

**Comment by tomchentw** [comment]
@Pegahkeshavarz https://tomchentw.github.io/react-google-maps/#searchbox

**Comment by Pegahkeshavarz** [comment]
I am trying to get the center by clicking on a button but when using this.refs.map.getCenter() i am getting the error of can not find property getCenter of undefined?

**Comment by tomchentw** [comment]
You need to store `ref` in some way so that they can access it later.

**Comment by Darksoulsong** [comment]
This is how I'm trying to use getCenter using a ref, and it's not working.

```
const Map = withScriptjs(
  withGoogleMap(() => {
    const ref: any = useRef<HTMLElement>(null);

    return (
      <GoogleMap
        options={{
          styles: mapOptions.styles,
          scrollwheel: mapOptions.scrollwheel
        }}
        defaultZoom={mapOptions.zoom}
        defaultCenter={{ lat: -26.896333, lng: -49.23524 }}
        ref={ref}
      >
        <Marker position={ref.current.getCenter()} />
      </GoogleMap>
    );
  })
);
```

**Comment by JustFly1984** [comment]
@Darksoulsong this repo is unmaintained more than a year, please refer to npm @react-google-maps/api
