### ISSUE TITLE
Failed to decode downloaded font

### ISSUE THREAD

**Issue by matwii** [tomchentw/react-google-maps#467]
After installing the npm package and creating a component of a Map I am getting this error:
`Failed to decode downloaded font: http://localhost:3000/fonts/roboto/Roboto-Regular.woff2
OTS parsing error: invalid version tag`

Someone know how to fix this?

**Comment by tomchentw** [comment]
Please refer to [Getting Help](https://github.com/tomchentw/react-google-maps#getting-help) section in the README (or #469).
