### ISSUE TITLE
Map not rendering properly

### ISSUE THREAD

**Issue by Larry850806** [tomchentw/react-google-maps#468]
There are two tabs in my page. I put google map in one of my tabs and it render properly.

![](http://i.imgur.com/ElSl8gM.png)

After I switch to another tab and switch back, the content inside map is disappeared. Is there any way to solve it?

![](http://i.imgur.com/okww4It.png)

**Comment by tomchentw** [comment]
Please refer to [Getting Help](https://github.com/tomchentw/react-google-maps#getting-help) section in the README (or #469).

**Comment by jmoh7969** [comment]
Any solution for this ?? I am also facing the same issue. @tomchentw

**Comment by oshalygin** [comment]
@jmoh7969 I've never seen this and I usually have 15+ tabs open with the same application running.  Can you post a repo that reproduces this?
