### ISSUE TITLE
Use it on a Windows machine

### ISSUE THREAD

**Issue by af7** [tomchentw/react-google-maps#48]
Is it possible that you show us the changes that need to be made (or if it is just one file upload it) so that we can compile the solution in a Windows machine? (that has npm and node of course).

Thank you.

**Comment by tomchentw** [comment]
Not sure. Does anyone face same issue?
I'll try to setup a Windows VM and test on it.

**Comment by af7** [comment]
First, let me say that ``npm run build`` **does** work.

But the other (more important ones) fail (``npm run dev`` for example).

If you have a Windows VM you can try this and you will see what I mean.

You may want to read this at the section about Windows:
http://blog.keithcirkel.co.uk/how-to-use-npm-as-a-build-tool/

"If you really need to have Windows support, it does not support rm - luckily there is rimraf which is a cross-compatible tool to do the same thing"

But the "rm" is not the problem actually, problems start when the "webpack" part runs. I will look at it but I am not an expert, you will immediately understand the problem (and possibly fix it) if you can run it on a Windows VM.

Thanks.

**Comment by af7** [comment]
Just the 1st error that I get. Also see the npm-debug.log here: https://gist.github.com/af7/95689af32f86d23c8086

{ file: 'E:/Repositories of Code/react-google-maps/examples/gh-pages/node_modules/bootstrap-sass/assets    
/stylesheets/bootstrap\\mixins\\_grid.scss' }                                                              
TypeError: tmp/server.js                                                                                   
--------------------------------------------------------------------------------options must be an obje    
ct                                                                                                         
    at TypeError (native)                                                                                  
    at Object.exports.createScript (vm.js:44:10)                                                           
    at module.exports (E:\Repositories of Code\react-google-maps\examples\gh-pages\node_modules\eval\ev    
al.js:55:8)                                                                                                
    at IsomorphicReactPluginFactory.evaluate (E:\Repositories of Code\react-google-maps\examples\gh-pag    
es\IsomorphicReactPluginFactory.js:56:12)                                                                  
    at IsomorphicReactPluginFactory.runCompilation (E:\Repositories of Code\react-google-maps\examples\    
gh-pages\IsomorphicReactPluginFactory.js:68:32)                                                            
    at IsomorphicReactPluginFactory.receivedClientAssets (E:\Repositories of Code\react-google-maps\exa    
mples\gh-pages\IsomorphicReactPluginFactory.js:33:10)                                                      
    at ClientPlugin.<anonymous> (E:\Repositories of Code\react-google-maps\examples\gh-pages\Isomorphic    
ReactPluginFactory.js:97:24)                                                                               
    at Tapable.applyPluginsAsync (E:\Repositories of Code\react-google-maps\examples\gh-pages\node_modu    
les\webpack\node_modules\tapable\lib\Tapable.js:71:13)                                                     
    at Tapable.Compiler.emitAssets (E:\Repositories of Code\react-google-maps\examples\gh-pages\node_mo    
dules\webpack\lib\Compiler.js:225:7)                                                                       
    at Tapable.<anonymous> (E:\Repositories of Code\react-google-maps\examples\gh-pages\node_modules\we    
bpack\lib\Compiler.js:183:10)                                                                              
--------------------------------------------------------------------------------module.exports=function    
(e){function t(r){if(n[r])return n[r].exports;var o=n[r]={exports:{},id:r,loaded:!1};return e[r].call(o    
.exports,o,o.exports,t),o.loaded=!0,o.exports}var n={};return t.m=e,t.c=n,t.p="",t(0)}([function(e,t,n)    
{"use strict";function r(e){return e&&e.__esModule?e:{"default":e}}Object.defineProperty(t,"__esModule"    
,{value:!0});var o=n(3),a=(r(o),n(13)),i=r(a);t["default"]=i["default"],e.exports=t["default"]},functio    
n(e,t,n){e.exports=require("react/addons")},function(e,t,n){"use strict";function r(e){return e&&e.__es    
Module?e:{"default":e}}Object.defineProperty(t,"__esModule",{value:!0});var o=n(26),a=r(o),i=n(24),s=r(    
i),l=n(25),c=r(l),u=n(8),p=r(u),f=n(27),d=r(f),g=n(28),h=r(g),m=n(29),v=r(m);t.GoogleMaps=a["default"],    
t.Circle=s["default"],t.DirectionsRenderer=c["default"],t.InfoWindow=p["default"],t.Marker=d["default"]

**Comment by tomchentw** [comment]
@af7 Did you try it with node `0.10` or `0.12`? I believe current `master` having some issue with `0.12`. See #49

**Comment by af7** [comment]
I am using node v0.12.3 and I can report this for Windows:

I run the following commands sequentially:

`npm run build` : works fine :+1: 

`npm run build_client`: works fine, with many warnings *from UglifyJs* (I assume these are just normal? or not?)

`npm run dev`: works fine, no errors (and no warnings from UglifyJS), but I get the following result on `E:\Repositories of Code\react-google-maps\public`:

![image](https://cloud.githubusercontent.com/assets/7850073/7671619/cd51a6a8-fce0-11e4-8092-551dabdcbc32.png)

??? I assume this is normal, correct?

**Comment by tomchentw** [comment]
Could you just try visiting `localhost:8080`?

**Comment by af7** [comment]
Hi, I get similar results:

![image](https://cloud.githubusercontent.com/assets/7850073/7678636/6f56889c-fd5e-11e4-873d-dcb70906d245.png)

![image](https://cloud.githubusercontent.com/assets/7850073/7678639/72920996-fd5e-11e4-8f0c-0e8c70a0ba09.png)

**Comment by tomchentw** [comment]
Please try #73, thanks!

**Comment by radnor** [comment]
Here's how I got the example to compile and run on Windows. You may need to install `webpack` and/or `webpack-dev-server` via `npm install -g` to get the commands to run properly. 

```
npm install
cd examples/gh-pages
npm install
webpack -d
webpack-dev-server -d
```

**Comment by tomchentw** [comment]
@radnor so `npm run dev` or `npm start` won't work on windows?

**Comment by radnor** [comment]
Correct, as `rm -rf` does not work in windows. Implementing the `npm clean` task with [rimraf](https://github.com/isaacs/rimraf) should solve this issue.

**Comment by tomchentw** [comment]
@radnor thanks to look into this. I didn't notice that even `rm` would be an issue though LOL. Would you mind to open PR for this?
