### ISSUE TITLE
GoogleMap class error

### ISSUE THREAD

**Issue by nats12** [tomchentw/react-google-maps#481]
Hi, 
I get to the stage where I'm just returning GoogleMapLoader & GoogleMap to display the map (no markers or anything) and I get these errors:

![screen shot 2017-04-26 at 12 17 59](https://cloud.githubusercontent.com/assets/15801768/25431974/a5bfcff6-2a7a-11e7-9add-92b0a088bb0d.png)

I'm not using React.createElement anywhere.

**This is my code so far:**

![screen shot 2017-04-26 at 12 20 00](https://cloud.githubusercontent.com/assets/15801768/25432001/b3c741ec-2a7a-11e7-9b39-4effe5df588e.png)

Can anyone help?

Thanks

**Comment by tomchentw** [comment]
Please consider upgrade to 6.0.0

**Comment by ChandraInAus** [comment]
Hi,

I have upgraded to 6.3.0, but I still get the above error for a basic setup as shown above.
Can some one please help?

Thanks,
Ram

**Comment by toroduque** [comment]
Hey! same issue here... I'm using 6.3.0 too. Please some help :) !

Thanks!

**Comment by chiramelwin** [comment]
I'm facing the same issue on 6.3.0 as well.

**Comment by 4arhan** [comment]
Hey folks, 

i also encountering same issue on 6.3.0, would be great if someone could help out! 

Cheers.

**Comment by tomchentw** [comment]
Can't help folks if you can't show me a complete repo to reproduce this. Closing.

Please refer to [Getting Help](https://github.com/tomchentw/react-google-maps#getting-help) section in the README (or #469).
