### ISSUE TITLE
keep OverlayView fixed to a position

### ISSUE THREAD

**Issue by andrewdamelio** [tomchentw/react-google-maps#483]
Not sure why i'm having such a tough time with this, but i'm trying to keep <OverlayView /> always in the top right of the map. 

Currently when I pan the map around the <OverlayView /> pans with it - any was to anchor this?

Effectively i'm trying to use OverlayView as a custom map control, hence they should stay anchor to the corners.

**Comment by tomchentw** [comment]
The OverlayView is not designed for this task. Please consult other solutions.

**Comment by tomchentw** [comment]
Please refer to [Getting Help](https://github.com/tomchentw/react-google-maps#getting-help) section in the README (or #469).

**Comment by gauthampait** [comment]
@andrewdamelio Did you manage to get a solution to this problem ? If yes, please post your finding.
