### ISSUE TITLE
Cannot instantiate google object ( google is undefined ) 

### ISSUE THREAD

**Issue by xshadowlegendx** [tomchentw/react-google-maps#485]
I am using **_MeteorJS ( 1.4.4 ) + ReactJS_**, currently i can get the map, markers, working properly. I am using ' **_withScriptjs.js ' async_** method to render the map, because i tried without the async and it does not work. Here is my problem, i want to use the **_DirectionsRenderer_** to draw direction, which is must needed for my traffic jam project, and following the example, I cannot get it works because of **_google is undefined_** when the code runs until 
`const DirectionsService = new google.maps.DirectionsService();` throws the error inside `componentDidMount()`.
Because I am still on testing the package, so there is no complex code, and my code was just exactly the same as the example code ( directions ). Thanks you very much for helping.
PS: Awesome package with almost google api completed.

**Comment by victors141** [comment]
I could solve this using window.google object

**Comment by Rupeshn73** [comment]
@xshadowlegendx I have faced this same issue before. So please refer to my question on same topic (ex [)](http://stackoverflow.com/questions/43888706/react-google-map-directionsrenderer-issue/43893131#43893131)

**Comment by Esoteric116** [comment]
Connect the ape tag before the bundle.js

**Comment by sebasgarcep** [comment]
Solved it by adding:
```html
<script src="https://maps.googleapis.com/maps/api/js"></script>
```
to the head of my `index.html`.

@tomchentw This should be documented, willing to send in a pull request.

**Comment by mpowell90** [comment]
This helped resolve my 'google is undefined issue'.
https://stackoverflow.com/questions/43714895/google-is-not-defined-in-react-app-using-create-react-app

My build is React.js with Next.js.

**Comment by oshalygin** [comment]
@sebasgarcep I'll put a PR together and add it to the README, because this comes up way too often.  Since you haven't sent a PR yet, I'll just open it up now.

**Comment by tomchentw** [comment]
A possible solution is using `withScriptjs`
https://tomchentw.github.io/react-google-maps/#directionsrenderer

**Comment by GrolaElmahdi** [comment]
You can try this after imports : 

`const google = window.google`
