### ISSUE TITLE
Uncaught TypeError: Failed to execute 'appendChild' on 'Node': parameter 1 is not of type 'Node'.

### ISSUE THREAD

**Issue by NathHorrigan** [tomchentw/react-google-maps#489]
I am using OverlayView to create custom markers. The markers are loading but I have the following error: `Uncaught TypeError: Failed to execute 'appendChild' on 'Node': parameter 1 is not of type 'Node'.` This error has occurred before in #461 but the solution doesn't apply in my case.

```
@inject("map") @observer
export default class MarkerBuilder extends Component {

    constructor(props) {
        super(props);
    }

    render() {
        return (
            <div>
                {
                    this.props.map.markers.map((marker) => (
                        <OverlayView
                            mapPaneName={OverlayView.OVERLAY_MOUSE_TARGET}
                            getPixelPositionOffset={(width, height) => {
                                return { x: -(width / 2), y: -(height / 2) };
                            }}
                            key={marker.id}
                            position={{ lat: marker.location.lat, lng: marker.location.lng }}
                            onClick={() => this.props.map.triggerDrawer(marker)}>

                                 <Marker/>

                        </OverlayView>
                    ))
                }
            </div>

        )
    }

}
```

**Comment by vozni4iy** [comment]
File OverlayView.js , lines 129and 130

```
helpers.mountContainerElementToPane(mapPanes, this._containerElement, props);
helpers.renderChildToContainerElement(mapCanvasProjection, this._containerElement, props);
```

should be changed to 

```
if (this._containerElement) {
      helpers.mountContainerElementToPane(mapPanes, this._containerElement, props);
      helpers.renderChildToContainerElement(mapCanvasProjection, this._containerElement, props);
    }
```
It is a library bug, I think.

**Comment by tomchentw** [comment]
Not sure why, but this should no longer be a problem in v8.0.0.
https://tomchentw.github.io/react-google-maps/#!/OverlayView

**Comment by gomezgoiri** [comment]
I'm using the still experiencing this problem in v8.4.1...

```
Uncaught TypeError: Failed to execute 'appendChild' on 'Node': parameter 1 is not of type 'Node'.
    at OverlayView.draw (OverlayView.js:142)
    at wrapper (_createBind.js:23)
    at _baseDelay.js:18
```

**Comment by erfansamieyan** [comment]
Same problem as @gomezgoiri mentioned in 8.3.0
I used `OverView` several times and had no problem. But this time there is no way to avoid this error.

**Comment by tomchentw** [comment]
@gomezgoiri @erfansamieyan could you post a minimal reproducible repository to demo the problem? It really doesn't help to just complain it here as I cannot **reproduce**

**Comment by gomezgoiri** [comment]
I understand. I'll do my best trying to isolate this error.

**Comment by quachsimon** [comment]
I'm on `v9.4.1` and am also receiving this error.
I'm doing something like so where I have a div inside the OverlayView 
        <OverlayView
          key={index}
          mapPaneName={OverlayView.OVERLAY_MOUSE_TARGET}
          getPixelPositionOffset={getPixelPositionOffset}
          ...
        >
          <div>
            Some content here
          </div>
        </OverlayView>
