### ISSUE TITLE
mapTypes is undefined

### ISSUE THREAD

**Issue by victors141** [tomchentw/react-google-maps#490]
How can i get a reference to map object, i have this code
`HandleMapMounted (map) {
   this._map = map;
   var customMapType = new google.maps. StyleMapType (style_file, styledMapOptions);
    this._map.mapTypes.set (MY_MAPTYPE_ID, customMapType);
     }`
Shows that maptypes is undefined

**Comment by tomchentw** [comment]
Please refer to [Getting Help](https://github.com/tomchentw/react-google-maps#getting-help) section in the README.

**Comment by StephanieDover** [comment]
@victors141, did you end up getting an answer or a work around for this? I need to use it and can't find anything that will work.

**Comment by MINZHE-XU** [comment]
<GoogleMap
    defaultExtraMapTypes={[
      ['custom_style', new google.maps.StyledMapType([
            {
              elementType: 'labels',
              stylers: [{visibility: 'off'}]
            }
          ], {
            name: 'Custom Style'
        })]
    ]}
    defaultMapTypeId={'custom_style'}
  >

</GoogleMap>

**Comment by TifaJ11** [comment]
@MINZHE-XU Thanks for the example!
