### ISSUE TITLE
The example-"simple map" shows nothing in my project

### ISSUE THREAD

**Issue by huangda2100** [tomchentw/react-google-maps#492]
How to use these components? Anybody can show me a full simple project?

**Comment by yazamiko** [comment]
Same here, I followed all steps and my page shows nothing

**Comment by GayanSandaruwan** [comment]
@yazamiko in developer tools did you check whether map is downloading ?
If it is downloading then you might have to adjust styles.

**Comment by thientran1707** [comment]
did you specify the width and height of the container?

**Comment by cagarweyne** [comment]
I had the same issue, I inspected the DOM and found that the div containing my map had an inline style of position: relative - this was causing it to not display anything. Hence why you also have no errors in the console. So, check your CSS.

**Comment by piya23300** [comment]
For me, the map is rendered but it has a style problem.

I use `display: flex` to solve it.

```
<div style="display: flex;">
    <div style="width: 300px; height: 300px;">
    </div>
    <div>
         <myGoogleMap
               containerElement={
                   <div style={{ height: '100%' }} />
               }
               mapElement={
                   <div style={{ height: '100%' }} />
               }
                markers={markers}
          />
    </div>
</div>

```

**Comment by tomchentw** [comment]
Try the new v8.0.0 with new docs:
https://tomchentw.github.io/react-google-maps/
