### ISSUE TITLE
Filter markers

### ISSUE THREAD

**Issue by hakanmhmd** [tomchentw/react-google-maps#493]
I am trying to filter markers based on some of markers properties.
`this.state = {
      allMarkers: [],
      currentMarkers: [],
};`

I store all markers in one array and current markers at another.

`this.setState({currentMarkers: this.state.allMarkers});`

currentMarkers in passed as props down to the Map component.
I have function 

`onFilterClick() {
    this.setState({
      currentMarkers: this.state.allMarkers.filter((item) => {
        // filter predicate
      })
    });
  }`

Presumably the map should react to that change and update itself but it does not.
How can I do that?

**Comment by eamonpenland** [comment]
can you post a gist?

**Comment by tomchentw** [comment]
Please refer to [Getting Help](https://github.com/tomchentw/react-google-maps#getting-help) section in the README.
