### ISSUE TITLE
Performance issue dynamically adding many markers 

### ISSUE THREAD

**Issue by bkellgren** [tomchentw/react-google-maps#495]
I have a map that loads additional markers when the user pans/zooms.

Looking for any ideas here on how I can manage the performance issues as the number of markers grows and each map move results in a re-render of every marker.

What's worse is our search method returns paginated marker results so each map move can result in 1-10 additional re-renders of all markers on the map.

Here is what it looks like....

MyGoogleMap.jsx
```
import React, {Component, PropTypes} from 'react';
import {withGoogleMap, GoogleMap, Marker, KmlLayer} from 'react-google-maps';
import {maps as gmaps} from 'google';
import {MARKER_CONFIG} from 'map-utils';

class MyGoogleMap extends Component {
    constructor(props) {
        super(props);

        this._markers = {};
        this._MARKER_SPRITE_PATH = '/static/main/img/sprites/sprite-markers@2x.png';
        this._HOVER_Z_INDEX = 1001;
    }

    render() {
        const {
            markers,
            zoom,
            position,
            mapOptions,
            onDragStart,
            onDragEnd,
            onIdle,
            onGoogleMapLoaded,
            getMarkerLabelText
        } = this.props;
        const renderedMarkers = (markers && markers.length > 0)
            ? markers.map(marker => {
                const {
                    spot,
                    state
                } = marker;
                const {
                    spotId,
                    latitude,
                    longitude,
                    activeMarker,
                    selectedRate,
                    facility,
                    title
                } = spot;
                const markerType = (selectedRate.unavailable)
                    ? 'disabled'
                    : (activeMarker)
                        ? 'large'
                        : 'medium';
                const icon = {
                    url: this._MARKER_SPRITE_PATH,
                    ...MARKER_CONFIG[markerType][state].icon
                };
                const zIndex = (state === 'hover')
                    ? this._HOVER_Z_INDEX
                    : (activeMarker)
                        ? this._HOVER_Z_INDEX - 1
                        : null;
                const markerText = getMarkerLabelText({selectedRate});
                const labelFontSize = (markerText.length > 5)
                    ? `${parseInt(MARKER_CONFIG[markerType][state].label.fontSize.replace('px', ''), 10) - 2}px`
                    : MARKER_CONFIG[markerType][state].label.fontSize;

                return (
                    <Marker
                        ref={node => {
                            this._markers[spotId] = {
                                node,
                                markerType
                            };
                        }}
                        key={spotId}
                        icon={icon}
                        title={title}
                        label={
                            (markerType === 'disabled' && state === 'default')
                                ? ''
                                : {
                                    text: markerText,
                                    color: MARKER_CONFIG[markerType][state].label.color,
                                    fontSize: labelFontSize,
                                    fontWeight: 'bold',
                                    fontFamily: 'Open Sans,sans-serif'
                                }
                        }
                        position={new gmaps.LatLng(latitude, longitude)}
                        zIndex={zIndex}
                    />
                );
            })
            : null;

        return (
            <GoogleMap
                ref={onGoogleMapLoaded}
                zoom={zoom}
                defaultCenter={position}
                options={mapOptions}
                onDragStart={onDragStart}
                onDragEnd={onDragEnd}
                onIdle={onIdle}
            >
                {renderedMarkers}
            </GoogleMap>
        );
    }
}

MyGoogleMap.propTypes = {
    markers: PropTypes.array.isRequired,
    zoom: PropTypes.number.isRequired,
    position: PropTypes.object.isRequired,
    mapOptions: PropTypes.object.isRequired,
    onDragStart: PropTypes.func.isRequired,
    onDragEnd: PropTypes.func.isRequired,
    onIdle: PropTypes.func.isRequired,
    onGoogleMapLoaded: PropTypes.func.isRequired,
    getMarkerLabelText: PropTypes.func.isRequired
};

export default withGoogleMap(MyGoogleMap);
```

And the parent render method (the markers come from the state and are updated when the map moves causing a re-render of the `MyGoogleMap.jsx`)...
```
return (
    <MyGoogleMap
        ref={node => { this._map = node; }}
        containerElement={
            <div
                style={{
                    height: '100%'
                }}
            />
        }
        mapElement={
            <div
                style={{
                    height: '100%'
                }}
            />
        }
        markers={markers}
        zoom={zoom}
        position={position}
        mapOptions={this._mapOptions}
        onDragStart={this._onDragStart}
        onDragEnd={this._onDragEnd}
        onIdle={this._onIdle}
        onGoogleMapLoaded={this._onGoogleMapLoaded}
        getMarkerLabelText={this._getMarkerLabelText}
    />
);
```

Any help would be greatly appreciated, kinda stumped here.  Thanks in advance!

**Comment by bkellgren** [comment]
went with native google maps, appreciate the library though for the right use case, keep it up!

**Comment by walreyes** [comment]
hey @bkellgren did you found the native google maps performance better?

**Comment by bkellgren** [comment]
@walreyes much but just keep in mind our use case is to only ever add markers to the map as the user browsers so there could be more value in this library for those who need either a pre-defined immutable list of markers OR a smaller overall volume of more dynamic markers being added and removed during the experience

if your needs are to add additional pins to the map as the user browses, my suggestion would be to write your own native wrapper of gmaps api

**Comment by walreyes** [comment]
thanks @bkellgren!

**Comment by davidjbradshaw** [comment]
I think you would get much better performance by changing 
```
position={new gmaps.LatLng(latitude, longitude)}
```
to
```
position={latLngLiteral}
```
And then change `latitude` and `longitude` In your state to be
```
{ lat: latitude, lng: longitude }
```
That way you react should start caching your `Marker`s instead of rerendering them on every state change.

**Comment by bkellgren** [comment]
Thanks for the suggestions @davidjbradshaw.

Originally we did leverage the Overlay Views over Markers also when using this library and it was much more performant.

Will definitely try this out if/when I come back to this library but moving to a native maps/markers implementation made everything much more sane in our case, allowed me to drop this dependency completely and the performance looking great.

IMO applying React approaches to elements that do not benefit from the virtual dom (google maps) end up being an extra layer of unneeded complexity with minimal ROI but YMMV

**Comment by walreyes** [comment]
You are right @bkellgren this library could be helpful for a quick mvp but dealing directly with the google maps api is much much better.

I agree with you about using React with Google Maps is not the most efficient way because they have different strategies to render elements.

I ended up using this library before I could notice the bad performance with many markers (10,000+) and writing my own wrapper for google maps was not an option for me, so I ended up tweaking the library to access the google maps api and using react refs to access the markers directly.

Somenone might be in a similiar situation than me so I will share what I did:

I render the map like this:

```
const ReactGoogleMap = withScriptjs(withGoogleMap(props => (
      <GoogleMap
        ref={this.handleMapMounted.bind(this)}
        defaultCenter={defaultCenter}
      >
        {markers.map( (marker) => {
           return <MarkerWrapperComponent
                    key={marker.id}
                    ref={(m) => {this.handleMarkerRef(m)}}
                    marker={marker}
                  />
         })}
      </GoogleMap>
    )));
```

I handle the marker component ref with this ` ref={(m) => {this.handleMarkerRef(m)}`

In the constructor I initialize an instance object called `this.markers = {}`
```
  constructor(props) {
    super(props);

    // Initialize an instance variable to markers and selectedMarkers
    this.markers = {}
  }
```

Then in `handleMarkerRef` I store the markers like this:
```
  handleMarkerRef(ref) {
    /*
      Once the marker component is rendered store it's ref in a hash
      The key of the marker it's the marker id
      The key gives instant access to the component with it's id
      This will be useful to get the marker and change it's properties like icon
    */
    if(ref) {
      this.markers[ref.props.marker.id] = ref
    }
  }
```

And in the component that renders the map I always `return false` in `shouldComponentUpdate` to stop react from rendering everything all the time. And I access the map and markers in this method. Something like this:

```
  shouldComponentUpdate(nextProps) {
    /*
      The component should never update because it is innefficient.
      For example, let's say we have 10,000 markers and we select 1 with an id x.
      If we want to tell a marker that is selected through props we would need to
      check each one of the 10,000 until we find the one it's selected. Too much comparisons.
      And they get multiplied if we have 2, 3, or  more wells selected.

      Instead the component does not update.
      It access the marker component directly through the hash with the id, and fire the function to make it selected.
      Then we set the center and zoom directly to the google map api.
      And that's it.

      Altough it works in this case because we don't have to add, or remove markers.
      If we needed it we would need to find some other way.
    */

    const selectedMarkers = this.props.selectedMarkers

    // Set markers selected
    selectedMarkers.forEach((selectedMarker) => {
      this.markers[selectedMarker.id].setMarkerSelected()
    })

    //Set new map center and zoom based on new selected wells
    // I need to tweak `react-google-maps` to give access to these map methods.
    this.map.setZoom(4)
    this.map.setCenter(this.getDefaultCenter())

    return false
  }
```

And with this I could get a much better performance, if someone is having the same issue I can elaborate more on my solution.

**Comment by bmakuh** [comment]
@walreyes when you say that you tweaked `react-google-maps` to add `setZoom` and `setCenter`, do you mean you forked the project? If so, did you publish that anywhere?

**Comment by walreyes** [comment]
Hey, @bmakuh 

I actually just setted up the fork, it might be useful for you, take a look: https://github.com/walreyes/react-google-maps. 

I did'nt do it because, honestly, I won't use this library for my next project, I'd rather build my own `GoogleMapsApi.js wrapper`, mount a map in a component, and access the API directly. It's so much more responsive, customizable, better performance and stuff.

But this library it's quite useful for a easy map for a quick project.

So you know what I just did: I entered `lib/GoogleMap.js` and below 

```javascript
panToBounds: function panToBounds(map, args) {
    return map.panToBounds.apply(map, (0, _toConsumableArray3.default)(args));
  },
```

I added these three:

```
setZoom: function setZoom(map, _zoom) {
    //For some reason zoom is an array
    const zoom = _zoom[0];
    return map.setZoom(zoom);
  },
  setCenter: function setCenter(map, _center) {
    //For some reason center is an array
    const center = _center[0];
    return map.setCenter(center);
  },
  setControl: function setControl(map, _control) {
    //For some reason center is an array
    const controlPosition = _control[0];
    const control = _control[1];
    return map.controls[controlPosition].push(control);

  },
```

I did'nt cleaned up this, because I don't intent to use it later and that's why I did'nt forked it or published it.

Let me know if I can help you! @bmakuh 

Good luck!

**Comment by bmakuh** [comment]
@walreyes thanks for the tip! Working with the Google Maps API was way more of a pain than I envisioned it being, but we got it shipped, so thanks for the help! I appreciate it.

**Comment by ntomkin** [comment]
Adding `key` to MarkerClusterer saved the day.

**Comment by guins** [comment]
thanks @ntomkin !
Indeed adding a key to `MarkerClusterers` seems a lot cheaper to render, especially when you deal with thousands of markers. When my app was sometimes slowing down to a 20-30 seconds render, it's now instant :)

**Comment by NoamsGit** [comment]
Hi @bkellgren @walreyes 
I ran into a similar problem, can you please elaborate more on your solution?
Thanks
