### ISSUE TITLE
How to highlight specific area in google map?

### ISSUE THREAD

**Issue by Swarna-Jain** [tomchentw/react-google-maps#496]
I want to highlight specific city/ area of city using group of lats or lngs belong to that area. How can I do this?

**Comment by eamonpenland** [comment]
Might be looking for this
```
<Polygon
  onClick={_.noop}
  onRightClick={_.noop}
  onDragStart={_.noop}
/>
```

**Comment by tomchentw** [comment]
Please refer to [Getting Help](https://github.com/tomchentw/react-google-maps#getting-help) section in the README.
