### ISSUE TITLE
Publish 7.0 to NPM

### ISSUE THREAD

**Issue by li3** [tomchentw/react-google-maps#497]
Looks like 6.3.0 is the latest version that's been published to the official NPM registry:

![image](https://cloud.githubusercontent.com/assets/5040327/26074858/f8fb4184-3978-11e7-9262-9ebf3f0ba98b.png)

Are there any plans to publish 7.x soon?

**Comment by flyingbuddha** [comment]
I got v7 using:
`npm install --save react-google-maps@next`
