### ISSUE TITLE
 highest count of way points that can be added between source and destination in DirectionsRenderer

### ISSUE THREAD

**Issue by Swarna-Jain** [tomchentw/react-google-maps#498]
I have dynamic data with 400+ way points to add between source and destination in DirectionsRenderer but it gives error sometimes when it exceeds 350+.
Is there any limit of adding way points? If so how to resolve it?

**Comment by tomchentw** [comment]
Please refer to [Getting Help](https://github.com/tomchentw/react-google-maps#getting-help) section in the README.
