### ISSUE TITLE
ReferenceError: google is not defined with Server Side Rendering

### ISSUE THREAD

**Issue by manoj150283** [tomchentw/react-google-maps#502]
I am getting the above error message while reloading the page (Server Side Rendering) while it works fine with client side rendering.

I am using the example from below link:
https://tomchentw.github.io/react-google-maps/basics/pop-up-window

Any solution for this ?

**Comment by tomchentw** [comment]
You have to decouple `google` on your own (for example, props you've passed in). I only guarantee on the library prospective.

**Comment by exogenesys** [comment]
@manoj150283 Did you come up with any solution?
