### ISSUE TITLE
Violation Errors with latest Chrome build:  Non passive event listeners

### ISSUE THREAD

**Issue by oshalygin** [tomchentw/react-google-maps#505]
To reproduce:
1) Latest Chrome
2) Turn the logging on to Verbose

![image](https://cloud.githubusercontent.com/assets/7675942/26418647/d8a7f602-4071-11e7-9d9b-27f9c89fc646.png)

Anyone have any ideas?

**Comment by oshalygin** [comment]
Anyone have any insight?  I'd throw a PR together but I've bene a bit busy and I'm not sure where to even start with this guy.

**Comment by ryanhomer** [comment]
These messages are being generated due to code in the Google Maps API JS code itself and even with the latest experimental version (3.exp), these messages are produced so I don't think anything can be done save waiting for Google to update the code.

**Comment by tomchentw** [comment]
Please refer to [Getting Help](https://github.com/tomchentw/react-google-maps#getting-help) section in the README.
