### ISSUE TITLE
How to add image overlay?

### ISSUE THREAD

**Issue by techhahn** [tomchentw/react-google-maps#508]
Is there a way to render the image on top of the map?

**Comment by duhaime** [comment]
@techhahn Yes, you can use an OverlayView for this. With an OverlayView component, you can position arbitrary html on the map. See https://tomchentw.github.io/react-google-maps/basics/overlay-view for an example...

**Comment by techhahn** [comment]
@duhaime i tried playing with this but im trying to accomplish this [example](https://developers.google.com/maps/documentation/javascript/examples/maptype-image-overlay). The image bound to map canvas, it zooms or moves along with the map.

**Comment by tomchentw** [comment]
Please refer to [Getting Help](https://github.com/tomchentw/react-google-maps#getting-help) section in the README.
