### ISSUE TITLE
Npm install fails on a VVV (vagrant) installation

### ISSUE THREAD

**Issue by af7** [tomchentw/react-google-maps#51]
Hello,

I am trying to install on a VVV (vagrant) installation (with no alterations, as is from the VVV github master) and it fails. Is there something that I am missing? Thanks!

This is the command:

vagrant@vvv:/vagrant/www/projects/react-google-maps$   **npm install**

This is what I get:

npm WARN optional dep failed, continuing fsevents@0.3.6
npm ERR! Linux 3.13.0-52-generic
npm ERR! argv "node" "/usr/bin/npm" "install"
npm ERR! node v0.10.37
npm ERR! npm  v2.9.1
npm ERR! path /vagrant/www/projects/react-google-maps/node_modules/tomchentw-npm-dev/node_modules/conntional-changelog/node_modules/lodash.assign/node_modules/lodash._basecreatecallback/node_modules/lodh._setbinddata/package.json.1ec3a17b60468f8c56d9573322440253
npm ERR! code EPERM
npm ERR! errno 50

npm ERR! Error: EPERM, open '/vagrant/www/projects/react-google-maps/node_modules/tomchentw-npm-dev/ne_modules/conventional-changelog/node_modules/lodash.assign/node_modules/lodash._basecreatecallback/ne_modules/lodash._setbinddata/package.json.1ec3a17b60468f8c56d9573322440253'
npm ERR!  { [Error: EPERM, open '/vagrant/www/projects/react-google-maps/node_modules/tomchentw-npm-d/node_modules/conventional-changelog/node_modules/lodash.assign/node_modules/lodash._basecreatecallba/node_modules/lodash._setbinddata/package.json.1ec3a17b60468f8c56d9573322440253']
npm ERR!   errno: 50,
npm ERR!   code: 'EPERM',
npm ERR!   path: '/vagrant/www/projects/react-google-maps/node_modules/tomchentw-npm-dev/node_modulesonventional-changelog/node_modules/lodash.assign/node_modules/lodash._basecreatecallback/node_modulesodash._setbinddata/package.json.1ec3a17b60468f8c56d9573322440253' }
npm ERR!
npm ERR! Please try running this command again as root/Administrator.
npm ERR! Linux 3.13.0-52-generic
npm ERR! argv "node" "/usr/bin/npm" "install"
npm ERR! node v0.10.37
npm ERR! npm  v2.9.1
npm ERR! path npm-debug.log.0ddeb4ce98c3b7b42b152ccb02139d11
npm ERR! code ETXTBSY
npm ERR! errno 62

npm ERR! ETXTBSY, rename 'npm-debug.log.0ddeb4ce98c3b7b42b152ccb02139d11'
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /vagrant/www/projects/react-google-maps/npm-debug.log

**Comment by af7** [comment]
I believe that I found the problem and you have also created a solution (as a patch for now):

https://github.com/mitchellh/vagrant/pull/5495

Please let me know if this is not the case. Thx.

**Comment by tomchentw** [comment]
Please try #73, thanks!
