### ISSUE TITLE
Deprecated things (PropTypes) and crashes

### ISSUE THREAD

**Issue by ktrzos** [tomchentw/react-google-maps#511]
When added map to my application, suddenly I've got these errors:

> Warning: Accessing PropTypes via the main React package is deprecated. Use the prop-types package from npm instead.

> Warning: GoogleMap: React.createClass is deprecated and will be removed in version 16. Use plain JavaScript classes instead. If you're not yet ready to migrate, create-react-class is available on npm as a drop-in replacement.

ALSO.... when v6.3.0 is working, v7.0.0 is crashing on React `^15.5.4`.

**Comment by MiLeung** [comment]
+1

**Comment by tomchentw** [comment]
This should all be fixed in v8.0.0
https://tomchentw.github.io/react-google-maps/
