### ISSUE TITLE
'google' is not defined when used SearchBox

### ISSUE THREAD

**Issue by IchsanWahyudi** [tomchentw/react-google-maps#514]
I new learned react and I use react google map but I find issue 'google is undefined' when I used SearchBoxExample, I've call script google maps api in my index.html but still undefined. I also try used Script.js and wrap withGoogleMap inside it but still undefined.

can anyone help me about this?

thank you

**Comment by mpowell90** [comment]
I had similar issue with 'google is undefined' on the Pop up info window example.

The following SO helped resolve it.
https://stackoverflow.com/questions/43714895/google-is-not-defined-in-react-app-using-create-react-app

**Comment by tomchentw** [comment]
Please refer to [Getting Help](https://github.com/tomchentw/react-google-maps#getting-help) section in the README.
