### ISSUE TITLE
Is there an option for adding full screen icon?

### ISSUE THREAD

**Issue by ImanMh** [tomchentw/react-google-maps#520]
That would be grate for mobile UX and desktop in many cases.

![Google Maps With Full Screen Icon](https://user-images.githubusercontent.com/4482199/27250855-bf06803e-534e-11e7-8fb3-aae41ea3353e.PNG)

**Comment by savalanpour** [comment]
I need this. Please add this feature.

**Comment by alanzongsianshen** [comment]
refer to [https://developers.google.com/maps/documentation/javascript/reference?hl=zh-tw#MapOptions](https://developers.google.com/maps/documentation/javascript/reference?hl=zh-tw#MapOptions)
add a options={{fullscreenControl: true}} to GoogleMap

`
<GoogleMap options={{ fullscreenControl: true }} />
`

**Comment by ImanMh** [comment]
@savalanpour I think you'd better close this issue. Please check this option.

**Comment by savalanpour** [comment]
tank you

**Comment by tomchentw** [comment]
Please refer to [Getting Help](https://github.com/tomchentw/react-google-maps#getting-help) section in the README.
