### ISSUE TITLE
addons/MarkerClusterer

### ISSUE THREAD

**Issue by aapostol87** [tomchentw/react-google-maps#522]
Can you please provide a full example using the addons/MarkerClusterer with webpack because I am not able to make it work?

Thank you,
Andrei

**Comment by tomchentw** [comment]
Please refer to [Getting Help](https://github.com/tomchentw/react-google-maps#getting-help) section in the README.

**Comment by forki** [comment]
since this is now top hit when googling I think it deserves an answer.

for me the missing piece was:

    import { MarkerClusterer } from "../../../node_modules/react-google-maps/lib/components/addons/MarkerClusterer.js";

but I doubt it's the correct way to do it. @tomchentw may have a different solution in mind

**Comment by tomchentw** [comment]
```js
import MarkerClusterer from "react-google-maps/lib/components/addons/MarkerClusterer";
```

Check the docs, please?
https://tomchentw.github.io/react-google-maps/#markerclusterer

https://github.com/tomchentw/react-google-maps/issues/410#issuecomment-341234697

**Comment by forki** [comment]
docs say: 

    const { MarkerClusterer } = require("./MarkerClusterer");

which is not helpful for me.

**Comment by tomchentw** [comment]
Yeah sorry because it's for the demo only and it's part of the `react-styleguidist`.

**Comment by tomchentw** [comment]
@forki just want to let you know I've updated the docs:
https://tomchentw.github.io/react-google-maps/#markerclusterer

<img width="1182" alt="screen shot 2017-11-02 at 4 37 52 pm" src="https://user-images.githubusercontent.com/922234/32316695-3b8d179e-bfec-11e7-8a40-b9b6d05a27e0.png">

**Comment by forki** [comment]
awesome. that's excellent!

**Comment by filipegorges** [comment]
Hello!
I've tried directly copying/pasting your example code, but found the following issue:

![image](https://user-images.githubusercontent.com/7244233/32623820-824140d4-c56e-11e7-879d-17716d9e0f43.png)

Have you got any ideas why is this happening? 

Thanks!

PS.: I'm new to React!

**Comment by tomchentw** [comment]
Not really. Do you define withHandlers?

**Comment by tomchentw** [comment]
I mean, require
