### ISSUE TITLE
Add description to Marker/Circle/Rectangle...

### ISSUE THREAD

**Issue by Deathangel908** [tomchentw/react-google-maps#523]
Could you please add main properties that Marker/Circle/Rectangle....  accept to `README.md`. So people wouldn't need to search for them in google api.
E.g.
```
<Marker
  onClick={_.noop}
  onRightClick={_.noop}
  onDragStart={_.noop}
/>
```

Would be

```
<Marker
  title='This is hover text'
  position={{lat: 12.3, lng: 44.5}}
  onClick={_.noop}
  onRightClick={_.noop}
  onDragStart={_.noop}
/>
```

I can make a pull request if you like.

**Comment by tomchentw** [comment]
Just use google api. Don't repeat myself.

Please refer to [Getting Help](https://github.com/tomchentw/react-google-maps#getting-help) section in the README.
