### ISSUE TITLE
Popup window on marker hover?

### ISSUE THREAD

**Issue by fraserprice** [tomchentw/react-google-maps#524]
New to Google Maps API and this library (which has been amazing to use so far!), was wondering if there's any way to listen for when mouse is hovering over a marker? My goal is to have an info windo pop up when mouse hovers over marker rather than on marker click.

Any help would be great, cheers

**Comment by tomchentw** [comment]
Please refer to [Getting Help](https://github.com/tomchentw/react-google-maps#getting-help) section in the README.
