### ISSUE TITLE
Places search box example is broken

### ISSUE THREAD

**Issue by gwintrob** [tomchentw/react-google-maps#525]
Thanks for providing such a useful component!

I'm just starting to dig in here, but the example at https://tomchentw.github.io/react-google-maps/places/search-box is broken. If you type in an address, the map doesn't update. I see this function in `handlePlacesChanged `:

```
const markers = places.map(place => ({
  position: place.geometry.location,
}));
```

The `place` object only has a `name` key where the value is the result from the search box, so `place.geometry.location` is undefined. Has anyone set this up correctly?

**Comment by tomchentw** [comment]
Updated in v8.0.0:
https://tomchentw.github.io/react-google-maps/#!/SearchBox

**Comment by chilander1** [comment]
I am using  "^8.3.0" version and it doesn't work(

**Comment by chilander1** [comment]
Hello!
How it use with another component, for example MarkerClusterer?

**Comment by tomchentw** [comment]
@chilander1 just connect them as you want.
