### ISSUE TITLE
Can any of your example could use ?

### ISSUE THREAD

**Issue by alanyong91** [tomchentw/react-google-maps#527]
Whatever I copy from sample it just came out wrong/error. Please provide a complete documentation. Thanks

**Comment by dylmye** [comment]
alan can you show us any examples of your tests? have you included google maps in your static html? have you imported everything you need to?

**Comment by alanyong91** [comment]
This is my code, same as your example except I removed Helmet
`import _ from "lodash";

import {
  default as React,
  Component,
} from "react";


import {
  withGoogleMap,
  GoogleMap,
  Marker,
} from "react-google-maps";

import { GoogleMapLoader } from "react-google-maps";

const GettingStartedGoogleMap = withGoogleMap(props => (
<GoogleMapLoader
  containerElement={<div/>}
  googleMapElement={
    <GoogleMap
      defaultZoom={3}
      defaultCenter={{lat: -25.363882, lng: 131.044922}}
    >
      <Marker {...this.props.markerProps} />
    </GoogleMap>
  }
/>
));

export default class GettingStartedExample extends Component {

  state = {
    markers: [{
      position: {
        lat: 25.0112183,
        lng: 121.52067570000001,
      },
      key: `Taiwan`,
      defaultAnimation: 2,
    }],
  };

  handleMapLoad = this.handleMapLoad.bind(this);
  handleMapClick = this.handleMapClick.bind(this);
  handleMarkerRightClick = this.handleMarkerRightClick.bind(this);

  handleMapLoad(map) {
    this._mapComponent = map;
    if (map) {
      console.log(map.getZoom());
    }
  }

  handleMapClick(event) {
    const nextMarkers = [
      ...this.state.markers,
      {
        position: event.latLng,
        defaultAnimation: 2,
        key: Date.now(), 
      },
    ];
    this.setState({
      markers: nextMarkers,
    });

    if (nextMarkers.length === 3) {
      this.props.toast(
        `Right click on the marker to remove it`,
        `Also check the code!`
      );
    }
  }

  handleMarkerRightClick(targetMarker) {
    const nextMarkers = this.state.markers.filter(marker => marker !== targetMarker);
    this.setState({
      markers: nextMarkers,
    });
  }

  render() {
    return (
      <div style={{height: `100%`}}>
        <GettingStartedGoogleMap
          containerElement={
            <div style={{ height: `100%` }} />
          }
          mapElement={
            <div style={{ height: `100%` }} />
          }
          onMapLoad={this.handleMapLoad}
          onMapClick={this.handleMapClick}
          markers={this.state.markers}
          onMarkerRightClick={this.handleMarkerRightClick}
        />
      </div>
    );
  }
}`

Then I get this error
`Warning: Make sure you've put a <script> tag in your <head> element to load Google Maps JavaScript API v3.
 If you're looking for built-in support to load it for you, use the "async/ScriptjsLoader" instead.
 See https://github.com/tomchentw/react-google-maps/pull/168`

and `Uncaught ReferenceError: google is not defined`

This is my package.json

{
  "name": "meal-alley-admin",
  "version": "0.1.0",
  "private": true,
  "dependencies": {
    "react": "^15.4.2",
    "react-dom": "^15.4.2",
    "react-dropzone": "^3.12.4",
    "react-fontawesome": "^1.5.0",
    "react-router-dom": "^4.0.0",
    "react-sidebar": "^2.3.0",
    "react-swipeable-views": "^0.12.3",
    "react-tap-event-plugin": "^2.0.1"
  },
  "devDependencies": {
    "react-scripts": "0.9.5"
  },
  "scripts": {
    "start": "react-scripts start",
    "build": "react-scripts build",
    "test": "react-scripts test --env=jsdom",
    "eject": "react-scripts eject"
  }
}

**Comment by khocef** [comment]
The error message is clear add <script src="https://maps.googleapis.com/maps/api/js"></script> to your HTML to provide google.maps reference

**Comment by tomchentw** [comment]
Please refer to [Getting Help](https://github.com/tomchentw/react-google-maps#getting-help) section in the README.
