### ISSUE TITLE
Update defaultCenter based on state

### ISSUE THREAD

**Issue by Bartozzz** [tomchentw/react-google-maps#528]
How can I update `defaultCenter`? I've tried by editing `map.props.defaultCenter` by `ref` but this is actually a read-only property. I've also tried the following code:

`defaultGeometry` is changed with `setState`:

```jsx
render() {
    <RestaurantLocation
        defaultGeometry={this.state.defaultGeometry}
        marker={{ position : { lat, lng } }}
    />
}
```

```jsx
const RestaurantLocation = withGoogleMap( props => {
    return (
        <GoogleMap
            defaultZoom={10}
            defaultCenter={{
                lat : props.marker.position.lat || props.defaultGeometry.lat,
                lng : props.marker.position.lng || props.defaultGeometry.lng
            }}
        >
        </GoogleMap>
    );
} );
```

But sadly it doesn't affect the `defaultCenter`.

**Comment by Bartozzz** [comment]
It looks like the same issue occurs in demo:
https://tomchentw.github.io/react-google-maps/events/accessing-arguments

**Comment by Bartozzz** [comment]
The only way I've found is by saving the reference to `map` in the state and calling:

```javascript
this.state.map.panTo(new google.maps.LatLng(lat, lng));
```

Then you just have to listen for `defaultCenter` change in `componentWillReceiveProps`.

**Comment by ammichael** [comment]
Or you can only use `center` props instead all of this (:

**Comment by ericxinzhang** [comment]
Personally I think the two properties `defaultCenter` and `center` just cause confusion.

**Comment by PowerOfM** [comment]
I think `defaultCenter` and `center` are in accordance with React's `defaultValue` and `value` properties, which are used in a lot of common places.

**Comment by shethmanan** [comment]
@PowerOfM is right. center and defaultCenter causes confusion. It you assign a state to defaultCenter it will be called only once and will not update when state is changed. Assign it to center and see the magic!
