### ISSUE TITLE
Polygon with Hole

### ISSUE THREAD

**Issue by AlessandroPilastrini** [tomchentw/react-google-maps#529]
Hi, in according with Maps JavaScript API, I've try to put inside **paths** prop of **Polygon** component an array of outerCoords and InnerCords, to show holes inside polygon:

```javascript
props.zones.value.data.map( () => {
        var outerCoords = [
          {lat: -32.364, lng: 153.207}, // north west
          {lat: -35.364, lng: 153.207}, // south west
          {lat: -35.364, lng: 158.207}, // south east
          {lat: -32.364, lng: 158.207}  // north east
        ];

        var innerCoords1 = [
          {lat: -33.364, lng: 154.207},
          {lat: -34.364, lng: 154.207},
          {lat: -34.364, lng: 155.207},
          {lat: -33.364, lng: 155.207}
        ];

        var innerCoords2 = [
          {lat: -33.364, lng: 156.207},
          {lat: -34.364, lng: 156.207},
          {lat: -34.364, lng: 157.207},
          {lat: -33.364, lng: 157.207}
        ];

        return (

          <Polygon
            key={zone.id}
            paths={[outerCoords, innerCoords1, innerCoords2]}
            //options={zonesStyles[zone.status]}
            onClick={props.onMapClick}
          />

        );
})
```
The result is a polygon with inside other polygons, not holes.

Did somebody else find this issue?

Thx

![render](https://user-images.githubusercontent.com/9392180/27577057-965ec208-5b1f-11e7-8bc4-ebd7b0a73ca0.png)

**Comment by tomchentw** [comment]
Can't help. Please refer to google maps API related questions.

Please refer to [Getting Help](https://github.com/tomchentw/react-google-maps#getting-help) section in the README.

**Comment by Skyline888** [comment]
@tomchentw real example from Google maps Doc https://developers.google.com/maps/documentation/javascript/datalayer#polygon
