### ISSUE TITLE
Applying custom map styles?

### ISSUE THREAD

**Issue by zth** [tomchentw/react-google-maps#53]
Hi! I just found this repo and am implementing it in a project I'm working on. Runs very smooth, thanks for this! 

However, I want to apply my own map style to the map, and I fail to see how/where I can do that. Any ideas on how/if that can be done?

Also, where do I put other props for the map/markers, like icon for marker, assigning an info window to it and opening it on click etc? I noticed there seems to be a component called InfoWindow, but I couldn't find any documentation about it.

Thanks in advance, and thanks for the great repo!

**Comment by tomchentw** [comment]
@zth do you refer to stuff like this?

### Custom map style:
http://git.io/vTkmW

### Marker and InfoWindow
https://tomchentw.github.io/react-google-maps/#events/event-closure

**Comment by wuct** [comment]
@zth You can apply all `google.map` [options](https://developers.google.com/maps/documentation/javascript/reference#MapOptions) as `props` to a `<GoogleMap />`. For example: 

```
<GoogleMap mapStyles={/* YOUR MAP STYLES*/} />
```

**Comment by JanKantyPawelski** [comment]
Not `mapStyles` but `styles`.

**Comment by tomchentw** [comment]
Close this due to inactivity. Thanks @JanKantyPawelski  to point that out.

**Comment by frankbo** [comment]
For me adding styles as a prop didn't work. I had to add the styles to the `defaultOptions` prop as one can see in this example.
https://github.com/tomchentw/react-google-maps/blob/master/src/app/pages/basics/StyledMapExample.js
It is also possible to add the custom styles to the `options` prop as `options.styles`.

**Comment by anilljoshi** [comment]
you can find this on here its really useful and easy to use
https://github.com/tomchentw/react-google-maps/blob/master/src/app/constants/fancyMapStyles.json

**Comment by jose56wonton** [comment]
If one of you can update your links that would make my night :D

**Comment by tomchentw** [comment]
New example:
https://tomchentw.github.io/react-google-maps/#!/InfoBox

Please read the  documentation site first!

**Comment by anusree-mmlab** [comment]
How can i add custom style on the GoogleMap

import {withGoogleMap, GoogleMap, Marker, Polyline} from "react-google-maps";

<GoogleMap
  mapStyles=[style object]

is not working

**Comment by winsandymyint** [comment]
@anusree-mmlab 
```
const exampleMapStyles = [] //Add some style  
<GoogleMap
    defaultOptions={{ styles: exampleMapStyles }}
    >

```
Example [here](https://tomchentw.github.io/react-google-maps/#!/InfoBox)
Check fancy map styles [here](https://snazzymaps.com/)

**Comment by jose56wonton** [comment]
Hey I am not sure if I actually ever got this working, because I know right
now I just have a greyscale filter. But Here is what my component
looks like[image:
Inline image 1]
where styles is [image: Inline image 2]
You can find/ create different mapstyle.json on Google map developer site.

Good luck!

**Comment by ghost** [comment]
@winsandymyint you did it! love you ❤️

**Comment by asmmahmud** [comment]
It is possible using the following way: 

```
const exampleMapStyles = [{
		featureType: "water",
		elementType: "labels.text.fill",
		stylers: [
			{
				color: "#9e9e9e",
			},
		],
	}] //Add some style  
<GoogleMap
    options={{ styles: exampleMapStyles }}
    >
```

**Comment by baughmann** [comment]
I can confirm @anusree-mmlab method worked for me.

Just put your JSON style into a JS file as so:
`export const MyStyle = [ YOUR STYLES HERE]`

Then, in your map component:
```
import { MyStyle } from './MyStyle';

// other stuff

<GoogleMap defaultOptions={{ styles: MyStyle }}
        defaultZoom={8}
        defaultCenter={{ lat: -34.397, lng: 150.644 }} />
```

**Comment by coderdix** [comment]
Little late to the party but nothing I do seems to quite work. I gave up on having ...

Style data as JSON (from snazzy maps) and placed within a exported variable named "greyMap" and saved the file as mapStyles.js

I then imported it into a component the GoogleMaps component is in `import { greyMap } from "./mapStyles"` 

With my GoogleMaps component looking like
`<GoogleMap
			id="map"
			zoom={9}
			center={hasLocation ? currentLocation : center}
			onLoad={(map) => setMapRef(map)}
			styles={greyMap}
		>`

I tried defaultOptions={{ style: greyMap }} and got the same results. Not sure what I'm doing wrong!

**Comment by JustFly1984** [comment]
@coderdix The repo of this project is unmaintained more than a year, and we had build new version https://www.npmjs.com/package/@react-google-maps/api

We had rewrite it to TypeScript, and updating it frequently: https://github.com/JustFly1984/react-google-maps-api/tree/master/packages/react-google-maps-api
You can enjoy autocomplete.

You can see our docs: https://react-google-maps-api-docs.netlify.app

Also a lot of examples: https://react-google-maps-api-gatsby-demo.netlify.app/ https://github.com/JustFly1984/react-google-maps-api/tree/master/packages/react-google-maps-api-gatsby-example/src/examples

The bundle size is much smaller: https://bundlephobia.com/result?p=@react-google-maps/api

Our Spectrum community: https://spectrum.chat/react-google-maps Our Slack channel: https://join.slack.com/t/react-google-maps-api/shared_invite/enQtODc5ODU1NTY5MzQ4LTBiNTYzZmY1YmVjYzJhZThkMGU0YzUwZjJkNGJmYjk4YjQyYjZhMDk2YThlZGEzNDc0M2RhNjBmMWE4ZTJiMjQ

Enjoy!

**Comment by coderdix** [comment]
I'm using that one I keep searching when I have an issue and posting on the wrong forum lol

**Comment by yhoungdev** [comment]
my map keeps overflowing

**Comment by ghost** [comment]
> my map keeps overflowing

Can you please provide a screenshoot? And also the code you used in the example for us to be able to reproduce it...

**Comment by jesusbubai25** [comment]
> my map keeps overflowing

Add position property as relative in mapContainerStyle props it will not overflow
