### ISSUE TITLE
Uncaught TypeError: Cannot read property 'apply' of undefined

### ISSUE THREAD

**Issue by aaaristo** [tomchentw/react-google-maps#530]
The google.map library triggers this error:

```
Uncaught TypeError: Cannot read property 'apply' of undefined
```

when a listener exists in the props object but is undefined.

Maybe we could change this line:

https://github.com/tomchentw/react-google-maps/blob/5748a96ec61cf55f8bccaeb024be6d7737a15773/src/lib/enhanceElement.js#L44

to

```javascript
if (typeof props[onEventName] === 'function') {
```

**Comment by tomchentw** [comment]
Please feel free to open a PR!

**Comment by oshalygin** [comment]
I'll be adding tests for this in the near future and we can include this as part of that PR.

**Comment by tomchentw** [comment]
Fixed in v8.0.0
https://tomchentw.github.io/react-google-maps/

**Comment by dlape** [comment]
The same error with the Map with a SearchBox, and I think there's something to do with this line 
`const nextCenter = _.get(nextMarkers, '0.position', this.state.center);`

**Comment by tomchentw** [comment]
@dlape could you point out *which file* at *which line number*?

**Comment by dlape** [comment]
No sorry, I think there are no errors in your code in this [https://tomchentw.github.io/react-google-maps/#circle](url) examples, Instead, I think there are conflicts when using recompose and material UI. It's so annoying it keeps passing this error `Uncaught TypeError: Cannot read property 'apply' of undefined`.

**Comment by Veloxious** [comment]
@tomchentw I think the file and line @dlape is referencing is SearchBox line 56.
```
const nextCenter = _.get(nextMarkers, '0.position', this.state.center);
```
 I think I am having the same issue '_' is undefined.

**Comment by tomchentw** [comment]
`_` is lodash.
