### ISSUE TITLE
Support for gestureHandling

### ISSUE THREAD

**Issue by realyze** [tomchentw/react-google-maps#531]
1. Thanks for this awesome project!
2. Google Maps now have a partly awesome, partly annoying feature where you may need to use two fingers to scroll the map on mobile devices, see https://developers.google.com/maps/documentation/javascript/interaction#gesture-handling

Please consider adding this options to the `react-google-maps` API.

**Comment by tomchentw** [comment]
Please feel free to open a PR!

**Comment by realyze** [comment]
For posterity: I can just pass `options={{gestureHandling: 'greedy'}}` to the map (I didn't know about `options`) so all's good.

**Comment by gabrielmicko** [comment]
<GoogleMap options={{gestureHandling: 'cooperative'} /> doesn't work for me this way.

**Comment by realyze** [comment]
@gabrielmicko Hmm...so you're trying to force `cooperative` mode? Isn't that the default on mobile (if your app is scrollable)?

**Comment by gabrielmicko** [comment]
According to google docs: Note: The gestureHandling property is set to cooperative by default on pages that are scrollable. This means that the map does not change when the user scrolls the page on touchscreen or mobile applications. Read more about gesture handling below.

Yes, I'll try to figure out why it doens't work that way for me.

**Comment by gabrielmicko** [comment]
The way the lib was included was incorrect, outdated... I had to change it & now it works. (desktop, mobile)

**Comment by tomchentw** [comment]
PRs welcomed

**Comment by el27egs** [comment]
Hi.

I checked the code but the option gesturehandling is not working for me, I saw the page: 

https://developers.google.com/maps/documentation/javascript/interaction#gesture-handling 

and I made the test scrolling the page with two fingers on my laptop and I can see a message indicating the use of ctrl key to zoom the map when the pointer is over it, but and I can't see the same message with <Map gesturehandling='cooperative' /> with google-map-react

Could you help me?

**Comment by gabrielmicko** [comment]
If I push that change it will probably break other features that I don't use. Sorry.
