### ISSUE TITLE
InfoBox

### ISSUE THREAD

**Issue by PaulieScanlon** [tomchentw/react-google-maps#533]
Hi i'm using ^6.3.0 but when i do:
import InfoBox from 'react-google-maps/lib/addons/InfoBox'; 
i get a module not found error, I can see InfoBox.js in the node_modules addons folder. 

MarkerClusterer however works fine:
import MarkerClusterer from 'react-google-maps/lib/addons/MarkerClusterer';

Any ideas?

**Comment by lilywang2110168** [comment]
try this: import {default as InfoBox} from 'react-google-maps/lib/addons/InfoBox'

**Comment by oshalygin** [comment]
> @lilywang2110168 try this: import {default as InfoBox} from 'react-google-maps/lib/addons/InfoBox'

unless I'm mistaken, the above is literally the same as `import InfoBox from 'react-google-maps/lib/addons/InfoBox'`

**Comment by tomchentw** [comment]
Docs here:
https://tomchentw.github.io/react-google-maps/#!/InfoBox
