### ISSUE TITLE
Google markers lat and long are functions

### ISSUE THREAD

**Issue by vedran-milic** [tomchentw/react-google-maps#534]
https://tomchentw.github.io/react-google-maps/
When using this example new added markers lat and long values are functions and not numbers.
<img width="242" alt="screen shot 2017-07-05 at 12 38 25" src="https://user-images.githubusercontent.com/9935076/27860905-e32c8eca-617e-11e7-9e1c-016a7ca02a7b.png">

**Comment by tomchentw** [comment]
The `event.latLng` is a `LatLng` instance so that `lat`, `lng` are instance methods and they're definitely functions.

Please refer to [Getting Help](https://github.com/tomchentw/react-google-maps#getting-help) section in the README.
