### ISSUE TITLE
Add class to OverlayView container

### ISSUE THREAD

**Issue by joaoreynolds** [tomchentw/react-google-maps#535]
What I ultimately want to do is add a class (or at least some css properties) to the OverlayView container which would enable me to add some animation to an OverlayView as it moves around the map.

A solution might be in `src/lib/utils/OverlayViewHelper.js` to change `createContainerElement()` to:

```
export function createContainerElement(className) {
  const containerElement = document.createElement(`div`);
  containerElement.style.position = `absolute`;
  containerElement.className = className;
  return containerElement;
}
```

For now, I must resort to adding my OverlayViews manually or I can use `findDOMNode(this).parentElement.className` on the child component inside `<OverlayView>` - which of course feels wrong in so many ways, but it works for now.

**Comment by tomchentw** [comment]
If we open up `className` what about `styles` in the future? I don't see a reasonable API for now.

**Comment by joaoreynolds** [comment]
I see your concern, but it would be nice to have some level of control. Is there a way to pass in our own `containerElement`, opening up the api fully so no need to worry about adding this prop or that prop in the future?

Maybe my issue is so edge-case that what I'm doing now with findDOMNode is good enough (I can live with it). Might be best to see if upvotes come in on this issue. Thanks for listening! And awesome library!

**Comment by tomchentw** [comment]
Yeah but opening up a `containerElement` we would have to deal with its changes. (People expect it to work and update automatically because we pass it to props)

**Comment by tomchentw** [comment]
Could you try if the new rewrite in v8.0.0 allow's you to do this?
https://tomchentw.github.io/react-google-maps/#!/OverlayView
