### ISSUE TITLE
Documentation doesn't mention using "options" for <GoogleMap>

### ISSUE THREAD

**Issue by jeremyk** [tomchentw/react-google-maps#536]
Some of the properties found here (https://developers.google.com/maps/documentation/javascript/examples/control-default#try-it-yourself) have to be passed in on an options parameter. I did not see that in the documentation (maybe missed it) and it just seemed like they weren't working. Would be nice if there was a warning message as well.

**Comment by tomchentw** [comment]
Just pass in via props directly. See examples

**Comment by jeremyk** [comment]
Not sure exactly what you mean by examples. I definitely tried passing them in directly. Spent about an hour and then looked through your source to find this: `options(map, options) { map.setOptions(options); },` so I decided to try options and then it worked. But maybe I am just missing something obvious.

**Comment by oshalygin** [comment]
@jeremyk you're really using the standard google maps options.  An example:

```javascript

  // Google Maps v3 API Options Reference: 
  // https://developers.google.com/maps/documentation/javascript/3.exp/reference
  const defaultOptions = {
    styles: [mapStyles],
    mapTypeId: props.mapTypeId,
    mapTypeControl: false,
    zoomControl: true,
    streetViewControl: true,
    draggableCursor: 'default',
    draggingCursor: 'move'
  };

<GoogleMap
      defaultZoom={12}
      defaultOptions={defaultOptions}
      options={{
        ...defaultOptions,
        draggableCursor: props.cursor
      }}
    >
// Markers if you have any
</GoogleMap>
```

**Comment by tomchentw** [comment]
Check the new `props & methods` section in v8.0.0 docs:
https://tomchentw.github.io/react-google-maps/#!/GoogleMap
