### ISSUE TITLE
SVG Marker gets rendered differently depending on screen

### ISSUE THREAD

**Issue by FBosler** [tomchentw/react-google-maps#542]
https://stackoverflow.com/questions/45147326/svg-marker-gets-rendered-differently-on-different-screens

**Comment by vincentvella** [comment]
Set a width and a height in the SVG file and then scale it down from it's original size if you need to.

**Comment by FBosler** [comment]
Tried that, doesn't change a thing ... :( this is really driving me nuts

**Comment by FBosler** [comment]
closed because https://github.com/tomchentw/react-google-maps/issues/581 (I expanded the example)
