### ISSUE TITLE
Calling getBounds

### ISSUE THREAD

**Issue by jchapelle** [tomchentw/react-google-maps#543]
Hello, How is it possible to call getBounds on the GoogleMaps components ?

**Comment by SaltySousChef** [comment]
If you use the option onGoogleApiLoaded as a flag on your component with a callback function, that callback function will receive the map object which can be used to get map data. To get bounds just call map.getBounds() or map.getBounds().getSouthWest() for a specific area. Then use the onChange option to continue to get data after first load.
