### ISSUE TITLE
Unable to access map reference in v6+

### ISSUE THREAD

**Issue by xveganxxxedgex** [tomchentw/react-google-maps#545]
SO post: https://stackoverflow.com/questions/44296040/accessing-map-reference-using-react-google-maps-v6

Is there a good way to get the internal map reference to be able to add custom labels and other extended logic?

Thank you!

**Comment by oshalygin** [comment]
https://github.com/tomchentw/react-google-maps/issues/161#issuecomment-310553564

Is the current solution, but we have plans to add something a bit more elegant.

**Comment by nzoLogic** [comment]
I'm still a bit confused how to implement adding custom control divs to the map through this reference. I'm trying to create something similar to how [google maps] (https://www.google.com/maps/@37.7832535,-122.4297368,15z) display results once you type in "food". Could you provide an example how to do this using react-google-maps?

**Comment by oshalygin** [comment]
@nzoLogic the `MAP` constant gives you a reference to the `map` object.  

https://developers.google.com/maps/documentation/javascript/examples/marker-labels
Gives details on how to add marker-labels

In regards to your last question, you mean the markers that are generated from google maps when you search?

![image](https://user-images.githubusercontent.com/7675942/28483826-042cf09a-6e24-11e7-8c72-8f956e154672.png)

**Comment by nzoLogic** [comment]
@oshalygin I understand how to render the markers and info windows. I want to add the left container underneath the search bar that displays the results in a list like in the picture you posted, but can't figure out how to add it to the map. 

Did that help clarify my last question?

**Comment by nzoLogic** [comment]
I've been able to get an instance of the map component using a ref function but can't for the life of me figure out how to add my own elements to the map

**Comment by oshalygin** [comment]
Yeah I get what you're saying, thats not supported with this library at this time.  Maybe in the future one we get some of the bigger items tackled.  

You'll notice that certain aspects from Google Maps don't carry over to the API and you'd have to build them out manually.  You can definitely use the Places API to query for the data and get the results, it'll just come back to you in the form of JSON that you then have to build out and display.

**Comment by oshalygin** [comment]
> @oshalygin I've been able to get an instance of the map component using a ref function but can't for the life of me figure out how to add my own elements to the map

You mean markers?  Just use the `<Marker />` component

**Comment by nzoLogic** [comment]
Thanks for your help @oshalygin. Do you guys need help with contributions? I haven't contributed to open source projects yet, but want to help out!

**Comment by oshalygin** [comment]
Always looking for contributors!

**Comment by nzoLogic** [comment]
Perfect! Any suggestions as to what would be a good first contribution?
