### ISSUE TITLE
Opening infoWindow from an external element

### ISSUE THREAD

**Issue by roz0n** [tomchentw/react-google-maps#547]
I'm trying to click an external element (a button) with an id property that would match a marker's id prop.  Then, I'd like to execute that marker's onClick function in order to open the infoWindow. Much like clicking a conventional Google Maps search result and it opening the relevant infoWindow on the map.

With vanilla Google Maps, I have previously stored all the markers in an array and simply called the bound function as need. I am having difficulty doing this as the Marker component itself is created inside a render function which prohibits me from modifying the state. Regardless, I have not found a way to successfully store the marker component itself in an array as it's being returned inside a map function.

Is this a limitation of this component?

**Comment by xveganxxxedgex** [comment]
Not sure if there's a more direct way like you're asking, but the way my app handles external events is setting the ID in our state manager and watching for changes in our map component. So when the result is clicked, set that ID in the app state, then have your map component watch for when that prop change. When the active result ID changes, create the info window for it and pass it to the map as a child component.

**Comment by roz0n** [comment]
Thanks a lot for responding. That method is very similar to what I've been trying for the past few days to no avail, but it seems you've pinpointed my main issue (or perhaps lack of understanding).

How does one deal with the marker prop passed to the InfoWindow component in a scenario like yours? Currently all my markers have an onClick prop with a handler that sets the marker itself to the state as the "activeMarker" and does some other things like set the infoWindow state to true. That activeMarker object is then passed as the Marker prop inside the InfoWindow as `this.state.activeMarker`. 

I cannot seem to find a way to create the infoWindow child as you've instructed being that I have no way of passing the correct marker to the InfoWindow component.

**Comment by xveganxxxedgex** [comment]
You could have it set the state to the marker ID or other identifying field, then search your array of markers to get the full details.

```
componentWillReceiveProps(nextProps) {
    const props = this.props;

    if (props.activeMarkerId !== nextProps.activeMarkerId) {
      const marker = nextProps.activeMarkerId && nextProps.allMarkers.find(m => m.id === nextProps.activeMarkerId);

      if (marker && marker.id) {
        this.openInfoWindow(marker);
      } else {
        this.closeInfoWindow();
      }
    }
}
```

I hope this helps.

**Comment by chadzheng** [comment]
+1 facing the same problem, is there any solution?

**Comment by tomchentw** [comment]
Don't. Just render <InfoWindow> under <Marker> to open it, and render nothing to close it.

**Comment by spaceforestchu** [comment]
Hey Tom,

Can you explain what do you mean render under to open it and render nothing to close it? 

Thanks
