### ISSUE TITLE
marker css style

### ISSUE THREAD

**Issue by joytek** [tomchentw/react-google-maps#548]
Can I add styles to the marker, and how do I do it

**Comment by oshalygin** [comment]
You can add your own marker altogether or use Googles:

http://maps.google.com/mapfiles/ms/icons/blue-dot.png
http://maps.google.com/mapfiles/ms/icons/red-dot.png

or you can add stroke color:
```
icon: {
        path: google.maps.SymbolPath.FORWARD_CLOSED_ARROW,
        strokeColor: "red",
        scale: 3
    },
```

Using the library you can do something like

```
<Marker
    onClick={() => this.mapClickHandler}
    icon={{
        url: myMarkerSVG,
        anchor: anchorPoint
    }}
    key={index}
    position={marker.location}
/>
```

Read through this for more information:
https://developers.google.com/maps/documentation/javascript/markers

**Comment by WeingartenHarel** [comment]
if you are using :
https://www.npmjs.com/package/google-map-react

simply edit this line (component) to edit the marker <div> {text} etc.....
const AnyReactComponent = ({ text }) => <div>{text}</div>;

class _someLocationComponent extends React.Component {

 {/* // Important! Always set the container height explicitly */}
      <div style={{ height: '100vh', width: '100%' }}>
        <GoogleMapReact
          bootstrapURLKeys={{ key: }}
          defaultCenter={center}
          defaultZoom={zoom}
        >
          <AnyReactComponent
            lat={30.30}
            lng={30.30}
            text={some test}
            size={'300','300'} 
          />
        </GoogleMapReact>
 }
 
 Cheers
 W.Harel
