### ISSUE TITLE
Refactor `SimpleChildComponent#_createOrUpdateInstance`

### ISSUE THREAD

**Issue by tomchentw** [tomchentw/react-google-maps#55]
I'd prefer to split out logics to two functions:
`SimpleChildComponent#_createInstance`
`SimpleChildComponent#_updateInstance`
So that subclasses are free and clear to modify

**Comment by wuct** [comment]
It will be nice when we need to use [google-maps-utilities](http://code.google.com/p/google-maps-utility-library-v3/wiki/Libraries), since the constructors of those utilities are not in global `google`.

**Comment by tomchentw** [comment]
Got it. Seems appealing to use `google-maps-utilities` too!

**Comment by tomchentw** [comment]
Closed for #88 .

**Comment by tomchentw** [comment]
Released [v2.0.0] and [v2.0.1].

[v2.0.0]: https://github.com/tomchentw/react-google-maps/releases/tag/v2.0.0
[v2.0.1]: https://github.com/tomchentw/react-google-maps/releases/tag/v2.0.1
