### ISSUE TITLE
Considering switching to airbnb styleguide

### ISSUE THREAD

**Issue by oshalygin** [tomchentw/react-google-maps#550]
https://github.com/airbnb/javascript

Right now we extend `react-app`'s eslint configuration with a few additions such as quotes, jsx-quotes and comma dangle.  It's great that we have a styleguide in place but it would be helpful for future contributors to take on a canonical and idiomatic way of writing modern javascript.

This issue is more of a discussion piece before I do a quick refactor.  Input appreciated 👍 

For reference, our styles:

https://github.com/tomchentw/react-google-maps/blob/master/.eslintrc
``` javascript
{
  "extends": "react-app",
  "rules": {
    // Possible Errors
    "comma-dangle": ["error", "always-multiline"],
    // Stylistic Issues
    "jsx-quotes": ["error", "prefer-double"],
    "quotes": ["error", "backtick"]
  }
}

```

**Comment by tomchentw** [comment]
Airbnb's style haven't been my taste. I'd suggest a looser lint config (like `react-app` or whatever FB uses) plus **prettier**.

**Comment by oshalygin** [comment]
I'd prefer a looser lint config as well, I would say the only thing that is hard to overcome are the backticks and the trailing commas.  Would you be comfortable if we just removed those from the configuration and let it be more loose?

**Comment by oshalygin** [comment]
Considerations: `react-app` + `prettier`


ref links: 
https://github.com/prettier/prettier
https://github.com/prettier/eslint-config-prettier

**Comment by tomchentw** [comment]
I'd like to keep trailing commas (and this can be done by prettier). `backtick` is just one of my personal preferences. Feel free to switch to either single or double quotes.

**Comment by oshalygin** [comment]
Agreed, lets keep trailing commas.  

Id prefer backtick be switched to single quotes but how about for now we just remove the rule so that we don't need to do a full refactor across the application.  We would have more freedom to use both.

I'll put a PR together for review.

**Comment by oshalygin** [comment]
In the PR, there will be two commits.  One to set the base config to extend prettier with the associated rules, and the second commit which will update the `src` codebase to conform to prettier with the strict error rule.  

If the second commit is too much right now and if we rather take it step by step then I'll bump it out.  I'll mention more in the PR :)

**Comment by tomchentw** [comment]
Switched to `prettier` in v8.0.0
https://tomchentw.github.io/react-google-maps/
