### ISSUE TITLE
streetViewControl and Zoom control  not working?

### ISSUE THREAD

**Issue by PinkPanda17** [tomchentw/react-google-maps#551]
I tried 
  <GoogleMap
    ref={props.onMapLoad}
    zoom={props.zoom}
    center={props.center}
    onClick={props.onMapClick}
    onBoundsChanged = {props.onBoundsChanged}
    streetViewControl= {props.streetViewControl}
    zoomControl={false}
  >

they aren't working. any solutions for this?

**Comment by PinkPanda17** [comment]
Fixed: Sorry, I just need to indicate zoomControl and streetView control inside the options property

**Comment by oshalygin** [comment]
Sounds good, glad you were able to figure it out @PinkPanda17 👍

**Comment by axhamre** [comment]
For those wondering how to set options:

      <GoogleMap
        defaultZoom={...}
        defaultCenter={...}
        options={{streetViewControl: false, mapTypeControl: false}}
      >
