### ISSUE TITLE
Map is going blank after rotating

### ISSUE THREAD

**Issue by jmoh7969** [tomchentw/react-google-maps#555]
Hi @tomchentw , I have two tabs consisting of one List and Map. If i am in Map tab and doing orientation change the map is loading fine. When i am in List tab and doing rotation, and then selecting map tab, Map is not loading / re rendering(Going grey). 
Anyone have any solution for this issue ? Need help.

**Comment by oshalygin** [comment]
Do you have a repo or some reference that we could repro?  This could be caused by a slew of things.

**Comment by jmoh7969** [comment]
Hi @oshalygin , i solved this issue. The tab was adding "display:none" style to map when it goes hidden. Because of this map was not getting the resize/orientation events. I changed it manually in JS by changing "display:none" to "visibility:hidden",then map was loading fine.

**Comment by jmoh7969** [comment]
Hi you can reproduce this issue by following the steps.
1. Create a nav-tab with map and something else(say List).
2. Toggle to List tab, rotate the device, toggle back to map tab.
3. The map will not be re rendered.
This is because if the containing div is having style display none(which will be added when you toggle to list), the rotation is not recognised by map, as it is hidden.

**Comment by tomchentw** [comment]
> @jmoh7969 This is because if the containing div is having style display none(which will be added when you toggle to list), the rotation is not recognised by map, as it is hidden.

According to your description above, I think it's an issue of Google Maps JavaScript API, not `reaact-google-maps`.
