### ISSUE TITLE
Circle: set color, etc.

### ISSUE THREAD

**Issue by freenice12** [tomchentw/react-google-maps#557]
https://developers.google.com/maps/documentation/javascript/examples/circle-simple

There are some options for color etc.
```javascript
var cityCircle = new google.maps.Circle({
            strokeColor: '#FF0000',
            strokeOpacity: 0.8,
            strokeWeight: 2,
            fillColor: '#FF0000',
            fillOpacity: 0.35,
            map: map,
            center: citymap[city].center,
            radius: Math.sqrt(citymap[city].population) * 100
          });
```
Could I add some code for props to Circle.js to set this up?

**Comment by oshalygin** [comment]
Are you using the drawing manager? if so there's already an example in the demo:
https://tomchentw.github.io/react-google-maps/drawing/drawing-tools

If you're straight up using the `<Circle />` component, you should be able to do the above with the `options` prop.
https://github.com/tomchentw/react-google-maps/blob/master/src/lib/Circle.js#L31

Feel free to comment if this doesn't solve your use case or you notice a bug.

**Comment by kenjiru** [comment]
@oshalygin all the links are dead..

**Comment by tomchentw** [comment]
@kenjiru please read the documentation
https://tomchentw.github.io/react-google-maps/#circle
