### ISSUE TITLE
Multiple Markers

### ISSUE THREAD

**Issue by Karrsen** [tomchentw/react-google-maps#558]
Hi,
I'd like to start out by saying that I am very new to coding especially when concerning Javascript, React, and HTML. But I really want to learn. Right now I am trying out react-google-maps and am trying to add multiple markers. I don't know how. I cannot add anything to an index.html file because, in this class project, it is not mine to edit. As such, I don't know what to do with my API key. Maybe that could fix it? Again, I don't know because I am only a beginner hoping to learn. Any help? Thanks.

**Comment by oshalygin** [comment]
Welcome and we appreciate you using the library:  Please refer to the [Getting Started](https://github.com/tomchentw/react-google-maps#getting-started) section for more information.

You'll need to modify the index file or pass the googleMapsURL to the component.

Read through this as well for a bit more of background and how to obtain a key:
https://developers.google.com/maps/documentation/javascript/get-api-key
