### ISSUE TITLE
Touch events?

### ISSUE THREAD

**Issue by af7** [tomchentw/react-google-maps#56]
Hi, I see these event_names:

const BASIC_EVENT_NAMES = (
  "click dblclick drag dragend dragstart mousedown mousemove mouseout mouseover mouseup rightclick"
);

How about tablet support with touch events? Are they supported somehow?

**Comment by wuct** [comment]
Hi @af7,
What kinds of touch events do you need? Because this library uses Google Maps API V3, events like `touchstart` or `touchstop` are not supported.

**Comment by af7** [comment]
Hi, does this mean that if someone uses the map on a tablet browser and then pans it, then this will not behave correctly?

**Comment by tomchentw** [comment]
I've tried on my iPad for the demo site, I can use two fingers to pan the map and click to add markers for no issue. However, as mentioned by @wuct , `touch` events are not natively supported by Google Maps API v3.

**Comment by mauriyouth** [comment]
Hi, what's the name of the handler for hover event on a marker, thanks :)

**Comment by wuct** [comment]
@mauriyouth There is no `hover` or `onhover` event in plain javascript, so as to Google Map API. Though, you can use `mouseout` and `mouseover` event to simulate something equal.

**Comment by mauriyouth** [comment]
@wuct thanks, but how do i set them up on the marker, <Marker onMouseover={this.handler1} onMouseout={this.handler2} > ?

**Comment by tomchentw** [comment]
I'm not sure how to add `mouseOver` and `mouseOut` event when using vanilla GoogleMaps JavaScript APIs v3. Maybe `events.addDomListener` will do the trick? If that's the case, we currently don't support event binding over `events.addDomListener`.

**Comment by mauriyouth** [comment]
it did work with <Marker onMouseover=""> and <Marker onMouseout="">, thanks for your help :)

**Comment by tomchentw** [comment]
Okay, naming matters LOL.
