### ISSUE TITLE
Map not rendering

### ISSUE THREAD

**Issue by alexknipfer** [tomchentw/react-google-maps#562]
I'm having an issue that was mentioned in one of the previous posts, but the comments didn't fix the issue. Any ideas why the map isn't rendering into the browser? Here is a link to my google map container and component: 

[Link to repo](https://github.com/alexknipfer/DiscShareClient/tree/dev/src/routes/Home/components/GoogleMap)

**Comment by oshalygin** [comment]
I see you closed/solved it?  I looked at the repo briefly but I couldn't figure out how `google` was getting passed down and used.  Take a look at some of the demos here and see if that helps you get going.

**Comment by alexknipfer** [comment]
Thanks for the response. Most people (almost everybody) suggested adjusting the height and width of the parent div if the map was not rendering. After some inspecting, I wasn't adjusting my height and width on the proper tag, all is good now! Thanks again.

**Comment by oshalygin** [comment]
Sounds good!
