### ISSUE TITLE
Custom Markers

### ISSUE THREAD

**Issue by Karrsen** [tomchentw/react-google-maps#563]
Hey! I've gotten pretty into this stuff and first I would like to say awesome stuff. You guys are incredible. I'm still new and learning but you've made it all very clear. I was wondering how I could make each marker into a custom image? I am using the withGoogleMap version. Any ideas? Also, if it includes using the "src + API key thing" could you explain to me a bit? I don't know where to put it in my file. Thanks!

**Comment by oshalygin** [comment]
@Karrsen 

Its a matter of passing down either the image(svg or otherwise) to the object through props.  Here is an example:

```jsx
<Marker
            onClick={() => props.onClick(marker.workId)}
            icon={{
              url: svg,
              anchor: workOrderSvgAnchor, // your anchor
            }}
            key={index}
            position={marker.location}
          />
```

**Comment by Karrsen** [comment]
Thanks for this but I still don't understand completely. What is my anchor and svg? I don't know those. Thanks.

**Comment by oshalygin** [comment]
@Karrsen the marker size is static on purpose, thats how standard markers are implemented within the map.  

If you wanted to keep it static you could use `<OverlayView />`

Closing for now :)

**Comment by aliaro428** [comment]
@oshalygin i have a question can we change the marker color dynamically ?

**Comment by JustFly1984** [comment]
@aliaro428 
The repo of this project is unmaintained more than a year, and we had build new version https://www.npmjs.com/package/@react-google-maps/api

We had rewrite it to TypeScript, and updating it frequently: https://github.com/JustFly1984/react-google-maps-api/tree/master/packages/react-google-maps-api
You can enjoy autocomplete.

You can see our docs: https://react-google-maps-api-docs.netlify.com/

Also a lot of examples: https://react-google-maps-api-gatsby-demo.netlify.com/ https://github.com/JustFly1984/react-google-maps-api/tree/master/packages/react-google-maps-api-gatsby-example/src/examples

The bundle size is much smaller: https://bundlephobia.com/result?p=@react-google-maps/api@1.7.5

Enjoy!
