### ISSUE TITLE
withScriptjs does not check if google exists

### ISSUE THREAD

**Issue by ZephD** [tomchentw/react-google-maps#564]
I have made two components - one GoogleMap and one StreetView.
Both use withScriptjs.
However, if both components are on the same page, the google maps script gets added twice.

I suggest that withScriptjs uses a global loading state, and checks if there is already a withScriptjs attempting to add before attempting to add it itself.

**Comment by ZephD** [comment]
Additional:
One uses the plane google map URL, the other uses the google map URL with `&libraries=visulization`.
Therefore, these are two different URLs, so scriptjs is working as expected.
Still, two versions of window.google.maps is loaded because of this.

**Comment by tomchentw** [comment]
You can
- move withScriptJs to the upper component.
- or implement your own withScriptJs that customized your loading logic

**Comment by renatodeleao** [comment]
Same problem here using multiple maps on one page (plus some async loaded ones on dialog windows) which was throwing errors from google map API due multiple includes. Rolled back to inline html include with `async` flag since I couldn't find a workaround for this at the time of writing. Will post a snippet if I that changes in the meantime.

**Comment by oshalygin** [comment]
yeah the path here is to use withScripts in a HOC that wraps any other content.  If the library was to support this we'd have to have a global loading state are you suggest though.

**Comment by tomchentw** [comment]
> However, if both components are on the same page, the google maps script gets added twice.

`withScriptjs` only check if the URL is already loaded or not, so you have to use all the SAME URL for static/async script. See the new docs site for v8.0.0:

https://tomchentw.github.io/react-google-maps/
