### ISSUE TITLE
Unable to set searchbox to only display results after 3 or more characters entered

### ISSUE THREAD

**Issue by trutherford2388** [tomchentw/react-google-maps#566]
I am working with the current library, but I cannot find where the API is called to show the search results drop-down. I need to set it where it only displays results only if the search box has 3 or more characters and not for it to show results after the first character is entered.

If you could point me to where this API is called to display the search results, then I can add my own modification in to get the search results to display only after the set number of characters are called.

Thank you for whatever assistance you can offer.

V/R
Travis L. Rutherford

**Comment by AstrasyA** [comment]
+1

**Comment by mitchellmartin** [comment]
+1

**Comment by oshalygin** [comment]
I can look at the code but this is fairly straightforward if you pass it down as props to the component.

Your component that reads the props can have a basic handler:

```javascript

  componentWillReceiveProps(nextProps) {
    const { searchTerm } = nextProps;
    if (searchTerm.length < 3) {
      this.setState({ searchTerm });
    }
  }

```

**Comment by oshalygin** [comment]
Yeah I don't see anything in the google maps api.
https://developers.google.com/maps/documentation/javascript/3.exp/reference#SearchBoxOptions

I also don't see a big need for the library to have a regex or filter function that filters out input until a certain number of characters is entered.  

IMO this is better handled in your component that consumes SearchBox.

Leaving this open for a little while to see if anyone else has an alternative solution.

**Comment by trutherford2388** [comment]
The reason to limit the calls after 3 a certain number of characters is entered is because Google sets a limit to how many API calls can be used before they start charging the company using their API's. If you limit the search to after 3 or more characters, you greatly reduce unnecessary calls.

V/R
Travis L. Rutherford

**Comment by tomchentw** [comment]
Close now. Feel free to re-open if it's `react-google-maps` fault
