### ISSUE TITLE
Module not Exported properly

### ISSUE THREAD

**Issue by abhatia-lixar** [tomchentw/react-google-maps#569]
I was trying to run the Basic Polygon example (https://gist.github.com/dyyylan/a81245ec7b88251c317148f3699c58a0) and I am getting this warning:
### Warning: React.createElement: type is invalid -- expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in.

Can anyone help me on this?

Thanks

**Comment by oshalygin** [comment]
Code looks good for this, I'll have to take a look and try to repro

**Comment by tomchentw** [comment]
You're using the very old API. The latest is v8.0.0:

https://tomchentw.github.io/react-google-maps/#marker
