### ISSUE TITLE
Polylines with multiple color

### ISSUE THREAD

**Issue by jmoh7969** [tomchentw/react-google-maps#572]
how to render multiple ploylines with different strokeColor ? 
@tomchentw @oshalygin 
`      <div>
        <Polyline path={props.wholePath[1].path} options={{strokeColor: 'red',strokeWeight: 6}}/>
        <Polyline path={props.wholePath[0].path} options={{strokeColor: 'grey',strokeWeight: 10}}/>
      </div>`
showing polyline with grey color only. Occupying red area also.

**Comment by oshalygin** [comment]
I'd have to pull it up to check but have you tried passing the strokeColor as a hash value? `#FF0000`

**Comment by oshalygin** [comment]
yeah that should work I pulled up the docs:

`strokeColor specifies a hexadecimal HTML color of the format "#FFFFFF". The Polyline class does not support named colors.`

Make sure to always reference the API itself when in doubt.
https://developers.google.com/maps/documentation/javascript/shapes#polyline_add

**Comment by oshalygin** [comment]
Let us know if it works and I'll close it out, otherwise i'll look to see if there's a bug somewhere but I'm pretty sure this component works as intended

**Comment by jmoh7969** [comment]
Tried with hash value and it is plotting properly. Doesn't know why facing such issue. Now it's **working with hash values**.

**Comment by oshalygin** [comment]
Cool closing for now.
