### ISSUE TITLE
How can i disable the drawing mode after first draw complete.

### ISSUE THREAD

**Issue by abhayjeetgupta** [tomchentw/react-google-maps#580]
I am not able to call following code onOverlaycomplete callback . What is the way we can achieve this.
handleOnOverlayComplete(event){
        
        this._drawingManager.setOptions({
            drawingControl: false
        });

    }

**Comment by Liaxs** [comment]
i have the same problem, I searched everywhere but i dont the answer...

**Comment by tomchentw** [comment]
Just set the `options` from props.
https://tomchentw.github.io/react-google-maps/#!/DrawingManager

**Comment by SyedSaifAli** [comment]
@tomchentw The above solution doesn't work. Help!
