### ISSUE TITLE
when I pass initial value through code to draw the circle or polygon on map in drawing manager. It doesn't work

### ISSUE THREAD

**Issue by abhayjeetgupta** [tomchentw/react-google-maps#584]
Something like this
circleOptions: {
                center: {lat: 28.424765, lng: 76.8496952},
                radius:200,
                fillColor: `#ffffff`,
                fillOpacity: .3,
                strokeWeight: 1,
                clickable: false,
                editable: true,
                draggable:true,
                zIndex: 1

            }

tried this as well

circleOptions: {
                center: new google.maps.LatLng(28.424765,76.8496952),
                radius:200,
                fillColor: `#ffffff`,
                fillOpacity: .3,
                strokeWeight: 1,
                clickable: false,
                editable: true,
                draggable:true,
                zIndex: 1

            }

**Comment by oshalygin** [comment]
I would take a look at the demo page and do a side by side comparison.

https://tomchentw.github.io/react-google-maps/drawing/drawing-tools
Without diving deep into the configuration, it looks like something may be off.

If you believe its a bug with the actual implementation, please comment and we can re-open.  As far as I can tell this functionality is working fine.
