### ISSUE TITLE
InfoWindow onClick method?

### ISSUE THREAD

**Issue by quachsimon** [tomchentw/react-google-maps#585]
I am trying to display just the `InfoWindow` component with an `onClick` event passing in the marker object.

I looked through the the docs and could not find any onClick related events with the InfoWindow component. 

Only 

``` 
  onCloseClick,
  onDomReady,
  onZIndexChanged
```

I am trying to following [Airbnb](https://www.airbnb.ca/s/Toronto--ON/homes?checkin=2017-08-17&checkout=2017-09-08&allow_override%5B%5D=&s_tag=k_Nzx_KW)'s map where they click the info window and it will redirect them to another page. 

I am able to display the marker and info window at the moment and have the marker's `onClick` event fire but, I do not want to display the pin and only have the InfoWindow.

Is this possible or am I missing something?

**Comment by tomchentw** [comment]
Try the onClick directly on the content?

**Comment by tomchentw** [comment]
Hook your `onClick` on the child of the `InfoWindow` directly.
https://tomchentw.github.io/react-google-maps/#infowindow

**Comment by nguyenvanphuc2203** [comment]
it work for me!
```
<InfoWindow  onCloseClick={props.onToggleOpen}>
            <div onClick={()=>{alert('hello')}} class="wow slideInLeft">
              <img src="https://i.imgur.com/7IgBxnH.jpg" width="150px" />
              <div>nhà trọ cho thuê</div>
              <div>1.500.000đ</div>
            </div>
          </InfoWindow>
```

**Comment by dhruvesingal** [comment]
Hi... I tried the above method for handling click method in InfoWindow component defined separately. Can't seem to call the listener. I have implemented the click listener inside attr value only, as you had mentioned.
