### ISSUE TITLE
Add support for rotation on Marker icon

### ISSUE THREAD

**Issue by tmcalves** [tomchentw/react-google-maps#586]
As far as I am aware, the rotation property of the marker icon is not yet supported. Are there any plans to implement this?

**Comment by tomchentw** [comment]
PRs welcomed.

**Comment by tomchentw** [comment]
@tmcalves I just check the docs, the `rotation` property is on the `google.maps.Symbol` class, and it's related to the `setIcon(icon:string|Icon|Symbol)` method on the `google.maps.Marker` class. Which, it can be set by `<Marker icon={icon:string|Icon|Symbol} />` in `react-google-maps` for no problem. There's no need for an update or a PR.

I'll close this for now, if you find it not-working feel free to re-open.

**Comment by tomchentw** [comment]
https://developers.google.com/maps/documentation/javascript/3.exp/reference#Marker

**Comment by CodingToBeWithHer** [comment]
I have tried but without success to rotate Marker, this is my marker:
```
 <Marker
      options={{icon: {url: carIconAppSilver, scaledSize: new window.google.maps.Size(30, 62)}}}
      position={{ lat: props.centerLat, lng: props.centerLong }}
    />
```

how can I rotate it, say, by 90 degrees?

Any help greatly appreciated. Really good library.

**Comment by sky-tiagoalves** [comment]
Unfortunately Maps API doesn't support this for web (you have that feature on Android for example)
In order to do the rotation I created a sprite image with all the angles I needed and just changed the icon of the marker accordingly @CodingToBeWithHer

**Comment by CodingToBeWithHer** [comment]
@sky-tiagoalves thank you for a quick answer - really appreciate it. 

Ok. I understand, doing sprite would work although in my case I may have any integer between 1 and 360 degrees so I would need to approximate somehow as I would rather avoid having sprite with 360 images in it...

According to this:
https://stackoverflow.com/questions/18951711/how-to-rotate-a-marker-in-google-maps
in the answer from BoomVang

it seems like it's a simple to do with just pure google API, would that be a lot of work to add it in the react-google-maps library?

**Comment by CodingToBeWithHer** [comment]
here is also discussion and some solution to rotate marker in v3 Google Maps:
https://stackoverflow.com/questions/6800613/rotating-image-marker-image-on-google-map-v3

but anyways, if someone would figure out some easy way to rotate the marker in react-google-maps I guess this would be the place to post it as it's the first result Google returns when searching for it on the search engine.

**Comment by addingama** [comment]
Hi, I've managed to rotate marker using this code

```
<Marker
        onClick={e => props.onMarkerClick(marker)}
        key={marker.id}
        position={{ lat: marker.lat, lng: marker.lng }}
        options={{
            icon: {
                path: window.google.maps.SymbolPath.FORWARD_CLOSED_ARROW,
                scale: 6,
                fillColor: 'red',
                fillOpacity: 0.8,
                strokeWeight: 2,
                rotation: marker.rotation,
            },
            }} 
      />
```

**Comment by CodingToBeWithHer** [comment]
right... this is working but only when I also use:
```
path: window.google.maps.SymbolPath.FORWARD_CLOSED_ARROW
```
but I have a custom image as my marker so I would need to have something like:

```
<Marker
        onClick={e => props.onMarkerClick(marker)}
        key={marker.id}
        position={{ lat: marker.lat, lng: marker.lng }}
        options={{
            icon: {
                url: carIconAppSilver,
                scale: 6,
                fillColor: 'red',
                fillOpacity: 0.8,
                strokeWeight: 2,
                rotation: marker.rotation,
            },
            }} 
      />
```

where carIconAppSilver is my image
in that case the image just ignores the rotation unfortunately

**Comment by yadynesh** [comment]
I am using a custom marker as well and not able to rotate it. How did you solve this problem?

**Comment by sky-tiagoalves** [comment]
@yadynesh I solved it by using an image sprite. There are ways to actually rotate the marker by making a custom one but the performance is terrible

**Comment by CodingToBeWithHer** [comment]
I have also used sprite, that contains 12 images, each rotated by 30 degrees, and based on the value of degrees between 1-360 I display one of the 12 images that is nearest the real degree value.

**Comment by franklinharvey** [comment]
I was able to solve this by getting the raw path out of my SVG icon and doing 

```
let anSVGPathString = "M61.2849 48.0244C61.2849 64.3164 48.0769 77.5244 31.7849 77.5244C15.4929 77.5244 2.28491 64.3164 2.28491 48.0244C2.28491 34.9504 22.2469 12.2714 29.6169 3.82141C31.1029 2.11741 33.7479 2.12141 35.2349 3.82441C42.6149 12.2764 61.2849 34.9514 61.2849 48.0244Z"
let aRotationVariable = 98
icon: {
          path: anSVGPathString,
          rotation: aRotationVariable
          anchor: new google.maps.Point(30, 36)
        },
```

**Comment by 0xK3vin** [comment]
is there still no solution to solve this problem?  Using SVG paths slows down performance considerably.

**Comment by zelin** [comment]
> I have also used sprite, that contains 12 images, each rotated by 30 degrees, and based on the value of degrees between 1-360 I display one of the 12 images that is nearest the real degree value.

How were you able to use it , do you have any sample to share?

**Comment by Akman13** [comment]
Has anyone had success with this? I'm trying to rotate my custom marker by a direction ranging from 0-360deg, similar to @CodingToBeWithHer and would really prefer not to go down the path of making a sprite if it can be avoided.

**Comment by tomasmalioesnaola** [comment]
I've tried but I haven't had any luck. From my point of view there is a problem with the icon and the rotation.
The only thing I have left is to create multiple icons to make the selection of which one to show previously but it is not the best and you have to create many for it to look good.

Could someone solve the problem?
