### ISSUE TITLE
How can change SearchBox inputStyle after added to map?

### ISSUE THREAD

**Issue by ericfong** [tomchentw/react-google-maps#587]
I want to show/hide SearchBox by a toggle button. 

However, I found that once SearchBox rendered to the map. Change searchbox props will have no effect.

How can I update the SearchBox style?

Thanks

**Comment by tomchentw** [comment]
Could you try the new `places/SearchBox` component in v8.0.0?
Dos here: https://tomchentw.github.io/react-google-maps/#!/SearchBox
