### ISSUE TITLE
Multiple Directionrenderer

### ISSUE THREAD

**Issue by dlape** [tomchentw/react-google-maps#588]
Hi good day is there a way that your Direction renderer can have multiple directions like from point A to B then to C and so on, please help me sir.

**Comment by oshalygin** [comment]
The issues section of GitHub is strictly for talking about features/bugs/etc.  
I would take a look at the API docs first:
https://developers.google.com/maps/documentation/javascript/directions

**Comment by devantic** [comment]
Similar question but want to render multiple routes when the 23 waypoint limit for a single route is exceeded. I've managed to do this in plain html/js before using multiple directionsRenderers with setMap to the same map object but can't do it in react, at least not by using multiple DirectionsRenderer components. Has anyone done this? help greatly appreaciated.

**Comment by camillegachido** [comment]
hi @myleftshoe, were you able to solve it?

**Comment by devantic** [comment]
@camillegachido. I abandonned this project years ago and don't remember much about it. What I do remember though is that it successfully rendered multiple routes each with more than 23 waypoints. So if you are asking if the 23 waypoint limit can be worked around the answer is/was yes, whether I ended up using react and this lib I honestly can't recall. :(
