### ISSUE TITLE
DrawingManager Polygon change event listener

### ISSUE THREAD

**Issue by jasurjuraev** [tomchentw/react-google-maps#589]
how to listen when DM Polygon changes its shape?
<DrawingManager
                defaultDrawingMode={google.maps.drawing.OverlayType.POLYGON}
                onOverlayComplete={handleOverlayComplete}
                defaultOptions={{
                    drawingControl: false,
                    drawingControlOptions: {
                        position: google.maps.ControlPosition.TOP_CENTER,
                        drawingModes: [google.maps.drawing.OverlayType.POLYGON]
                    },
                    polygonOptions: {
                        fillColor: '#199ee0',
                        fillOpacity: 0.2,
                        strokeWeight: 2,
                        strokeColor: '#113460',
                        clickable: true,
                        draggable: true,
                        editable: true,
                        zIndex: 1
                    }
                }}
/>

**Comment by tomchentw** [comment]
Could you search if vanilla Google Maps JavaScript API support this?

**Comment by tomchentw** [comment]
This should be on SO

**Comment by tomchentw** [comment]
Try the callback exposed by the `DrawingManager`, if there's no such thing I can't help (it's google
's lib)
https://tomchentw.github.io/react-google-maps/#!/DrawingManager
