### ISSUE TITLE
How to add search box without rendering google map.

### ISSUE THREAD

**Issue by rnagavel** [tomchentw/react-google-maps#593]
Hi All,
We are trying to render Searchbox typeahead without google map. We tried in many ways, but couldn't accomplish. 
is this a known constraint ?

**Comment by edgareler** [comment]
@rnagavel check this lib: https://github.com/kenny-hibino/react-places-autocomplete

**Comment by tomchentw** [comment]
Could you try the new `places/SearchBox` component in v8.0.0? It's possible now in v8.0.0
Dos here: https://tomchentw.github.io/react-google-maps/#!/SearchBox

**Comment by tomchentw** [comment]
Release [v8.2.0](https://github.com/tomchentw/react-google-maps/releases/tag/v8.2.0)
StandaloneSearchBox: https://tomchentw.github.io/react-google-maps/#standalonesearchbox

**Comment by rnagavel** [comment]
@tomchentw , Hi Tom
Thank you so much. It worked.

**Comment by 0x1bitcrack3r** [comment]
How to handle multiple searchboxes using react-google-maps?
Like FromLocation:Searchbox1
        ToLocation:Searchbox2.
