### ISSUE TITLE
Adding markerWithLabel With Async Google Map 

### ISSUE THREAD

**Issue by abhayjeetgupta** [tomchentw/react-google-maps#595]
How can I add MarkerWithLabel With Async Google Map ?

**Comment by tomchentw** [comment]
Will need some rewrite on the `MarkerWithLabel` component……

**Comment by RGFnaGFuIEd1bmF5** [comment]
@abhayjeetgupta I handled this issue using with external google loader for temporarily not with AsyncLoader.

After call back of [google-maps](https://www.npmjs.com/package/google-maps)  library i set up [marker-with-label](https://www.npmjs.com/package/markerwithlabel)

@tomchentw I need this implementation too. If there will be not a PR for this, I could do it in a couple of days.

**Comment by tomchentw** [comment]
@RGFnaGFuIEd1bmF5 please do a PR. Also note that 8.0.0 is released with a brand new architecture. It should be **a lot** easier to create a component now.

**Comment by d46** [comment]
#657

**Comment by tomchentw** [comment]
Released [v9.0.0](https://github.com/tomchentw/react-google-maps/releases/tag/v9.0.0)
