### ISSUE TITLE
importing DrawingManager fails for create-react-app

### ISSUE THREAD

**Issue by sdwio** [tomchentw/react-google-maps#597]
In an app created via create-react-app using
`import DrawingManager from "react-google-maps/src/lib/drawing/DrawingManager";`
will fail with the error message

    Module parse failed: /.../react-google-maps-test/node_modules/react-google-maps/src/lib/drawing/DrawingManager.js Unexpected token (77:4)
    You may need an appropriate loader to handle this file type.
    | 
    |   propTypes: {
    |     ...controlledPropTypes,
    |     ...defaultUncontrolledPropTypes,
    |   },

Since create-react-app uses a strictely defined build-process I have little influence on the features used.
Object spread is supported by the app.

The requested [SO-question](https://stackoverflow.com/questions/46111073/importing-drawingmanager-from-tomchentw-react-google-maps-fails-for-create-react).

Example: https://github.com/sdwio/react-google-maps-test

**Comment by sdwio** [comment]
`import DrawingManager from "react-google-maps/**src**/lib/drawing/DrawingManager";` will fail
`import DrawingManager from "react-google-maps/lib/drawing/DrawingManager";` is working just fine

**Comment by sdwio** [comment]
Careful here: WebStorm proposes the import from `src` and directly from react-google-maps. Both options will fail. The correct import is **not** proposed by WebStorm.

**Comment by maluramichael** [comment]
Thank you @sdwio good workaround.
@tomchentw what do you think? Is this workaround ok or could this be fixed in the code for everyone?
