### ISSUE TITLE
Error in installing 

### ISSUE THREAD

**Issue by ControlAdad** [tomchentw/react-google-maps#599]
Hello

While I try to install react-google-maps, using this command :

`npm install -g react-google-maps@next`

I receive this error :

`npm WARN react-google-maps@7.1.0 requires a peer of react@^15.5.4 but none was installed.`

And finally it doesn't install. I am using React version :     "react": "^15.6.1",

**Comment by tomchentw** [comment]
Please try v8.0.0
https://github.com/tomchentw/react-google-maps/blob/master/CHANGELOG.md#change-log
