### ISSUE TITLE
How to implement Address search ?

### ISSUE THREAD

**Issue by ShunmugamAiyappan** [tomchentw/react-google-maps#601]

**Comment by edgareler** [comment]
@ShunmugamAiyappan check this lib: https://github.com/kenny-hibino/react-places-autocomplete

**Comment by ShunmugamAiyappan** [comment]
My question is How to implement auto-complete address search using react-google-maps

**Comment by tomchentw** [comment]
Could you try the new `places/SearchBox` component in v8.0.0? It's possible now in v8.0.0
Dos here: https://tomchentw.github.io/react-google-maps/#!/SearchBox

**Comment by ShunmugamAiyappan** [comment]
Thanks

**Comment by tomchentw** [comment]
Release [v8.2.0](https://github.com/tomchentw/react-google-maps/releases/tag/v8.2.0)
StandaloneSearchBox: https://tomchentw.github.io/react-google-maps/#standalonesearchbox
