### ISSUE TITLE
Multiple InfoBox trigger fitBounds() when map dragged or zoomed

### ISSUE THREAD

**Issue by stelro** [tomchentw/react-google-maps#609]
hello, I updated today to react-google-mas v8.0.0 and I replace my markersWithLabel with InfoBox, but I noticed that when i am dragging the map ( moving ) or zoomed it, its seemes that the map bounds are changed. This happens only with InfoBox. Is it possible to prevent this event?

**Comment by stelro** [comment]
Correction: it seems that the map tries to fit the labels inside the viewport, and thus its change the map bounds. Is there any way to prevent this behavior?

**Comment by tomchentw** [comment]
@stelro this might be the implementation issue of `InfoBox`, could you check on their project site?
https://github.com/lucasfs7/google-maps-infobox-module

If you find any suspicious implementation in the `addons/InfoBox` component, feel free to re-open this issue:
https://github.com/tomchentw/react-google-maps/blob/95269d2d9c190995ce302015c4ae57aaeebdffb2/src/components/addons/InfoBox.jsx

**Comment by stelro** [comment]
Ok I just post here the solution to disable fitBounds event .
```
<InfoBox
              options={{ closeBoxURL: '',
                enableEventPropagation: true,
                pixelOffset: new google.maps.Size(-40, -36),
                pane: 'mapPane',
                infoBoxClearance: new google.maps.Size(-6, -6),
                disableAutoPan: true,
              }}
       >
    ....
</Infobox>
```
Just set disableAutoPan option to true.
