### ISSUE TITLE
Addon imports on documentation should be named imports

### ISSUE THREAD

**Issue by valstu** [tomchentw/react-google-maps#610]
## Description
We just updated to version 8.0.0 and followed the docs to create clusters on a map with `<MarkerClusterer />`. You will get the following error on console:
```
Warning: React.createElement: type is invalid -- expected a string (for built-in components) 
or a class/function (for composite components) but got: undefined. 
You likely forgot to export your component from the file it's defined in.
```
## Solution
In documentation example you're importing <MarkerClusterer /> as "default import". It should be named import. MarkerClusterer is named export as you can see from line 17. https://github.com/tomchentw/react-google-maps/blob/master/src/components/addons/MarkerClusterer.jsx#L17 

InfoBox documentation has the same thing. It should be named import.

## How to reproduce
Here's a link to CodeSandbox

[![Edit 21q35lr49n](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/21q35lr49n)

Open the link, open console and run. You will get the error mentioned above. Change line 8 on Map.js to named import `import { InfoBox } from "react-google-maps/lib/components/addons/InfoBox";`
and everything works as intended.

**Comment by tomchentw** [comment]
Released [v8.1.0](https://github.com/tomchentw/react-google-maps/releases/tag/v8.1.0)
