### ISSUE TITLE
integrate in angularJS

### ISSUE THREAD

**Issue by ioana-m** [tomchentw/react-google-maps#617]
Hello,

I am using angular-google-map(https://github.com/angular-ui/angular-google-maps) in my angular project (angularjs 1.4). And because I have many markers and clusters on the map it has started to work really slow. 
Can I use this react component in my angular project. And if yes then how, can me please point me in the right direction with some tips, useful links and examples if you have any.

Thank you.

**Comment by tomchentw** [comment]
Sorry, haven't use Angular for a while, but I think it's definitely possible. Please post this in StackOverflow, thanks!
