### ISSUE TITLE
Is it possible to use SearchBox Alone to implement autocomplete 

### ISSUE THREAD

**Issue by ShunmugamAiyappan** [tomchentw/react-google-maps#618]
The sample works fine when I remove GoogleMap Tag and using search box alone, this is not workin, I know I am doing wrong , Still I need to put my questions here to get an understanding . From Google API service we have AutoComplete Search Box without loading a MAP . Does this could be achieved here. 

<GoogleMap ref={props.onMapMounted} defaultZoom={15} center={props.center} onBoundsChanged={props.onBoundsChanged}>
    <SearchBox ref={props.onSearchBoxMounted} bounds={props.bounds} controlPosition={google.maps.ControlPosition.TOP_LEFT} onPlacesChanged={props.onPlacesChanged}>
        <input type="text" placeholder="Customized your placeholder" style={{ boxSizing: `border-box`, border: `1px solid transparent`, width: `240px`, height: `32px`, marginTop: `27px`, padding: `0 12px`, borderRadius: `3px`, boxShadow: `0 2px 6px rgba(0, 0, 0, 0.3)`, fontSize: `14px`, outline: `none`, textOverflow: `ellipses`, }} />
    </SearchBox>
    {props.markers.map((marker, index) =>
    <Marker key={index} position={marker.position} /> )}
</GoogleMap>

**Comment by tomchentw** [comment]
Please post your sample code

**Comment by tomchentw** [comment]
Release [v8.2.0](https://github.com/tomchentw/react-google-maps/releases/tag/v8.2.0)
StandaloneSearchBox: https://tomchentw.github.io/react-google-maps/#standalonesearchbox
