### ISSUE TITLE
Is there a way to disable dragging? 

### ISSUE THREAD

**Issue by ummahusla** [tomchentw/react-google-maps#626]
I wonder if there is an option to disable dragging/movement and turning the Google Map is some kind of the static map

**Comment by ummahusla** [comment]
Ah! I just found that it can be easily achieved  passing `draggable: false` to `defaultOptions` 😅

**Comment by MustafaHossaini** [comment]
draggable is now deprecated. you can see `gestureHandling` property on the options and set it to `none`


https://developers.google.com/maps/documentation/javascript/reference/map#MapOptions.draggable

**Comment by leszekkrol** [comment]
Fixed in PR: https://github.com/Knokd/knokd-web/pull/2085
