### ISSUE TITLE
Change Routes on DirectionsRenderer

### ISSUE THREAD

**Issue by nathanqueija** [tomchentw/react-google-maps#628]
Hi,
I would like to have a list of possible destinations and depending what destination user clicked the route would change accordind to curren destination.
The best solutons for this is to pass the origin and destination as props to MapWithADirectionsRenderer (like the example on docs) ? Or is it possible to change routes inside the component with DirectionsService?
Thanks!

**Comment by tomchentw** [comment]
> The best solutons for this is to pass the origin and destination as props to MapWithADirectionsRenderer

Yes

> Or is it possible to change routes inside the component with DirectionsService?

You can try and let me know.

**Comment by nathanqueija** [comment]
Hey, @tomchentw 
I passed origin and destination as props and it worked.
Thanks!

**Comment by ejswenson15** [comment]
Hey how did you pass origin and destination to the directions renderer?

**Comment by tomchentw** [comment]
using props……

**Comment by swetha2** [comment]
Hey how can i change styles of path line in DirectionsRenderer component?
