### ISSUE TITLE
Breaking changes going to v8.3.0?

### ISSUE THREAD

**Issue by quachsimon** [tomchentw/react-google-maps#633]
I am currently running v7.3.0 and noticed that v8.3.0 is released. I could not find any docs on updating to the latest version.

Are there any breaking changes or can I easily update to v8.3.0?

Are the docs that are available now compatible with v7.3.0? I noticed there were a few differences from a quick glance i.e. the `compose` wrapper

**Comment by tomchentw** [comment]
> https://github.com/tomchentw/react-google-maps/blob/7cb9194877594c0205193c9fe222554affb5564d/README.md#changelog

## Changelog

The changelog is automatically generated via [standard-version][standard-version] and [can be found in project root](https://github.com/tomchentw/react-google-maps/blob/master/CHANGELOG.md) as well as npm tarball.

**Comment by tomchentw** [comment]
> the compose wrapper
Which is the consumer code, it has nothing to do with the liv\brary itself
