### ISSUE TITLE
Click events on custom overlay still going through to map points of interest underneath

### ISSUE THREAD

**Issue by jamesjsewell** [tomchentw/react-google-maps#634]
I still want to be able to click on POI too but they interfere with buttons in my OverlayView component. I've been researching all over the web and can't find a good solution. I was wondering if anyone here has a solution.

**Comment by jamesjsewell** [comment]
I opted for the InfoWindow instead, I'm not sure what is going on with the OverlayView component, at least in my use case, it is not registering as even being there in relation to the mouse cursor

**Comment by jamesjsewell** [comment]
I think I will

**Comment by jamesjsewell** [comment]
I think I will use an InfoBox with these settings options={{ closeBoxURL: ``, enableEventPropagation: false }}

**Comment by amangeot** [comment]
Hello @jamesjsewell I have the same issues with OverlayView, did you manage to have your own display with InfoWindow or do you have to go with the default close button and fancy margins?
