### ISSUE TITLE
GoogleMap's prop zoom can not be a floating number

### ISSUE THREAD

**Issue by Skyd1400** [tomchentw/react-google-maps#635]
So, while setting up my map, I got this weird bug. I'not sure if it is in your code or the google map api, but when I try to set the zoom to a floating number like 10.75, the map froze. It won't refresh, and all it will do is send a bunch of network calls to a GetVIewport Something service. Setting it to a natural number and it works fine again.

**Comment by tomchentw** [comment]
Not related to `react-google-maps`. It should be Google Maps JavaScript API issue.
