### ISSUE TITLE
"fitBounds" doesn't work as expected

### ISSUE THREAD

**Issue by sergeykaikin** [tomchentw/react-google-maps#641]
The function behaves very strange (read wrong) when passing equal "nw" and "se" properties in "bounds" argument.
```
fitBounds({
    nw: {
        lat: -51.764504,
        lng: -71.215984
    }
    se: {
        lat: -51.764504,
        lng: -71.215984
    }
}, {
    width: 200,
    height: 200
});
```
I get center as some random coordinate:
```
{
    lat: -51.76450399999998,
    lng: 108.78401600000001
}
```
whereas I would expect to get:
```
{
    lat: -51.764504,
    lng: -71.215984
}
```
and zoom is something funny -1. Shouldn't we make it min = 1?

**Comment by tomchentw** [comment]
@sergeykaikin I'm getting this in the console:

```
js?v=3.exp&libraries=geometry,drawing,places:50 Uncaught Vb {message: "not a LatLngBounds or LatLngBoundsLiteral: unknown property nw", name: "InvalidValueError", stack: "Error↵    at new Vb (https://maps.googleapis.com/m…act-google-maps/build/bundle.152ffada.js:32228:9)"}
```

**maybe** you're using it wrong:
https://developers.google.com/maps/documentation/javascript/3.exp/reference#LatLngBoundsLiteral

**Comment by sergeykaikin** [comment]
Try it again. I was missing a comma ;)

**Comment by sergeykaikin** [comment]
Sorry, my fault!

**Comment by alanhogan** [comment]
@sergeykaikin numbers in JavaScript will do this because they have only a certain amount of precision. If this doesn't make sense, you may want to read more about numbers in JavaScript.

**Comment by vTrip** [comment]
I am getting `fitBounds is not a function` error. Any thoughts? Accessing via `this.refs.refsName.fitBounds()`
