### ISSUE TITLE
React 15.5.4 peerDependencies

### ISSUE THREAD

**Issue by fibo** [tomchentw/react-google-maps#642]
Hi,

is it possible to update module and require React 16.x or at least React 15.x ?

**Comment by tomchentw** [comment]
What do you mean? I'm not sure I get it.

We're currently on:

https://github.com/tomchentw/react-google-maps/blob/4a41c5d306709d283235dd6f50f80e6ded5227d4/package.json#L123-L125

**Comment by tomchentw** [comment]
React 16 is in #640

**Comment by fibo** [comment]
Is it possible to set `"react": "15.x"` or even 16?

**Comment by tomchentw** [comment]
Released [v8.3.4](https://github.com/tomchentw/react-google-maps/releases/tag/v8.3.4)

**Comment by fibo** [comment]
Thanks, I confirm that in my current project I have React v15.5.4 and installing latest react-google-maps version I have no peer dependency warning at all.
