### ISSUE TITLE
google.maps.SymbolPath

### ISSUE THREAD

**Issue by guyiluz** [tomchentw/react-google-maps#652]
I'm `getting 'google' is not defined  no-undef `error  when i use this:

```
 icon: {
                                  path: google.maps.SymbolPath.FORWARD_CLOSED_ARROW,
                                  strokeColor: "red",
                                  scale: 3
                              }
```

can i access the .

> SymbolPath

 using  react-google-maps?

Tnx

**Comment by sandalsoft** [comment]
@guyiluz  Did you find  a solution for this?

**Comment by guyi0** [comment]
Yes,
 You need to add `/*global google*/` at top on map component

**Comment by sandalsoft** [comment]
@guyi0 Worked like a charm, thanks!

**Comment by tomchentw** [comment]
You can add to docs with a pull request

**Comment by mishacucicea** [comment]
> global google*

Can you detail a bit where this should be put? getting not defined
