### ISSUE TITLE
GroundOverlay doesn't change the image when component updates and the url in redux state updates 

### ISSUE THREAD

**Issue by bansalrachita** [tomchentw/react-google-maps#655]
render() {
        const {bounds, imgSrc} = this.props;
        const boundsObj = new google.maps.LatLngBounds(
            new google.maps.LatLng(bounds.south, bounds.west),
            new google.maps.LatLng(bounds.north, bounds.east));

        return (<GroundOverlay
            url={imgSrc}
            bounds={boundsObj}
            defaultOpacity={.6}/>);
    }

I can't seem to find a way to update the ground overlay image. The component doesn't remount but the its' receiving new props from the redux state. Have been struggling with this for a while, would be great if anyone has a quick resolution. Thanks!

**Comment by tomchentw** [comment]
Yeah, this was introduced by #624

**Comment by tomchentw** [comment]
Released [v9.0.1](https://github.com/tomchentw/react-google-maps/releases/tag/v9.0.1)

**Comment by bansalrachita** [comment]
Thanks for the fix! I could re-render it by re-mounting the component using the react key prop as a hack.
