### ISSUE TITLE
Search box doesn't work

### ISSUE THREAD

**Issue by Epichris360** [tomchentw/react-google-maps#656]
Hey guys, when i try to use the code for the search box from the docs(exactly as it is in the docs), i get an error saying 
"Uncaught Error: Expected subtree parent to be a mounted class component. This error is likely caused by a bug in React. Please file an issue."

Does anyone have any ideas as to how to solve this?

**Comment by Michael-Brooks** [comment]
If you're using React version 16 then it currently doesn't work https://github.com/tomchentw/react-google-maps/issues/640

**Comment by Epichris360** [comment]
i probably am, it's a small project i started a couple of days ago. Guess i'll just wait till the next update. Thanks Micheal Brooks

**Comment by niiapa** [comment]
Any update on this? :o

**Comment by tomchentw** [comment]
Released [v9.1.0](https://github.com/tomchentw/react-google-maps/releases/tag/v9.1.0)

**Comment by Littlewiz123** [comment]
I'm having the same issue with my project, and it using react version 17.0.1; Is there any solution for this bug? Please help me with this problem.

**Comment by JustFly1984** [comment]
@Littlewiz123 The repo of this project is unmaintained more than 3 years, and we had build new version https://www.npmjs.com/package/@react-google-maps/api

We had rewrite it to TypeScript, and updating it frequently: https://github.com/JustFly1984/react-google-maps-api/tree/master/packages/react-google-maps-api
You can enjoy autocomplete.

You can see our docs: https://react-google-maps-api-docs.netlify.app

Also a lot of examples: https://react-google-maps-api-gatsby-demo.netlify.app/ https://github.com/JustFly1984/react-google-maps-api/tree/master/packages/react-google-maps-api-gatsby-example/src/examples

The bundle size is much smaller: https://bundlephobia.com/result?p=@react-google-maps/api

Our Spectrum community: https://spectrum.chat/react-google-maps Our Slack channel: https://join.slack.com/t/react-google-maps-api/shared_invite/enQtODc5ODU1NTY5MzQ4LTBiNTYzZmY1YmVjYzJhZThkMGU0YzUwZjJkNGJmYjk4YjQyYjZhMDk2YThlZGEzNDc0M2RhNjBmMWE4ZTJiMjQ

Enjoy!
