### ISSUE TITLE
Spelling mistake for the constant FLOAT_PANE of the OverlayView component

### ISSUE THREAD

**Issue by Paul-DS** [tomchentw/react-google-maps#658]
Hi,

First, thank you for this great component !

It seems that a spelling mistake has been introduced in the commit 8c66c14.

The constant `FLOAT_PANE` is now named `LOAT_PANE` (src/macros/OverlayView.jsx line 28).

**Comment by tomchentw** [comment]
Thanks! Released [v8.4.1](https://github.com/tomchentw/react-google-maps/releases/tag/v8.4.1)
