### ISSUE TITLE
Incompatible with recompose@0.26.0

### ISSUE THREAD

**Issue by hsz** [tomchentw/react-google-maps#659]
`recompose` package has been updated to `0.26.0` - with updated library I get:

```
withGoogleMap.js:71 Uncaught TypeError: (0 , _recompose.createEagerFactory) is not a function
    at withGoogleMap (withGoogleMap.js:71)
```

With above update, they have removed `createEagerElement` and `createEagerFactory` methods.

Ref: https://github.com/acdlite/recompose/commit/c830f184123eebc8ea6b8b712840fdc86a680fa2

**Comment by tomchentw** [comment]
@hsz got it. It's interesting, since `recompose` is listed under `dependencies` as `^0.25.0`, which shouldn't be able to be upgraded to `0.26.0`

**Comment by hsz** [comment]
@tomchentw My project also uses `recompose` and updated it manually to `0.26.0` - that's why `react-google-maps` inherited it and we have a conflict.

**Comment by tomchentw** [comment]
Got it. Fixing it now

**Comment by tomchentw** [comment]
Released [v8.4.2](https://github.com/tomchentw/react-google-maps/releases/tag/v8.4.2)

**Comment by roybigapps** [comment]
I still getting this error on production server

**Comment by tomchentw** [comment]
@roybigapps could you elaborate which `react-google-maps` version you're using?
