### ISSUE TITLE
Support Places API

### ISSUE THREAD

**Issue by idolize** [tomchentw/react-google-maps#66]
Support for the [Google Maps Places Autocomplete and SearchBox widgets](https://developers.google.com/maps/documentation/javascript/places-autocomplete) would be great, as it would provide an easy way to search for locations on the map (a common use case).

----

In order to make it work, I think we would have to do the following:

- Wrap the `google.maps.places.SearchBox` and `google.maps.places.Autocomplete` classes with `SimpleChildComponent`
    - These classes require an input DOM node in their constructor (ex: `var searchBox = new google.maps.places.SearchBox(inputNode)`), which we could construct on the fly before mount and remove on unmount
        - It may also be possible to pass in a React virtual DOM node instead (maybe using `React.findDOMNode` or `dangerouslySetInnerHtml`?) but that would be trickier
    - Expose the `places_changed` event on the `SearchBox` and `Autocomplete` components as `onPlacesChanged`
    - Expose the `setBounds(LatLngBounds)` method of `SearchBox`/`Autocomplete` via the `props`

This should allow for something like:

```js
// Updates the bounds of the map to the current search results
// and biases the search results to the current map location
class PlacesMap extends React.Component {
  getInitialState() {
    return { bounds: new google.maps.LatLngBounds() };
  }
  _set_bounds_(bounds) {
    this.setState({ bounds });
  }
  _places_changed_() {
    let places = this.refs.search.getPlaces();
    if (places.length == 0) return;
    let bounds = new google.maps.LatLngBounds();
    for (let i = 0; i < places.length; i++) {
      bounds.extend(places[i].geometry.location);
    }
    this._set_bounds_(bounds);
  }
  render () {
    const {props, state} = this,
          {googleMapsApi, ...otherProps} = props;
    return (
      <GoogleMaps containerProps={{
          ...otherProps,
          style: {
            height: "100%",
          },
        }}
        onBoundsChanged={this._set_bounds_}
        ref="map"
        googleMapsApi={google.maps}
        zoom={8}
        center={{lat: -34.397, lng: 150.644}}>
            <SearchBox ref="search" bounds={state.bounds} onPlacesChanged={this._places_changed_}>
      </GoogleMaps>
    );
  }
}
```

Thoughts?

**Comment by tomchentw** [comment]
Very reasonable. Maybe put them under `/src/places` folder and require them like `require('react-google-maps/places/AutoComplete')

**Comment by idolize** [comment]
Personally I'm not a big fan of `require`ing files in subdirectories, because then you can't use ES6 import destructuring very well (plus it's less obvious without documentation that these files aren't internal and can be `required` directly).

**Comment by tomchentw** [comment]
Proper documentations would be needed. `require`ing in subdirectories will overall reduce the bundle size and I think it's a good fit for a medium-sized library.

**Comment by tomchentw** [comment]
I took a day to rewrite the module from scratch on #88 . It will be great if you could take a look at it. Thanks!

**Comment by pjnovas** [comment]
oh :hankey: ! what an awesome work guys!, +1 to the Places API :+1:

**Comment by tomchentw** [comment]
Does anyone interest in working on this?

**Comment by pjnovas** [comment]
hey there, I'm just starting with React so I'm not confident to code in your library yet but after some research I have found the Autocomplete implementation as a react component which I'm pretty sure could be to just required inside this library: https://github.com/ubilabs/react-geosuggest.

Hope it helps! :dancers:

**Comment by idolize** [comment]
@pjnovas Yep, I found that too and was too lazy to implement this PR myself as a result (sorry @tomchentw) :laughing:

**Comment by tomchentw** [comment]
Thanks! That's pretty awesome. Consider adding this section to the docs ...

**Comment by tomchentw** [comment]
`SearchBox` has been done in #110 .

**Comment by Victordmdb** [comment]
+1 on the Autocomplete, it has the very useful `autocomplete.setTypes(types);` to only display certain types of locations.

**Comment by tomchentw** [comment]
Feel free to submit a PR. Close for now

We're also looking for maintainers. Involve in #266 to help strengthen our community!
