### ISSUE TITLE
8.5.0 requires a peer of react@^15.0.0

### ISSUE THREAD

**Issue by erickvica** [tomchentw/react-google-maps#663]
Getting this error using  "react-dom": "^16.0.0"
(react-google-maps@8.5.0 requires a peer of react-dom@^15.0.0 but none is installed. You must install peer dependencies yourself.)

**Comment by tomchentw** [comment]
Currently, there're some issues with React 16. See #640

**Comment by Northshoot** [comment]
This is half year later, any update?
