### ISSUE TITLE
Multiple Waypoints

### ISSUE THREAD

**Issue by jm-mwi** [tomchentw/react-google-maps#664]
I asked on StackOverflow, but is it possible to have multiple waypoints for a route? Google Maps will optimize a route with up to 23 waypoints, but I'm not able to find if this library supports it?

https://stackoverflow.com/questions/46696324/multiple-waypoints-with-react-google-maps

**Comment by tomchentw** [comment]
It's simply a wrapper around `DirectionsRenderer`. Anything you can do with native `google.maps.DirectionsRenderer` can be done. Please figure it out yourself.
