### ISSUE TITLE
GoogleMap component become brown section when come to other routes and then go back .

### ISSUE THREAD

**Issue by caoduy1293** [tomchentw/react-google-maps#665]
![react map error](https://user-images.githubusercontent.com/28828834/31535820-b0fc2e32-b026-11e7-95ce-2f2ac5df8481.png)

GoogleMap component become brown section when come to other routes and then go back .
I dont know cause my code or your component or I missing something. Have you used your component with react router ?

**Comment by tomchentw** [comment]
Hey, I just created a demo app here:
https://tomchentw.github.io/

You can try
1. clicking on `react-google-maps` item in the list
2. clicking on the header to goback
3. repeat 1-2 to see it's still working

The source code is located here:
https://github.com/tomchentw/tomchentw.github.io/blob/master/src/Pages/Demos/ReactGoogleMaps.jsx

Here's the recording:

![2iek2bn4mx](https://user-images.githubusercontent.com/922234/31574361-1a7481ee-b094-11e7-8ba1-892865c14e38.gif)

**Comment by caoduy1293** [comment]
Thanks so much for your support :) I figured out because of my webpack not cause of your component. But when I used SearchBox component it will be got an error if I use React ver 16 . Hope you can solve it soon. Thanks for your contribution .

**Comment by tomchentw** [comment]
React 16 is in #640
