### ISSUE TITLE
Polyline change event

### ISSUE THREAD

**Issue by sbienia** [tomchentw/react-google-maps#666]
Hello,

Is any way to listen polyline change event or read path from reference?

I have `<Polyline path={path} options={{editable:true}}/>` but I don't know how to read polyline path after edit.

**Comment by tomchentw** [comment]
I'm afraid that's not possible given the current `react-google-maps` architecture. PRs welcomed.

**Comment by sbienia** [comment]
@tomchentw thanks for response. Unfortunately I'm beginning works with javascript and react and I don't have skills to update library. Do you see any option to read edited path using api or maybe hacks?
