### ISSUE TITLE
infowindow text below bubble for a split second

### ISSUE THREAD

**Issue by wowzaaa** [tomchentw/react-google-maps#670]
Hey

I have a problem with the InfoWindow component ... it does not have long content but for some reason ... after i open the second time ... the text actually appears like in a very thin column below the bubble ... this happens for a fraction of a second

i think it is related to this #444

**Comment by tomchentw** [comment]
@wowzaaa  Could you provide a minimal reproducible repository?

**Comment by wowzaaa** [comment]
would it be ok if i share code for that component?

**Comment by wowzaaa** [comment]
here is the flicker in action

https://streetpin-dev.herokuapp.com/

**Comment by tomchentw** [comment]
@wowzaaa I see. I suspect that might be due to `MarkerClusterer > Marker > InfoWindow`. I'll look into this and see what I can do.

**Comment by wowzaaa** [comment]
thanks ... is there anything i can try?

**Comment by tomchentw** [comment]
You can try add an example here in the markdown, so that contributors have a place to try
https://tomchentw.github.io/react-google-maps/#markerclusterer

**Comment by tomchentw** [comment]
@wowzaaa I may have spotted the issue, can you try the latest version?

**Comment by tomchentw** [comment]
Released [v9.2.1](https://github.com/tomchentw/react-google-maps/releases/tag/v9.2.1)

**Comment by wowzaaa** [comment]
sry ... the same :( ... one detail ... the first time it opens it does not have the glitch ... it is only after i opened it the second time

**Comment by tomchentw** [comment]
Could you try add an example here in the markdown and create a PR? It's simple, just using some mock data points in the markdown file. @wowzaaa
