### ISSUE TITLE
How to use Autocomplete and other components from Google Maps v3?

### ISSUE THREAD

**Issue by JarLowrey** [tomchentw/react-google-maps#672]
[I asked this question on SO](https://stackoverflow.com/questions/46780770/utilizing-google-maps-in-other-components-through-withscriptjs-withgooglemap) which hasn't gotten much traction, hopefully someone here can help out. 

I have my map setup, and want to include google autocomplete (maybe setup via [react-places-autocomplete](react-places-autocomplete), but willing to change if something is easier). When I use withScriptjs and/or withGoogleMap to async load my `react-google-maps` this component, PlacesAutocomplete cannot initialize as it does not see Google Maps v3 as loaded. 

Below is how I am trying to render these components:

```js
         render(){
            return (<div>
                <PlacesAutocomplete inputProps={autocompleteProps} />
                <GoogleMapsWrapper ...
            </div>);
         }
```

And my GoogleMapsWrapper:

```js
    import React from 'react';
    import { GoogleMap,withGoogleMap,withScriptjs } from 'react-google-maps';
    
    // https://github.com/tomchentw/react-google-maps/issues/636#issuecomment-333732995
    
    const GoogleMapsWrapper = withScriptjs(withGoogleMap(props => {
      return <GoogleMap {...props} ref={props.onMapMounted}>{props.children}</GoogleMap>
    }));
    
    export default GoogleMapsWrapper;
````

And the errors.

    Uncaught Error: Google Maps JavaScript API library must be loaded. See: https://github.com/kenny-hibino/react-places-autocomplete#load-google-library

**Comment by tomchentw** [comment]
If `PlacesAutocomplete` requires `google` as global variable, it **should** be wrapped inside the component decorated by  `withScriptjs`. You can think like this:
**whenever this function `props => { return <GoogleMap }` is rendered, the _google_ global variable is ready**

You can of course use any means you want to load google maps JS API. `withScriptjs` is just one of the way of doing it.

**Comment by JarLowrey** [comment]
Something like this? I'm using an input here instead of the package to make it more general. Will this load Google twice if it's placed next to a google map component?


```
export default class AutocompleteComponent extends React.Component {

    initAutocomplete(map){
        this.autocomplete = new google.maps.places.Autocomplete(this._input);
    }

    render() {
        const MyComponent = withScriptjs(
            (props) => {
                return (
                    <input ref={(c) => {this.initAutocomplete} }  />
                );
            }
        );

        return (
            <div>
                <MyComponent
                    googleMapURL="https://maps.googleapis.com/maps/api/js?key=____&libraries=geometry,drawing,places"
                    loadingElement={<div style={{ height: `100%` }} />}
                    ref={this.initAutocomplete}
                />
            </div>
        );
    }
}
```

**Comment by tomchentw** [comment]
You're using it in the wrong way, please read the source code and understand what's going on under the hood. There's nothing I can help for now
