### ISSUE TITLE
How to get all markers in the current bounds?

### ISSUE THREAD

**Issue by pavitran** [tomchentw/react-google-maps#673]
I'm trying to get all the markers when MarkerCluster is clicked, how can I achieve this?

**Comment by tomchentw** [comment]
There's a function in `MarkerClusterer#getMarkers()` but we haven't implement it. PRs welcomed

https://github.com/mahnunchik/markerclustererplus/blob/master/docs/reference.html#L80

**Comment by tomchentw** [comment]
Released [v9.0.3](https://github.com/tomchentw/react-google-maps/releases/tag/v9.0.3)

**Comment by tomchentw** [comment]
@pavitran it turns out we don't need to implement the method because it doesn't make any sense. See the docs for usage:
https://tomchentw.github.io/react-google-maps/#markerclusterer
