### ISSUE TITLE
how to custom marker in DirectionsRenderer 

### ISSUE THREAD

**Issue by bossbossk20** [tomchentw/react-google-maps#674]
#### I need help 

can you guide me

how to custom each marker in DirectionsRenderer

Thank you

**Comment by tomchentw** [comment]
Check the options. If it doesn't help, it's Google's problem.
https://developers.google.com/maps/documentation/javascript/reference?hl=zh-tw#DirectionsRendererOptions

**Comment by bossbossk20** [comment]
Actually, I'm done 
I really like your google map. it helps me create map easier. 
 Thank you.  @tomchentw

**Comment by brigitmerito** [comment]
> Actually, I'm done
> I really like your google map. it helps me create map easier.
> Thank you. @tomchentw

can u explain in brief how u did that ?
