### ISSUE TITLE
Docs - missing import statement

### ISSUE THREAD

**Issue by the-noob** [tomchentw/react-google-maps#675]
*Might* be an improvement, the [SearchBox](https://github.com/tomchentw/react-google-maps/blob/master/src/components/places/SearchBox.md) example is using  `lodash` but the import statement is missing.
```JavaScript
const nextCenter = _.get(nextMarkers, '0.position', this.state.center);
```
Other examples seem to work 'out of the box'.

**Comment by tomchentw** [comment]
Good to know, thanks!
