### ISSUE TITLE
Re-render map after changing state

### ISSUE THREAD

**Issue by ForeverYouth** [tomchentw/react-google-maps#676]
I Have 1 task and 1 problem. 
My task is: adding markers by the event(for example - click on map). 
My problem - after every adding point position marker re-render component GoogleMap. 
And map has flicker effect if i use statefull component or HOC. 
I've tried use recompose as you advice. Good library. But a marker is added to the state but the marker is not added to the map. Give some advice for resolve this problem.

**Comment by tomchentw** [comment]
Please try to post your problem in a minimal way in here:
https://www.webpackbin.com/

or no one will help.
