### ISSUE TITLE
Cluster overlayview marker or custom marker

### ISSUE THREAD

**Issue by HERRKIN** [tomchentw/react-google-maps#678]
hello
I have been looking for days on the web on how to make a custom marker which fits my needs, that being I needed to shape the pin the way that I wanted and also put some icons if I wanted, so I didn't find a way to do it by using the Marker component but I also noticed I could use overlayView component for that and I did it.
the problem is that I need to cluster the markers and I see that my customMarkers based on overlayView never hides when clustering, it seems that clusters don't apply to overlayViews
![problem](https://files.gitter.im/tomchentw/react-google-maps/8D4x/FireShot-Capture-140---Yu-Track---http___localhost_3000_dashboard_maps.png)
is there a way to make the cluster work with overlayview?
or to make the marker work like the one I described?

**Comment by tomchentw** [comment]
> is there a way to make the cluster work with overlayview?

Read its source. I don't know: https://github.com/mahnunchik/markerclustererplus

> make the marker work like the one I described?

`<Marker>` has a `icon` props:
https://tomchentw.github.io/react-google-maps/#marker
