### ISSUE TITLE
Marker cluster taking 2 mins to re render 1000 markers

### ISSUE THREAD

**Issue by Shubham-Sinha** [tomchentw/react-google-maps#679]
Is there a way to cluster maps after markers have been rendered ? I can't find any props for doing that.

**Comment by tomchentw** [comment]
I'm not sure what you mean. Your title and description are talking about two different things.

> Is there a way to cluster maps after markers have been rendered ?

Just re-render a map with it's contents is `<MarkerClusterer>` instead of `<Marker>`.

If you still don't know, please provide a minimal repository to describe what you want to do.

**Comment by Shubham-Sinha** [comment]
I'm doing the same. But while re-rendering it's taking a lot of time. I remove the MarkerClustered and the delay in showing the markers reduces drastically. I took a snapshot to check what's taking so much time, and it was ``markerClusterer.js`` 
![snapshot](https://i.imgur.com/CiMzWyb.png)

**Comment by tomchentw** [comment]
There's nothing I can help. It's inside the implementation of `markerClusterer.js`, which is https://github.com/mahnunchik/markerclustererplus

Again, `react-google-maps` is simply a wrapper around these APIs. I **really** cannot do anything for these issues.

**Comment by Shubham-Sinha** [comment]
Okay. I'll look into this repo. Last update was 3 years ago. :(
