### ISSUE TITLE
InfoBox rerender when hover on marker (when state changes)

### ISSUE THREAD

**Issue by exoslav** [tomchentw/react-google-maps#682]
Hello guys, I just migrated form react-google-maps version 7.3.0 to 9.2.0. I am experiencing problematic behavior after migration (this problem seems to started to appear in 8.0.0 when infoBox component was rewritten to pureComponent). I have three markers on my map with custom icon. When I hover on marker, icon changes (state of component is is changed). When I click on the marker, infobox will show relatively to marker. But when infobox is opened and I hover on different marker, infobox disappear for a millisecond and shows again. State changes, because of icon change, but it seems that infobox is re rendered again as well (but did not experienced such behavior in 7.3.0). Does anybody have similar problem?

You can copy paste JS code from this [link](https://liveweave.com/njie5i ) and put it to [demo page](https://tomchentw.github.io/react-google-maps/#infobox), infobox section, to simulate such behaviour. Icons are default google maps icons, but icon changing code is implemented. Tested in Chrome.

**Comment by tomchentw** [comment]
> @exoslav  You can copy paste JS code from this link 

You didn't **save** so that the link doesn't contain maps code

**Comment by exoslav** [comment]
@tomchentw strange, I can see JS code clearly. Posting link again: https://liveweave.com/zbDKQn

**Comment by tomchentw** [comment]
Thanks! May have spotted the issue.

**Comment by tomchentw** [comment]
Released [v9.2.1](https://github.com/tomchentw/react-google-maps/releases/tag/v9.2.1)
