### ISSUE TITLE
How To delete all Polygons in the Map?

### ISSUE THREAD

**Issue by Skullflow** [tomchentw/react-google-maps#685]
Hello,
how can i delete all polygons in my map? Is there some refs or callbacks that i can use?

**Comment by Skullflow** [comment]
I can do something like:

```
let polygon = new google.maps.Polygon({
          paths:[
            {lat:45.48,lng: 9.16},
            {lat:45.48,lng: 9.23},
            {lat:45.44,lng: 9.22},
            {lat:45.44,lng: 9.15}
          ]
        })
        refs.map = ref
        polygon.setMap(refs.map.context.__SECRET_MAP_DO_NOT_USE_OR_YOU_WILL_BE_FIRED)

```

and then i am able to remove polygons doing: polygon.setMap(null)

But is there a better way?

**Comment by tomchentw** [comment]
Just don't render it by controlling react state

**Comment by Skullflow** [comment]
I tryed to render it using react state and the Polygon component and it works. But if im using the DrawerManager and i draw a polygon on the map im not able to control the new polygon drawn. Maybe because the new polygon reference is controlled inside the googlemaps componeny

**Comment by tomchentw** [comment]
@Skullflow DrawerManager internal state is out of this project's scope.
