### ISSUE TITLE
React 16 + SearchBox no longer works with default input?

### ISSUE THREAD

**Issue by JesperWe** [tomchentw/react-google-maps#690]
In earlier versions I was doing:

	<GoogleMap
		defaultZoom={props.defaultZoom}
		defaultCenter={props.defaultCenter}
		center={props.center}
		onBoundsChanged={props.onBoundsChanged}
		ref={props.onMapMounted}
		onClick={props.onMapClick}
		options={props.options}>
		
		<SearchBox
			ref={props.onSearchBoxMounted}
			controlPosition={2}
			onPlacesChanged={props.onPlacesChanged}
			inputPlaceholder={props.t('Search...')}
			inputStyle={INPUT_STYLE}/>
			
		{props.markers.map((marker, index) => (
			<Marker position={marker.position} key={index} draggable={true} onDragEnd={props.onMarkerDragEnd}/>
		))}
	</GoogleMap>

...and this worked fine. Using v9.2.1 + React 16 I get.

```
Uncaught Error: React.Children.only expected to receive a single React element child.
    at invariant (invariant.js:42)
    at Object.onlyChild [as only] (react.development.js:1020)
    at SearchBox.render (SearchBox.js:242)
...
```

Line 242 in the compiled code corresponds to Line 169: `React.Children.only(this.props.children)` and `this.props.children` is undefined here, causing the crash.

Does this mean we now *have* to specify an `<input/>` as a child of `<SearchBox/>` ?

**Comment by tomchentw** [comment]
I'm confused why people don't read the changelog while upgrading from the older version?
https://github.com/tomchentw/react-google-maps/blob/master/CHANGELOG.md#800-2017-09-14

**Comment by JesperWe** [comment]
I guess there is a significant difference between "can now" and "now has to".... :-)

**Comment by tomchentw** [comment]
My apology :(
