### ISSUE TITLE
How to do rezoom and recenter to the polygon?

### ISSUE THREAD

**Issue by ahgan84** [tomchentw/react-google-maps#693]
Hi sir, I'm drawing a polygon in the googlemap and I've save it in my db. Is there  way to do zoom in and recenter everytime after I load the polygon coordinates from my db? Is there a way to autozoom or autocenter? Or I have to get the zoom value and center coordinates to save into my db too and load it everytime?

**Comment by tomchentw** [comment]
Use `zoom` and `center` props instead of `defaultZoom` or `defaultCenter`

**Comment by palakt4f** [comment]
hi @tomchentw 
How can I use [getZoom()](https://stackoverflow.com/a/6385750/7762250) with defaultZoom. and set dynamic value place of a static number.
