### ISSUE TITLE
CustomMarker in DirectionsRenderer component

### ISSUE THREAD

**Issue by dlape** [tomchentw/react-google-maps#694]
Hi, is it possible to customize the marker in this example [https://tomchentw.github.io/react-google-maps/#directionsrenderer](url) this works as expected but it really gives me a hard time changing the marker of this 2 address points?. Thank you in advance!.
![screenshot from 2017-11-07 10-29-53](https://user-images.githubusercontent.com/29973629/32474345-12df4f24-c3a7-11e7-8c2d-cbeb3b9566f2.png)

**Comment by tomchentw** [comment]
Check the official documentation. I'm not an expert
https://developers.google.com/maps/documentation/javascript/reference#DirectionsRenderer
