### ISSUE TITLE
[InfoWindow] React Portals: Invariant Violation Target container is not a DOM element.

### ISSUE THREAD

**Issue by MrSaints** [tomchentw/react-google-maps#696]
We are encountering issues with using `InfoWindow` in tandem with `Marker`. I believe it is related to 6a61f2c4e2c6dc1956b3154fb2ad90795842371b. I've tracked the error on development, and production. I'll try to create a small, replicable example.

**Comment by MrSaints** [comment]
I have a PR opened for this @tomchentw. If you can have a quick look, that'd be great.

**Comment by CarlosLanderas** [comment]
I've tested  @MrSaints pull request and it seems to work fine. If you can integrate the PR would be great. Thanks!

**Comment by tomchentw** [comment]
Released [v9.2.3](https://github.com/tomchentw/react-google-maps/releases/tag/v9.2.3)

**Comment by gondar00** [comment]
Hello, with version `9.4.5` this is breaking -

component code - 
`      <Marker position={location} onClick={this.toggleInfoWindow}>
          <InfoWindow onCloseClick={this.toggleInfoWindow}>
            Hello
          </InfoWindow>
        </Marker>
`

![screen shot 2018-03-25 at 12 24 01 am](https://user-images.githubusercontent.com/12490590/37867786-0aa5dd72-2fc3-11e8-9dd2-3b6a85dda1f3.png)
