### ISSUE TITLE
Unable to change the state of a InfoBox while using it for multiple markers.

### ISSUE THREAD

**Issue by SuryaAcube** [tomchentw/react-google-maps#697]
@tomchentw : I have a question related to InfoBox.If I want to use InfoBox for multiple markers how can I use.
I have created **isOpen :[]** with default values as **false**.I am not able to determine how to change that array value to **true**.
Below is my withStateHandlers :
**withStateHandlers(() => ({
isOpen: _.range(20).map(() => { return false; }),
}),
{
onToggleOpen: ({ isOpen }) => (index) => ({
isOpen: !isOpen,
})
}),**
I am not able to determine how to change to true for a particular index of **isOpen Array**.

I am a newbie to react.

**Comment by tomchentw** [comment]
Sorry, please ask on StackOverflow instead. This is not related to this project.
