### ISSUE TITLE
How to access the map after creation

### ISSUE THREAD

**Issue by CraigglesO** [tomchentw/react-google-maps#700]
No big deal if you guys are busy. I was wondering if there is a way to expose the `<GoogleMap />` object? 

In another google react map module it allows me to access it like this:
```
<GoogleMap
          ...
          onGoogleApiLoaded={({ map }) => drawPolygons(map, center.lat, center.lng)}
        >
</GoogleMap>
```

Couldn't find any way in the docs so....

**Comment by tomchentw** [comment]
Sorry, no. Only react ref:
https://tomchentw.github.io/react-google-maps/#!/SearchBox
