### ISSUE TITLE
Ability to center Marker Icon

### ISSUE THREAD

**Issue by wayofthefuture** [tomchentw/react-google-maps#703]
I've been all through the docs. The Marker component will place a custom icon using the bottom center as the anchor point. The ability to place the icon with the center/center as the anchor point would be nice. From what I've seen this isn't possible. Thanks.

**Comment by tomchentw** [comment]
I'm not sure about that either. Please consult official Google Maps JS API instead.

**Comment by neilyoung** [comment]
@wayofthefuture In case you haven't found it yet: This works:

```
icon: {
        url: 'icon.png',
        scaledSize: { width: 30, height: 30},
        anchor: { x: 15, y: 15 },
      }
```

**Comment by erfoon** [comment]
@wayofthefuture Perfect! Through all docs I searched your help was survivor <3
