### ISSUE TITLE
Marker Moving Animation

### ISSUE THREAD

**Issue by tamal-appsbee** [tomchentw/react-google-maps#705]
How I can implement animation between points
Like this example : http://jsfiddle.net/rcravens/RFHKd/13/

Thanks

**Comment by tomchentw** [comment]
Implement your own `transition` logic with React's state.

**Comment by rodolfopeixoto** [comment]
Tomchentw, Can you help me? I would like to know, how can I get the <Marker component and a setPosition () in the component. Getting from setPosition I believe I can implement the transition, just like the example above.

**Comment by AhmedHassan07** [comment]
@rodolfopeixoto i also need help on this, have you done it?

**Comment by pumpkin-codes** [comment]
+1

**Comment by pumpkin-codes** [comment]
@rodolfopeixoto @tomchentw  +1 if someone done this then please give the example
