### ISSUE TITLE
StandaloneSearchBox does not accept wrapped inputs

### ISSUE THREAD

**Issue by jkettmann** [tomchentw/react-google-maps#708]
[StandaloneSearchBox](https://github.com/tomchentw/react-google-maps/blob/master/src/macros/places/StandaloneSearchBox.jsx#L47) does not create the `google.maps.places.SearchBox` in the same way [SearchBox](https://github.com/tomchentw/react-google-maps/blob/master/src/components/places/SearchBox.jsx#L126) does. As far as I see it `StandaloneSearchBox` accpects the input to be a direct child, `SearchBox` allows it to be wrapped in other elements like divs.

I would propose to adjust the behavior of  `StandaloneSearchBox` to allow wrapped inputs. This would allow for better styling control. I can open a PR if you wish.

**Comment by tomchentw** [comment]
@jkettmann a PR definitely works! Please open!
