### ISSUE TITLE
InfoBox: TypeError GoogleMapsInfoBox is not a constructor

### ISSUE THREAD

**Issue by tuccle22** [tomchentw/react-google-maps#711]
Example of issue: https://tomchentw.github.io/react-google-maps/#infobox

Line of error: https://github.com/tomchentw/react-google-maps/blob/master/src/components/addons/InfoBox.jsx#L110

Thanks!

**Comment by tomchentw** [comment]
Oh wow! This was due to #646 .

**Comment by tomchentw** [comment]
Released [v9.4.1](https://github.com/tomchentw/react-google-maps/releases/tag/v9.4.1)
