### ISSUE TITLE
Fitbounds with lifecycle errors.

### ISSUE THREAD

**Issue by ahgan84** [tomchentw/react-google-maps#713]
Hi guys, in relation to issue #707 , I have try another method which us using the lifecycle but still have errors. Below is my code:

```
const PGoogleMap = compose(
  withProps({
    googleMapURL: `https://maps.googleapis.com/maps/api/js?key=${GOOGLE_MAP_API_KEY}&v=3.exp&libraries=geometry,drawing,places`,
    loadingElement: <div style={{ height: `100%` }} />,
    containerElement: <div style={{ height: `400px` }} />,
    mapElement: <div style={{ height: `100%` }} />
  }),
  withState('isOpen', 'updateIsOpen', null),
  withHandlers({
    onToggleOpen: ({ updateIsOpen }) => key => {
      updateIsOpen(key)
    }
  }),
  lifecycle({
    componentWillMount() {
      const refs = {}

      this.setState({
        setZoom: ref => {
          refs.map = ref
          var bounds = new google.maps.LatLngBounds();
          allMarkers.forEach((p) => {
            var latLng = new google.maps.LatLng(p.lat, p.lng);
            bounds.extend(latLng);
          })
          console.log(bounds)
          refs.map.fitBounds(bounds)
        }
      })
    }
  }),
  withScriptjs,
  withGoogleMap
)((props) =>
  <GoogleMap
    ref = {props.setZoom}
    defaultZoom={18}
    defaultCenter={props.centerFocus}
  >
```

Now the fitbounds function is working fine. The problem is, when I goes other pages, the map keep mounting on the bottom of the  other page which does not contain the map and giving error msg `refs.map is null`. Anyone knows what's wrong?

**Comment by tomchentw** [comment]
It's because React:

> React will call the ref callback with the DOM element when the component mounts, and call it with null when it unmounts.

https://reactjs.org/docs/refs-and-the-dom.html#adding-a-ref-to-a-dom-element

**Comment by ahgan84** [comment]
@tomchentw  Then how do we solve the problem? How do we prevent it to mount the map on the bottom of every page?

**Comment by tomchentw** [comment]
```js
refs.map = ref
if (!ref) { return }
```

**Comment by sureshreddyputta** [comment]
@tomchentw How to prevent onZoomChanged event after using fitBounds in onMapMount function?
