### ISSUE TITLE
Map is empty when I want to print.

### ISSUE THREAD

**Issue by ahgan84** [tomchentw/react-google-maps#718]
Hi guys, I'm using react google maps to show the google maps in my website. When displaying website, the map will show up. But when I want to print on paper, the map won't show up. It is empty... When I use print preview, the map is empty also. Anybody can tell me what's wrong?

**Comment by tomchentw** [comment]
Please search `Google Maps JavaScript API v3` for some related answers.

**Comment by jevy-wangfei** [comment]
> Hi guys, I'm using react google maps to show the google maps in my website. When displaying website, the map will show up. But when I want to print on paper, the map won't show up. It is empty... When I use print preview, the map is empty also. Anybody can tell me what's wrong?

Hi ahgan84, 
I experienced the same issue with you, did you find the solution? 
Thanks

**Comment by JustFly1984** [comment]
@jevy-wangfei @ahgan84 basically map is a canvas element, and OS driver don't have access to WebGL.
The worst part is that this canvas is rendered inside of iframe, which is not accessible from main document.
