### ISSUE TITLE
Marker: onPositionChanged does not provide event

### ISSUE THREAD

**Issue by daniellobrunello** [tomchentw/react-google-maps#723]
The onPositionChanged event does not provide the triggered event.
See [StackOverflow](https://stackoverflow.com/questions/47673588/onpositionchanged-handler-of-gmaps-marker-scope-issue)

```
class FindLocationMarker extends Component {

  onMarkerPositionChange = (event) => {
    let target = event.target; // event is undefined
    this.props.handleMarkerPositionChange(target);
  }

  render() {
    let that = this;
    return (
      <div>
        <Marker
          position={this.props.position}
          draggable
          onPositionChanged={this.onMarkerPositionChange}
        />
      </div>
      )
  }
}
```

**Comment by tomchentw** [comment]
Yes, no args from vanilla.

<img width="903" alt="screen shot 2017-12-07 at 10 20 58 am" src="https://user-images.githubusercontent.com/922234/33695438-59b2c950-db38-11e7-9c6c-d467074b383f.png">

https://developers.google.com/maps/documentation/javascript/3.exp/reference#Marker

You may use `ref` with public methods to get the location.

**Comment by vhuytdt** [comment]
a use ref and call get Postion. but null value :(
![image](https://user-images.githubusercontent.com/18238875/33797996-c519fdf0-dd43-11e7-9046-81484d34dac0.png)

**Comment by tomchentw** [comment]
It's a function. Call it `.lat()`

**Comment by daniellobrunello** [comment]
For everybody whos looking for [a solution](https://stackoverflow.com/questions/47673588/onpositionchanged-handler-of-gmaps-marker-scope-issue/47673751#47673751).

**Comment by tomchentw** [comment]
Thanks @daniellobrunello ! Would you mind open a PR containing the demo code for this feature?
