### ISSUE TITLE
Cannot add components to container element?

### ISSUE THREAD

**Issue by quachsimon** [tomchentw/react-google-maps#724]
I am attempting to add a custom button component inside the containerElement. However it is not rendered when I add it as a child.

```
containerElement={
  <div style={{ height: `100%`, position: 'relative' }}>
      <div>{refreshButtonComponent}</div>
  </div>
}
```

I can add the component in the inspector and it seems to work fine:

![screenshot 2017-12-07 13 27 10](https://user-images.githubusercontent.com/20729321/33732035-0ec0eaa6-db53-11e7-8881-0bd2831dd5c7.png)

Am I doing this correctly or is there another way of adding these components?

**Comment by tomchentw** [comment]
Didn't work this way, sorry

**Comment by chead2344** [comment]
Try:

```
const ContainerElement = ({ children }) => (
   <div style={{ height: '100%', position: 'relative' }}>
      <RefreshButtonComponent />
      {children}
   </div>
);

<MyMapComponent
   containerElement={<ContainerElement />}
/>
```
