### ISSUE TITLE
can not add more elements to polyline

### ISSUE THREAD

**Issue by Tayapanic** [tomchentw/react-google-maps#726]
I am trying to see a polyline for a moving marker/car. But only the first two locations are shown in the polyline. Here's the code
```
    showPolylines() {    
        return this.props.deviceLocations.map((location, index) => {
            let arr = this.props.polylineDict[location.deviceID]
            console.log("array of locations",arr);    
            if(arr.length >1){
                return <Polyline
                    key={index}
                    path={arr}>
                </Polyline> 
            } 
            else {
                return null
            }
        })
    }
```
in array of locations all the locations are present,but Polyline is not updated after 2 locations.The rendering part is working properly as log shows me "array of locations" with updated array each time

**Comment by Ayke** [comment]
I am going through the same thing. If you let Polyline start with 3 points, the Polyline in display will always stick with 3 points even if you add more points to the path. I don't know if I made this right, but I've searching through every single possible resources.

For anyone interested in reproducing it, try add "MarkerLayer" in a google map, and set the map center to (29.7604,-95.3698) (Houston) :


`var vvvPath = [{ "lat": 29.87033, "lng": -95.52427 }, { "lat": 29.87037, "lng": -95.51266 }, { "lat": 29.86689, "lng": -95.50694 }, { "lat": 29.86558, "lng": -95.50081 }, { "lat": 29.86557, "lng": -95.4981 }, { "lat": 29.86549, "lng": -95.49296 }, { "lat": 29.86553, "lng": -95.49291 }, { "lat": 29.86552, "lng": -95.4926 }, { "lat": 29.86556, "lng": -95.49259 }, { "lat": 29.86575, "lng": -95.49769 }, { "lat": 29.86571, "lng": -95.50668 }, { "lat": 29.8656, "lng": -95.52037 }, { "lat": 29.86899, "lng": -95.52451 }, { "lat": 29.87889, "lng": -95.52472 }, { "lat": 29.87387, "lng": -95.52927 }, { "lat": 29.87722, "lng": -95.53734 }, { "lat": 29.88534, "lng": -95.53743 }, { "lat": 29.8854, "lng": -95.54038 }, { "lat": 29.8854, "lng": -95.54044 }, { "lat": 29.88548, "lng": -95.54044 }, { "lat": 29.88589, "lng": -95.54056 }, { "lat": 29.88615, "lng": -95.54349 }];
class MarkerLayer extends Component {
  constructor(props) {
    super(props);
    this.state = { path : [] };
    this.addpath = this.addpath.bind(this);
  }
  
  addpath() {
    let foo = vvvPath.shift();
    console.log("Size of path:", this.state.path.length);
    
    this.setState((prevState, props) => {
      let bar = prevState.path;
      bar.push(foo);
      return { path : bar};
    });
  }
  
  render() {
    return <div>
      <div> <Polyline
        path={this.state.path}
        options={{
          'strokeColor':'#FE5F55',
          'strokeOpacity': 1,
          'strokeWeight': 3,
          'geodesic': true
        }}
      /> </div>
      <button onClick={this.addpath}> Next {this.state.path.length} </button>
    </div>;
  }
}`

Remember to import Polyline when reproducing

**Comment by tomchentw** [comment]
It's the way you using React state is wrong.
https://developers.google.com/maps/documentation/javascript/examples/polyline-simple

**Comment by ajay-bsoft** [comment]
for code solution please check [#491](https://github.com/tomchentw/react-google-maps/issues/491)
