### ISSUE TITLE
Problems with dynamic rendering of Ground Overlay

### ISSUE THREAD

**Issue by neilyoung** [tomchentw/react-google-maps#734]
This is my map component:

```
const PositioningComponent = compose(
  
  withProps({
    googleMapURL:
      "https://maps.googleapis.com/maps/api/js?key=xxxxxxxxxxxxxxxxx&v=3.exp&libraries=geometry,drawing,places",
    loadingElement: <div style={{ width: '100%', height: `100%` }} />,
    containerElement: <div style={{ width: '100%', height: '100%' }} />,
    mapElement: <div style={{ width: '100%', height: '100%' }} />
  }),
  withScriptjs,
  withGoogleMap
) (props => (
  
  <GoogleMap zoom={props.zoom} center={props.center}>
    <Marker options={{
      icon: {
        url: 'pin.png' 
        scaledSize: { width: 20, height: 20},
        anchor: { x: 10, y: 10 },
      }
    }} position={{ lat: props.latitude || 0, lng: props.longitude || 0 }} />
    
    <GroundOverlay
      defaultUrl={props.href}
      defaultBounds={new google.maps.LatLngBounds(
        new google.maps.LatLng(props.south, props.west), 
        new google.maps.LatLng(props.north, props.east)  
      )}
      defaultOpacity={props.opacity}
      />
      
  </GoogleMap>

));

```

It is rendered timer based like so:

```
<PositioningComponent
                        center =    {this.state.center}
                        zoom =      {this.state.zoom}
                        latitude =  {this.state.latitude}
                        longitude = {this.state.longitude}
                        href =      {this.state.href}
                        opacity =   {this.state.opacity}
                        south =     {this.state.south}
                        west =      {this.state.west}
                        north =     {this.state.north}
                        east =      {this.state.east}
/>

```

Whereas **marker**, **center** and **zoom** are following the props on dynamic change, unfortunately the **Groundoverlay** does not. It is just drawn once with the very first props. 

Here is a trace of the initial render props:

PositioningComponent:  {"zoom":2,"center":{"lat":0,"lng":0},"href":null,"north":0,"south":0,"east":0,"west":0,"opacity":0}

The reason is, that I don't have all the required parameters for the ground overlay by hand, when it is first time to render the overlay.

If I later provide this (mock coordinates), the ground overlay does not appear:

PositioningComponent:  {"zoom":20,"center":{"lat":10.00000000,"lng":10.00000000},"href":"https://image.com/a.png","north":10.000000,"south":10.000000,"east":10.000000,"west":10.000000,"opacity":1}

Zoom, center and marker are fine.

What is required to redraw the GroundOverlay?

**Comment by neilyoung** [comment]
Disregard. Solved by conditional rendering

**Comment by tomchentw** [comment]
You need to use controlled props (ex. `<GroundOverlay url={url} />`) instead of default ones.

**Comment by neilyoung** [comment]
Tried that. Didn't work. Somehow I got a trace or debug info, that GroundOverlay is immutable, once instantiated.

**Comment by tomchentw** [comment]
Yeah, recalled it now. Read the warning in #671

**Comment by svnnynior** [comment]
> Disregard. Solved by conditional rendering

@neilyoung

Sorry for asking, but can you elaborate more on how to do the conditional rendering method. 
Thank you in advance.
