### ISSUE TITLE
Rendering Google Maps link

### ISSUE THREAD

**Issue by FGCorp** [tomchentw/react-google-maps#735]
i want to show a location by sending the map direct link come from browser.
example link:https://www.google.com.tr/maps/place/Maimonides+Medical+Center/@40.6383801,-74.0084432,14z/data=!4m13!1m7!3m6!1s0x89c24fa5d33f083b:0xc80b8f06e177fe62!2sNew+York,+Birle%C5%9Fik+Devletler!3b1!8m2!3d40.7127753!4d-74.0059728!3m4!1s0x89c25accc457649b:0x319d12e89a244ab9!8m2!3d40.6391953!4d-73.9984131?hl=tr
but i dont figure it out how?

**Comment by tomchentw** [comment]
GitHub issue tracker is NOT designed for **how to** questions
