### ISSUE TITLE
How to insert InfoWindow inside MarkerWithLabel for last react-google-maps version ?

### ISSUE THREAD

**Issue by andreoman** [tomchentw/react-google-maps#741]
How to insert InfoWindow inside MarkerWithLabel for react-google-maps@9.4.3 ?
In previous versions I used next code and it worked perfect:
```
<Marker
	key={index}
	markerWithLabel={window.MarkerWithLabel}
    position={location}
    icon={icon}    
    ...        
>
    { marker.showInfoWindow && 
<InfoWindow onCloseClick={() => props.onCloseInfo(marker)} zIndex={zIndex}>
	...
```
![default](https://user-images.githubusercontent.com/2317579/34570418-687fcca6-f174-11e7-8c6f-081dbc8af74b.png)

Should I use following ?
```
<MarkerWithLabel
       key={index}
        position={location}
	icon={icon}	
	...
>
	<span>    
		<div>{marker.name}</div>
		
		{ marker.showInfoWindow &&
			<InfoWindow 
				onCloseClick={() => props.onCloseInfo(marker)} 
				zIndex={zIndex}
			>
			...
```
![default](https://user-images.githubusercontent.com/2317579/34570485-9a3f9ffa-f174-11e7-89e4-c6f1bc379556.png)

**Comment by tomchentw** [comment]
`MarkerWithLabel` !== `Marker`

**Comment by andreoman** [comment]
So, could you help how to display marker with label with capability to display  InfoWindow above marker icon ? Is it possible ?

**Comment by kedwin** [comment]
i think he gives a f*** :rofl:

**Comment by dreadrocksean** [comment]
Nothing?  No reply??  This thing does not work.

**Comment by JustFly1984** [comment]
This library is not maintained, please look at @react-google-maps/api
