### ISSUE TITLE
react-google-maps@9.4.5" has unmet peer dependency

### ISSUE THREAD

**Issue by pladaria** [tomchentw/react-google-maps#750]
I'm getting warnings from yarn when using this library:
```
warning " > react-google-maps@9.4.5" has unmet peer dependency "@types/googlemaps@^3.0.0".
warning " > react-google-maps@9.4.5" has unmet peer dependency "@types/markerclustererplus@^2.1.29".
warning " > react-google-maps@9.4.5" has unmet peer dependency "@types/react@^15.0.0 || ^16.0.0".
```
I guess those dependencies shouldn't be `peerDependencies` (they are already listed in `devDependencies`, which is fine)

I would suggest to remove `@types` deps from `peerDependencies` (or move to `optionalDependencies`).

**Comment by pladaria** [comment]
I see there's already an open discussion in #737

**Comment by Mahdiyeh** [comment]
`npm install --save @types/googlemaps @types/react @types/markerclustererplus `
