### ISSUE TITLE
Markers not displaying on cluster click in case of same latitude and longitude

### ISSUE THREAD

**Issue by Neha1490** [tomchentw/react-google-maps#751]
I am using Marker cluster inside the map. In case of same latitude and longitude, the cluster is formed but it is not breaking into markers on click or zoom in. In case of different locations (i.e. nearby locations with slightly different lat long) marker is displaying on cluster click or on zoom in.

My code is -
<GoogleMap
        ref={this.handleMapLoad}
        defaultZoom={zoom}
        defaultCenter={center}
        center={center}
      >
        <MarkerClusterer
          averageCenter
          enableRetinaIcons
          zoomOnClick
          maxZoom = {25}
          gridSize={30}
        >
          {markers.map((marker, index) => (
            <Marker
              {...marker}
              key={marker.id}
              zIndex={index}
              label={enableIndex ? (index + 1).toString() : null}
              onClick={() => onMarkerClick(marker)}
            >
              {marker.showInfo && (
                <InfoWindow onCloseClick={() => onMarkerClose(marker)}>
                  <div>
                    <div>Employee: {marker.employee_name}</div>
                    <div>Date: {marker.datetime}</div>
                    <div>Activity: {marker.activity_name}</div>
                    <div>Address: {marker.address}</div>
                  </div>
                </InfoWindow>
              )}
            </Marker>
          ))}
        </MarkerClusterer>
      </GoogleMap>

**Comment by tuccle22** [comment]
The problem that you're having isn't particular to this library, as I've seen it in a project not using react-google-maps.  One possible solution is to increase the `minimumClusterSize` prop's value to greater than two.  Of course, this could be a problem if you have 3 markers on the exact same (or very similar) coordinates, but this isn't an issue with this library.

**Comment by Neha1490** [comment]
@tuccle22  
Thanks for your reply.
I have solved this problem.I was not using the maxZoom property,that's why I was facing the problem.
