### ISSUE TITLE
Simple usage instructions in the doc

### ISSUE THREAD

**Issue by stanonyime** [tomchentw/react-google-maps#76]
It will be nice to have a simple example usage in the docs for the Map and Marker. One should not have to dig through the example codes to figure out the basics. In my case I need a draggable marker

**Comment by gcrossfield** [comment]
I just figured this out..

Set draggable: true in the _handle_map_click function, like so:

```javascript
_handle_map_click (event) {
    const {markers} = this.state;
    markers.push({
     position: event.latLng,
     draggable: true
    });
    this.setState({ markers });
}
```
...and in the <Marker/> component like this...

```javascript
<Marker
  position={marker.position}
  key={marker.key}
  draggable={marker.draggable}
  animation={marker.animation}
  onRightclick={this._handle_marker_rightclick.bind(this, index)} />
```

**Comment by stanonyime** [comment]
Ok. Thanks
