### ISSUE TITLE
Instance of Map

### ISSUE THREAD

**Issue by knapeto** [tomchentw/react-google-maps#77]
Hello,

How can I get instance of google map in react?

I need work with triggers

Thanks.

**Comment by knapeto** [comment]
Ahh..

I got it!
```
componentWillUpdate: function() {
    var map = React.findDOMNode(this.refs.map);
    google.maps.event.trigger(map, 'resize');
}
```

When I have map in accordion, is it known problem with google blank page..
IT SOLVED!

**Comment by tomchentw** [comment]
Looks great! Mind to add this info into `README.md` and send a PR?
