### ISSUE TITLE
Circle component stopped working

### ISSUE THREAD

**Issue by topgiter** [tomchentw/react-google-maps#776]
A few days ago `Circle` stopped working, before that everything worked fine.

![image](https://user-images.githubusercontent.com/14260820/36286090-044728a8-12a6-11e8-8987-ab2a31006c17.png)
![image](https://user-images.githubusercontent.com/14260820/36286145-4d305634-12a6-11e8-935b-d84957e56280.png)

**Comment by egormiron** [comment]
I have the same problem, could someone explain where is a problem?

**Comment by GuillaumeJasmin** [comment]
There are some issues since few days with Google map API. Try to change the API version to `v=3.26` .

See also this: https://github.com/tomchentw/react-google-maps/issues/773

**Comment by topgiter** [comment]
👍
