### ISSUE TITLE
compatibility with rails-assets.org

### ISSUE THREAD

**Issue by tgoldenberg** [tomchentw/react-google-maps#78]
When I tried to make this a gem on rails-assets.org, I got this error message. Can it be fixed? Thanks.

This component doesn't define main assets in bower.json.
Please open new pull request in component's repository:
https://github.com/tomchentw/react-google-maps

**Comment by tomchentw** [comment]
Sorry I'm not a big fan of committing bundled file into repo ATM. Please consider using browserify/webpack in your rails environment (which I believe worth it).
