### ISSUE TITLE
Unable to get google's map object

### ISSUE THREAD

**Issue by ivgrin** [tomchentw/react-google-maps#781]
Here is my component:

```jsx
'use strict';

import React from 'react';
import {withGoogleMap, GoogleMap} from 'react-google-maps';
import {MAP} from 'react-google-maps/lib/constants';

export default class Presentation extends React.Component {
    
    static contextTypes = {
        [MAP]: React.PropTypes.object
    }
    
    render() {
        
        var _this = this;

        const MyMap = withGoogleMap((props) => (
            <GoogleMap
                defaultCenter: {
                    lat: 38.809972,
                    lng: -100.60729
                },
                defaultZoom: 5,
                onDragEnd={(e) => {
                    console.log(_this.context[MAP]);
                    console.log(e.latLng.lat(), e.latLng.lng());
                }}
            ></GoogleMap>
        ));

        return (
            <MyMap
                loadingElement={<div className="map-loading" />}
                containerElement={<div className="map-container" />}
                mapElement={<div className="map-element" />}
            />
        );

    }

}
```

In onDragEnd function I want to get google's map object.
Here I found an example how to do that: https://github.com/tomchentw/react-google-maps/issues/161
(I mean using context)
But `_this.context[MAP]` is always undefined for me.

Please provide any workable example or just tell me what is wrong with mine. 

- "react": "^15.4.0"
- "react-google-maps": "^9.4.5"

**Comment by marwan38** [comment]
```
<GoogleMap ref={map => this._map = map} />
onDragEnd={this._map.getCenter().toJSON()}
```

I've been trying to figure out how to update the _current_ center coords, this is what worked for me.

**Comment by ivgrin** [comment]
Yes, this works for me too, big thanks!!)

**Comment by ila-darji** [comment]
@marwan38 are you able to setState of this._map.getCenter().toJSON() ??

I want to set this result in the local state so i did

`<GoogleMap
    ref={ map => !props.isSetMapRef && props.setMapRef(map && map) }
    defaultZoom={props.markerData.length !== 0 ? 13 : 5}
    defaultCenter={{
      lat: parseFloat(props.markerLat),
      lng: parseFloat(props.markerLang),
    }}
    center={{
      lat: parseFloat(props.markerLat),
      lng: parseFloat(props.markerLang),
    }}
    defaultOptions={{
      disableDefaultUI: true, // disable default map UI
      draggable: true, // make map draggable
      keyboardShortcuts: false, // disable keyboard shortcuts
      scaleControl: true, // allow scale controle
      scrollwheel: true, // allow scroll wheel
      // styles, // change default map styles
    }}
    // onCenterChanged={() => props.setCenterLatLong(props.mapRef.getCenter().toJSON())}
    onDragEnd={() => props.setCenterLatLong(props.mapRef.getCenter().toJSON())}
  >`

`setCenterLatLong = (centerLatLongData) => {
     this.setState({
     panCenterLatitude: centerLatLongData.lat,
     panCenterLongitude: centerLatLongData.lng,
     onPanSearchRadios: 5,
     isSearchInThisAreaEnabled: true,
     });
  }`

when I comment the block of  this.setState, then the map is draggable else drag is not dragged, map position remains the same.

Please help I m struggling to resolve this.

**Comment by marwan38** [comment]
> 
> 
> @marwan38 are you able to setState of this._map.getCenter().toJSON() ??
> 
> I want to set this result in the local state so i did
> 
> `<GoogleMap
> ref={ map => !props.isSetMapRef && props.setMapRef(map && map) }
> defaultZoom={props.markerData.length !== 0 ? 13 : 5}
> defaultCenter={{
> lat: parseFloat(props.markerLat),
> lng: parseFloat(props.markerLang),
> }}
> center={{
> lat: parseFloat(props.markerLat),
> lng: parseFloat(props.markerLang),
> }}
> defaultOptions={{
> disableDefaultUI: true, // disable default map UI
> draggable: true, // make map draggable
> keyboardShortcuts: false, // disable keyboard shortcuts
> scaleControl: true, // allow scale controle
> scrollwheel: true, // allow scroll wheel
> // styles, // change default map styles
> }}
> // onCenterChanged={() => props.setCenterLatLong(props.mapRef.getCenter().toJSON())}
> onDragEnd={() => props.setCenterLatLong(props.mapRef.getCenter().toJSON())}
> 
> > `
> 
> `setCenterLatLong = (centerLatLongData) => { this.setState({ panCenterLatitude: centerLatLongData.lat, panCenterLongitude: centerLatLongData.lng, onPanSearchRadios: 5, isSearchInThisAreaEnabled: true, }); }`
> 
> when I comment the block of this.setState, then the map is draggable else drag is not dragged, map position remains the same.
> 
> Please help I m struggling to resolve this.

ila-darji,

First, make sure you preview your post, as to make sure it is neatly presented.

I made that post ages ago, I don't even remember what it is for. But, from looking at your code and mine, there is a difference in the program. `setCenterLatLong` is a void function - it does not return anything. In my example, I am feeding the JSON to the `onDragEnd` prop, and in your case, you are calling a function but not returning data. I don't know if this has anything to do with your problem, but it's just the obvious difference I can see.

If what you're working on is open sourced, I can perhaps take a look at try to give you a hand - even though I don't remember what this all is about. Link me, and describe what you are trying to do.

**Comment by JustFly1984** [comment]
@ila-darji @marwan38 
The repo of this project is unmaintained more than a year, and we had build new version https://www.npmjs.com/package/@react-google-maps/api

We had rewrite it to TypeScript, and updating it frequently: https://github.com/JustFly1984/react-google-maps-api/tree/master/packages/react-google-maps-api
You can enjoy autocomplete.

You can see our docs: https://react-google-maps-api-docs.netlify.com/

Also a lot of examples: https://react-google-maps-api-gatsby-demo.netlify.com/ https://github.com/JustFly1984/react-google-maps-api/tree/master/packages/react-google-maps-api-gatsby-example/src/examples

The bundle size is much smaller: https://bundlephobia.com/result?p=@react-google-maps/api@1.7.7

Our Spectrum community: https://spectrum.chat/react-google-maps

Enjoy!
