### ISSUE TITLE
No Rectangle shape available

### ISSUE THREAD

**Issue by alistairjcbrown** [tomchentw/react-google-maps#79]
There is no `Rectangle` shape available (just `Circle`, `Polygon`, and `Polyline`)

It should be fairly simple to add a new wrapping component in the same vein as `Polygon` to allow for `<Rectangle />` to be created.

I'll try and get a PR up for this tomorrow, but happy for someone to beat me to it :grin:

**Comment by alistairjcbrown** [comment]
Hi @tomchentw, just thought I'd give a bump on this.
There's a PR up to fix this which just follows the same code for circle to add in the rectangle support - it should be an easy win. Give me a shout if there's anything else which needs updated.

**Comment by tomchentw** [comment]
Close this for #80
