### ISSUE TITLE
Dragging problem on the map with SearchBox

### ISSUE THREAD

**Issue by andychongyz** [tomchentw/react-google-maps#790]
Hi guys,
I'm facing the problem where dragging is not working properly. Basically, when I try to drag the map, it moves a little, then it stops. I'm not sure what is happening. And I found out that the search box example is having the same problem, [https://tomchentw.github.io/react-google-maps/#searchbox](url)

The website I work on: [https://postco.com.my/](url)

**Comment by andychongyz** [comment]
Solution found here: https://github.com/tomchentw/react-google-maps/issues/777

**Comment by andychong1996** [comment]
#777
