### ISSUE TITLE
The Autocomplete list in search box is not showing

### ISSUE THREAD

**Issue by fawwaz** [tomchentw/react-google-maps#791]
Dear tom, it seems that the Autocomplete list in SearchBox Component not showing. Am I the only one who is affected by this issue ? It is reproducible in your official docs.

Here is the screen recording : 
![not showing](https://user-images.githubusercontent.com/1295143/36835996-93323c50-1d6a-11e8-9180-9a5961f64341.gif)

I am pretty sure that this is not caused by API search limit since I am using paid plans.

**Comment by adelpuva** [comment]
Also for me with Chrome and Safari on macOS Sierra, from this morning.

I'm using the library in one of my projects and it's not going anymore!

**Comment by cborboni** [comment]
I have the same problem, tested on different browsers (Chrome, Firefox and Safari) on macOS.

**Comment by ghost** [comment]
the same here
response from autocomplete service:
/**/_xdc_._wvyn9i && _xdc_._wvyn9i( [4] )

**Comment by baqui** [comment]
the same here, since today google.maps.places.SearchBox doesn't seem to be working. But if I change this to google.maps.places.Autocomplete is showing autocomplete dropdown.

**Comment by fawwaz** [comment]
@baqui would you like to give a more specific details on how to fix the issue ? It seems that I couldn't find Autocomplete.js in this repo. 
FYI, I'm using the latest version of react-google-maps (9.4.5)

**Comment by romannep** [comment]
@fawwaz You can use autocomplete from another repo. For example - https://github.com/ErrorPro/react-google-autocomplete or https://github.com/kenny-hibino/react-places-autocomplete

**Comment by Hemant-yadav** [comment]
I think this one is caused by a conflict in google's latest experimental version 3.32.
You can resolve it by passing the version as 3.31 or add v=3.31 or v=3.

**Comment by fawwaz** [comment]
Thanks it works !

**Comment by evilandfox** [comment]
Hi! I had this problem too, version changings didn't help. My google map renders in bootstrap modal. The reason was that map has `z-index: 1000` and modal has `z-index: 1050`. So, adding
```
.pac-container {
    z-index: 1100 !important;
}
```
somewhere in css fixes problem.

**Comment by naveendb92** [comment]
@evilandfox  Thank you so much. I was searching for hours. And you are right. Your solution worked !!!

**Comment by sahus16** [comment]
in fullscreen search box is not working

**Comment by sahus16** [comment]
> Hi! I had this problem too, version changings didn't help. My google map renders in bootstrap modal. The reason was that map has `z-index: 1000` and modal has `z-index: 1050`. So, adding
> 
> ```
> .pac-container {
>     z-index: 1100 !important;
> }
> ```
> somewhere in css fixes problem.

in full screen the searcg box not workingg

![image](https://user-images.githubusercontent.com/49634949/56115787-dfb34b00-5f81-11e9-8a3c-d189a3efbea3.png)

**Comment by AlessandroAnnini** [comment]
I confirm this is still not working

**Comment by andsalves** [comment]
> Hi! I had this problem too, version changings didn't help. My google map renders in bootstrap modal. The reason was that map has `z-index: 1000` and modal has `z-index: 1050`. So, adding
> 
> ```
> .pac-container {
>     z-index: 1100 !important;
> }
> ```
> 
> somewhere in css fixes problem.

My hero!
