### ISSUE TITLE
While trying to use InfoWindow getting error 'React.Children.only expected to receive a single React element child'

### ISSUE THREAD

**Issue by SyedSaifAli** [tomchentw/react-google-maps#816]
Hello, I am trying to use the InfoWindow with Marker as mentioned in the documentation but still getting the error. using 9.0.2 version currently?

Can you please tell me what is the problem here? And how do I solve it?

```
<Marker position={props.latlng} icon={{url:marker,anchor:{x:20,y:20}}} animation={true} onClick={()=>props._onChange}>
      <InfoWindow> hello world </InfoWindow>
</Marker>

```
![screen shot 2018-04-05 at 1 44 02 am](https://user-images.githubusercontent.com/26343961/38332232-1a5d94a4-3873-11e8-9a3a-e41b7bd4374b.png)

**Comment by SyedSaifAli** [comment]
Anything ?? @tomchentw

**Comment by SyedSaifAli** [comment]
I've done showing InfoWindow outside the marker component and it worked. thanks

**Comment by devin-yuan** [comment]
right：
<InfoWindow>
    <div>blabla</div>
</InfoWindow>
--------------------------------
error:
<InfoWindow>
    blabla
</InfoWindow>

**Comment by devin-yuan** [comment]
right:
```
<InfoWindow>
  <div>blabla</div>
</InfoWindow>
```
---------------------------------
error:
```
<InfoWindow>
  blabla
</InfoWindow>
```
