### ISSUE TITLE
Marker - addListener events

### ISSUE THREAD

**Issue by lethanhquang** [tomchentw/react-google-maps#83]
Hello guys, 
Really great components, but I want to listen event  `dragend` on Marker, I tried like this:
```
<Marker position={origin}
              googleMapsApi={googleMapsApi}
              dragend={this.handleMarkerChanged}
              key={'marker-origin'}
              draggable={true}
              animation={2} />
```
But, it not work. So, how can I addListener events on Marker component?

Thanks.

**Comment by tomchentw** [comment]
Try `onDragEnd`?

**Comment by lethanhquang** [comment]
Yeah, I did, It's worked perfectly, thank @tomchentw

**Comment by tomchentw** [comment]
Cool!

**Comment by andyfenelon** [comment]
`onDragend`  worked for me

**Comment by erickvica** [comment]
May I send an extra argument to the function without lossing the event?

      onDragEnd={()=>props.onMarkerPositionChanged(props.reloadsitios)}
