### ISSUE TITLE
Inject a adrress and show it on maps [help]

### ISSUE THREAD

**Issue by yuritoledo** [tomchentw/react-google-maps#861]
Hello!

How can I inject a address (from a form) on map, and show the address on it, thru the mark?

I've make a search, and sadly found nothing.

**Comment by ratonjuancarlos** [comment]
Hi @yuritoledo .
Can I ask you why you close this issue? Do you find any solution?
Thanks!

**Comment by yuritoledo** [comment]
Hello dude
Yes, i've made a workaround :P

**Comment by ratonjuancarlos** [comment]
Great, can you share it? or give us a tip?
Thank you anyway!!

**Comment by yuritoledo** [comment]
Sure
I've made a "two-way data binding" between the inner search component and one input text in my app.
Then you hide the inner search with the last example css.
I suggest add `width: 10px, height: 10px` in the inner search (just in case the user hover the map and change the cursor, case hover the search)
Then, when the address is completed filled to search, you need to trigger the onBlur of inner search and VOILÀ!

some examples of my code:

![image](https://user-images.githubusercontent.com/18474538/45167413-81dea980-b1cf-11e8-9258-892433e13f5f.png)

![image](https://user-images.githubusercontent.com/18474538/45167484-9fac0e80-b1cf-11e8-93a3-f77b2122538a.png)
![image](https://user-images.githubusercontent.com/18474538/45167540-b81c2900-b1cf-11e8-83a9-1b6c47acc5b4.png)

**Comment by ratonjuancarlos** [comment]
Thank you very much!!!!
