### ISSUE TITLE
Get latitude longitude of a place on map click

### ISSUE THREAD

**Issue by ckshameer** [tomchentw/react-google-maps#863]
## Getting Help

**Before doing this, did you**:

1. Read the [documentation](https://tomchentw.github.io/react-google-maps)
2. Read the [source code](https://github.com/tomchentw/react-google-maps)

_You can get someone's help in three ways_:

1. Ask on StackOverflow [with a google-maps tag](https://stackoverflow.com/questions/tagged/google-maps?sort=votes&pageSize=50) or [use react-google-maps as a keyword](https://stackoverflow.com/search?q=react-google-maps)
2. Ask in [the chat room][gitter-url]
3. Create a Pull Request with your solutions to your problem

Please, be noted, **no one**, I mean, **no one**, is obligated to help you in **ANY** means. Your time is valuable, so does our contributors. Don't waste our time posting questions like “how do I do X with React-Google-Maps” and “my code doesn't work”. This is not the primary purpose of the issue tracker. Don't abuse.

[gitter-url]: https://gitter.im/tomchentw/react-google-maps?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge

**Comment by ckshameer** [comment]
How to get latitude and longitude of a place on click in map

**Comment by bossbossk20** [comment]
@shameersam  You can get lat, lng by add onClick to props in GoogleMap

```javascipt
<GoogleMap  onClick={this.handleClickedMap }  />

handleClickedMap = (e) => {
   let latitude = e.latLng.lat()
   let longtitude  = e.latLng.lat()
   console.log(lat, lng)
}

```

I hope it useful.
