### ISSUE TITLE
get path of newly plotted polygon

### ISSUE THREAD

**Issue by johnantoni** [tomchentw/react-google-maps#865]
Hi I've been building a Google Map Editor with the Drawing Manager, god it was difficult.

I think the hardest was just working out the flow within the React eco-system.

One last bit, probably easy but please forgive me, I'm trying to get the path of the new plotted polygon.

I've added a listener to the DrawingManager,

      <DrawingManager
        options={{
          drawingControl: props.drawingMode,
          drawingControlOptions: {
            position: google.maps.ControlPosition.TOP_LEFT,
            drawingModes: [
              google.maps.drawing.OverlayType.MARKER,
              google.maps.drawing.OverlayType.POLYGON
            ],
          }
        }}
        onMarkerComplete={props.onMarkerComplete}
        onPolygonComplete={props.onPolygonComplete}
        drawingMode={props.drawingMode
              ? window.google.maps.drawing.OverlayType.MARKER
              : null}
      />

So on finishing the polygon it fires props.onPolygonComplete which fires this and ref is attached to that new Polygon

    onPolygonComplete: ref => {
          // need to get polygon path
    },

My final problem is to get the path array of that polygon.

I got the marker position via 

     newMarker.myLat = ref.position.lat()
     newMarker.myLng = ref.position.lng()

Do you know how to get get the path array?

Looked in the docs and a bit stuck, any help greatly appreciated.

**Comment by kylepierce** [comment]
https://github.com/tomchentw/react-google-maps/issues/454#issuecomment-385072288

**Comment by aqweider** [comment]
```
onPolygonComplete = poly => {
    const polyArray = poly.getPath().getArray();
    let paths = [];
    polyArray.forEach(function(path){
      paths.push({latitude:path.lat(), longitude: path.lng()});
    });
 }
```

**Comment by johnantoni** [comment]
Excellent, thanks
