### ISSUE TITLE
Standalone Library

### ISSUE THREAD

**Issue by pedroseac** [tomchentw/react-google-maps#87]
Hey!

How can i use this project as a standalone library in my project? I tried importing the js files from /lib but it didn't work.

Thanks!

**Comment by tomchentw** [comment]
Currently I only support build tools like webpack or browserify as specified in [README.md]

[README.md]: https://github.com/tomchentw/react-google-maps/blob/9a733413c3f41e3f749cd8710955c71ba25a1b50/README.md#usage
