### ISSUE TITLE
lat and lng position is incorrect despite confirming

### ISSUE THREAD

**Issue by davidgtu** [tomchentw/react-google-maps#876]
I'm passing in `lat` and `lng` into my markers and they seem to be off by a bit for some reason. i'm tried looking up the exact of where I need it to be but it never seems to be placed on the spot.

my coordinates: `{ lat: 40.7433682, lng: -73.99427500000002 }` and `{ lat: 40.744801, lng: -73.992755 }`

gives me 
<img width="306" alt="screen shot 2018-07-26 at 11 55 35 am" src="https://user-images.githubusercontent.com/9327616/43273631-ec774a5c-90ca-11e8-91fc-a8ca5e98507e.png">

and it should be 
<img width="262" alt="screen shot 2018-07-26 at 11 56 36 am" src="https://user-images.githubusercontent.com/9327616/43273704-1e9f9516-90cb-11e8-8469-50dc6797c1ab.png">

is it the way i'm rending it? why is it off by a few degrees?

**Comment by AonanLi** [comment]
did you set proper anchor point for your customized marker?

**Comment by davidgtu** [comment]
That was the problem. Thank you.
