### ISSUE TITLE
Not working with new google API and valid key ...

### ISSUE THREAD

**Issue by tchaton** [tomchentw/react-google-maps#882]
Bug

**Comment by oshalygin** [comment]
I'll take a look

**Comment by tchaton** [comment]
Hey,

I am meaning even on the website.
The maps doesn t seem to load or is it me ?

Best,
Thomas

2018-08-05 5:03 GMT+00:00 Oleg Shalygin <notifications@github.com>:

**Comment by oshalygin** [comment]
Not sure yet but I'm about to test it right now, the latest version of the google maps api may have broken a few things internally but I doubt it, they're very good about semver.

I'll let you know within the hour

**Comment by oshalygin** [comment]
FYI for reference:
https://developers.google.com/maps/documentation/javascript/versions

**Comment by oshalygin** [comment]
Everything is working fine with v3.33 of GoogleMaps:
https://developers.google.com/maps/documentation/javascript/releases

Take a look at the README and the getting started.  If you see any issues please comment back in this Issue and I will reopen it.

Thanks!

![image](https://user-images.githubusercontent.com/7675942/43689398-d8e4f232-98ae-11e8-9d7f-24acb9879c5c.png)

**Comment by tchaton** [comment]
Hey,

I have this error on both my website, yours and the documentation

2018-08-05 20:55 GMT+01:00 Oleg Shalygin <notifications@github.com>:
