### ISSUE TITLE
Corrupt polyline

### ISSUE THREAD

**Issue by devantic** [tomchentw/react-google-maps#888]
Has anyone else encountered this - polyline is corrupt, i.e. there are segments missing. This is happens sporadically for me - it usually renders properly. I've tried the  old google maps directions renderer (v3.3.1) too - didn't help.

![image](https://user-images.githubusercontent.com/32611040/44084492-360e8778-9ffa-11e8-97cd-2047e2463ce2.png)

**Comment by JustFly1984** [comment]
@myleftshoe The repo of this project is unmaintained more than a 2 years, and we had build new version https://www.npmjs.com/package/@react-google-maps/api

We had rewrite it to TypeScript, and updating it frequently: https://github.com/JustFly1984/react-google-maps-api/tree/master/packages/react-google-maps-api
You can enjoy autocomplete.

You can see our docs: https://react-google-maps-api-docs.netlify.app

Also a lot of examples: https://react-google-maps-api-gatsby-demo.netlify.app/ https://github.com/JustFly1984/react-google-maps-api/tree/master/packages/react-google-maps-api-gatsby-example/src/examples

The bundle size is much smaller: https://bundlephobia.com/result?p=@react-google-maps/api

Our Spectrum community: https://spectrum.chat/react-google-maps Our Slack channel: https://join.slack.com/t/react-google-maps-api/shared_invite/enQtODc5ODU1NTY5MzQ4LTBiNTYzZmY1YmVjYzJhZThkMGU0YzUwZjJkNGJmYjk4YjQyYjZhMDk2YThlZGEzNDc0M2RhNjBmMWE4ZTJiMjQ

Enjoy!
