### ISSUE TITLE
DirectionsRenderer Perfs

### ISSUE THREAD

**Issue by cateland** [tomchentw/react-google-maps#89]
Hello,

Im using the DirectionRenderer component, and i noticed that the rendering performance of it drop really fast depending on the number of waypoint returned by the gmaps direction api.

Ex: with 219 path points the webpage freeze for several seconds. When using vanilla gmap api it draw in a matter of milliseconds.

Ex: 
start location 43.124161, 5.9281405000000404
end location : 47.2294142, -1.5732278000000406

This on chrome and on a fast computer.

**Comment by tomchentw** [comment]
Which version did you use? v1.x.x or v.2.x.x?

**Comment by cateland** [comment]
Happen on both 1.X.X and 2.X.X

**Comment by cateland** [comment]
Closing this issue another part of the application was responsible for the bad performences.

My apologies.

**Comment by tomchentw** [comment]
Thanks! Please feel free to reopen this if anything go wrongs here!
