### ISSUE TITLE
2.0.0 build is broken

### ISSUE THREAD

**Issue by nevir** [tomchentw/react-google-maps#91]
https://github.com/tomchentw/react-google-maps/blob/master/src/Rectangle.js#L11 `_RectangleCreator` no longer exists

**Comment by tomchentw** [comment]
Thanks! Will fix it soon.
https://twitter.com/ishwr/status/629726314631532545

**Comment by tomchentw** [comment]
Closed for #91

**Comment by tomchentw** [comment]
Released [v2.0.0] and [v2.0.1].

[v2.0.0]: https://github.com/tomchentw/react-google-maps/releases/tag/v2.0.0
[v2.0.1]: https://github.com/tomchentw/react-google-maps/releases/tag/v2.0.1
