### ISSUE TITLE
Wrap markers with class

### ISSUE THREAD

**Issue by simPod** [tomchentw/react-google-maps#919]
Is it possible to wrap markers with className? I'd like to modify some markers group with css by classname but I wasn't able to make it render marker with class. Thanks

**Comment by stenrdj** [comment]
Hello @simPod  , you may think about using [overlayView ](https://tomchentw.github.io/react-google-maps/#overlayview) component  , unless that it's impossible to add as a className attribute to markers . it's not even possible on plain JS google maps api .

**Comment by simPod** [comment]
Thanks for response!
