### ISSUE TITLE
Pick up a script loader and provide as a optional Compoent

### ISSUE THREAD

**Issue by tomchentw** [tomchentw/react-google-maps#92]
## Why

Inspired by #81 , I think it would be great if we could provide a `<Component>` that will load this module.

## Candidates

https://tomchentw.github.io/xrossref/#ZG96b2lzY2gvcmVhY3QtYXN5bmMtc2NyaXB0LCBzeXN0ZW1qcy9zeXN0ZW1qcywgZGVkL3NjcmlwdC5qcywgU2xleEF4dG9uL3llcG5vcGUuanMsIGdldGlmeS9MQUJqcywgd2Vzc21hbi9kZWZlci5qcw==

## Thoughts

Since `System.js` seems to be the best, future proof library ATM, I think it would be great to implement this feature with it. However, it seems to be too overkilled for a simple feature to use ~13KB in minified, ungzipped bundle.

I was thinking if we could provide a tiny polyfill when `System` is not exist:

```js
const loadScript = System.import || function (url) {
  return new Promise((resolve, reject) => {
    // add <script> tag to <head> and resolve when loaded.
  });
}
// Use it like this
loadScript("https://maps.googleapis.com/maps/api/js").then(fn);
```

Is this polyfill matches what System.js do? Or will there be any problem associate with it?

## References

```text
https://github.com/whatwg/loader/issues/43
https://github.com/systemjs/systemjs/issues/384
```

**Comment by Qrysto** [comment]
+1. I've been using react-async-script for loading googlemaps API and it worked fine before updating to v2. I'm against adding a script tag to load googlemaps API, it's against reactjs's modular structure, so I think react-google-maps itself should provide a way to load googlemaps API or at least play well with 3rd party async script loaders.

**Comment by tomchentw** [comment]
Thanks for the info of [`react-async-script`](https://github.com/dozoisch/react-async-script). I believe it's suitable for our usage. I will look at it soon.

**Comment by Bazze** [comment]
Hey! Any progress on this?

**Comment by Qrysto** [comment]
How is this progressing?

**Comment by tomchentw** [comment]
Okay. Right now I could add another `async.html.js` endpoint to `examples/gh-pages` to demonstrate async loaded scripts. Here's the current result:

## Branch

http://git.io/vCWHm

## Screenshot

<img width="1194" alt="screen shot 2015-10-12 at 10 36 56 am" src="https://cloud.githubusercontent.com/assets/922234/10420764/80de5292-70cd-11e5-9c4e-09a636b02239.png">

The error in the web console shows that async loaded google.maps script will fail due to `document.write` API. 

## Reason for that

We use `react-async-script` to load the Google Map API v3. However, inside the code, the `script.async` flag is set to `1` and cannot change by props. (REF: http://git.io/vCWHB).

**Comment by tomchentw** [comment]
Guys, I've added a new component using `scriptjs` to load google maps API v3. The example can be seen on `gh-pages`:
https://tomchentw.github.io/react-google-maps/async/

Please check it out and let me know any issues, thanks! You can use the version of [4.3.1](https://github.com/tomchentw/react-google-maps/releases/tag/v4.3.1)

**Comment by tomchentw** [comment]
@tstavinoha consider using the `callback` query parameter in the `query` props? This is the standard way by Google Maps JavaScript API v3 to handle the "loaded" event. Notice that it has to be a global variable.

**Comment by tomchentw** [comment]
Close for now.

We're also looking for maintainers. Involve in #266 to help strengthen our community!
