### ISSUE TITLE
Polyline not showing at all.

### ISSUE THREAD

**Issue by Aashir1** [tomchentw/react-google-maps#925]
I have followed all mentioned steps in the documentation but polyline not showing at all. This is My code [DEMO](https://codesandbox.io/s/ry6oq08pjn).
And this is polyline Component that I used in my code.
`let coords = [{latitude: 24.90025, longitude: 67.04422}, {latitude: 24.90043, longitude: 67.04231}]`
`<Polyline`
      `onClick={() => alert("clicked")}`
      `path={coords}`
      `geodesic={true}`
      `options={{`
        `strokeColor: "#000",`
        `strokeOpacity: 0.75,`
       ` strokeWeight: 5`
      `}}`
    />`

**Comment by TimurAsayonok** [comment]
@Aashir1  try to change `latitude` to `lat` and `longitude` to `lng`

**Comment by Aashir1** [comment]
@TimurAsayonok Now it works. Thank you.
