### ISSUE TITLE
mapHolderRef only gets attached to direct child

### ISSUE THREAD

**Issue by nickhs** [tomchentw/react-google-maps#94]
Great library! Just one hiccup I've noticed so far:

When including a child in `<GoogleMap>` that could include an object (such as a `Marker`) the magic `mapHolderRef` property doesn't get attached to the underlying `Marker` object.

For example creating a structure something like:

```
<GoogleMap />
    <MyMarkerHolder />
         <Marker />
```

Will result in none of the `<Markers />` having the necessary property set. The current workaround is to add a property in `MyMarketHolder` that establishes the link:

```
<GoogleMap />
     <MyMarketHolder mapHolderRef={this.props.mapHolderRef} />
         <Marker />
```

The relevant code in [creators/GoogleMapHolder.js](https://github.com/tomchentw/react-google-maps/blob/master/src/creators/GoogleMapHolder.js#L75) - perhaps that should be something like a recursive descent instead?

**Comment by tomchentw** [comment]
Something like `<MyMarketHolder>` is not currently supported. And I think you're right, right now in `MyMarkerHolder#render` you have to manually pass down `mapHolderRef` to children (Marker).

**Comment by replaid** [comment]
I hit this too. Would you consider documenting this decision?

**Comment by tomchentw** [comment]
Close for #266 now.

We're also looking for maintainers. Involve in #266 to help strengthen our community!
