### ISSUE TITLE
how to unmount COMPLETELY

### ISSUE THREAD

**Issue by dogofpavlov** [tomchentw/react-google-maps#940]
Hello. I've been using react-google-maps so far without any issues and it has been great. 

There is a problem though... that if you leave google maps up and running for ... 3 days or so.  suddenly the tiles no longer work and you will get a 403 error. https://issuetracker.google.com/issues/65212482 

This is an issue that google said is intended behavior. Basically when google maps starts up, it creates a session... which expires eventually (understandable)

Google's suggested resolution to this is to use an iframe for the map and then tell the iframe to reload... this is an option that is not possible for my application because of the tons of complex logic going from app to map.

SO, I've been looking into figuring out a way how to do this without refreshing the page.  I believe the issue is that the main google js (https://maps.googleapis.com/maps/api/js) is the script that creates the "session" that expires after a few days.

I noticed that when I first mount the maps, I can see "react-google-maps" add's a bunch of scripts to the header of the page, ex:
<script async="" src="https://maps.googleapis.com/maps/api/js?key=MYKEYHERE"></script>
<script type="text/javascript" charset="UTF-8" src="https://maps.googleapis.com/maps-api-v3/api/js/35/3/common.js"></script>
<script type="text/javascript" charset="UTF-8" src="https://maps.googleapis.com/maps-api-v3/api/js/35/3/util.js"></script>
<script type="text/javascript" charset="UTF-8" src="https://maps.googleapis.com/maps-api-v3/api/js/35/3/map.js"></script>

But I noticed that when I unmount the map, the script's remain in the header. 

Now I do not know if this would work, but my idea was to try to figure out a way to remove those scripts from the header, and then add them back in  (hoping to essentially refresh the session)

SO... is there any way to do this with your library? Do you think what I am trying to do is possible?

**Comment by dogofpavlov** [comment]
after further research, I've learned that just removing the script tags will not clear all the variables that were instantiated, meaning the problem would still exist. Looks like the only way is to literally reload the page. :(

**Comment by JustFly1984** [comment]
Hello @dogofpavlov We are developing new package `react-google-maps-api` currently. I will make sure to cleanup those scripts on unmount. It will have simplified API, and will support latest React. Please wait.
