### ISSUE TITLE
Highlight particular route of multiple routes in google map

### ISSUE THREAD

**Issue by mrajeshkrossark** [tomchentw/react-google-maps#966]
I want to hightlight the particular waypoints (route) from multiple waypoints in a google map. 

For example in the below image, I want only need the route which is drawn line in red color. How to show/ highlight the certain route?

![image](https://user-images.githubusercontent.com/22819712/53733479-18ea9c80-3ea7-11e9-98aa-4ac55b28658c.png)

**Comment by JustFly1984** [comment]
@mrajeshkrossark As I understand correctly, you can change route color globally for all paths together: https://stackoverflow.com/questions/19022702/how-to-change-the-color-of-route-in-google-maps-v3

There is a new version of this module at npm `@react-google-maps/api` Please consider to switch.

**Comment by mrajeshkrossark** [comment]
No, let I will explain clearly. I have multiple routes. So I have view
specific route button for every routes. If user selects particular view
then all other routes should be hide. Same for every routes. How to achieve
this?

**Comment by JustFly1984** [comment]
@mrajeshkrossark In new version of @react-google-maps/api you can make several <DirectionsRenderer /> components, and assign to each renderer its own default color, show al of them by default, and hide those you don't need.

**Comment by mrajeshkrossark** [comment]
I just managed with the array collection of multiple routes.
