### ISSUE TITLE
Not defaults options not working in GoogleMap

### ISSUE THREAD

**Issue by samuelsantia** [tomchentw/react-google-maps#97]
Hi there! I just started to implement your library in a personal project. Its look great.

I'm trying to initialize a map with custom styles, but I've detected that when you use differents options that there are defined in optionNameList when calling to composeOptions in the _createdMap method they are ignored.

My GoogleMap initializer:

```javascript
<GoogleMap ref="map" containerProps={{className: 'map-container'}}
    styles={mapStyles}
    defaultZoom={2}
    defaultCenter={{lat: -25.363882, lng: 131.044922}}>
</GoogleMap>

// when are calling to 
composeOptions({ 
  defaultZoom: 2, 
  defaultCenter: {lat: -25.363882, lng: 131.044922},
  styles: mapStyles
}, [
  "center",
  "heading",
  "mapTypeId",
  "streetView",
  "tilt",
  "zoom",
]); 

// Its returning { zoom: 2, center: {...} } and ignoring styles prop
```

Thanks in advance :)

**Comment by tomchentw** [comment]
Put them into `containerProps`?

**Comment by samuelsantia** [comment]
Sorry I refer to styles to change the map styles (https://developers.google.com/maps/documentation/javascript/styling#styling_the_default_map)

The same issue occurs if I use google.maps.MapOption draggable that its not applying to map initializer.

I think that it would fix updating options list in 
```javascript
// src/creators/GoogleMapsHolder line 55
return new google.maps.Map(domEl, composeOptions(mapProps, [
      // https://developers.google.com/maps/documentation/javascript/3.exp/reference#MapOptions
      "center",
      "heading",
      "mapTypeId",
      "streetView",
      "tilt",
      "zoom",
    ]));
```
Or changing the composeOptions method to returns all props that are not defined in defaults.

**Comment by tomchentw** [comment]
Got it. So in v2.x the API has changed to exclude collect options from `this.props`. If you like to set something that belongs to `options`, you should use `options/defaultOptions` property:

```js
options={{style: mapStyle}}
```

The rule to expose them as `optionNameList` is only when those properties has exposed getter/setter on the API document. Since we don't have a `google.maps.Map#setStyle` method, you should change style inside the options property.

**Comment by samuelsantia** [comment]
Its working!!
Thanks a lot, and congrats for you library :)

I think when you have time you should update the styledMap example to work well

PS: sorry if my english is bad :(

**Comment by tomchentw** [comment]
Glad it works! No problem @samuelsantia !

Sorry to confuse you with the outdated example :( Fix it soon...
