### ISSUE TITLE
Show my current Location icon on map

### ISSUE THREAD

**Issue by aliaro428** [tomchentw/react-google-maps#972]
Do we have any way to show current location icon on map? I could not found any such props in [Documentation](https://tomchentw.github.io/react-google-maps/)

**Comment by Mekala-palaniyappan** [comment]
@aliaro428 :
Why you were closed this issue? what is the solution for this?

**Comment by JustFly1984** [comment]
@aliaro428 The repo of this project is unmaintained more than 3 years, and we had build new version https://www.npmjs.com/package/@react-google-maps/api

We had rewrite it to TypeScript, and updating it frequently: https://github.com/JustFly1984/react-google-maps-api/tree/master/packages/react-google-maps-api
You can enjoy autocomplete.

You can see our docs: https://react-google-maps-api-docs.netlify.app

Also a lot of examples: https://react-google-maps-api-gatsby-demo.netlify.app/ https://github.com/JustFly1984/react-google-maps-api/tree/master/packages/react-google-maps-api-gatsby-example/src/examples

The bundle size is much smaller: https://bundlephobia.com/result?p=@react-google-maps/api

Our Spectrum community: https://spectrum.chat/react-google-maps Our Slack channel: https://join.slack.com/t/react-google-maps-api/shared_invite/enQtODc5ODU1NTY5MzQ4LTBiNTYzZmY1YmVjYzJhZThkMGU0YzUwZjJkNGJmYjk4YjQyYjZhMDk2YThlZGEzNDc0M2RhNjBmMWE4ZTJiMjQ

Enjoy!

**Comment by Mekala-palaniyappan** [comment]
Hi @JustFly11984:
   Okay, I will check it

> @aliaro428 The repo of this project is unmaintained more than 3 years, and we had build new version https://www.npmjs.com/package/@react-google-maps/api
> 
> We had rewrite it to TypeScript, and updating it frequently: https://github.com/JustFly1984/react-google-maps-api/tree/master/packages/react-google-maps-api
> You can enjoy autocomplete.
> 
> You can see our docs: https://react-google-maps-api-docs.netlify.app
> 
> Also a lot of examples: https://react-google-maps-api-gatsby-demo.netlify.app/ https://github.com/JustFly1984/react-google-maps-api/tree/master/packages/react-google-maps-api-gatsby-example/src/examples
> 
> The bundle size is much smaller: https://bundlephobia.com/result?p=@react-google-maps/api
> 
> Our Spectrum community: [https://spectrum.chat/react-google-maps Our](https://spectrum.chat/react-google-maps%E2%80%A8Our) Slack channel: https://join.slack.com/t/react-google-maps-api/shared_invite/enQtODc5ODU1NTY5MzQ4LTBiNTYzZmY1YmVjYzJhZThkMGU0YzUwZjJkNGJmYjk4YjQyYjZhMDk2YThlZGEzNDc0M2RhNjBmMWE4ZTJiMjQ
> 
> Enjoy!
