### ISSUE TITLE
Access LatLong Info

### ISSUE THREAD

**Issue by davidlashlee** [tomchentw/react-google-maps#98]
Hey,

If I'm using drawing manager, and make a polygon, how would I go around getting the polygon points?

**Comment by tomchentw** [comment]
Listen to the `*complete` events:
https://github.com/tomchentw/react-google-maps/blob/081d03f10a7200952c65f7994e896fb3d96d3bc5/src/eventLists/DrawingManagerEventList.js
https://developers.google.com/maps/documentation/javascript/3.exp/reference#DrawingManager

**Comment by mychaelgo** [comment]
@tomchentw  can you give me a simple example how to implement that?

**Comment by jbakerdev** [comment]
Can you give an example of this? I've tried adding a method to circlecomplete as well as onCircleComplete in many places in the DrawingManager props and it never gets called.

**Comment by jbakerdev** [comment]
Ok, found that the issue is the drawingManager events do not quite follow camel case convention:

onCirclecomplete works but I think it should be onCircleComplete... they all follow this pattern so it's easy once you figure it out but it's not obvious unless you step into the source at runtime

**Comment by tomchentw** [comment]
Glad it's resolved! We're also looking for maintainers. Involve in #266 to help strengthen our community!
