### ISSUE TITLE
MarkerWithLabel ignore click events

### ISSUE THREAD

**Issue by apellizzn** [tomchentw/react-google-maps#983]
Hi guys I am using `GoogleMap` with `MarkerWithLabel` and it seems that all click events inside the Label are being ignored

I've created the following example to show this issue: 
https://codesandbox.io/s/reactgooglemaps-example-89h10?fontsize=14

Is this supported or am I supposed to be handle it differently?

**Comment by JustFly1984** [comment]
Hello @apellizzn , this library is not maintained more than a year. We have built new version @react-google-maps/api https://www.npmjs.com/package/@react-google-maps/api

We have active community at spectrum, examples and working docs.
